### ISSUE TITLE
Provide option to disable NFC

### ISSUE THREAD

**Issue by ckbisek** [nextcloud/android#10110]
### Is your feature request related to a problem? Please describe.
When Nextcloud / Nextcloud Talk is opened, the application is allowed to read nearby NFC devices.

### Describe the solution you'd like
Provide an application option to disable NFC

### Describe alternatives you've considered
Alternatives include to not utilize the application on the mobile devices which this impacts
Disabling NFC outright (system level) on the devices should not be considered an alternative

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Why is this behaviour problematic?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@ckbisek, consequently, is this not a problem that your OEM or Google should remediate rather than Nextcloud if that notification is undesirable?

**Comment by ckbisek** [comment]
> @ckbisek, consequently, is this not a problem that your OEM or Google should remediate rather than Nextcloud if that notification is undesirable?

That is implying most Android application is exhibiting this behavior.  Whereas this is the only application installed that performs this function in this manner.  I do not recall the ownCloud application performing in the same fashion nor does the webdav applications installed perform in the same manner.

Perhaps my question should really be: What function within Nextcloud / Nextcloud Talk require NFC?

**Comment by AlvaroBrey** [comment]
> Perhaps my question should really be: What function within Nextcloud / Nextcloud Talk require NFC?

Two-factor authentication with NFC hardware keys. More info in #8606

**Comment by AnorakMan** [comment]
My wife told me that Nextcloud had started to make her phone vibrate constantly. 
It turns out that it's because the phone had started to be stored in a case, the case contains bank cards.
Nextcloud is using NFC and every time an action is taken in the client (eg navigation) it tries to read something from the bank card and vibrates.

Storing a phone in a wallet or case that contains bank cards is fairly common, I think that's a good reason to have the option to disable the functionality.
