### ISSUE TITLE
All accounts removed after updating to v. 20220421

### ISSUE THREAD

**Issue by mark-franz** [nextcloud/android#10158]
After updating to version 20220421, all my existing accounts have been deleted. I had three of them. 

I'm on Shiftphone 5me with Android 8.0.0 and installing from F-Droid.

**Comment by joshtrichards** [comment]
By chance were you using a release (non-Dev) version before you updated? Your version number being a date suggests you're now running a dev version.

**Comment by RokeJulianLockhart** [comment]
I don't know how much assistance this is, but since I'm subscribed to this (and upvoted it) I imagine I once experienced this issue, not that I recall it. However, I certainly was using the Dev version, also installed via F-Droid, during +2022-04.

**Comment by joshtrichards** [comment]
The main reason I asked, though the original reporter hasn't responded, is because accounts/settings are independent across the different builds - e.g.

- Dev upgrade -> Dev version will retain the prior Dev versions settings
- QA upgrade -> QA version will retain the prior Dev versions settings
- Stable upgrade -> Stable version will retain the prior Dev versions settings

So an "upgrade" from a Dev or QA version (e.g. "20220421") to the latest Stable release isn't actually an upgrade - it's a clean installation.
