### ISSUE TITLE
scan not showing in f-droid build

### ISSUE THREAD

**Issue by farfromrefug** [nextcloud/android#10195]
### Steps to reproduce
1. install github non gplay release
2. open the app
3. tap on +

### Expected behaviour
should show the scan document option

### Actual behaviour
not showing

it is working with the gplay version from github. and I also can't seem to be able to use the PDF viewer

### Environment data
Android version: 10

Device model: a3 2017

Stock or customized system: los

Nextcloud app version: 3.20.1

Nextcloud server version: 24

**Comment by AndyScherzinger** [comment]
The scanner includes a binary component which is something f-droid forbids in general so f-droid version won't get this feature for the time being.

**Comment by farfromrefug** [comment]
@AndyScherzinger could it be clearer on the website?

**Comment by AndyScherzinger** [comment]
@farfromrefug which website? nextcloud.com?

**Comment by farfromrefug** [comment]
@AndyScherzinger to be honest not sure where.
maybe on the readme here and on the website.
more and mor people are looking to f-droid. And it can be hard to understand the reason why you don't get it in f-droid build.

**Comment by g-work** [comment]
> @farfromrefug which website? nextcloud.com?

Yes, for example. Especially since it says:

"Nextcloud Files 3.20 for Android
In addition, the 3.20 version of the Nextcloud Android client is out too! Update your smartphone today to take advantage of these great new features developed by our team on Google Play or F-Droid"
(https://nextcloud.com/blog/major-improvements-for-nextcloud-clients-nextcloud-files-3-5-for-desktop-and-3-20-for-android)

This is clearly not the case - and I didn't find this information anywhere!

**Comment by AndyScherzinger** [comment]
cc @jospoortvliet 

Not sure how to handle this from a communication perspective but I also think it would create some confusion and a growing list to list what kind of feature might not be available on which app store because you could state the same for the Huawei App Gallery. While other than the two mentioned features all other shipped features are available.

**Comment by g-work** [comment]
> While other than the two mentioned features all other shipped features are available.

Well, that makes one out of three named features :)

> What’s new on Android Files?
> - A built-in PDF viewer
> - More choice for storage permissions
> - Scan document to upload option
> - ➕ More bug fixes and improvements

https://nextcloud.com/blog/major-improvements-for-nextcloud-clients-nextcloud-files-3-5-for-desktop-and-3-20-for-android/

I really would appreciate, if one could find this information somewhere. I really tried hard to find the features. Would have saved me some time, if I had known, that they don't exist in my version.

**Comment by thrillfall** [comment]
I was thrilled to read in the fdroid updates about the multi page scanner in the latest android files app release (https://github.com/nextcloud/android/pull/11312). Can I assume it is not available on fdroid built even after the mentioned change?

**Comment by AlvaroBrey** [comment]
> I was thrilled to read in the fdroid updates about the multi page scanner in the latest android files app release (#11312). Can I assume it is not available on fdroid built even after the mentioned change?

Nope, still not available on Fdroid.

**Comment by thrillfall** [comment]
thanks. 
where can i add my :+1: that we cannot advertise something in the release notes that is simply not available?

**Comment by joshtrichards** [comment]
#10046 has the context

**Comment by farfromrefug** [comment]
Hope this will be fixed someday. In the meantime for f-droid users i created an open source app to scan your documents. You can easily share to nextcloud from there https://github.com/Akylas/com.akylas.documentscanner

**Comment by AndyScherzinger** [comment]
@meichthys the scanner binary component is OSS yet it means that nextcloud would need to build and include a build process for this binary shipped by the scanner lib dependency ourselves.

So anybody could build and contribute this but it is currently not a priority for Nextcloud. So we are happy to see folks contributing this in order to also have document scanning capabilities in the f-droid version. 👍

**Comment by farfromrefug** [comment]
@meichthys we should move that discussion to my repo. But you should be able to "share" scanned images or pdf with nextcloud app so you can write there. Now webdav sync does work with nextcloud (this is why i implemented it) but it syncs app data (not pdf, images) so that you dont loose your app data upon uninstall/install
