### ISSUE TITLE
Wrong icon for external storage in file list

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/android#10234]
*Note: Originally was for groupfolders, but now only still an issue for external storage (see https://github.com/nextcloud/android/issues/10234#issuecomment-1294737494)*

### Steps to reproduce
1. Create a groupfolder
2. Open nextcloud android app
3. Check icon of groupfolder

### Expected behaviour
- Icon of groupfolder should look like in the webif
![Groupfolder icon_webif_2022-05-12](https://user-images.githubusercontent.com/4077683/168050538-4d8b5fa4-f8f5-4be1-8f30-da4549fb9eb3.PNG)

### Actual behaviour
- Icon does look like a regular/local folder (you can't see that this is a groupfolder)
![Groupfolder icon_android_2022-05-12](https://user-images.githubusercontent.com/4077683/168050731-4105e714-97ea-4d33-a4b4-78a4a9d33841.jpg)
- Android app was removed completely and reinstalled, but issue still persists

### Can you reproduce this problem on https://try.nextcloud.com?
- imho this issue can't be tested on try.nextcloud.com

### Environment data
Android version: 10

Device model: Huawei Mate 40 Pro

Stock or customized system: Stock

Nextcloud app version: 3.20.1

Nextcloud server version: 24.0.0

Reverse proxy: yes (nginx)

### Logs
No logs available

**Comment by ryester19** [comment]
I noticed this too for External Storage folders

**Comment by Jerome-Herbinet** [comment]
I just noticed that the group folder icon appears in the Nextcloud for Android app on my wife's smartphone.

Her smartphone is a Huawei P20 Pro running Android 10.

When I noticed that, her Nextcloud app was in version 3.19.1. I thought at first that this might be due to a bug in the app that appeared after this version. So I updated the Nextcloud application for Android to version 3.20.3. After that, I killed the app, and cleared its cache, then restarted it and it still displays the correct group folder icons. 

My wife's smartphone: 

![2022-07-06_10-28](https://user-images.githubusercontent.com/33763786/177506471-49cae23b-d37f-4ea9-b77f-2a1afd7138c5.png)

My Xiaomi 11T 5G smartphone runs with Android 12 and the Nextcloud app in version 3.20.3 but it sadly still uses the classic folder icons for my group folders (unlike my wife's smartphone).

My smartphone : 

![2022-07-06_10-30](https://user-images.githubusercontent.com/33763786/177506500-caaa5208-3829-46ba-8db1-57fde7230df5.png)

For your information : 
My wife's smartphone and mine are connected to the same Nextcloud instance (24.0.2) and we have access to common group folders. Server side Group Folders app version is 12.0.1.

So I wonder if the bug is not related to the Android version or even the Android layer of the manufacturer ... but I may be talking nonsense.

I hope this information can help and avoid some waste of time.

**Comment by ThibautPlg** [comment]
Works fine for me on an Asus Zenfone (Almost stock android 12) for a Nextcloud android 3.20.1 and a 23.0.6 server.

**Comment by XueSheng-GIT** [comment]
Just tested on an old device (Mate20 Pro, Android 10), which I upgraded to nextcloud android 3.20.3.
Initially the groupfolder icon was shown properly for the existing account. After adding another account (additional user), wrong icon was shown for this addtional user, but correct icon was still shown for the existing user.
After clearing cache and data of nextcloud android, user accounts were removed and after adding them again, wrong groupfolder icon was shown for all users.

Thus I assume that for those who still see the correct groupfolder icon, it's just because they upgraded from and older nextcloud android version and didn't completely clear all data since then.

**Comment by Jerome-Herbinet** [comment]
> Just tested on an old device (Mate20 Pro, Android 10), which I upgraded to nextcloud android 3.20.3.
> Initially the groupfolder icon was shown properly for the existing account. After adding another account (additional user), wrong icon was shown for this addtional user, but correct icon was still shown for the existing user.
> After clearing cache and data of nextcloud android, user accounts were removed and after adding them again, wrong groupfolder icon was shown for all users.
> 
> Thus I assume that for those who still see the correct groupfolder icon, it's just because they upgraded from and older nextcloud android version and didn't completely clear all data since then.

@dorianne-arawa and @ThibautPlg , i suggest that you clear your app cache. 
After that, if you still have GF icon, i suggest that you clear all you NC app data and that you completely  renew user setup in order to see if you still have the GF icon. Thanks.

**Comment by XueSheng-GIT** [comment]
I've updated to nextcloud android 3.21.0 RC1. Groupfolder icon appeared again, but external storages are displayed with a wrong icon. The following screenshot shows the folder "public" which is an external smb mount, but does show a groupfolder icon.

**Android:**
![Folder icons_android](https://user-images.githubusercontent.com/4077683/178710941-aea7669d-1833-43d0-bf66-b1cc4665f663.jpg)

**Webif:**
![Folder icons_webif](https://user-images.githubusercontent.com/4077683/178710954-c7c5b453-e84c-4a10-8b6b-db2fb3752340.png)

**Comment by Jerome-Herbinet** [comment]
Solved for me since 3.21.0.

**Comment by XueSheng-GIT** [comment]
I'm on 3.21.2 and external storage is still displayed wrong, as shown in https://github.com/nextcloud/android/issues/10234#issuecomment-1183040948

**Comment by Jerome-Herbinet** [comment]
> I'm on 3.21.2 and external storage is still displayed wrong, as shown in https://github.com/nextcloud/android/issues/10234#issuecomment-1183040948

Try to completely delete your app's data (reset) and set it up again (user setup).

**Comment by XueSheng-GIT** [comment]
> > I'm on 3.21.2 and external storage is still displayed wrong, as shown in [#10234 (comment)](https://github.com/nextcloud/android/issues/10234#issuecomment-1183040948)
> 
> Try to completely delete your app's data (reset) and set it up again (user setup).

Did that but doesn't fix this issue. Still wrong icon for external storage.

**Comment by AlvaroBrey** [comment]
Since groupfolders are showing correctly, I'll rename this issue

**Comment by joshtrichards** [comment]
External Storage folder icon has it's own issue #1289 so closing this since GF matter was fixed and the remaining is already covered there.
