### ISSUE TITLE
Feature Request?? Where is the option to view images without downloading??

### ISSUE THREAD

**Issue by HardRevo** [nextcloud/android#1029]
Last year I installed the developer app because It had the capability to see the images without downloading. Now  it looks like it has been removed.
I Think being able to see images on the app without having to wait 1-5 seconds or more (depending on the internet connection)  it's one of the key features that the Android App should have.

**Comment by AndyScherzinger** [comment]
Hi @HardRevo, 

the developer app version has been re-created from scratch and the feature you are referring to is #69 and has been implemented by @tobiasKaminsky. Due to the recent, massive changes for the upcoming stable release we haven't found the time yet to integrate it back into the new developer version but that is on our agenda. Be be assured that we haven't "removed" it the new and rebuild developer version just hasn't gotten back all former features and we are working on that. Unfortunately I can't tell you whne if will be back (maybe @tobiasKaminsky can) since the upcoming stable release is keeping everyone quite busy these days...

**Comment by tobiasKaminsky** [comment]
Currently we are doing bugfixes for the next release (1.5).
After that this is my no.1 priority.

**Comment by HardRevo** [comment]
Thanks for clarifying this and letting us know. 
With so many changes coming up it's quite hard to keep up with whats happening. 
Thanks can wait.
