### ISSUE TITLE
New login in NC12

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1034]
Server is now sending both auth methodes:
`< WWW-Authenticate: Basic realm="Nextcloud"
< WWW-Authenticate: Bearer realm="Nextcloud"`

Currently android only uses only the latest string.
Oauth/Bearer is not working on android client.
To have a real fix, the client needs to parse both methodes and check if any says "basic".

Another way @nickvergessen just found out is to use /dav instead of /webdav.
With this approach we only get "basic realm":
- contra:  we do not get "bearer"/oauth
- pro: we have not to handle two auths

@mario @AndyScherzinger

**Comment by nickvergessen** [comment]
No, misunderstanding. On /dav you get both too, but in a different order:
```
< WWW-Authenticate: Bearer realm="Nextcloud"
< WWW-Authenticate: Basic realm="Nextcloud"
```

However Lukas just told me, that header order might be arbitrary, since there is enterprise software which automatically sorts headers alphabetically.
So decent parsing and looking for one "basic" sounds like the correct approach.

**Comment by tobiasKaminsky** [comment]
Thanks for clarifying Joas!
Then I'll do it this way :-)
