### ISSUE TITLE
Nextcloud android app does not move or delete original files

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#1048]
### Actual behaviour
I setup Nextcloud android app to auto upload my photos to server and the original files to be moved to app folder. Instead, the original files are kept in the original folder.
The exact same behaviour happens with the setting "Original file will be..." - deleted.
Also, the same behaviour happens when I manually upload a file to the server and select Move or Delete.

### Expected behaviour
I take a photo, nextcloud app uploads it to the server then it moves it to the application folder.
or
I take a photo, nextcloud app uploads it to the server then it deletes the original photo.

### Steps to reproduce
1. Setup Nextcloud android app to auto upload files from DCIM/Camera folder;
2. Setup Nextcloud android app "Original file will be..." - "moved to app folder";
3. Take a photo;
4. Wait for Nextcloud to upload the photo on the server;
5. Go to Nextcloud app and browse the InstantUpload folder to confirm the photo is uploaded;
6. Using a file browser, got to DCIM/Camera folder and verify if the original photo is still there.

### Environment data
Android version: 6.0.1

Device model: Samsung Galaxy J5 (2016) [SM-J510FN]

Stock or customized system: Stock

Nextcloud app version: 1.4.3

Nextcloud server version: 11.0.3 (stable)

![screenshot_20170529-104638](https://cloud.githubusercontent.com/assets/21157928/26544679/ef26bd10-4462-11e7-90a5-04395310c9bc.png)
![screenshot_20170529-110956](https://cloud.githubusercontent.com/assets/21157928/26544680/ef2bbcac-4462-11e7-89cd-f0231cbd3e27.png)
![screenshot_20170529-112630](https://cloud.githubusercontent.com/assets/21157928/26544681/ef30ea60-4462-11e7-8c13-97c2f8049601.png)

**Comment by georgefl** [comment]
One more detail I'd like to add, the app data of Nextcloud is stored on a 64GB SanDisk microSD card mounted as "Portable storage" (there is no other way in my Samsung dumbphone).

**Comment by tobiasKaminsky** [comment]
@georgefl on some other issues we discussed the same.
With my tests it is working if you set the sdcard to "internal storage", which is not working on any samsung phone.
So the best way to stop confusing users it so disable this option on sdcards where we cannot delete/move the files...

**Comment by georgefl** [comment]
Hi Tobias,
I appreciate your effort for checking this. As I am sure Samsung won't change the policy on using the SD cards and I won't change my phone just because of this, I hope in future you will be able to implement this functionality for all users.
Cheers!

**Comment by gjanssens** [comment]
Ok, I'm running into this issue as well. Just as @georgefl I'm using several Samsung devices and switching devices just because of this is not an option.

Just to gather more data on this, can someone explain why the sdcard has to be set to "internal storage" in the first place ? What difference does this make, and how does this prevent the Nextcloud client from performing the move or delete action ?

**Comment by gjanssens** [comment]
Update: I have been searching the web and I'll fill in the missing info as far as I understand it.

The issue seems to be {as of android KitKat no longer allows apps to write into directories it doesn't own on sdcards](https://www.androidcentral.com/kitkat-sdcard-changes#content). A move or delete in the context of this bug would mean Nextcloud requires permission to alter the Camera folder on the SD card, which it no longer has. And from [the answers on this Quora thread](https://www.quora.com/How-can-I-make-my-SD-card-as-a-default-storage-for-the-WhatsApp-media?share=1) I understand newer android versions have an option to merge the sdcard  with internal storage (probably what @tobiasKaminsky was referring to) so these limitations wouldn't apply. Unfortunately Samsung chose not to implement this.

Now for my use case I can work around this by reconfiguring my Camera app to store its pictures on the real internal storage. It has much less capacity, however as images are moved/deleted relatively shortly after the have been captured this is not an issue in my particular case. It may become one if one takes lots of pictures/videos between sync actions of if internal storage is becoming extremely tight. Still I thought I'd mention it as an alternative workaround (mostly targeted at Samsung users).

**Comment by tobiasKaminsky** [comment]
Good summarize 👍 
As you pointed out there is not that much we can do on Samsung devices :-(

**Comment by childnode** [comment]
just a mention (from experience in https://github.com/nextcloud/android/issues/2731):
when doing a "manual migration" `/storage/0381-09EC/Android/data/com.nextcloud.client/files`to `/storage/B840-C408/Android/media/com.nextcloud.client` by using the internal storage manager from android 7.1.1; then changing the storage path in  nextcloud will not detect files as already downloaded but will redownload offline marked files only on browsing to the folder in nextcloud app as like what happened in https://github.com/nextcloud/android/issues/186

I expected to not have to do that when changing an SD card ;/
