### ISSUE TITLE
[Feature Request] Password change inside android app

### ISSUE THREAD

**Issue by gituser789** [nextcloud/android#10539]
### Is your feature request related to a problem? Please describe.
Nowadays, a large number of users only use their smartphones to get things done. So also file sharing is mainly done from the smartphone (and not from the computer). In most Nextcloud instances, the administrator sends the initial user data with the instruction to change the initial password immediately. The smartphone user now desperately searches for the option to change the password in the app. Many users do not know the concept behind Nextcloud, and do not know that there is a parallel web interface.

### Describe the solution you'd like
May there are the following solutions
 - Possibility to change password directly in the app
 - Possibility to change password via link from within the app
The function could be located e.g. under 'Menu' -> 'Settings' -> 'Change password'.

What do you think about the usability improvement of this feature?

**Comment by AlvaroBrey** [comment]
> Possibility to change password directly in the app

Not possible right now AFAIK

> * Possibility to change password via link from within the app
>       The function could be located e.g. under 'Menu' -> 'Settings' -> 'Change password'.

This could be possible but would rather be in the profile menu, not in settings. Also we would need to make sure that the app is auto-logged out after the password is changed.

What do you think @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
- we always hesitate to do this, as it causes then 4x work when changing (web, Android, iOS, Desktop), while this is a task that is done not very often
- some identity management systems, like ldap, saml, etc. do do allow to let user change their password or it is a more complex (background) logic needed, which is why we only have this in web (if at all)
- most big instances use kind of ldap, etc system, so this cannot then be used
- changing main/login password is independent from app token (which is used by apps)

All in all ratio between effort and benefit is not that good, so likelihood to do this is small, in mid-term future.
