### ISSUE TITLE
Move to Material You / 3

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#10568]
In Talk we are already moving step by step to Material You, we should coordinate to have both apps steadily move towards this more modern look. :) https://m3.material.io/

Also ref Talk app issue for this, as probably some components can be shared? https://github.com/nextcloud/talk-android/issues/2076

And cc other Android app devs @tobiasKaminsky @AlvaroBrey @AndyScherzinger @mahibi @nextcloud/android @stefan-niedermann @David-Development @joleaf

**Comment by tobiasKaminsky** [comment]
Such a meta-overview ticket is nice, but we shall have concrete actions, which we then can do.
So, from a design/UX perspective, what are the most visible/best changes to do? 
Shall we first focus on e.g. colors? Or specific components, like buttons?

**Comment by jancborchardt** [comment]
@tobiasKaminsky from your view what would make sense? I’d assume it would be best to cut it into upgrading the individual components, if that’s technically possible?
- Content view / file list
- Header
- FAB
- Navigation
- File detail view (activity, sharing etc)
- Image viewer
- Settings
- …

Does that make sense?

**Comment by AndyScherzinger** [comment]
The UI "components" would be the right way like you stated @jancborchardt - I already started working on it in https://github.com/nextcloud/talk-android/pull/2084 but paused the work to first have the server theme implementation in place since some things change with the latest material libraries for the UI elements API-wise.

The biggest impacts I have seen so far are then with the dialogs and bottomsheets since it affects the background-coloring. Buttons are rather flexible in their design-options now so we can stay with the pill-style, chips needs to rework (see Talk code), for the Toolbar we might want to thing about using the theme color for text and icons in light theme (at least, dark theme I am not sure).

**Comment by jancborchardt** [comment]
Should we close this in favor of https://github.com/nextcloud/android/issues/10638 then or the other way around?

**Comment by AndyScherzinger** [comment]
@jancborchardt I think we can close this one since the other one has the. Top level steps and references to talk
