### ISSUE TITLE
"server took too long to respond" odd edge case

### ISSUE THREAD

**Issue by evilantishad0w** [nextcloud/android#1094]
### Actual behaviour
Client refuses to log on to one server, reports "The server took too long to respond" - but logs on to a different server with no problem

### Expected behaviour
Should connect fine, no problem with two other Android devices or PC/web connections
 
### Steps to reproduce
1. I'd prefer not to disclose my private server address, contact for testing...  Note that it's running on HTTPS at a high port # (22111) in the subdirectory /cloud
2. Enter server address, shows connected...  Enter u/p (valid or not)
3. 

### Environment data
Android version:  5.1.1

Device model: SM-T330NU (Galaxy Tab 4)

Stock or customized system: Stock

Nextcloud app version:  1.4.3

Nextcloud server version:  12.0.0

#### Web server error log
```
No errors
```

#### Nextcloud log (data/nextcloud.log)
```
no errors
```

**Comment by evilantishad0w** [comment]
Update: Added "/index.php" to URL, connected successfully. (?)

**Comment by tobiasKaminsky** [comment]
Index.php should not be necessary. 
We are currently working on a way to prevent this "timeout message", which is occurring if bruteforce is enabled.
But glad that it is working now for you.

**Comment by mstuckless** [comment]
I'm still having this server timeout issue on android app.

Android version: 5.0
Device model: Zenfone 2
Stock or customized system: Stock
Nextcloud app version: 1.4.3
Nextcloud server version: 12.0.0

**Comment by tobiasKaminsky** [comment]
We have improved the login in current master and it will be available in next version.
If you want you can try the dev version, which can be installed parallel: https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

**Comment by ManuelFte** [comment]
I have this issue too, I can log into browser and desktop app, but the Android app returns "The server took too long to respond". Googling for a solution I found that this bug also exists on ownCloud and [a user said](https://github.com/owncloud/android/issues/516#issuecomment-294915745) that changing from auto config to DHCP in his router solved it. Since I don't have that option in my router I tried using a VPN and I could log in, but I need to use it permanently because otherwise the app can't connect (and therefore is useless). I tried the dev version but it didn't work either, the app responds "Trying to log in.." and after a few seconds the message just disappears and it stays in the same login screen.

**Comment by CrazedProgrammer** [comment]
I've had this same issue and have been able to fix it.
It seems to have to do with the brute force protection in NC12, which can make the timeout way higher than the timeout in the app. I tested this by trying to log in on the mobile browser, which took 30 seconds to respond.
I added this line to my `config.php`, and the problem was fixed:  
`'auth.bruteforce.protection.enabled' => false,`  
This is obviously not optimal because it's disabling a security feature, but a possible fix might be to increase the timeout to something higher than the maximum brute force protection timeout.

**Comment by AndyScherzinger** [comment]
@CrazedProgrammer which version of the Android app are you using?

**Comment by CrazedProgrammer** [comment]
@AndyScherzinger The latest version from the Play Store, version 1.4.3.

**Comment by milankni** [comment]
Same here. Android app times out. Login via web (Chromium) takes up to 30 secs, then it works normally. Setting `'auth.bruteforce.protection.enabled' => false,` helpd - the login is immediate again.
I do not know what triggered the bug in NC, it work fine few hours ago and I did not change anything in the setup.

**Comment by AndyScherzinger** [comment]
You can check the bruteforce database table of Nextcloud and remove all entries and then the client won't be blocked anymore. This should geht better with the next release in case you are running Nextcloud 12+

**Comment by tobiasKaminsky** [comment]
Additionally I would try to figure out why your IP is listed as blacklisted.
It is often that a caldav/carddav or some other clients are trying to login with old credentials and then flood with wrong attempts. Then your ip will get blocked.

**Comment by milankni** [comment]
Yep, that was the case:
I tried to use a new 3rd party webdav upload client, and as usual the initial setup involved a bit of trial and error in setting the app password (blank space added to text file by NC's text editor in web GUI, which I did not notice before copying to clipboard in Android NC client) and direct path guessing (/remote.php/webdav/target vs /remote.php/dav/files/username/target).

It would be good to see blocked IPs in admin's web GUI with 'release' option rather than modifying the database manually.

**Comment by tobiasKaminsky** [comment]
Glad that you solved it 👍 

> It would be good to see blocked IPs in admin's web GUI with 'release' option rather than modifying the database manually.

Please open up an issue on https://github.com/nextcloud/server/issues for this.
