### ISSUE TITLE
Registered device name on the server is machine type/identifier, not the hostname

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/android#10958]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [ ] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install the Android Nextcloud Client on ChromeOS
2. Connect to a server
3. See the list of registered devices

![image](https://user-images.githubusercontent.com/6132793/198849031-1f5bee03-062d-46b5-b3c4-72c8ed32e6f1.png)

"Google zork" is the device type (Lenovo C13 Yoga mainboard), not it's name (that should have been chromOSom).

I have three of them and there is that problem with triplet witches; you never know which witch is which witch. They could at least get numbers.

### Expected behaviour

Seeing a device name showing up in the list.

### Actual behaviour

see above

### Android version

9

### Device brand and model

Lenovo Thinkpad C13 Yoga

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3 RC1

### Nextcloud server version

any between 22.x and 25

### Using a reverse proxy?

I don't know

### Additional information

I don't believe the logs show where the system name is coming from and I can't easily access them without forcing me to reset the system completely ("powerwash it") afterwards.

**Comment by joshtrichards** [comment]
This is expected behavior.

My ChromeOS tablet running the Nextcloud Android client appears in a similar manner: `Google kukui (Android)`.

What gets displayed under the *Personal->Security->Devices & sessions* section in the Web UI is just based on the User-Agent (along with some fall backs or any manually specified renames) - i.e.

https://github.com/nextcloud/server/blob/master/apps/settings/src/components/AuthToken.vue#L93-L136

If manually renaming it from the three dots menu isn't sufficient, and you want to change this behavior to be different, this would be a [`server`](https://github.com/nextcloud/server) enhancement matter, but it's not a client issue.
