### ISSUE TITLE
Autoupload uploads to wrong account when multiple accounts are present on client

### ISSUE THREAD

**Issue by MadMakz** [nextcloud/android#11088]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

It started out of the blue in i think 3.22.3

Other than that i have no idea how to reproduce because i didn't touch it for it to appear. 

### Expected behaviour

Choose user A, under Settings setup Syncing folders.

User A syncs to remote user A

### Actual behaviour

It syncs new files with folder settings of user A to remote user B. 

### Android version

12

### Device brand and model

Galaxy A71

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.7.1

### Using a reverse proxy?

Yes

**Comment by simongehrig** [comment]
> Addition:
> 
> I just figured that local account B just uploads new files & folders to Remote A while local user B actually has no sync set up at all?
> 
> I just saw that when i was logged in as user B on remote.
> 
> At this state i'd mark this app as broken!

Actually I have two accounts set up in my app, both with multiple different sync folders and it seems to randomly mix up the accounts.
Additionally I have to say that one of the instances is not permanently reachable, in that case - at least from my impression - the app tends to choose the online instance for all syncs.

**Comment by farhills** [comment]
Agreed with Simongehrig, my experience with this issue was it looked like a race condition, with files scattered between the two accounts.  

I have autoupload configured on account A (personal) to save photos in yyyy-mm folders.  Account B is a corporate instance, I had it logged in on the app so that I can selectively share project photos taken on my phone to job folders without having to plug in to a computer.

**Comment by nottheend** [comment]
Also confirming this bug. It is very risky.
Because it may upload sensitive data to a wrong account. It is better if autoupload can be enabled for 1 account only rather than uploading to the accounts randomly.

**Comment by AlvaroBrey** [comment]
Can any of you provide a log from the device? Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output for privacy.

**Comment by farhills** [comment]
Well I've just spent 45 minutes trying to replicate the issue and can't....  

I re-added the second account to the app and tried various combinations of taking and sharing photos between the accounts.  I thought it may have had something to do with a queue of photos, so took photos while in airplane mode, then re-enabled wifi.  No dice.  🤷 

I'll run with both accounts active and see if the issue repeats itself in the future.  Hopefully someone else having this issue has better luck giving the devs some useful feedback.

**Comment by simongehrig** [comment]
Setup:
Connected accounts:
username1@nc1.server.com - files stay on phone
username1@nc2.server.com - files stay on phone
username2@nc2.server.com - files get deleted phone after upload


---------------------------------------------------------
---------------------------------------------------------

Logfile of following:
---------------------------------------------------------
both instances up and running
---------------------------------------------------------
generate files that should be uploaded to username2@nc2.server.com and username1@nc1.server.com 
--> uploads files correctly

---------------------------------------------------------
stopping nc2.server.com instance
---------------------------------------------------------
generate files that should be uploaded to username2@nc2.server.com and username1@nc1.server.com 
-->all files upload to username1@nc1.server.com, files for 
username2@nc2.server.com get deleted from phone

---------------------------------------------------------
restarting nc2.server.com
---------------------------------------------------------
files that should be uploaded to username1@nc1.server.com get uploaded to username2@nc2.server.com

[20230115_NCClient_logcatOutput_edit.txt](https://github.com/nextcloud/android/files/10420386/20230115_NCClient_logcatOutput_edit.txt)

**Comment by derkleinekobold** [comment]
I can also confirm this behaviour on a Samsung S10 with Android 12. The app is randomly uploading some files from one auto upload folder setup with account A to account B and the other way round.
I also failed to actively reproduce the issue. I only know I also solved some issues with automatic uploads in combination with different power saving settings around the same time when the wrong uploads happened. But I guess this was only a coincidence.
Also I noticed the failure happened at a time when multiple files where uploaded to account A (approx. 100 from 2 folder rules) and a few files ( approx. 10 from one folder rule) where uploaded to the account B. At this time around 30 wrong files ended up in account B and one wrong file made it to account A. All files in question also where correctly uploaded to the account they belong to.
The files are only shown in the "uploads" menu of the correct accounts. I could not find them in the uploads of the wrong account.

**Comment by fluke29a** [comment]
(Just signed up here to also comment on this issue.)

### Steps to reproduce
Added a second Nextcloud account (B) to the app.
1: Switch to (old) account A. In the files view of the app, add a new folder on the server via the app.
2: Switch to account B. In the files view of the app, chose a local file to upload.

### Expected behaviour
1: Folder gets created in account A.
2. File gets uploaded to account B.

### Actual behaviour
1: Folders are created in account B, though they show up in the app in account A (I only found out when using the web interface)
2: File gets uploaded to account A (and stops because it gets over quota).

### Android version
13

### Device brand and model
Pixel 6

### Stock or custom OS?
Stock

### Nextcloud android app version
3.24.1

Nextcloud server version
1: 25.0.4 (Account A)
2: 25.0.4 (Account B)

### Using a reverse proxy?
No

### Android logs
_None_

### Server error logs
_None_

### Additional information
_None_

**Comment by behinger** [comment]
Can confirm this behavior on lineage 11 - Nextcloud 3.24.1 .

Can I highlight again, how critical it is that private pictures are uploaded to only one instance, and not another, potentially public one?

**Comment by tilllt** [comment]
Yes, i have the same issue. Two accounts configured, auto upload (for camera folders) to Server 1 is enabled. Client just uploaded 6GB of my phones photos to Server 2 which DOES NOT HAVE AUTO UPLOAD ENABLED. Lucky i saw it because server 2 auto-deletes files after two weeks. This is not only a security desaster but generally a major bug.

**Comment by laarisyko** [comment]
I have the same issue. I use two Nextcloud instances (private & work). The work instance gets regular updates, now a ton of my private photos is somehow trapped in the legitimate backups of my company. This is a privacy desaster :(

I need to disable this extremly nice feature I fear. Is there any offical reaction, if and when this major bug could be solved. I really appriciate the exisitence of Nextcloud and are a happy user of it since years. This was the first time I got a bit nervous.

**Comment by JustACasual** [comment]
same here, got 2 nextcloud instances set up in my nc android app
only one has auto upload enabled for fotos
Sometimes, the fotos are auto uploaded to the wrong instance

Unfortunately, I could not see any patterns how to force the misbehaviour...

**Comment by joshtrichards** [comment]
Many additional reports and reproduction ideas here: https://github.com/nextcloud/android/issues/11645#issue-1722575847
