### ISSUE TITLE
Test your release

### ISSUE THREAD

**Issue by endurlanion** [nextcloud/android#11191]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

It's been a long time since your app actually did what it is supposed to do...

Basically none of your last 3-4 versions has been usable.

- previous version of the app crashed immediately when opened on Android 13

- current version , auto upload is just stuck on continuous listing of files and does not actually sync anything. While this is going the phone can barely be used for anything else (it's reporting 18k files needed to sync which seems completely wrong.

### Expected behaviour

See above 

### Actual behaviour

See above 

### Android version

13

### Device brand and model

Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

Latest snap version

### Using a reverse proxy?

Yes

### Additional information

I guess this will not qualify as a bug due to the unspecified detail... I guess you can see this as feedback if you want. Nextcloud app used to be a great tool but something has changed and now each release has severe bugs making it unusable.

**Comment by endurlanion** [comment]
To add to this, friends and colleagues with recent Android versions are telling me they experience similar issues...

**Comment by AlvaroBrey** [comment]
Hey @endurlanion , you're right in that I will close this for being a generic complaint rather than a bug report.

However let me say that we're doing what we can to ensure releases are as stable as possible. It's just a really big codebase with tons of tech debt and there's too few of us. It also doesn't help that Nextcloud is self-hosted so we can't test every possible server setup.

> * auto upload is just stuck on continuous listing of files and does not actually sync anything. While this is going the phone can barely be used for anything else (it's reporting 18k files needed to sync which seems completely wrong.

This should be greatly improved by #11124  ,  which is in 3.23.1, currently in review in GPlay and already published on Github.

If you have any other specific bug reports please do submit them as individual issues or search if they are already reported.
