### ISSUE TITLE
All uploads stuck on "waiting to upload", continuously trying to re-upload duplicates

### ISSUE THREAD

**Issue by atrauzzi** [nextcloud/android#11485]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Try to use automatic upload functionality.

### Expected behaviour

Files upload and sync silently in the background without getting huge backlogs of duplicate or incomplete transfers.

### Actual behaviour

It's just an unmitigated mess right now. The next cloud app seems to take a different course of action every day of the week.

Some days it tries to resync everything, forcing me to resolve an avalanche of duplicates.

Some days it just stalls outright and I'm not sure what's going on.

Some days I just get a big list of failed uploads.

It's completely unpredictable.

### Android version

12

### Device brand and model

OnePlus 7t

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

Latest

### Using a reverse proxy?

Yes

**Comment by BLu85** [comment]
It sounds like this issue #11263

**Comment by atrauzzi** [comment]
I just have nothing to work off of, so maybe. But the UI and functionality are clearly not mature enough to give me a hope of figuring it out.

**Comment by joshtrichards** [comment]
Are some of the files successfully ending up on the server or are you getting all this noise without any files showing up server-side?

**Comment by atrauzzi** [comment]
Not sure to be honest. I don't get any clear indicator.

**Comment by joshtrichards** [comment]
Can the share the settings of your active auto-upload configuration profiles?

**Comment by jmigual** [comment]
To me something similar is happening. Right now I'm on 3.25.0 because 3.26.0 did not upload anything. Right now it uploads some files (5-10) and then it completely stops uploading. Version 3.26 did not upload anything at all.

**Comment by p3dr01991** [comment]
I'm seeing the same thing as @jmigual, my server was offline for a few months (a painful house move), and now it's not working well for all of the auto upload photos which it's trying to sync.) It'll maybe do 10 at a time every now and then, but there are hundreds "pending". Unlike #11263 the photos aren't actually uploaded to my server, so the app status seems to be "true".

**Comment by chentso** [comment]
I'm also seeing the same as @jmigual  and @p3dr01991. I got through about 400 of the 2000 files to upload last night and at one point it just stops, I would close the app, restart it and it would sync about 5-10 files and then just stop completely again, and right now I can't even get it to upload anything no matter what I do. I'm on version 3.26.0.

**Comment by demaniak** [comment]
To add - in my case, there are no conflicts, it's all brand new photos.

I observed, just opening and closing (no changes) the sync settings for the Camera folder triggers a couple of photos to upload. But then it stops again.

**Comment by dinccey** [comment]
> To add - in my case, there are no conflicts, it's all brand new photos.
> 
> I observed, just opening and closing (no changes) the sync settings for the Camera folder triggers a couple of photos to upload. But then it stops again.

Same behavior here with multiple devices, Nextcloud AIO backend, all up to date

**Comment by dewi-ny-je** [comment]
> To add - in my case, there are no conflicts, it's all brand new photos.
> 
> I observed, just opening and closing (no changes) the sync settings for the Camera folder triggers a couple of photos to upload. But then it stops again.

Same for me. It states "app terminated", then when I push the "retry" button (the two circling arrows) it starts fine, after few photos it stops again.
I just reinstalled nextcloud snap after a server upgrade. I had exported and then I reimported the snap settings with the provided commands ("export/import -abc ...").

**Comment by dodysw3** [comment]
I'm in the same boat, tons of images stuck on waiting to upload status. This is dumb, but I clicked the (X) icon next to the first file on that status, this seems unblock whatever was blocking.

**Comment by dewi-ny-je** [comment]
In my case it was an error in the configuration of nextcloud

**Comment by demaniak** [comment]
> In my case it was an error in the configuration of nextcloud

Hey @dewi-ny-je , could you maybe elaborate?
Would just like to sanity check my configs as well.

**Comment by dewi-ny-je** [comment]
> > In my case it was an error in the configuration of nextcloud
> 
> Hey @dewi-ny-je , could you maybe elaborate? Would just like to sanity check my configs as well.

I think it was a problem with the reverse proxy and/or the URL set in the config file, but I don't remember the details anymore.

**Comment by joshtrichards** [comment]
If you one of you is able to provide logs + the exact settings of all your enabled auto-upload profiles that would be helpful.

Otherwise there isn't much to go on here, unfortunately.

There have also been quite a few changes all throughout this area of code since these original reports.

**Comment by dewi-ny-je** [comment]
> If you one of you is able to provide logs + the exact settings of all your enabled auto-upload profiles that would be helpful.
> 
> Otherwise there isn't much to go on here, unfortunately.
> 
> There have also been quite a few changes all throughout this area of code since these original reports.

It still happens.

How do I provide the logs? I couldn't find any obvious buttons in the app.

**Comment by joshtrichards** [comment]
@dewi-ny-je https://github.com/nextcloud/android/?tab=readme-ov-file#logs

**Comment by demaniak** [comment]
> If you one of you is able to provide logs + the exact settings of all your enabled auto-upload profiles that would be helpful.
> 
> Otherwise there isn't much to go on here, unfortunately.
> 
> There have also been quite a few changes all throughout this area of code since these original reports.

I can chime in here from a Samsung device perspective:
As best as I can make it out, somewhere along the line Nextcloud app lost filesystem permissions.
It is unclear to me if this happened because of OS updates (maybe permission model was changed?) or if the new (?) samsung-android "auto permission removal for unused apps" feature scraped nextcloud.

On my device, removing the app, then installing it again kicked of the permission request flows, and after granting everything, things started working again.

On a family member device, I then went looking for the permissions, manually granted them, and again, things started working again.

So at least for Samsung, as many, many other threads/issues point out:
- look out for the "battery optimizer" feature (it eventually prevents background running)
- and now it seems, also look out for the "auto remove unused app permissions" feature

**Comment by dewi-ny-je** [comment]
> I can chime in here from a Samsung device perspective: As best as I can make it out, somewhere along the line Nextcloud app lost filesystem permissions. It is unclear to me if this happened because of OS updates (maybe permission model was changed?) or if the new (?) samsung-android "auto permission removal for unused apps" feature scraped nextcloud.
> 
> On my device, removing the app, then installing it again kicked of the permission request flows, and after granting everything, things started working again.
> 
> On a family member device, I then went looking for the permissions, manually granted them, and again, things started working again.
> 
> So at least for Samsung ( as many, many other threads/issues point ou)t:
> 
> * look out for the "battery optimizer" feature (it eventually prevents background running)
> * and now it seems, also look out for the "auto remove unused app permissions" feature (which can cause all kinds of strange behavior/failure modes)

I have a Samsun A52s 5G and your solution doesn't work: battery optimizer was already off. Some permissions were not granted (like photos, which surprised me since auto-upload works most of the time), so I granted everything.

"Preparing to auto-upload" still shows up in the notifications, but at least no photo gets left behind, it's mostly an annoyance.

I'll have to try the procedure explained in the help page, which is quite involved but apparently the only way. I wish there were an "export logs"...

**Comment by realies** [comment]
Reopen the issue and plan for it.

**Comment by jacobq11** [comment]
This is still an issue!!!

**Comment by fromage9747** [comment]
So I began encountering this issue.  Thought it was because I was on an old server version.  Updated to the latest, issue persisted.  Gave up for a while but then I started using immich and I wanted to ensure that all my photos had been uploaded correctly. As a troubleshooting step, I cancelled all pending uploads and then resumed them.  They started uploading!  This wasn't a permanent fix as the queue got stuck again, so I cancelled them again and resumed.  Keep on doing this when it gets stuck and you will be able to get through your "waiting to upload..." stuck queue. Hopefully this helps! Cheers!
