### ISSUE TITLE
Nextcloud custom Server URL Pre-enter on Android App

### ISSUE THREAD

**Issue by ShanJUN520** [nextcloud/android#11577]
Hi,
While developing android app for Nextcloud i want to pre enter our Nextcloud Server URL, so the user can directly login into to account without entering the Server URL.Even the setting
“show_server_url_input”>true when changed to false it still shows up when the app is executed on the android device.

**Comment by joshtrichards** [comment]
Disclaimer: I'm not officially affiliated with NC.

I presume you changed other parameters as well. Can you provide the actual parameters you used and rebuilt with that did not work?

Possible parameters:

https://github.com/nextcloud/android/blob/aa55dd63905c9be7b79c0899a8a43f5672fa4a4d/app/src/main/res/values/setup.xml

All of the logic is implemented here:

https://github.com/nextcloud/android/blob/aa55dd63905c9be7b79c0899a8a43f5672fa4a4d/app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java

And some of the info (error/success) messages here:

https://github.com/nextcloud/android/blob/aa55dd63905c9be7b79c0899a8a43f5672fa4a4d/app/src/main/res/values/strings.xml

If you discover an issue with this functionality and develop a fix, please contribute back via a PR.

There isn't any other documentation I'm aware of beyond the code itself.

There is also enterprise support which covers this need so that's another option:

https://nextcloud.com/branding/
https://nextcloud.com/blog/branded-nextcloud-clients/

**Comment by joshtrichards** [comment]
https://nextcloud.com/blog/branded-nextcloud-clients/
