### ISSUE TITLE
Feature Request: direct camera upload

### ISSUE THREAD

**Issue by meson11** [nextcloud/android#1158]
a feature included in the "plus" sign to directly shoot a foto and upload it, like facebook has it. would be nice for "scanning" invoices and other documents.

------
As wished by mail:
- go into a folder
- open camera, take a photo
- upload photo directly

This is the same like in whatsapp, dropbox.
We could do this in our FAB, and add it there.

**Comment by tobiasKaminsky** [comment]
This would lead to trouble if you also have enabled auto upload?
With enabled auto upload you would not have to open nc app to get your images uploaded, or am I overlooking here the use case?

**Comment by AndyScherzinger** [comment]
Not overlooking anything and yes auto upload could take care of this while it wouldn't be as instant. Such a use case is rather very user specific since you could argue the same case for videos and audios and notes which would put a special use case at a very general and prominent spot so I would advise against it.

**Comment by tobiasKaminsky** [comment]
Maybe we can solve this via a widget (as someone already planned it back in the old days):
while adding a widget the user can choose what the "+" button does
- take image and move to [locate remote folder
- ...

**Comment by meson11** [comment]
Auto upload is quite unspecific, it spams all pictures up.  And is this really a rare usecase? I it could be an easy way for many people to get their documents on a pc or just specific fotos.

**Comment by AndyScherzinger** [comment]
@nextcloud/designers @jancborchardt @MorrisJobke @tobiasKaminsky @mario I'd be happy to get your input on this :) Some time has passed since this request has been opened and right now I tend to change my original comment/opinion and would vote to add this feature (in the future). Since we now introduced the bottom sheet with the actions of the FAB I think it is valid and doesn't "polute" the menu.

**Comment by AndyScherzinger** [comment]
From what I understood it should then be possible to take several pictures in a row (that all get uploaded9, not just one at a time.

**Comment by jancborchardt** [comment]
Yup! This would be a nice addition, seeing how Dropbox for example also has this. :)

**Comment by tobiasKaminsky** [comment]
I have no real opinion on this ;-)

> From what I understood it should then be possible to take several pictures in a row (that all get uploaded9, not just one at a time.

This might be a little trickier…

**Comment by AndyScherzinger** [comment]
> This might be a little trickier…

Yes, this is the tricky part I guess but important nevertheless

**Comment by medcloud** [comment]
+1 for this feature : it would be great to have such a feature !

**Comment by oparoz** [comment]
Would be good to have to keep feature parity between platforms.

**Comment by AndyScherzinger** [comment]
I already started playing around with a possible implementation for this on a feature branch, see https://github.com/nextcloud/android/tree/cameraDirectUpload 

It is still a work in progress and only works for single photos, yet.

**Comment by AndyScherzinger** [comment]
implemented via #1782

**Comment by AndyScherzinger** [comment]
implementation #3467
