### ISSUE TITLE
Images not showing up in app

### ISSUE THREAD

**Issue by ahendre2010** [nextcloud/android#1160]
![img-20170702-wa0000](https://user-images.githubusercontent.com/20182133/27767667-38c3b774-5f1c-11e7-9539-ea2e3f386754.jpg)
### Actual behaviour
-Tell us what happens
Some auto-uploaded files cannot be shown.
I tried files scanning but nothing helped.
Also tried reinstalling app on android.
Also didn't found any help on this topic.

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 7.0

Device model: Moto g5 plus

Stock or customized system:

Nextcloud app version: 1.4.3

Nextcloud server version: 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Are the files correct uploaded, e.g. verify with web ui or with desktop client?
If you open nc app and navigate to the upload folder, what size do the images have? Can you delete them locally and re-download them? Does this help?

**Comment by ahendre2010** [comment]
I am normally keeping files in source folder. Files can be seen in web UI. In app removing them locally and re-downloading helped.
But there are lot of images which doesn't show up in Android app and I don't want to remove and re-download them it will take lots of time.
Can you please find a way to detect those files and automatically re-download them ?

**Comment by ChristianNext** [comment]
I only have this issues for InstantUpload.
Android icon-view is fine, but I cannot see the full image on Android "The image cannot be shown". The image is uploaded and can be viewed on server just fine.

When I manually upload an image the full image displays fine on Android and server.

**Comment by abnerf** [comment]
I see the same problem with AutoUpload. Here are some clues:

- The image is correctly uploaded to the server
- The image is shown as available locally in the nextcloud app with that small green check overlay (but it's not)
- The image file on nextcloud app shows OK, with it's size and everything. But if you explore the nextcloud app directory, the image file size is 0 (that's why it never shows anything)
- Selecting the file on nextcloud app and synchronizing it doesn't fix the problem
- The problem only happen on AutoUpload if the the "Keep original folder" is used. If selected "Move to app folder" the problem doesn't happen
- By "Deleting locally" through the nextcloud app and then downloading the image again fixes the problem

So, it seems that when you select "keep in original folder" on AutoUpload, the file is uploaded fine, but nextcloud app thinks it's also available locally, showing the green check overlay, when it's actually not, which honestly it's the right behavior IMO. For me the fix here is only to the app to consider that the image is not available locally, only in the server, removing the green check overlay from the image and not having a 0 size file in the app directly.

**Comment by mario** [comment]
Dear users,

thank you for your patience. After lots of work, we’re super excited to be able to give you a test version with new auto upload implementation. Keep in mind we will only accept bugs related to Auto Upload in this APK, as other things might be broken.

https://cloud.nextcloud.com/s/ftZraTruRQjTe0R

This is a dev APK so it will not overwrite your existing play store/f-droid APK unless you’re already running dev version. Also, you might need to remove your existing dev version before installing this one.

Explanation of the current functionality:
- added support for custom folders
- separated image and video folders
- checks for new files happens every 15-20 minutes
- automatic retry every 15-20 minutes or when you force close/open the app
- automatic pause once network is changed (untested!)
- significantly less battery usage

All and any testing is more than appreciated, especially with large and ever-going files like Videos. (like, try to record a 30 min video).

Let me know if you’ve got any questions.

Cheers,
Mario

**Comment by tobiasKaminsky** [comment]
Meanwhile we enhanced the app. Can you please try and report back if the bug still exists on latest official version or even try our [dev version](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release)?

**Comment by ati562** [comment]
I am experiencing a similar issue with autoupload:

Device:
* Android 7.0 on Samsung Galaxy S8
* Nextcloud v2.0.0

Autoupload is configured to:
* Upload only via wifi
* Upload to sub-folders based on date
* Move the image to app folder after upload

How to reproduce:

1. Take several photos while there is a wifi network available
2. Photos are successfully uploaded and moved to app folder
3. The recently uploaded photos are viewable with the Samsung Gallery app (even after their move to Nextcloud folder)
4. Start Nextcloud app and open the folder where the photos were uploaded

Issue:
After the target upload directory is opened in Nextcloud app, the following issues arise:
* The uploaded photos are visible in the Nextcloud app, but shown that they are available on the server side only - not locally
* The photos are somehow removed locally from the mobile, I need to dowload them from server
* Uploaded photos are not viewable (not available) in the Samsung Gallery app any more

Expected behaviour:
* The uploaded photos remain locally even if I check the target directory with the Nextcloud client
