### ISSUE TITLE
Crash during "share to nextcloud"

### ISSUE THREAD

**Issue by tstreibl** [nextcloud/android#11614]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment]
Hi @tstreibl - You'll have to provide more details, such as the stack trace from the crash.

Also, app version, etc.

**Comment by tstreibl** [comment]
Sorry - can't provide more technical insights as the issue was created automatically by the app.

The crash appears when I use the share feature from within some other app (in this case it was a whats app picture)  and choose to share some content to the  nextcloud app . When the nextcloud app pops up I trie to change the directory. In this moment the app immediately crashes. I can reproduce that (just tried it again before answering). My app version is the latest form app store: Version 3.25.0 from June 13, 2023. My phone is a Galaxy S5 - so might not be representative any more. Thanks for looking into it.

**Comment by joshtrichards** [comment]
Thanks for your response. The mentioned fix was merged, but a new official release with it hasn't been published yet. It'll be in the next one out.

You can also test the nightly image just to see if the issue is gone (if you are so inclined), but I'm not necessarily recommending that:

https://github.com/nextcloud/android/#development-version-hammer
