### ISSUE TITLE
PreviewText: extraneous ui elements shown

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/android#11700]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. set up nextcloud app with account
2. create empty `file.txt` in root directory
3. download file via three dots menu
4. open file (local editor)

### Expected behaviour

Text editor ui replaces previous ui.

### Actual behaviour

Some ui elements from previous screen remain visible, such as the display (List/Card view) and sorting options (*A - Z*). These elements do not perform any visible action.

Additionally, the *Search* icon, visible on the top right-hand corner remains on screen. Inserting any text into the provided search and returning using the back button will result in graphical glitches and eventually a list of search results being displayed. Now, one is unable to return to the main, unfiltered, view, as navigating back leads to the same screen. Further attempts to navigate anywhere result in a broken interface.

### Android version

13

### Device brand and model

OnePlus 6T

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

849799c

### Nextcloud server version

26.0.1

### Using a reverse proxy?

No

### Additional information

Custom OS: LineageOS 20.0

**Comment by parneet-guraya** [comment]
Hi, @AndyScherzinger @tobiasKaminsky. I have a solution which solves this issue (although the issue mentioned is for text previews but it was bigger than this), Just need suggestion if my approach is valid or not :-)

- So, from the main (`OCFileListFragment`) we have list of files and we can go to `DetailedFragment` from the overflow (three dots) menu and same way we can also go into detail while we're in the preview of that same file.

But, these two cases needs different handling. First of all the main view we have has it's `sortButton` visible and going from there to `DetailedFragment` changes the visibility to false (since we are not showing `sortButton` in this fragment). So when coming (onBackPress) if we don't do anything `sortButton`'s not visible (since we changed it while going in details fragment).
- Let's say we handle this by setting the visibility to true while coming back from the `DetailsFragment`.

Now, there's another problem. As I mentioned we can also access `DetailedFragment` from the preview fragment (which needs the `sortButton` visibility to false). So, when we press back button, it takes us to preview fragment which should not show the `sortButton` but it is showing now because now `DetailedFragment` set it to visible while popping out. There's no way we can determine which fragment will show after the detail fragment pops out, So we cannot handle individual case.

Cases like `DetailFragment` can make things out of sync hence this is happening. 

SOLUTION --> I chose to use a Stack Object in the Activity class (main activity for the main view `FileDisplayActivity`). This is how it will work -->
- Initially the `sortButton` is visible.
- When going into another fragment we will save the current visible status (true in this case) and then launch the fragment with new visibility.
- When coming back we will pop the element (visibility status -boolean) and use that to set the `sortButton` status.
### Example Below -->

![Initial Main view stack is empty](https://github.com/nextcloud/android/assets/111801812/2a9e5575-95a7-4b38-b4a6-167505ef444c)
