### ISSUE TITLE
App can not access external sub folder

### ISSUE THREAD

**Issue by draekster** [nextcloud/android#11751]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Connect an external storage (SMB/CIFS share, e.g. pictures) from the root account of Nextcloud server.
2. Use for this external storage a sub folder (e.g. Handy/SOMEUSER/DCIM).
3. Use folder name Photos (this overwrites the original Nextcoud folder).
4. Assign this external storage to a user.
5. In a browser, login to Nexcloud as user.
6. Look for the Photos folder.

The Photos folder should exist an point to the external storage.

7. Use the Nextcloud Android app and look for the folder Photos.

The Folder seems to be connected but is empty.
There are also no uploads possible.

### Expected behaviour

Like in step 6. the folder Photos should be acessable in the Android app too.

### Actual behaviour

The Folder seems to be connected but is empty.
There are also no uploads possible.

### Android version

13

### Device brand and model

One Plus 8 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.0.0

### Using a reverse proxy?

Yes

### Android logs

[logs.txt](https://github.com/nextcloud/android/files/11782229/logs.txt)

### Server error logs

```bash
172.19.0.2 - anon [18/Jun/2023:17:18:39 +0000] "PROPFIND /remote.php/dav/files/anon/Photos/ HTTP/1.0" 207 1989 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.25.0"
172.19.0.2 - anon [18/Jun/2023:17:18:40 +0000] "PROPFIND /remote.php/dav/files/anon/Photos/ HTTP/1.0" 500 985 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.25.0"
```

### Additional information

I use LineageOS 20-20230611-NIGHTLY-instantnoodlep.
But I have the same problem on a Samsung Galaxy A41 with Stock Android 12.

The logfile is from the development version. Same problem.

**Comment by joshtrichards** [comment]
Hi @draekster - Can you post the associated server-side `nextcloud.log` entries? Your web server logs indicate a 500 error was thrown. We need to see what's going on on the server side.

**Comment by draekster** [comment]
Hi @joshtrichards,
thank you for your response.
I've attached the nextcloud.log from today.

The problem occurs at 2023-07-12T17:44:14+00:00 (line 16513).
Just before i tried it with the app, i tried it with the browser. Here i had no problems and also no log entries.

[nextcloud.tar.gz](https://github.com/nextcloud/android/files/12030960/nextcloud.tar.gz)

**Comment by joshtrichards** [comment]
Technically I think this problem isn't in the client, but it happens that the client is apparently a bit more sensitive to it. The `server` is having problems getting some attributes about the files accessed via SMB. 

The underlying cause, however, is more mysterious. The trigger is we're not receiving the `attributes` data we expect from the smbclient (or we're not able to parse it for some reason).

I do note you're using the wrapped smbclient rather than the native one. That requires weird parsing hacks (where this issue happens to be occurring). 

Any chance you can switch your NC server's smbclient to the native one to see if it resolves the problem for you (the native one is more reliable and higher performing so I'd recommend it anyway)?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/smb.html?highlight=smbclient

**Comment by draekster** [comment]
Thank you,
this seems to work.
I had to enable the PHP module.
https://github.com/nextcloud/docker/tree/master/.examples#php-module-smbclient

Now I can access the Share and can also up/download as before.
