### ISSUE TITLE
Crash when opening remote image in nextcloud-dev

### ISSUE THREAD

**Issue by agilob** [nextcloud/android#1184]
### Actual behaviour
-Tell us what happens
App crashes when opening an remote image

### Expected behaviour
-Tell us what should happen
dont crash
 
### Steps to reproduce
1. click on remote image 

### Environment data
Android version: 6.0.1
Stock or customized system:stock

Nextcloud app version: nextcloud-dev from fdroid

Nextcloud server version:11

**Comment by tobiasKaminsky** [comment]
This should be fixed in https://github.com/nextcloud/android/commit/ac1984bf4289d0d9edf77b87e96e5be6b36e940c, which is dev-20170711, but frdoid is somehow slow these days. So you'll have to wait some time...
Alternatively you can download the latest here: 
https://download.nextcloud.com/android/nightly/latest.apk but then you have to reinstall the app as it is different signing key.
Can you report back once it is working? :+1:

**Comment by agilob** [comment]
> Can you report back once it is working? 👍

sure, waiting for update.

**Comment by dom11990** [comment]
Had the same issue. Upgrading to the version in your link resolved the issue.

**Comment by tobiasKaminsky** [comment]
It now also works again on the current fdroid version.
