### ISSUE TITLE
client crashes upon first open

### ISSUE THREAD

**Issue by keunes** [nextcloud/android#1197]
I installed Nextcloud client 1.4.2 via F-Droid on my phone. It does ask permission for folders, but then crashes ('Nextcloud has stopped'). It does the same after having given the folder permissions. In the background (behind the error) I can (sometimes) see the login screen.

After having installed a legacy version (1.4.1) from F-Droid, start-up works perfect. Then, after updating again via F-Droid to 1.4.2, it crashes upon startup.

### Environment data
Device: Fairphone 2
OS: Fairphone OS 17.04.8 (Android 6.0.1)
Nextcloud app version: 1.4.2

**Comment by tobiasKaminsky** [comment]
This is fixed in 1.4.3 on play store, but due to library licence problems it is omitted on fdroid. You can either use the dev version on fdroid or try changing the lanuage to english (american one) and then start the app one time and then you can switch back.
This might help.

As the bug is fixed and there will soon be a 1.5. version, I will close this one.
