### ISSUE TITLE
Integrated Services

### ISSUE THREAD

**Issue by affanse** [nextcloud/android#121]
Too much setup like owncloud. Davdroid for cal, card, tasks. Notes and files is another sync adapter. 

I'm a big note taker, everyday I'm using grauphel tomboy sync server to sync across multiple devices.

If there is any possibilities, please, please add one account for multiple services. Thanks.

**Comment by felisucoibi** [comment]
agree, at least contacts, card and tasks would be nice to not have to install different apps like davdroid that is good anyway.

**Comment by Hanzei** [comment]
We could add more links to other apps under Settings -> More. So people didn't had to search for a app to sync tasks.

**Comment by tobiasKaminsky** [comment]
This is a very promising idea: https://github.com/David-Development/ownCloud-Account-Importer/issues/3

**Comment by xXSTrikeXx** [comment]
refer: #1694

**Comment by joshtrichards** [comment]
> If there is any possibilities, please, please add one account for multiple services. Thanks.

The original scope of this Issue (integrated authentication) seems to have been addressed. There are other issues for tracking additional app ecosystem integration, plus numerous improvements in that area have occurred since this issue was created. Closing since I don't see anything still actionable in this issue alone.
