### ISSUE TITLE
Auto-upload working for photos, not videos

### ISSUE THREAD

**Issue by locksec** [nextcloud/android#12347]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Taking a photo triggers an auto-upload instantly
2. Recording a video is not triggering auto-upload of the video
3. Tried using the Google Camera which uses a prefix PXL_(E.g. PXL_20240108_001526696.mp4) and the stock camera which has a VID_ prefix. Doesn't make any difference
4. Disabled "Pause app activity if unused"
5. Tried disabling Battery Manager

Unsure if this is only happening on GrapheneOS, or this specific version of Android.

### Expected behaviour

Videos should upload

### Actual behaviour

No videos are uploaded

### Android version

14

### Device brand and model

Pixel 8 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

27.1.5

### Using a reverse proxy?

I don't know

### Additional information

Running latest version of GrapheneOS

**Comment by joshtrichards** [comment]
Do you have two auto-upload profiles configured - one for images and another for videos - or just one?

**Comment by joshtrichards** [comment]
@neoriae Sounds like a reasonable idea. Would you create a dedicated issue containing your enhancement idea so it doesn't get lost in this one?

**Comment by blkhawk** [comment]
While it is likely that GP had just not added the folder for video files I had something similar happen to me on a recently installed grapheneos and thats why I thought I mention it for the record. Basically the Nextcloud app stopped uploading my pictures and videos eben tho I have a similar permissive setup as GP. 
I noticed that in the Auto Upload configuration folders were offered that I had already deleted with thumbnails of images I had also already deleted. Force stopping the Nextcloud app made those go away but new pictures were still not uploaded but strangely one of the pictures showed up in the autoupload view but again was not synced. I have 3 camera apps installed on the phone and i made pictures with two of them as a test. 
I think what happens is this: the nextcloud app cannot properly deal with multiple apps if they all point to the same directory for upload. This is a bug I think probably with how Android deals with file access permissions. A workaround might be to just use different folders for each app.
Why does this happen in grapheneos? Frankly because the Camera app is a bit barebones and that prompts people to install OpenCamera and/or Pixel Camera. My guess its not something tested.
