### ISSUE TITLE
Automatic Upload is prepared

### ISSUE THREAD

**Issue by LunaticTazz** [nextcloud/android#12596]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Set up Automatic Upload for in total four folders.
From time to time a notification is present on Android, that the automatic upload is prepared (German version "Automatisches Hochladen wird vorbereitet"). A progress bar is at min, the message disappears after a while and is retriggered from time to time. According to Android it pops up about 80 times a day.
Mobile background data is allowed, but uploads are only allowed on a WiFi network.
In addition to this, mobile data is consumed, but no files seem to be uploading. There's no files in the upload queue, there is nothing arriving on the server.
It is unknown to me, which files caused this behavior, but it's also present with only the photo folder being on automated upload (the other three have been deactivated).

### Expected behaviour

Wait for WiFi to upload the files and be quiet if there is nothing to upload. No usage of mobile data.

### Actual behaviour

Constant notifications, decreased battery life and mobile data consumption.

### Android version

Android 11

### Device brand and model

moto G 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

26.0.10

### Using a reverse proxy?

No

**Comment by davidcrds** [comment]
I have the same issue on Android 14 (S22+). Auto Upload still works fine, but it keeps trying to do something which drains battery. 

Running Nextcloud AIO currently on Version 27.1.5 on the Server.

**Comment by kadrim** [comment]
I have the same issue. It appeared a few days ago, most probably due to an update of the android app

- samsung note 9
- android 10
- nextcloud server 28.0.2

**Comment by steel-moose** [comment]
Same issue here.

- android 9
- nokia 8 (HMD TA-1004)
- version 3.28.0
- nextcloud snap 27.1.6

Seems to be draining the battery much faster.

**Comment by regs01** [comment]
Also stuck for over almost a day now.
<img width="712" alt="firefox_2024-02-25_19-36-18" src="https://github.com/nextcloud/android/assets/10468217/eb7a9cce-cbe1-462a-9fc3-9bc7b2cd5d69">

The problem with permanent scanning draining the battery has been there for very long. They just made a visible notification, so now those having the problem can see there is a problem.

**Comment by davidcrds** [comment]
> Also stuck for almost a day now.
> <img width="712" alt="firefox_2024-02-25_19-36-18" src="https://github.com/nextcloud/android/assets/10468217/eb7a9cce-cbe1-462a-9fc3-9bc7b2cd5d69">
> 
> The problem with permanent scanning draining the battery has been there for very long. They just made a visible notification, so now those having the problem can see there is a problem.
> 

Removing bigger folders from Auto Upload shortens the notification considerably. So you are probably right.

**Comment by regs01** [comment]
And past the 17 hours it's still there in same position.

**Comment by JustACasual** [comment]
I am also having this exact behaviour "Automatisches Hochladen wird vorbereitet" which appears from time to time.
App Version 3.28.0 from F-Droid
Android 13
Pixel 4a

**Comment by regs01** [comment]
> I have removed all folders from auto upload, I have disabled background data for the app, it's still scanning.

It stuck in some loop. Reboot the phone to have it restarted.

**Comment by vanMacG** [comment]
Since 3.28.0 I also see the "Prepare automatic update" notification several times a day, although I don't have any folders configured for automatic upload.
There was no notifiaction in previous versions.

**Comment by LunaticTazz** [comment]
> > I have removed all folders from auto upload, I have disabled background data for the app, it's still scanning.
> 
> It stuck in some loop. Reboot the phone to have it restarted.

I have cancelled all my Auto uploads, I have restarted the phone, the notification still pops up.

**Comment by el-kute** [comment]
I have the same issue

- Samsung Galaxy SIII neo and Google Nexus 7 (2013)
- both on Lineage 18.1 / Android 11

The problem stopped when reverting the Nextcloud app version back to 3.27.0 (using `adb install -d nextcloud-3.27.0.apk` from f-droid)

**Comment by marcdw1289** [comment]
In the app under Settings -> More subsection -> Auto Upload is all the directories with images.

They are all toggled off but I guess the app does a check and hence the 'preparing' notifications (I think).

However, on my Android 8 and 9 ROMs I do no get these notifications. Only on A11. Don't have A12+ but assume this is an A11+ thing maybe. My A10 ROM doesn't have Nextcloud so haven't checked yet.

**Comment by supern64** [comment]
same issue here, Galaxy A53, Android 14, Nextcloud AIO 27.1.5

**Comment by iGaneshKumar** [comment]
![Nextcloud Auto Upload Notification](https://github.com/nextcloud/android/assets/121607014/e369a60d-d5a9-462a-8933-36f2d01b48e4)

Same here, I should say I started using recently and from the very beginning I've been experiencing this issue.

Nextcloud Server Version: 28.0.2
Device Brand and Model: Samsung S9 Plus
Android Version: 10
Nextcloud Android App Version: 3.28.0

**Comment by symetryczny** [comment]
Same here, the notification started popping up a few days ago. Possibly when I updated the nextcloud app to the newest version but I cannot confidently confirm that.

Samsung S22FE
Android 14
Nextcloud app 3.28.0 downloaded from f-droid

**Comment by pglpm** [comment]
Same issue here, on Android, with Nextcloud 3.28.0 from F-droid. Most important is that **no** folders are chosen for autoupload in the settings; yet I see this recurring message. Uninstalling Nextcloud app until this problem is fixed.

**Comment by vabene1111** [comment]
Same issue on android 14 one plus 10. 

Also, something is wrong with power consumption, 1 hour of the cable, 10% battery used and 6% went to nextcloud without any sync that could even happen.

**Comment by antoineguichard** [comment]
I have the same issue (Notification "Preparing auto upload" appearing most of the time). 
On three phones of the same model and running the same software versions.
From what I can figure out, it appeared right after NC app upgrading to 3.28.0.

Honor 10 lite (HRY-LX1)
Android 10
NC app 3.28.0
![Screenshot_20240305_091432_com nextcloud client_preparing-auto-upload](https://github.com/nextcloud/android/assets/35461971/3e1a4fbe-ffe1-489b-94ab-374f97db27f9)

**Comment by meonkeys** [comment]
I'm able to get rid of the "Preparing auto upload" notification temporarily if I disable Battery Saver and force kill the app.

I recall I'm supposed to leave the Nextcloud app battery usage set to "Unrestricted" but I noticed it draining my battery a few weeks ago so for now it is "Restricted".

**Comment by JonasMayerDev** [comment]
Hi all, thanks for the report. 
### Analysis
Yes, this behavior of showing a notification when ever sync work is done (so also checking if files need to be uploaded) was introduced in https://github.com/nextcloud/android/pull/12337. The idea behind it was to make the autoupload more reliable and a lot faster because there were cases where the background worker was killed by android and the sync didn't work because of this. In theory, as some already said, the notification should only visualize what was already happening in the versions before. I would say there are 3 issues with this implementation currently: 
1. Worker runs without auto upload activated when auto upload was activated before (issue probably existed before but was never visible).
2. I think the sync worker runs too often (I would guess that is the reason you see the notification all the time, I guess that the sync worker just executes again and again and is always showing the notification)
3. The new foreground worker consumes too much energy (This is also just a guess, but I think changing the sync worker to a foreground worker results in higher batterie usage because the worker is not randomly killed by the android system. This is on one side good for reliability of the sync but bad for the batterie consumption)
I actually have not looked into it deeply yet, so those are just some guesses that need to be confirmed.
### Question
It would help if you could answer some questions to confirm / fix those issues more quickly:
1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?
2. How large are the folders for which auto upload is activated (rough folder size and file count)?
3. Was autoupload before this update unreliable for you?
4. For those that have a notification that sticks for longer than 5 min, is it stuck from the first time appearing or is it first behaving normally (so appearing for short times and disappearing again) and then at some point it is stuck? Do you have a way to reproduce the issue of a stuck notification?

**Comment by kadrim** [comment]
> 1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?

N/A

> 2. How large are the folders for which auto upload is activated (rough folder size and file count)?

120 GB, 100K+ Files

> 3. Was autoupload before this update unreliable for you?

Many times, but was pretty stable until the upgrade to app version 3.28.0

> 4. For those that have a notification that sticks for longer than 5 min, is it stuck from the first time appearing or is it first behaving normally (so appearing for short times and disappearing again) and then at some point it is stuck? Do you have a way to reproduce the issue of a stuck notification?

it seems to be stuck right away. hard to reproduce other than to reboot the phone and taking a picture or something like that.


Notice: i only let the sync happen during charging of the phone for all of my folders, so i thought the scan would only initiate while charging. currently it seems, that the scan will run all the time which might contribute to the high power usage, which might have been handled differently in the previous versions where the scan might have been run only when the phone was charging (and configured to sync only while charging)

**Comment by LunaticTazz** [comment]
>     1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?

Yes, 4 uploads folders had been defined, although one was used twice, once for images once for videos.

>     2. How large are the folders for which auto upload is activated (rough folder size and file count)?
Enormous in size: The largest was 16 GB with over 4000 files.
>     3. Was autoupload before this update unreliable for you?
Yes, close to no issues. Sometimes you had to rebump it if it has lost connection or anything minor had happened. But that was easy to check in the upload section.
> 
>     4. For those that have a notification that sticks for longer than 5 min, is it stuck from the first time appearing or is it first behaving normally (so appearing for short times and disappearing again) and then at some point it is stuck? Do you have a way to reproduce the issue of a stuck notification?

It was shorter before I intervened. That's when the traffic even on mobile data was excessive, as well as battery usage. I have unchecked the background data for the app and I have unchecked the battery optimization. Since then the progress bar is completely stuck and does not go away until you kill the app, but then it reappears after some time.
Before that it came and went away after a short period if I remember correctly.

**Comment by cvonderstein** [comment]
> How large are the folders for which auto upload is activated (rough folder size and file count)?

Something along the lines of 70-80 GB, probably about 10-20k files (mainly my images on the phone)

> Was autoupload before this update unreliable for you?

Didn't work perfectly, but I also didn't disable battery optimization, since I was too lazy to search in the settings (seems like this is kind of hidden on current samsung phones, or I am just blind). My workaround if I really needed something uploaded directly was to quickly open the app, then it was uploaded. As I said, I was just too lazy to look for the battery optimization setting.

> For those that have a notification that sticks for longer than 5 min, is it stuck from the first time appearing or is it first behaving normally (so appearing for short times and disappearing again) and then at some point it is stuck? Do you have a way to reproduce the issue of a stuck notification?

It comes randomly and doesn't disappear at all. I can swipe it away, but then it reappears after a while. Reproducing is simply waiting something between 2 hours and 1,5 days I would guess. Not helpful for debugging, but that's how it appears to me. Opening the app is not neccessary though.

**Comment by paulchen** [comment]
> 1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?

As I installed the app long time ago I didn't know. I cleared the app data and then configured my two accounts. I did not configure auto upload.

After some time, the notification "Preparing auto upload" appeared. It is a sticky notification that I cannot get rid of. I need to kill the Nextcloud app to make it go away.

> 4. For those that have a notification that sticks for longer than 5 min, is it stuck from the first time appearing or is it first behaving normally (so appearing for short times and disappearing again) and then at some point it is stuck?

It appears after some time for no apparent reason.

> Do you have a way to reproduce the issue of a stuck notification?

Unfortunately, no, besides setting up the app and waiting.

**Comment by JustACasual** [comment]
For me also auto upload is doing fine, I just find the notification every few minutes annoying. Not so bad though.
It stays for a few seconds on my device. Then it goes away.

**Comment by JonasMayerDev** [comment]
Hi, do you all use custom folders (create new custom folder from the 3 dot menu) for auto upload or did you just activate auto upload for the automatically detected media folders? In general do you just backup images and videos or do you also auto upload other file types like documents=

**Comment by vanMacG** [comment]
>1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?

I can't remember having it activated in the past... nevertheless I just deinstalled the app and did a fresh installation. The notification didn't show up in the last minutes, so this seems to "fix" the issue.

**Comment by vanMacG** [comment]
> > 1. For those that see the notification without autoupload activated, did you all have it activated at some point in the past or do you even see the notification on a clean installation for example?
> 
> I can't remember having it activated in the past... nevertheless I just deinstalled the app and did a fresh installation. The notification didn't show up in the last minutes, so this seems to "fix" the issue.

And there it is again... So no, notification also on a fresh installation without autoupload activated even once.

**Comment by beardhatcode** [comment]
I also see this issue on A Samsung Galaxy S10+ (Android 12)

**Comment by JonasMayerDev** [comment]
Hi, in the latest 3.28.1 release there is a fix that maybe helps with this issue. Can you check if the problem has decreased? We don't expect a complete fix, the question is if it is better than before (3.28.0) or not, to see if we work on the right places.

**Comment by GanterFengDavid** [comment]
Same issue here with Xiaomi 14, HyperOS 1.0.31.0, Android 14

**Comment by reox** [comment]
I have not seen the message yet with 3.28.1 (I had it like every hour or so before and it would not go away on a Pixel 7 / Android 14) but instead some photos are upload much later than before. They are not even scheduled to upload right away. So far, it looks like all of them were uploaded eventually, thus no photo is lost, but it takes much longer than before.

**Comment by reox** [comment]
I saw the message not once in 3 weeks and now it's back with 3.29.0

**Comment by ghaberek** [comment]
> I saw the message not once in 3 weeks and now it's back with 3.29.0

Can confirm this issue was gone while on 3.28.1 and has since returned with 3.29.0. I am on Android 12 on OnePlus Nord N20.

**Comment by ezelbanaan** [comment]
> I saw the message not once in 3 weeks and now it's back with 3.29.0

Same here

**Comment by markthebro** [comment]
Couple of days ago I did an update to V3.29.0.
My friends and family as well.
Before we were using V3.28.2 - no issues at all.

Since V3.29.0 every ~ 30min a notification appears that an auto-upload is in preparation even though there is nothing to upload.
Issue is on several different phones.

- Samsung Galaxy S23 (Android 14)
- Samsung Galaxy A51 (Android 14)
- OnePlus Nord (Android 11)

I think no more details need to be added - if so, please do not hesitate to ask for more infos, like logfiles, configuration etc.

**Comment by JonasMayerDev** [comment]
Hi, yes, we are aware of this. The "fix" in V3.28.2 was a bug that reduced reliability (to the point it was before 3.28), because it removed the foreground worker (basically a prioritized worker that needs to show a notification to run). We are trying to get rid of the foreground worker (https://github.com/nextcloud/android/issues/12954) but it is not that easy while maintaining and guaranteeing reliability.

Just FYI the notification has nothing to do with upload, it shows when the file system is scanned for changes. Maybe the text was not well-chosen.

**Comment by paulchen** [comment]
> Just FYI the notification has nothing to do with upload, it shows when the file system is scanned for changes. Maybe the text was not well-chosen.

But why does the app scan the file system at all if "Auto Upload" is disabled? Or has that behaviour already been changed?

**Comment by reox** [comment]
At least I noticed that with the new version, the notifications are visible much less often and typically also disappear on their own. Before 3.28.1 they would be persistent for me.

**Comment by vabene1111** [comment]
Not sure if its relevant but on 3.29.0 even tough the phone is not charging and I have automatic upload set to run only when charging the notifcation is popping up every few hours. Its also still the case that nextcloud is responsible for the majority (1/4 of total usage, usually highest app consumption) of my battery usage (no change between automatic upload with or without charging). 

I have two folders synced, one with just a few hundred, one with several thousand images.

**Comment by JonasMayerDev** [comment]
@reox That's wonderful to hear. We did a lot of optimization for auto upload to make the issue less annoying, and it's nice to hear that it at least helped a little bit. 

@vabene1111 @paulchen good point, I included fixes for that in this PR: https://github.com/nextcloud/android/pull/12372 With it, it should only scan the file system if charging when "only when charging" is activated :)

**Comment by billie80** [comment]
> @vabene1111 @paulchen good point, I included fixes for that in this PR: #12372 With it, it should only scan the file system if charging when "only when charging" is activated :)

If I did not get this wrong this fixes would only apply to custom auto upload folders. If no folders are defined it should not scan at all I guess?

Under "More - Auto upload" I did not define any folders and "Show media scan notifications" is disabled so media folders aren't scanned and thus also not shown as auto upload folders.

Still with this settings from time to time the "Prepare automatic update" notification appears. This is with the Nextcloud App Version 3.29.0.

**Comment by JonasMayerDev** [comment]
@billie80 it should with this fix also not do anything if no auto upload folder is enabled.

**Comment by JonasMayerDev** [comment]
With https://github.com/nextcloud/android/pull/13015 we removed the foreground worker and with it the notification "Preparing auto upload" 🥳

There is the risk that with the change the auto upload is a little bit more unreliable since android background restrictions could act harder on our background jobs. As they did before introducing background worker and the according notification -> So if it was without that notification reliable then it still should be. 

I would consider this issue closed since the notification is gone in the next releases. Thanks for reporting this. If there should be other issues with auto upload and / or significant reduction in reliability, please open another issue about it and feel free to connect it to this issue or the PR.

**Comment by billie80** [comment]
Still happens with 3.29.1!
