### ISSUE TITLE
Server under maintenance mode

### ISSUE THREAD

**Issue by jadjoud** [nextcloud/android#12709]
### Is your feature request related to a problem? Please describe.
I can't connect to nextcloud android using android emulator on windows, first i set up the server with docker and i opened the dashboard but when i try to connect using the URL it says "server on maintenance mode" even though everything is local.

### Additional context
I also checked the config.php file and made sure that the maintenance mode was set to false.

![image](https://github.com/nextcloud/android/assets/118366366/61935896-878a-453c-abd2-86d87fc187bf)

and for IOS I get this:
![431169851_349525900778672_7603892023229838189_n](https://github.com/nextcloud/android/assets/118366366/dcf70c9a-85af-4694-889b-0ddfae07fc84)

**Comment by AndyScherzinger** [comment]
can it be, looking at the browser screenshot that the service is running on http, while the URL on the Android screenshot points to https. So if the local server doesn't run on https with a SSL certificate, than that is the issue why you can't connect.

**Comment by jadjoud** [comment]
Hello
Thank you for your reply

Yes i noticed that and i fixed it and im connecting through the right url
But the issue now is that i get a message saying "the server is under maintenance"

Even on the ubuntu shell it shows the connection attempt

Can you help me ?

Best Regards,
Jed Boulahya
________________________________

**Comment by AndyScherzinger** [comment]
I personally can't, but maybe @tobiasKaminsky @ZetaTom @alperozturk96 maybe.

**Comment by joshtrichards** [comment]
It appears you're trying to *not* use HTTPS, correct?

Enter the URL in the client as `http://192.x.x.x`.

Port 80 will be assumed.

Though you may be dealing with multiple issues from the looks of it. Since `/status.php` is definitely return 503 per your logs.

What do your actual Nextcloud Server app container logs show for those transactions? Also, your server `nextcloud.log`?

**Comment by ZetaTom** [comment]
As @joshtrichards pointed out, the Android app will assume HTTP***S*** when entering a domain name or IP address. This won't work, if the server/proxy isn't set up to handle secure connections. If you want to connect to your local instance for testing purposes via an *in*secure connection, you'll have to specify `http://` as the protocol explicitly (e.g. `http://192.168.1.12` in your case). Otherwise a secure connection is *always* recommended. For more information on how to correctly set up a reverse proxy for Nextcloud, please have a look at our [documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html) and the corresponding docs of your proxy.

Another thing to consider is that the Nextcloud server keeps a list of domains from which you are allowed to connect. If the url doesn't match that domain, the server will throw an error. This value can be set via `occ` and is called `trusted_domains`. To allow *all* domains to connect, which is *absolutely **not*** recommended for production environments but useful for testing, run the following command. Please keep in mind that proper firewall rules should be in place.

```sh
# DO NOT USE IN PRODUCTION ENVIRONMENT!!
php occ config:system:set trusted_domains 0 --value=*
```

**Comment by jadjoud** [comment]
> It appears you're trying to _not_ use HTTPS, correct?
> 
> Enter the URL in the client as `http://192.x.x.x`.
> 
> Port 80 will be assumed.
> 
> Though you may be dealing with multiple issues from the looks of it. Since `/status.php` is definitely return 503 per your logs.
> 
> What do your actual Nextcloud Server app container logs show for those transactions? Also, your server `nextcloud.log`?

Where can I find this because I used the development server doc

**Comment by joshtrichards** [comment]
> Where can I find this because I used the development server doc

In your Nextcloud Server installation's data directory (at least by default) as well as in the Web UI under *Administration settings -> Logging*

**Comment by joshtrichards** [comment]
Closing this since there's nothing actionable here to track. If you need further general troubleshooting assistance, I encourage you to use the dedicated channels for that - e.g. help forum (https://help.nextcloud.com).
