### ISSUE TITLE
Remove "On device"

### ISSUE THREAD

**Issue by mario** [nextcloud/android#1270]
- [ ] - remove "On device" support
- [ ] - add support for folder synchronization
- [ ] - automatically synchronize favorite files & folders

**Comment by OlivierS1** [comment]
@mario I kind of like having the "On device" option, especially since it has been reworked to work on NC Dev.
As of NC Dev 20170805, "On device" only shows folders and files which have been downloaded. It will not show thumbnails.
When potentially running out of memory on device, this feature will find itself handy to check and remove no longer needed files on the devices.

Maybe you have other solutions in mind.

**Comment by mario** [comment]
@OlivierS1 we will now only show files that you currently see "On device" when offline. This is the joint approach by iOS & Android app, and makes quite a lot of sense.

Maybe we can add tag support to search or something...

**Comment by OlivierS1** [comment]
@mario You got me confused.
On NC Dev 20170805, only files that are already downloaded on device show in the "On device" menu.
All the thousands of folders and document that exist on server but have not been synchronized with device no longer show in the list. This behavior was corrected after posted this post:
https://github.com/nextcloud/android/issues/1062

**Comment by mario** [comment]
We're both confused looks like ...

This issue is partly related to:
https://github.com/nextcloud/android/issues/1143

**Comment by vondes** [comment]
How i can do that with https://mobile-phone-tracker.org mobile recorder ?

**Comment by tobiasKaminsky** [comment]
For the first point we already have #1143 
The second and third point seem to be independent from "remove on device" title and should have both separate issues, or?

**Comment by mario** [comment]
@tobiasKaminsky it's all VERY related so I think one issue makes sense.

**Comment by mario** [comment]
Feel free to change the issue & open new issues if you feel otherwise.

**Comment by tobiasKaminsky** [comment]
Maybe it is related, but from the sort bullet points without any further infos I do not see the relation.

As I understand/imagine it:
- add support for folder synchronization: 2 way sync (upload/download files, resolve conflicts)
- automatically synchronize favorite files & folders: global, all favorited files should always be up-to date (this is currently "keep up to date". I remember that @jancborchardt wanted this change long long time ago)

If this is correct, then at least different PRs are needed, otherwise we get a nightmare PR ;-)

**Comment by mario** [comment]
True that we need more than 1 pr to solve this issue, but it makes sense to
track it all in one ticket.

**Comment by OlivierS1** [comment]
@tobiasKaminsky I am not sure I want to synchronize my favorite folders, at least not all of them.
I have a Photo folder which is in excess of 200GB and I place it as one of my favorite so I don't have to search in my hundreds of folders.
If synchronization means downloading all the favorites, then my phone will not have the required storage capacity.
However, I wouldn't mind thumbnails be generated. To me it makes more sense.
To keep folders and document synchronized and available on phone, then my understanding is that "Available offline" already takes care of this scenario.

What do you think?

**Comment by jancborchardt** [comment]
> we will now only show files that you currently see "On device" when offline. This is the joint approach by iOS & Android app, and makes quite a lot of sense.

@mario can you elaborate here? I hope it doesn’t mean that when you are offline, the »All files« view will only show files which you already have on the device. Cause that would be confusing as hell. ;)

**Comment by mario** [comment]
@jancborchardt why is it confusing? It would clearly show that you are offline.

**Comment by jancborchardt** [comment]
Because even though I am offline, I want to browse all my files:
- It doesn’t seem like I suddenly lost data, just because I’m offline
- All files provide an important anchor to where I’m at
- I might want to delete files, regardless if they are on the device or not – which should absolutely be possible

Being offline is not something special. It happens all the time, due to being in a train, plane, being in a different country, or just the connection dropping. It shouldn’t change the entire appearance of the app. "On device" totally makes sense as a filter, but not as a default view I’m dropped into.

**Comment by mario** [comment]
I agree partly, but:

- separate filter is pointless
- to achieve offline file(s) navigation syncing needs to be fixed

**Comment by jancborchardt** [comment]
Well, my main point is that we should definitely _not_ hide other files when offline. That's the most important thing.

**Comment by OlivierS1** [comment]
@jancborchardt Agree 300%

**Comment by tobiasKaminsky** [comment]
> Well, my main point is that we should definitely not hide other files when offline. That's the most important thing.

If device is offline: grey out those files that are not available?
We could also sort the downloaded files to be on top?

**Comment by jancborchardt** [comment]
Greying out seems ok, also thought about that. It basically emphasizes the sync state icons.

But no different sorting. As said offline should not be treated like a special or error case, cause it can happen all the time due to different reasons.

**Comment by gjanssens** [comment]
>     * I might want to delete files, regardless if they are on the device or not – which should absolutely be possible

I'm particularly interested in  being able to delete files from server even when off-line. Are there plans to support this ? Other than the short mention on this issue I didn't find a formal enhancement request for it.

**Comment by jancborchardt** [comment]
@gjanssens agree, but it’s a lot of work. The most related issues are https://github.com/nextcloud/android/issues/1143#issuecomment-322188754 and https://github.com/nextcloud/android/issues/1008

**Comment by gjanssens** [comment]
Ok thanks.

**Comment by o0donder0o** [comment]
Is the delete on device pictures feature (after succesfull upload) still on the roadmap for the Android app? 

Pictures take most space on my device and i don't want to risk losing pictures that cannot be synced for any reason.

**Comment by tobiasKaminsky** [comment]
> Is the delete on device pictures feature (after succesfull upload) still on the roadmap for the Android app?

This is already in. You can specify what happens after a successful auto upload.
Other than that, we plan to keep "on device".
Part 3 is also already done, in terms of "sync downloaded files".
Part 2 can be found here #19
