### ISSUE TITLE
NC Assistant - Task list items are too large

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/android#12853]
Even if the items are expandable, the collapsed items are still very large. Collapsed size should be reduced by a lot, and iOS and Android should look similar. @alperozturk96 let's sync on this.

<img width="452" alt="image" src="https://github.com/nextcloud/android/assets/6960329/6217f7fe-eb19-4ee5-9e8a-dbf2b6f7558a">

**Comment by alperozturk96** [comment]
@mpivchev font size is 12sp and output text is 100dp in Android and I used scrollable TextView so no need to expand all. User can scroll screen and text itself. Also I removed expand and collapse icons because no need for them anymore.

Here is demo:

https://github.com/nextcloud/android/assets/67455295/3ccae32b-09a9-4fbe-8f36-7e2a66c38d40

**Comment by mpivchev** [comment]
On IOS we have a separate screen for reading the details, IMO it's much better this way.
 
https://github.com/nextcloud/android/assets/6960329/416b57a8-9484-49a3-84c6-991ae1a1b438

**Comment by alperozturk96** [comment]
> On IOS we have a separate screen for reading the details, IMO it's much better this way.
> 
>  Simulator.Screen.Recording.-.iPhone.15.-.2024-04-15.at.18.05.58.mp4

This looks also good. @jancborchardt What do you think?

**Comment by jancborchardt** [comment]
Yep, looks good to me! Specific screen is much better than expand/collapse, and especially the collapsed view with internally scrollable elements would lead to usability issues. :)

**Comment by alperozturk96** [comment]
@jancborchardt @mpivchev How is it now?


Uploading sx.mp4…
