### ISSUE TITLE
Can't open files with 3rd party apps

### ISSUE THREAD

**Issue by pklapperich** [nextcloud/android#1285]
### Actual behaviour
I'm not sure if this is related to issue #751. I'm unable to open files at all, not just read-only, so I think this is a different issue. I've tried PDFs (I have Google Drive pdf viewer app), jpg files, and my KeePass database. jpg files work, but appear to be using a jpg viewer built into Nextcloud app. PDFs and my KeePass database don't open, with different errors. I don't have any problems opening these file types from the Dropbox app, but I'd like to get away from using that service.

### Expected behaviour
-I expect Nextcloud app should launch the appropriate 3rd party app to view/edit the file (and then if there's changes to the file, synchronize those, but I'd be happy if they just open).
 
### Steps to reproduce
1. Find a PDF file. Click on it.
2. Wait for it to download. 
3. "Can't open file" is displayed. Click close.
4. Check the box "Set as available offline. A sprite shows "File contents already synchronized"
5. Press back. Notice the file has a green checkmark.
6. Click the file again.
7. "Can't open file." is displayed.

I can use a 3rd party file manager and browse to /storage/SD-CARD-NAME/Android/data/com.nextcloud.client/files/...../FILENAME.pdf and it opens just fine.

1. Find a *.kdb file (keepass 1.x database)
2. Click on it.
3. After it downloads a sprite displays "KeePassDroid cannot handle this uri".
3. Check the box "Set as available offline". A sprite shows "File contents already synchronized".
4. Press back. Notice the file has a green checkmark.
5. Click the file again.
6. A sprite displays "KeePassDroid cannot handle this uri".

I can manually open KeePassDroid and then browse to /storage/SD-CARD-NAME/Android/data/com.nextcloud.client/files/...../FILENAME.kdb and it opens read-only.

### Environment data
Android version: AICP 12.1 (Android 7.1.2)

Device model: Moto X Pure Edition (XT1575)

Stock or customized system: Customized

Nextcloud app version: 1.4.3

Nextcloud server version: 12.0.0.1

#### Web server error log
Will find and post if you think it's relevant.

#### Nextcloud log (data/nextcloud.log)
This file doesn't exist on my device.

**Comment by tobiasKaminsky** [comment]
You seem to have the storage on an external sd card. Can you try to use the internal storage and then download/open the file again?

**Comment by pklapperich** [comment]
Internal storage as a workaround works. Thanks!

**Comment by sehucke** [comment]
I am having a similar (the same?!) problem: I cannot open files with third party apps. Behavior is quite different, though:
1. Click on a file
1. File is automatically downloaded
1. It is opened... or should be opened I should say
1. What I get instead is the third party app being opened - but without the document itself.

This happened with PDF files (Adobe Reader), DOC/MD/TXT files (TextMaker Mobile Free), XLSX (TextMaker Mobile Free) MP3 (Total Commander) as well as with ODS files (Open Document Reader). In addition, if I try to "Open with..." on a jpeg my gallery app crashes.

I am using a Moto G 4G LTE (peregrine) with LineageOS 14.1-20170706-NIGHTLY-peregrine (Android 7.1.2) installed (unlocked bootloader, but no su). NC app is version 1.4.3 in combination with NC 11.0.2. I have configured my NC app to store the data on an external sd card, too. Unfortunately, this is mandatory for me due to the limited internal memory of my device.

**Comment by mario** [comment]
Should be fixed via: https://github.com/nextcloud/android/pull/1651

**Comment by tobiasKaminsky** [comment]
Closing as #1651 is merged.
