### ISSUE TITLE
Problema sulla sincronizzazione dei file

### ISSUE THREAD

**Issue by ravafenice** [nextcloud/android#13067]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Quando creo un file in una cartella e cambio il nome, il programma di sincronizzazione di Windows non aggiorna sul server il nome rimane quello vecchio, ed appare invece che la spinta verde l' icona con le frecce. Questa cosa non accade se si cambia nome alle cartelle. Questa cosa si risolve se il file viene in qualche modo modificato, i PDF o file che non possono essere modificati rimangono con il vecchio nome. Se prendo il file che risiede ne PC lo sposto fuori dal Cloud e poi lo rimetto dentro questa volta il nome sarà quello giusto.

### Expected behaviour

Dovrebbe accadere che dal momento che cambio il nome anche sul server dovrebbe cambiare e la spunta con le frecce passare a verde.

### Actual behaviour

Spiegato sopra

### Android version

Si tratta del servizio sync di windows

### Device brand and model

Windows 11

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Windows 11

### Nextcloud server version

Windows 11

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
> Device brand and model
> 
> Windows 11

This is the repository for an *Android* based client for Nextcloud. I think you're in the wrong place. :)

If you happen to be trying to report an issue with the Desktop client, see https://github.com/nextcloud/desktop/. But I would suggest doing so in English so that as many people as possible can review the report (even if you must use a translator app).

If a general Nextcloud matter, the help forum might also be a resource: https://help.nextcloud.com
