### ISSUE TITLE
"Enter key" support after inputting server name

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#1309]
### Actual behaviour
When installing NC fresh it asks for a server. I pop it in and automatically hit the keyboard "enter" or -> key and nothing happens 

### Expected behaviour
This is supported 
 
It works when inputting user/pass in the next screen so would be good to have parity.

**Comment by tobiasKaminsky** [comment]
I tried many different approaches 
-  android:imeOptions="actionDone"
- setOnKeyListener

But neither did worked with my samsung s5 neo, however the current state is already working on my emulator (but there I click enter on my physical keyboard).

So, I am currently a little bit helpless. :/

**Comment by mario** [comment]
@AndyScherzinger can you look into this please? :) Thanks!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please see here: https://github.com/nextcloud/android/blob/424e2cdbc0e3361db26fa8f4b9b12d9d1edd0c88/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java#L2080

This check prevents the server check from being executed since at the moment this will only be done if it is SAMl based. It works it the CookieToken check is removed which will then mean than it'll always execute when you hit enter for the URL field no matter what kind of login you have in the background. 

Hope that helps :)

**Comment by jasonbayton** [comment]
And now you know, we can fix it 😆

**Comment by AndyScherzinger** [comment]
Already merged for the next RC :)
