### ISSUE TITLE
I can't see my gallery on Android

### ISSUE THREAD

**Issue by alexandre-leng** [nextcloud/android#13743]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Subject: Media display bug in Nextcloud - October 2024

Hello,

I would like to report a bug I encountered in the Nextcloud app related to media display. When browsing my photos and videos for October 2024, I only see grey placeholder icons instead of the actual image previews.

The images are not loading properly and remain stuck with the default icon, with no preview available.

Here are some additional details:

Nextcloud version: 3.29.2

Device used: Xiomi poxo x4 pro

Stable internet connection (4G+/Wi-Fi)

Date and time of the issue: October 9th, 2024

Could you please look into this issue and let me know of any solutions or fixes?

I have allowed all permissions 

Best regards,

See in attachment 
Alexander![Image](https://github.com/user-attachments/assets/6bfb1dd5-884f-43ba-b2a5-59e1ffe47544)

### Expected behaviour

It should have a thumbnail of the photos displayed 

### Actual behaviour

Photo thumbnails are not displayed

### Android version

13 TK1

### Device brand and model

Xiaomi poco x4 pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.29.2

### Nextcloud server version

1

### Using a reverse proxy?

No

**Comment by alperozturk96** [comment]
Could you try with [latest](https://github.com/nextcloud/android/releases/tag/rc-3.30.1-01) version?

**Comment by orionp13** [comment]
Hi,
I simply configured the photos and linked the folder to Nextcloud Photos, and it resolved the bug.

**Comment by joshtrichards** [comment]
>  I simply configured the photos and linked the folder to Nextcloud Photos, and it resolved the bug.

What do you mean by "configured the photos"? Were previous turned off server-side?

**Comment by DaleBCooper** [comment]
> Could you try with [latest](https://github.com/nextcloud/android/releases/tag/rc-3.30.1-01) version?

Same problem with latest 3.30.1release.
It used to work and I don't know when it started to fail (not using it on a daily basis).

Server log (Nextcloud30.0.1) :

`"GET /index.php/core/preview?fileId=0092443151cda369ab867&x=540&y=1078&a=1&mode=cover&forceIcon=0 HTTP/1.1" 404 2 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.30.1"`
`[...]`

**Comment by himpierre** [comment]
maybe related to #13515

**Comment by joshtrichards** [comment]
> `/index.php/core/preview?fileId=0092443151cda369ab867&x=540&y=1078&a=1&mode=cover&forceIcon=0`

@DaleBCooper What happens when you try to open that URL (e.g. `https://domain.tld/index.php/core/preview?fileId=0092443151cda369ab867&x=540&y=1078&a=1&mode=cover&forceIcon=0` from a logged into your Nextcloud browser?) A 404 indicates a server-side matter. Please check server logs too.

**Comment by DaleBCooper** [comment]
> > `/index.php/core/preview?fileId=0092443151cda369ab867&x=540&y=1078&a=1&mode=cover&forceIcon=0`
> 
> [@DaleBCooper](https://github.com/DaleBCooper) What happens when you try to open that URL (e.g. `https://domain.tld/index.php/core/preview?fileId=0092443151cda369ab867&x=540&y=1078&a=1&mode=cover&forceIcon=0` from a logged into your Nextcloud browser?) A 404 indicates a server-side matter. Please check server logs too.

Sure it throws a 404, too. But:
If I remove the leading zeros and the random string (aka instance id) from the fileID I get the correct preview image:

/index.php/core/preview?fileId=924431&x=540&y=1078&a=1&mode=cover&forceIcon=0

Before you ask, the instance id in config.php is correct and corresponds the the appdata folder. I guess otherwise there would be more problems. ;-) 


I have an old test installation (upgraded to latest NC 30.0.2) where both URI work (e.g. fileId=00007001oco7qtfh9yyg and fileId=7001).

The only difference between the two installations is: The production uses a data folder **outside** web root where the test installation uses default settings where the data folder is located **inside** the web root. May this be the cause?

**Comment by DaleBCooper** [comment]
Additional notes: the leading zeros don't matter, fileId=00924431 works also.

I wonder why the android app appends the instance id the the file id? Accessing the web interface via browser does not show this behaviour. All request are done with the real plain file id.

**Comment by joshtrichards** [comment]
Found it I'm pretty certain! Thanks. That was helpful!

Wrong in `doResizedImageInBackground()`:

https://github.com/nextcloud/android/blob/cff4973f3579b635fb2f449521a08471700a3989/app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java#L1402-L1404

Correct in `doThumbnailFromOCFileInBackground()`

https://github.com/nextcloud/android/blob/cff4973f3579b635fb2f449521a08471700a3989/app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java#L718-L720

local id = just the file id  (the `oc:fileid` DAV property)
remote id = file id + instance id (the `oc:id` DAV property )

> I have an old test installation (upgraded to latest NC 30.0.2) where both URI work (e.g. fileId=00007001oco7qtfh9yyg and fileId=7001).
>
> The only difference between the two installations is: The production uses a data folder outside web root where the test installation uses default settings where the data folder is located inside the web root. May this be the cause?

That shouldn't work on either I'm fairly certain. I'll re-look at the server code after the Android side is fixed. Either way, the Android app will be doing the right thing and should work.

**Comment by joshtrichards** [comment]
@DaleBCooper:

> > I have an old test installation (upgraded to latest NC 30.0.2) where both URI work (e.g. fileId=00007001oco7qtfh9yyg and fileId=7001).
>
> The only difference between the two installations is: The production uses a data folder outside web root where the test installation uses default settings where the data folder is located inside the web root. May this be the cause?

That shouldn't work officially, but based on the server code I suspect it can work sometimes because that value comes is as a string but it used as an integer. That would have the effect of dropping the instance id from it in some cases... I'll see if there's a way to make that more robust on the server-side. 

Might also explain some of the inconsistent test results I saw mentioned in some of the discussions related to a prior PR in this code area in `android-library`. So thanks also for mentioning that detail. :)

**Comment by DaleBCooper** [comment]
> Found it I'm pretty certain! Thanks. That was helpful!

I'm glad I could help.
Thanks a lot for taking a look into this issue and fixing it!

**Comment by DaleBCooper** [comment]
I cannot believe this bug got re-introduced. Exactly the same problem, no thumbnails shown and I see the same requests in the access log as described above. How is this possible? 
App version: 33.0.1

**Comment by alexandre-leng** [comment]
Reopen a bug ? @DaleBCooper

**Comment by DaleBCooper** [comment]
Not necessary, just debugged it via logging all sql commands and found the real problem: it is the **instanceid**!
I have a very old installation with an instanceid of 13 characters beginning with 2 digits. 

Looking up the preview for file with fileid **1029802** results in wrong sql queries like:

`SELECT `storage`, `path`, `mimetype` FROM `oc_filecache` WHERE `fileid` = 102980251`
instead of
`SELECT `storage`, `path`, `mimetype` FROM `oc_filecache` WHERE `fileid` = 1029802`

The first two digits of the instanceid got appended the the fileid!

I compared this with a test installation where the instanceid is 12 characters long and begins with 'oc'.

To permanently fix this I changed my instanceid to an new one which begins with 'oc' and a length of 12 characters.

Check your instanceid. If it begins with one or more digits then you have the same problem.
Let me know if this is the case. Then I will write down the necessary steps to change the instanceid. It involves changes related to config.php, database and file system.  It is NOT sufficient to change it in config.php only!
