### ISSUE TITLE
What would be involved in supporting SAML login?

### ISSUE THREAD

**Issue by KroniK907** [nextcloud/android#1461]
The user_saml app for nextcloud is extremely useful for my implementation since our group has an SSO system set up to provide our users with only a single username/password for pretty much all the apps they use in our organization. 

However, many of them are using the nextcloud app on their phones and have to set up a separate password, which is a minor security concern for us as well as an inconvenience for the users. 

What would it take to allow SAML login to work like it does in the browser?

**Comment by KroniK907** [comment]
Please close this, it works fine on the dev version. Didn't realize the version on the play store was only 1.4.x

**Comment by AndyScherzinger** [comment]
Hi @KroniK907 if you register as a tester on the PlayStore for the Nextcloud app then you will also see this new login feature since we are closing in on the next stable release (2.0.0) with 2.0.0 RC5 currently available to testers. Registration can be done via: https://play.google.com/apps/testing/com.nextcloud.client

You can opt out at any time and will then from that moment on not get any beta/rc versions served from Google Play anymore (while running a RC you would then not be able to go back but have to wait for the next stable). ...Just in case this might be of interest for you.
