### ISSUE TITLE
Notifications list doesnt really refresh

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/android#1477]
### Steps to reproduce
1. Receive a push notification
2. Tab on the push notification
3. See list of notifications
4. Web UI: delete the notification
5. Phone: pull down the notifications list
6. See the loading circle

### Expected
After loading circle the list should be empty

### Actually
The item is still shown.

### Steps to continue
7. Open side navigation
8. Go to notifications
9. A new view starts with the empty list
10. Back button brings you back to the old notification list with the already deleted entry

### Environment data
Android version: 6.0

Device model: Huawei P8 lite

Stock or customized system: stock

Nextcloud app version: 2.0.0rc5

Nextcloud server version: 12.0.2

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I just tested this and found the issue when this happens but don't have the time and technical tools to test this since I can't create notifications :/
The issue is not with removing notifications but with removing all of them, so the pull to refresh works e.g. when you delete 2 out of 3. If you remove all notifications the list won't be refreshed.

Hope that helps :)

**Comment by nickvergessen** [comment]
@AndyScherzinger you can create a second account on your instance and \@mention your other account in a comment on a shared file. That should create a notification ;)

**Comment by AndyScherzinger** [comment]
PR is #1478
