### ISSUE TITLE
Auto upload: Screenshots folder should have priority sorting

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1493]
Currently there’s two folders important for me to auto-upload: Camera and Screenshots.

Camera is correctly sorted up top. Screenshots however is all the way on the bottom between folders of album covers and such on the SD card. It should be given priority sorting and put to the top, even when not synced.

What do you think @tobiasKaminsky @AndyScherzinger?

**Comment by mario** [comment]
Makes no sense to me? Why would Screenshots get preferential treatment? Afaik Camera is at the top because we sort by (IMHO correct) by alphabet.

**Comment by AndyScherzinger** [comment]
I'd also vote against it since for me Screenshots is the least important folder to me.

> Currently there’s two folders important for me to auto-upload: Camera and Screenshots.

This is imho a personal preference, I for example care about Camera, Instagram and WhatsApp 

> Afaik Camera is at the top because we sort by (IMHO correct) by alphabet.

* Kind of... We sort alphanumerically (by alphabet) but give "Camera" a priority since we "decided" that for auto upload this would be the most important folder ever
* At the very top are always the active one, so if someone would think the Screenshots are important than activate auto upload and it will be on top. If it is not important enough to be auto uploaded it is imho not important enough to be sorted at the top when inactive. "Camera" imho being the only special folder we should have.

2 two cents :)

@tobiasKaminsky ?

**Comment by jancborchardt** [comment]
I wasnt talking about _top_ priority. The current state though is that I have around 50-100 other folders in that list I need to scroll past - and they are all irrelevant to autoupload since they are album covers from my music.

So this, and WhatsApp, other specific widely used ones should definitely be specifically sorted before any random folders with images.

**Comment by mario** [comment]
@jancborchardt this explanation makes more sense, but it's rather tricky as we can also have "Snapchat" folder without it actually belonging to Snapchat. Edge case, I know, but still...

**Comment by AndyScherzinger** [comment]
@jancborchardt kind of different approach I wanted to implement / suggest at some point anyways: allow the user to hide folders in the auto upload view.

Would that be something that should be implemented and would this work around this issue? I know it is not as nice as an intelligent sorting while I don't know how to actually implement that since we would then need a list of typical app folders that need priority while most likely missing some for a certain user base I guess :/

**Comment by mario** [comment]
Oh my. This further complicates it...

**Comment by AndyScherzinger** [comment]
xD

Just a thought ;) No worries :D

**Comment by comradekingu** [comment]
@jancborchardt How about being able to scroll upwards to get to the latest ones, (bottom of list) if sorted by date?
It would at least give quick access to two places.

**Comment by jancborchardt** [comment]
> allow the user to hide folders in the auto upload view.
> Would that be something that should be implemented and would this work around this issue? 

No, as it doesn’t change the default. ;)

I had no idea this would be such a big discussion. In my experience there are _two_ picture folders in a default Android install (without any additional apps) which can have stuff which is only on your phone and you would need to back up. One is **Camera**, the other **Screenshots**. We do list Camera first correctly already, so putting Screenshots below seems sensible.

**Comment by mario** [comment]
There are no folders by default. They might EXIST, but not registered as media providers. Not super excited about this, but not against it much either. If @AndyScherzinger is for it, we can do it.

**Comment by tobiasKaminsky** [comment]
I understand the jan's intention, but this is a config screen which is not accessed that often. 
So I am fine with both
- make camera and screenshot top priority
- keep it the way it is.

If we change it, this should be relative simple...
Extend it to a list atnd voila ;-)
https://github.com/nextcloud/android/blob/329bccd51439705520e153cd53aec21ae4aa8e58/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java#L89-L89

**Comment by tilosp** [comment]
What is the state of this? 
@AndyScherzinger Are you fine with prioritizing the screenshots folder?

**Comment by AndyScherzinger** [comment]
@tilosp still pending I'd say. I have the same opinion as Tobias https://github.com/nextcloud/android/issues/1493#issuecomment-336435326 -> I'm fine either way

**Comment by AndyScherzinger** [comment]
Thanks for the contribution @tilosp 🥇 🎉

**Comment by jancborchardt** [comment]
Thanks a lot @tilosp! Great contribution! :)
