### ISSUE TITLE
Update contributing.md with new merge/git workflow

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1524]
As discussed on the conf we want to try a slightly different workflow with master and a 2.x release branch.
@AndyScherzinger has the corresponding images and volunteered to draw & update the contributing.md

**Comment by AndyScherzinger** [comment]
I raised a concern to @mario about maybe rather go with Master + 2.0.x since then features would always go to master, strings would make it to master for translation.

After having thought a little about our discussion and decision I believe this to be a leaner approach since I think working on 3.0 on master isn't happening. We always went from release to release so master would then always be the next feature release. Issue that would remain is that we end up with a similar situation like 2.0 as in not being able to do a feature release since the feature release isn't complete yet.
That can imho be fixed by not merging features which we don't consider complete and beta ready which then also means that getting them stable for a release is the top priority...
