### ISSUE TITLE
Disappearing menu items in autoupload list

### ISSUE THREAD

**Issue by pztrn** [nextcloud/android#1582]
### Actual behaviour
As autoupload isn't working on my device (Meizu m3 note, flyme 6, android 5.1), I'm launching autoupload sync manually with menu item at upload status screen. But when I click any menu item - it is disappearing until I reopen upload status screen.

Nothing in logs. Absolutely.

### Expected behaviour
Menu items do not disappear.
 
### Steps to reproduce
1. Open upload status screen.
2. Click on ANY menu item.
3. Item disappeared until upload status screen is reopened.

### Environment data
Android version: 5.1 (flyme 6 global)

Device model: Meizu m3 note

Stock or customized system: stock

Nextcloud app version: 2.0.0RC6

Nextcloud server version: 11.0.5

### Logs

Nothing in logs on my phone. Absolutely.

**Comment by OlivierS1** [comment]
@pztrn I think this behavior is acting that way on purpose.
I found it confusing at first as I had the same behavior but as it behaves consistently, I don't think it is a bug.
I think it acts as a reminder.

**Comment by mario** [comment]
This is true only for two menu items: Retry failed uploads and "Force rescan", and there is a good reason - you shouldn't run this again for quite some minutes. Hiding is a simple way to accomplish this since this menu will be completely removed in the future.

The fact that auto upload does NOT work on Meizu is something that needs to be fixed, but that part is in another ticket, and I don't know how to test without access to the phone.
