### ISSUE TITLE
App is dying in background / breaks auto-upload feature

### ISSUE THREAD

**Issue by sinnlosername** [nextcloud/android#1583]
### Actual behaviour
- Sometimes, the nextcloud app stop in background, so it doesn't sync any new photo's using the auto-upload feature. After restarting it, it doesn't recognize new photo's made in the time it was stopped. 

### Expected behaviour
- Doesn't crash & upload photo's made while the app was stopped.
 
### Steps to reproduce
Happen randomly while using the app. There is no way to exactly reproduce it.

### Environment data
Android version: 7

Device model: Huawei p10 Lite

Stock or customized system: Stock

Nextcloud app version: Latest 
Nextcloud server version: Latest (Updated it 2 days ago)

### Logs
As it seems to be a clientside problem, I didn't add any logs here. Tell me, if you need them.

**Comment by mario** [comment]
What does "latest" in app version means? 2.0.0 RC6/7?

**Comment by memen45** [comment]
Since you have a Huawei, this could be caused by the 'battery manager' which closes apps automatically and seemingly random (but more likely when screen is off and/or on low battery). 

Settings > Advanced Settings > Battery manager > Protected Apps, find Nextcloud app in the list and allow it to stay active after screen is turned off.
Does that work?

**Comment by tobiasKaminsky** [comment]
@sinnlosername can you try the last suggestion?
Is this still happening?
