### ISSUE TITLE
Cache background image / drawer image

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1595]
Related to #1566 

Cache background image in a proper way.
Capabilities return: "background": "https:\/\/server.com\/core\/img\/background.png?v=5"
So this should change on every new image.
I think glide can handle this.

**Comment by esafirm** [comment]
@tobiasKaminsky @AndyScherzinger can you guys elaborate more on this? 🙏

**Comment by AndyScherzinger** [comment]
Tobias will be back next week but I try my best....

The server offers a capabilities API which we already call to get information about the server's setup. This API provides us a JSON which contains the key/value mentioned by Tobias and which we use to load the background image. What we don't do yet and that is what this issue is about is to save and compare this value. Since it contains a version information which can be used to detect if the background image on the server has changed and should be fetched again and put into the image cache.

What I can't say (since I don't know) is if (as implied by the description) Glide (one of the frameworks we use) can handle such work by itself out of the box. Maybe @mario knows?

**Comment by esafirm** [comment]
@AndyScherzinger ah i see, thanks for your explanation. AFAIK Glide do caching as the default configuration and the default key is the URL and the query parameter too. 

So the background source is from here, right? 
```
getStorageManager().getCapability(getAccount().name).getServerBackground()
```

Questions: 
1. How one can set the background URL? 
2. Where i should look, If i want to know more about `OCCapability`?  Is there any documentation?

**Comment by AndyScherzinger** [comment]
@esafirm maybe we need to wait until Tobias is back (next week). 

1. The background can be set on the server in the admin area via the themeing capabilities (Admin-->Thememing-->Background) in the web UI.
2. ```OCCapability``` is provided via the client lib https://github.com/nextcloud/android-library/blob/master/src/com/owncloud/android/lib/resources/status/OCCapability.java and offers the information available via the getters like you already and correctly referred to ```getServerBackground()```.

**Comment by mario** [comment]
@AndyScherzinger @esafirm the solution is rather simple. Since the URL changes, if we move to Glide to load the image, it'll automatically pull the new image and cache it the next time we call it.

I don't know if we use Glide to set/download this image, but if not - just use that and done! :)

**Comment by AndyScherzinger** [comment]
@mario will glide auto detect the change since it is only the URL that changes?

**Comment by mario** [comment]
@AndyScherzinger yes.

**Comment by esafirm** [comment]
@AndyScherzinger 👍

> I don't know if we use Glide to set/download this image, but if not - just use that and done! :)

It already is 

<img width="877" alt="screen shot 2017-10-05 at 9 59 33 pm" src="https://user-images.githubusercontent.com/1691440/31234231-88d945e8-aa18-11e7-9444-21acae212f11.png">

**Comment by mario** [comment]
@esafirm @AndyScherzinger then this should already work afaik.

**Comment by AndyScherzinger** [comment]
@esafirm @mario I am sorry, then I must have missread #1566 which states: 

> When change any user info on server must be reflected in the client. This already happens for the background image. So both images should be cached for a certain amount of time, e.g. 24 hours.

And @mario alsready did the part for the avatars in another PR so then yes we should be all set here... Sorry folks, my mistake... 😢
