### ISSUE TITLE
Device credentials and pincode / fingerprint

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1758]
In #1657 we get thanks to @rhari991 the possibility to use device credentials to lock our app (for Android M and later).
Previously we had pincode and fingerprint implemented on our own.

Do we need pincode and fingerprint independent of device credentials? Or can we remove/hide them?
Is there a use case where the device is unlocked, but an user wants to lock only our app with e.g. fingerprint or pincode?

To simplify our code base and UI I vote for removing it (fingerprint is already done in the PR I guess).
Removing in >= Android M as we should still allow passcode on older devices.

**Comment by AndyScherzinger** [comment]
> Is there a use case where the device is unlocked, but an user wants to lock only our app with e.g. fingerprint or pincode?

That is basically what the security measure is for in general ;) And with @rhari991 you would still have that like 30 seconds after device unlock the app when opened would ask for the authentication :)

> To simplify our code base and UI I vote for removing it (fingerprint is already done in the PR I guess).
Removing in >= Android M as we should still allow passcode on older devices.

Perfectly fine since < Android M we don't have fingerprint anyways so keep the legacy pincode for that matter >= Android M only support device credentials. While I suspect some users to brag about not having yet another authentication. I think it is an edge case handing out your unlocked device within 30 seconds (including the other person opening Nextcloud). This is basically like handing out your physical credit card and bragging about the other person buying stuff with it...

**Comment by AndyScherzinger** [comment]
obsolete
