### ISSUE TITLE
Sync fails since android client update to 2.0.0

### ISSUE THREAD

**Issue by csjjpm** [nextcloud/android#1785]
Auto uploaded of photos or synchronisation of files no longer happens on my android phone since the client update to 2.0.0.  when auio uploading photos the error says 'upload failed'. When trying to synchronise a remote folder with my phone the progress stays at 0% and then fails.

Before the client update it worked fine.

My server is version 10.0.6

I don't know how to get logs
 
 
### Environment data
Android version: 6.0

Device model: cubot max

Stock or customized system: none

Nextcloud app version: 2.0.0

Nextcloud server version: 10.0.6

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by johnjgsmith** [comment]
I had the same problem in 12.0.3. I had to delete   theNextCloud Manual pdf from the NextCloud app (it would not open anyway) and after that everything synced without problems.
In the sync log it will tell you which file couldn't be synced.

**Comment by csjjpm** [comment]
Hi John,
  any photos that were in the folder to auto sync all fail regardless.  But as well as this if I try and synchronise a remote folder nothing happens for ages and then it times out.
Paul

**Comment by csjjpm** [comment]
Direct me to some instructions and I will get you whatever logs I can find

**Comment by arkdae** [comment]
I am also having this problem. I just installed NextCloud server 12, and downloaded the latest NextCloud app from the Google Play store. I have selected the only two directories that are shown in the Auto upload screen, Camera and Download. I have unchecked "Only upload on Wi-Fi" and "Only upload when charging." I have turned on and off WiFi. I have restarted my phone.

Nothing I have done so far has caused the existing files in these directories to upload. Is auto upload supposed to only upload new files, or all files? If only new, how do I get all files copied over?

Some people talk about sync. Is that a different thing? The app does not mention sync. I have also seen some mention of a queue, but, again, I do not see anything about a queue in the app. Finally, where might I find the app logs? I would love to help, as this is the core functionality that I wanted NextCloud for, and it is not working at all for me.

**Comment by alexknobbe** [comment]
Hi all, here the same issue but as temp solution you can move current images to another folder on your phone and move them back, the client detects the change and start the sync to nextcloud.

Met vriendelijke groet,

￼

￼


Alex Knobbe |  Jouw data in de cloud
Boxu B.V.
Moezel 3  2491 CV  Den Haag
Tel  +31 (0)88 100 2070 | Mob  +31 (0)6 4063 1903
www.boxu.nl  |  alex@boxu.nl l

 ￼ ￼ ￼ ￼





Gebruikt je nog Dropbox, Google Drive en WeTransfer?
Stap eenvoudig over op Boxu een maak gebruik van 1 oplossing.



-------- Oorspronkelijk bericht --------
Onderwerp: Re: [nextcloud/android] Sync fails since android client update to 2.0.0 (#1785)
Van: arkdae
Aan: nextcloud/android
Cc: Subscribed


I am also having this problem. I just installed NextCloud server 12, and downloaded the latest NextCloud app from the Google Play store. I have selected the only two directories that are shown in the Auto upload screen, Camera and Download. I have unchecked "Only upload on Wi-Fi" and "Only upload when charging." I have turned on and off WiFi. I have restarted my phone.

Nothing I have done so far has caused the existing files in these directories to upload. Is auto upload supposed to only upload new files, or all files? If only new, how do I get all files copied over?

Some people talk about sync. Is that a different thing? The app does not mention sync. I have also seen some mention of a queue, but, again, I do not see anything about a queue in the app. Finally, where might I find the app logs? I would love to help, as this is the core functionality that I wanted NextCloud for, and it is not working at all for me.

**Comment by ddmesh** [comment]
Android app 2.0.0 in Google store still does
Not upload older files. I need this function to have files automatically being stored in extra directories (year, months, week or day). 
manually uploading of almost 2000 files in one directory is not very good idea.

**Comment by AndyScherzinger** [comment]
Hi @ddmesh that functionality is still in the roadmap #285 but the actual focus is on end-to-end encryption. If you need the 2000 files uploaded via the auto upload there is a workaround: move the files on the phone to a different folder and then after some time move them back to the camera folder. This way the Android Media Index will kick in and the files will be detected as "new" so they will be uploaded then.

**Comment by ddmesh** [comment]
Didn't get notification of your answer. Thanks for your solution. Perhaps it is already implemented since than.

**Comment by AndyScherzinger** [comment]
I'll close it then. Please reopen if it occurs again.
