### ISSUE TITLE
Auto Upload does not work

### ISSUE THREAD

**Issue by vdmkenny** [nextcloud/android#1832]
I added my openCamera folders to auto upload when connected to wi-fi.

### Actual behaviour
-Nothing happens. No error, no sync, have been waiting for a few hours while connected to wifi.

### Expected behaviour
-I expect that the pictures on my device get uploaded to nextcloud.
 
### Environment data
Android version:LineageOS 14.1 (Custom build) / Android 7.1.2

Device model: Sony Xperia Z5 Compact

Stock or customized system: Rooted, Only minimal google services. (Pico openGapps)

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.4

**Comment by MarkusHLudwigsfeld** [comment]
I have the same issue:

Nextcloud Server: 12.0.4
App version: 2.0.0
Sony Xperia Z3 compact
Android 6.0.1

**Comment by AndyScherzinger** [comment]
Hi @MarkusHLudwigsfeld @vdmkenny do you mean existing pictures or newly taken pictures after activating auto upload aren't uploaded? Just asking because existing picture upload hasn't been implemented yet, see #285 for the auto upload roadmap.

**Comment by MarkusHLudwigsfeld** [comment]
Hi @AndyScherzinger 
I tried to use it for files (not pictues) which indeed exist already.

Full feature I want to use is:
* using SmsContactsBackup to auto create backups 
* use Nextcloud autoupload to move this backups to nextcloud 
   I like to move because memory on the phone is limited. 

If I understand you correct, then this will work for all new created backups by SmsContactsBackup, but not for existing ones.
So I need to upload existing ones manually, but after this one time action it will work for me as expected?

**Comment by vdmkenny** [comment]
@AndyScherzinger ; Hi, I just noticed that new pictures do indeed sync. Thank you, for checking. The full auto-upload of existing pictures is something I expected/need.

**Comment by mario** [comment]
Closing this because we're tracking this issue in other issues :)

**Comment by rugk** [comment]
Also btw, there is a nextcloud SMS add-on for your sever available, also the corresponding app. Maybe that fulfills your use case.
