### ISSUE TITLE
[Android] [App] Can't access "instant upload" 

### ISSUE THREAD

**Issue by Windyo** [nextcloud/android#1841]
### Actual behaviour
As soon as I try to click on "instant upload" to configure instant uploads, the next cloud app crashes. 

No instant upload can take place. 

### Expected behaviour
-Tell us what should happen
 
Should be able to open instant upload setting page. 

### Steps to reproduce
1. Click on instant upload 
2. Instant crash
3. No upload 

### Environment data
Android version:
7.0
Device model: 
S G935F
Stock or customized system:
stock 
Nextcloud app version:
2.0.0
Nextcloud server version:
12

**Comment by tobiasKaminsky** [comment]
Instant upload is the old feature, for Android 7 there should be "AutoUpload".
Can you try to provide aus a logcat? 
https://github.com/nextcloud/android/blob/master/README.md#get-debug-infos-via-logcat

**Comment by Windyo** [comment]
I don't have root or ADB... :/ any otherway I can generate a log ?

**Comment by Windyo** [comment]
Also you're right it's called Auto Upload now. Still won't open though. Clicking on it crashes the app.

**Comment by AndyScherzinger** [comment]
@Windyo are you able to install apps via f-droid? --> https://f-droid.org/packages/com.nextcloud.android.beta/ is the dev version (kind of a nightly build). Just asking since I think there has been a fix to the Auto Upload screen to prevent a crash scenario (which might be what happens to you too). So you could test if the dev version fixes that problem for your device and if so you'd know that the next stable release won't have this issue anymore.

**Comment by tobiasKaminsky** [comment]
Additionally in this dev version there is logging enabled, so you can send us the logs (hopefully they record the crash)

**Comment by Windyo** [comment]
downloaded the new version via fdroid. No longer crashes on Autoupload selection :)
