### ISSUE TITLE
Delayed deletion of photos

### ISSUE THREAD

**Issue by scoopex** [nextcloud/android#1899]
I really like the automatic upload and automatic deletion functionality for photos and videos, because this saves space on my android devices and make new photos and videos quickly available on my desktop system/nextcloud server.

There is only one thing which is little bit annoying:
Very often the upload and deletion is already performed when i want to review the media files on my phone (with familiy members, friends, ....) and it is a bit clumsy to reach these medias...

Therefore it will be great to have the possibility to delay the deletion of the media files if the are already uploaded after a certain amount of days.
A fixed amount of days (i.e 14 days) would be great for a initial implementation to reduce the amount of modifications of the ui.

**Comment by tobiasKaminsky** [comment]
I recall that there was a discussion about this some time ago.
If I remember correctly the idea was not to add this as, but the user can simply click on the folder and delete it locally.
But having one option "delete after 14 days" in the option menu of an upload folder would also be fine for me. 
Let's see what others say?

**Comment by scoopex** [comment]
I think this is a very common usecase: Users will welcome to have the photos for a certain of time on their smartphone.

Probably a variant of this feature request would be smarter:
- the photos can be moved to the Nextcloud folder (common photo apps should find them anyway?) in a regular way
- Add a cache limit to folders, which removes locally cached files by a age limit or probably size limit (i.e. 200MB cache for this folder, keep most recent files)

**Comment by mario** [comment]
The discussion ended in a way that (at least) @AndyScherzinger and me agree that ALL Auto-upload behaviours need to be removed.

**Comment by tobiasKaminsky** [comment]
Well that would be really pity if we drop this as this is very often used feature as far as I can read...
And of course I personally really like it ;-)

**Comment by scoopex** [comment]
I also agree, managing the free space of my phone by automatic upload and deletion might be a key feature for many users....

**Comment by mario** [comment]
Well then the behaviours need to be fixed properly to work in 99% of cases (which I'm not sure is possible), and they most definitely don't at this moment. I am not a fan of filling the app with features in general.

**Comment by AndyScherzinger** [comment]
My reason for voting to remove the behaviors are two:

- other apps like Google photos for example also don’t manipulate the files of other apps, non-app locations
- we would have to test file manipulations prior to offering them on a per device folder level

**Comment by tobiasKaminsky** [comment]
> other apps like Google photos for example also don’t manipulate the files of other apps, non-app locations

This does not mean that we cannot be "better" ;-)

> we would have to test file manipulations prior to offering them on a per device folder level

Yes, this is my idea: to test on setup of auto upload folder if it is possible and only then show the option. Otherwise show a info that the storage is "readonly".

**Comment by doits** [comment]
This would be a killer feature IMO. I'd use this for the regular camera/DCIM folder: Remove pictures older than say 6 months, remove videos older than 1 month (for example).

Currently I have to do this manually, but there is one flaw: I cannot be sure the file has been uploaded! I had the case that some files did not manage to be uploaded (maybe due to bugs, maybe by bad luck etc.), so I am hesitant to delete them without checking first that there is a copy on the server. Which means I only do this manually for videos for now, because it saves the most space per file - and I found 3-4 out of maybe 40 which weren't uploaded in my last few runs, so this fear is not theoretical for me. (I have the idea to write a script that does this check automatically by looking for the file through maybe webdav and only deleting it when found or uploading it when not - but this feels like replicating auto upload.)

Would be nice to have such a feature in the app directly: To delete old files when uploaded, but with a delay.

(When I finally come to write that mentioned script I'll post it, so maybe other users (probably with a rooted phone / adb connection) will be able to use it.)

**Comment by joshtrichards** [comment]
Let's consolidate this into #2323
