### ISSUE TITLE
Uploads view doesn't need a user info line if only one account is in the app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#1943]
The row with the username for every upload is only necessary as soon as there are at least 2 accounts in the app.

**Comment by arundhati24** [comment]
@jancborchardt @AndyScherzinger May I work on this? :)

**Comment by AndyScherzinger** [comment]
@arundhati24 sure, absolutely :+1:

**Comment by mario** [comment]
Uploads view doesn't need username line at all because it's per-user ;)

**Comment by AndyScherzinger** [comment]
So drop it in general @jancborchardt @mario @tobiasKaminsky?

**Comment by tobiasKaminsky** [comment]
I know that there was a discussion regarding this, back some time.

On the one hand it is right that uploads are only shown for the current account.
But what if you have auto upload on account A, switch to B, files on A get uploaded and fail, you dismiss the notifications (yes, user fault, but can happen), and then you are frustrated that you do not see any pending upload, but still the files are not there.

--> I would handle uploads just like settings, so that it is independent from current account.
If we agree to keep this on a per-user view, then maybe we can have some kind of information/switch if (and only if) there are failed jobs on other accounts, so that at least the above scenario is handled.

**Comment by jancborchardt** [comment]
@tobiasKaminsky I'd say the proper way to handle that subcase (active notification or error in other account) is to put some sort of indication also into the app.

Like a red dot in the top right corner of the sidebar menu icon, and then also onto the avatar of the relevant account. Would that work?

Cause uploads view (also in the future merged to activity) should definitely be per-user and separated, and hence does not need a username. (Like people don't want to see their work and personal data interspersed.)
