### ISSUE TITLE
Files and folders are displayed twice after they had once marked as favorite

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#2015]
As requested in the help forum (https://help.nextcloud.com/t/help-test-the-android-3-0rc1-client/25912/14) , I've created this issue ticket. The root cause might be related to other issues which have already been reported, like https://github.com/nextcloud/android/issues/1908.

### Actual behaviour
After I’ve installed the latest app version (3.0 RC1) I realized the following behavior:

- In the past I had marked several folders and files as favorites which caused double entries in the favorites menu. Although I’ve removed the favorite marker, I still got double files and folders displayed if I browsed through the folder tree.

- I’ve removed all favorite markers in the app so that the favorites folder itself was empty. Nevertheless some of the favorite markers automatically reappearing after I’d refreshed the folder?!

As recommended in the help forum I tried to get rid of the double entries by using the refresh function. Unfortunately the refresh function seems not to work as expected because I wasn’t able to delete double entries by refresh the folder view. On my web server I saw that the app requested an update but it had no effect on how the sub-folder was displayed in the app.

### Expected behaviour
File and folder entries shouldn't be displayed twice if they had been marked as favorite for a while.
 
### Steps to reproduce
1. I decided to delete the app to start from scratch. After I've installed the app again and entering my credentials I opened the folder and now all sub-folders and files were only displayed once. Then I marked a file and a sub-folder as favorite and switch to the favorite menu entry in the app.
2. Surprisingly both favorites were displayed twice again. I return to the original folder and checked the original file and and folder entries again and now the **favorite** directory and file entries were displayed twice in that view too.
3. I wasn’t able to solve it be deselecting the favorite markers. The folder view still showed double entries.

It might be of relevance that the files and folders reside on a WebDAV share.

### Environment data
Android version: 7.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud app version: 3.0 RC1
Nextcloud server version: 12.0.4

#### Web server error log
```
No error messages were logged.
```

#### Nextcloud log (data/nextcloud.log)
```
No error messages were logged.
```

**Comment by tobiasKaminsky** [comment]
> It might be of relevance that the files and folders reside on a WebDAV share.

At least I did not tested it with this.

Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by j-ed** [comment]
@tobiasKaminsky I did some further testing with a dedicated test account and found out that the root cause seems to be related to the use of an external WebDAV share. As soon as I mark files or folders as a favorite they got doubled. If I use a local file system everything works as expected. I'll send you a test account to android at nextcloud dot com asap.

**Comment by tobiasKaminsky** [comment]
@MorrisJobke have you heard of anything regarding web dav?

**Comment by MorrisJobke** [comment]
Could be related to https://github.com/nextcloud/server/issues/6941

**Comment by MorrisJobke** [comment]
And https://github.com/nextcloud/server/issues/7499 & https://github.com/nextcloud/server/issues/4869

**Comment by jdutsler** [comment]
I am using nextclloud as one of the pre-built extensions on the latest stable release of nas4free.  After getting initial configuration and setting up the nextclloud app on my Android phone, I went to the photos directory in the nextclloud app and issued an instruction to upload all my phone pictures and delete them from the phone.  Upload worked fine but the nextclloud app now shoes duplicates of every photo.  I have logged into nas4free and viewed the directory.  There is only one copy of each photo on the NAS.

**Comment by tobiasKaminsky** [comment]
@jdutsler do you see the images double in the regular file list "all files" or at "photo" view (both on drawer)?

**Comment by jdutsler** [comment]
Hi Tobias,

As with most times I build something on Linux, I have kept pretty detailed
notes on how I built it as I will usually wipe and build a clean version
once I am done experimenting and learning through the challenges.  I am in
the middle of that wipe process right now to build my third (and hopefully
final) version of nas4free with nextcloud.  As soon as it comes back up (I
expect within 2 days) I will check and answer your questions.

When I open the app now (no server backend), click the top left drop down
menu, and select all files view there is only one copy of each item.  From
the all files view when I open photos it only shows one image of each
item.  When I hit the photos view from the drop down menu on top left of
app it just spins (assume it is looking for the server).

James


On Feb 20, 2018 5:09 AM, "Tobias Kaminsky" <notifications@github.com> wrote:

@jdutsler <https://github.com/jdutsler> do you see the images double in the
regular file list "all files" or at "photo" view (both on drawer)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/android/issues/2015#issuecomment-366972170>,
or mute the thread

**Comment by AndyScherzinger** [comment]
PR is #2490

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger manually adding this info is not needed anymore, if we specify "fix #issue-number" in the PR.
Then you can see the PR-number above the very first post.
(We still should add the label "pr exists" as we then see which bugs are already handled).
