### ISSUE TITLE
Show message in auto upload configuration dialog when manditory fields haven't been filled and the users hit save.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/android#2034]
### Actual behaviour
After I’ve installed the latest app version (3.0 RC2) I wanted to set a custom folder for the automatic upload function but the Save-button doesn't work at all.

### Expected behaviour
It should be possible to save custom settings in the automatic upload dialog.
 
### Steps to reproduce
1. Selected the automatic upload menu.
2. Select `create your own folder`.
3. A configuration dialog opens which allows to set different parameters and also the upload folder itself.
Everything seem to work, except that the new configuration cannot be saved because the Save-button is not working. The Abord-button works without any problem.

### Environment data
Android version: 7.0
Device model: Samsung Galaxy S7
Stock or customized system: Stock ROM
Nextcloud app version: 3.0 RC2
Nextcloud server version: 12.0.4

#### Web server error log
```
No error messages were logged.
```

#### Nextcloud log (data/nextcloud.log)
```
No error messages were logged.
```

**Comment by AndyScherzinger** [comment]
@j-ed just tested it and it (at least) works for me. Did you set the local and the remote folder? Else the save button is blocked.

**Comment by j-ed** [comment]
@AndyScherzinger You're absolutely right, I missed setting the local folder. Due to the fact that no error message was displayed I thought all other settings would have been pre-populated by the app. It might be worse to
a) set the local folder parameter to a default value.
b) through-out an error message if it hasn't been set or couldn't be accessed.

**Comment by AndyScherzinger** [comment]
Happy to hear it work and thanks for the suggestions.
Since you are basically setting up the upload for a local folder I would not set it to a default (might be rather an option for the remote folder).
So showing a message for missing fields might be the easier option to implement :)

What do you think @tobiasKaminsky @mario ?

**Comment by mario** [comment]
Yup yup.

**Comment by tobiasKaminsky** [comment]
![2018-02-13-120853](https://user-images.githubusercontent.com/5836855/36146959-aa23217e-10b6-11e8-9fee-1f03a3aaf419.png)

Save button needs to be grayed out / disabled so that user can see that something is missing.
Showing a message on top of this dialog will look weird, I think. 

@jancborchardt do you have an idea how to make it more visible to the user that both local and remote folder needs to be chosen?

**Comment by AndyScherzinger** [comment]
> Showing a message on top of this dialog will look weird, I think.

true, so yes the best would be to either
* grey out the button or
* highlight the mandatory fields in case they haven't been filled when the user hits the save button

**Comment by jancborchardt** [comment]
How about radically simplifying the flow there? The only _really_ necessary thing is the local folder, right?

- The remote folder could be set to `Root → Name of local folder` by default
- Other settings are kept like default
- There’s an »Advanced settings« button which reveals the settings to be like the dialog shown above


That would make it absolutely clear you need to choose the local folder, and make it much more easy to set up. :)

**Comment by AndyScherzinger** [comment]
I like @jancborchardt's approach very much :+1:

**Comment by AndyScherzinger** [comment]
> The remote folder could be set to `Root → Name of local folder` by default

@jancborchardt so don't show the remote folder only as an »Advanced settings«? (Fine by me!)

**Comment by tobiasKaminsky** [comment]
I would show it, but have the above as a sane default

**Comment by jancborchardt** [comment]
@AndyScherzinger yep, only show it in advanced settings. It's not necessary to show directly when it's automatically set, that would just be confusing again. :) 

We should help people to focus on the absolute essentials, and in this case that's only the local folder.

**Comment by tobiasKaminsky** [comment]
This is only shown if people enable "expert mode" in settings. 
Hiding now the remote folder behind an additional advanced setting is somekind of redudant for me.
And it is also not consistent to the "regular" synced folder where you see it directly:

![2018-02-21-145022](https://user-images.githubusercontent.com/5836855/36483478-8f6d33a4-1716-11e8-908f-48d0855451cb.png)

So I vote for "sane default", but keep it simple with only one dialog and no advanced setting

**Comment by jancborchardt** [comment]
To be honest, "Expert mode" is confusing. It's completely unclear what changes as a result of it.

Also, it doesn't matter if you are an expert or not – the UX in this case should be perfect. We shouldn't have a "Disable good design" mode in our app, so to speak.

It's much better to go for simple flow and advanced settings on a case-by-case basis as I proposed, rather than to have a mystery switch in the settings.

**Comment by mario** [comment]
Why not just set default instead? I agree with Tobi in this case.

**Comment by AndyScherzinger** [comment]
:rofl: I'd guess everyone is right...

> So I vote for "sane default", but keep it simple with only one dialog and no advanced setting

* the "advanced" settings would simply be hidden with an accordion like element have sane default set already (true for "normal" auto upload as well as "custom folder" auto upload)

The issue here is actually not the custom folder: there you only need to provide the local folder and we could (don't do this yet) have defaults for everything (only thing missing is the default for the remote folder). The issue then is that: 
*with normal auto folder because you don't need to configure them. Their are all-smart-default by simply hitting the cloud icon. The screenshot by Tobias is showing the settings screen which gives you the opportunity to change all the defaults. 
* with the custom folder the user needs to provide the local folder but there is no good reason to hide anything else -> so the user has to open the screen again just to set an appropriate remote folder

> Also, it doesn't matter if you are an expert or not – the UX in this case should be perfect. We shouldn't have a "Disable good design" mode in our app, so to speak.

> It's much better to go for simple flow and advanced settings on a case-by-case basis as I proposed, rather than to have a mystery switch in the settings.

There is some confusion... The "expert mode" doesn't disable good design it enabled the user to even have the option to define custom folders which need (at least) the local folder to be provided while the always (also non-expert mode) just gives you the option to activate (and later if you want to configure) media folders that are auto detected. So 
* Media folders don't need a wizard, because we know everything, Tobias' screenshot shows you the details screen that can then be used afterwards to change anything for a folder-pair (media folders)
* custom folders need a "wizard" because one needs to tell us the local folder. Yes anything else can be defaulted and then later be changed in the same way as for the media folders but this also leads to bad UX in my opinion because from my pov a custom folder is a very explicitly configured local-remote folder-pair for any kind of files so I'd most definitely _never_ want this to end in the standard "auto upload folder" nor my account's root folder.

So what we could do is have a dialog for "creating" custom folders that only shows local and remote while remote will be filed with a default after the local folder has been set. We could also just show the remote folder part _after_ the user picked a local folder.

In any case I don't see a truely good solution here atm regarding nice UX :cry:

**Comment by jancborchardt** [comment]
Again - even if this dialog is only shown to people who enabled "Expert mode", my suggestion still stands. Obviously the current design of just showing everything causes confusion.

**Comment by AndyScherzinger** [comment]
> Again - even if this dialog is only shown to people who enabled "Expert mode", my suggestion still stands. Obviously the current design of just showing everything causes confusion.

True, while "just not showing it/hiding it" isn't a complete solution either ;) It is not the "Expert mode" that shows this dialog in contrast to the "normal mode" but that the "Expert mode" enabled custom folders which differ from "media folders" with regards to mandatory user input.

I'll see if I find the time to post some screenshot sicne my impression is that the actual situation isn't fully understood and that we don't have a common understanding of the status quo on the app's behavior...

Other than that "Expert mode" is mixing things here, because it enabled expert functionality and experimental features (like custom folders).

I'll see that I can do some mock ups in the coming days to visualize how I think this matter can be solved nicely, supporting all arguments :)

**Comment by AndyScherzinger** [comment]
Small update #3664 does grey-out the save butotn in case mandatory fields haven't been filled out yet.

**Comment by tobiasKaminsky** [comment]
Closing then as this is a proper fix :-)

If it (still) is not enough, we have to rethink about this.
