### ISSUE TITLE
[UX] Confusing terminology / icon: "Set as available offline" for files, refresh/sync icon for folders

### ISSUE THREAD

**Issue by codethief** [nextcloud/android#208]
As of Nextcloud 1.2.0*, selecting a file makes an option "Set available offline" appear in the "…" menu on the top right. Selecting a folder, however, makes a refresh/sync icon appear on the top right. _(UX remark: I expected to see a "Set available offline" menu entry pop up for the folder as well. It took me a minute of going back and forth between folders and files to realize that there's that icon, instead, and that it doesn't just refresh the current view.)_ As a user, I have absolutely no clue what tapping this icon does. Does it do a one-time download? Does it make the folder permanently available offline (i.e. one-way sync)? A two-way sync? (I know the latter hasn't been implemented yet but still.)

To me it looks like it makes all files contained in the folder available offline one-by-one as I suddenly see green check marks appearing on all my files in that folder (similarly to if I had made them available offline individually). However, I do not see a similar check mark on the folder itself. Does that mean it is a one-time procedure only and new files in the folder won't automatically be made available offline later? Lots of questions here…

**Update:** I just realized that offline availability is now denoted by a yellow download icon, while a green check mark means… that the file is in fact available on the device, i.e. was downloaded, and/or that it is up-to-date? Quite confusing! Anyway, I therefore assume that the sync/refresh icon appearing for folders just downloads all files in the folder once?

**My suggestion:** Make the terminology and the use of icons consistent and their meaning unambiguous. If in doubt, introduce a menu entry "Legend help" to explain the icons.

PS: I hope it doesn't make a difference but I'm still running OwnCloud. According the [announcement of the Android client](https://nextcloud.com/nextcloud-android-client-1-1-0-is-here/), the latter should still be fully compatible to OwnCloud.

(*) I was 100% sure I would be downloading v1.1.0 from the Play Store as this is the version that was last announced (see above). Where can I find information on the v1.2.0 release?

**Comment by AndyScherzinger** [comment]
Thank you for your report @codethief !
@jancborchardt and @tobiasKaminsky this is quite an issue imho without talking about features we do not have as of now but only about the given functionality.

File(s) Selected:
* Download (download arrow): basically downloads the file (end status is the green check mark)
* Set available offline (usually text, except some Samsung devices which display the icon - device with down arrow): downloads the file and marks it for sync (green check mark + the yellow download arrow)

Folder(s) Selected:
* Sync (refresh icon): downloads all files within marked folder(s) (files then have the green check mark)

Folder(s)+File(s) Selected:
* Sync (refresh icon): downloads all files within marked folder(s) and the marked files (files then have the green check mark)

Functionality wise this is "correct" since we can only download files and flag files for "keep them in sync". But as mentioned in the ticket the icons/text are misleading. Any ideas on how to correct this? @jancborchardt and @nextcloud/designers ?

**Comment by AndyScherzinger** [comment]
repinging @jancborchardt and @nextcloud/designers

**Comment by Bugsbane** [comment]
Ok, so if I understand correctly from your description Andy, then the general pattern would be to call files and folders either Downloaded (with a download icon) if they're not going to be kept in sync with changes, or Sync (refresh icon), if they are. So following that pattern...

"Set available offline" should really be called "Sync" as "Set available offline" doesn't imply that the files will be kept up to date with changes. I mean, just downloading the files makes them available offline, whether they're kept synced or not (which it sounds like they are).

"Sync" in the context of folders and folders+files should actually be called "Downloaded" and use the download icon (a checkmark implies more a job that needs to be done, than the availability of a file). Files downloaded should be marked the same.

**Comment by codethief** [comment]
As a remark, are file changes propagated back to the server if they are "synced"? If I remember correctly, there's no 2-way sync yet, right? In this case it would probably be wise to include either a 1-time popup note to advise the user on this or to call it "mirroring".

**Comment by Bugsbane** [comment]
@codethief - Yes, there's only 1 way sync at the moment. While it's more technically accurate to call it mirroring, , I highly suspect that the majority of users wouldn't be aware of the difference between syncing and mirroring. I agree that a one time warning that sync is one way only (aka mirroring) is worthwhile to avoid confusion. I'd still just refer to it as sync though, or if we have space "Keep synced with server version" as far more users will understand "One way sync" (from the server) than "mirroring", especially in the medium to lower tech userbase. Also, this allows us to avoid changing all of the terminology in the interface when we do eventually introduce 2 way sync (which I'm assuming is on the roadmap to happen eventually, right @AndyScherzinger ?)

**Comment by AndyScherzinger** [comment]
@Bugsbane imho it is a sync and it works both ways as in keep files on par between client and server. It is though a so called 1-way sync as in you can only push changes one way not both ways (at the same time) which would be a 2-way sync. That is something we probably never implement since that would mean that we would have to diff/merge a file which leads to possible so called 3-way merges and different conflict resolving strategies (very technical description) which is close to impossible to properly solve. If I am correct if a conflict is detected the app asks you if you want to keep both versions (while one will than be renamed). The mirroring is the "set available offline" I think. But I am not an expert on this functionality since I am not using it.

Any feedback @tobiasKaminsky ?

**Comment by codethief** [comment]
@Bugsbane Ok, that makes. Please do include a warning, though! A couple days ago, I thought that 2-way sync simply hadn't been implemented for entire folders yet but expected it to work for single files. That is, I expected the changes I made to one of my files (that were selected to be available offline) to be propagated back to the server. Well, that obviously didn't happen and due to an unfortunate series of events (me thinking that the version on the server is up-to-date and so on) I lost all my changes which were worth days of work…

@AndyScherzinger As far as I understand most people here have been using "1-way sync" in the sense of mirroring and "2-way sync" as "propagating changes back and forth between server and device". (See the famous owncloud/android#1136.) Conflict resolution is somewhat orthogonal to the latter.

**Comment by AndyScherzinger** [comment]
@nextcloud/android we should probably do a session on which kinds of "pushing file changes back and forth between client and server" are possible and which of them we should support in the app. What do you think?

**Comment by tobiasKaminsky** [comment]
Closing as "available offline" will be removed via #2886.
