### ISSUE TITLE
Idea: Upload only when connected to "x" network

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#2099]
I'm really dying for the ability to allow automatic uploading only when connected to a specific network.

Currently I'm using Tasker to basically start the Nextcloud app only when I am connected to my home network. When on the local network where my Nextcloud server is running it allows uploading of images 100x faster. The problem is the mess of having to set this up and kill the app on a device reboot (so it won't upload on the wrong network).

Could we please get a simple feature to specific the SSID of networks we allow auto upload jobs to run when connected to?

Thanks.

**Comment by stratege1401** [comment]
the only wifi is not enough ???

**Comment by tobiasKaminsky** [comment]
I think this overcomplicate things and we want to avoid too many manual config options.
We introduced "walled garden" check, so we already check if wifi is working.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky totally agree, while I get the motivation behind it which we may or may not consider an edge case. User sets up Nc in a LAN so the only time it makes sense to try to upload would be when connected to that LAN and there are others who argue that this is a security issue (which I disagree) since you might be using a open wifi hot spot "by accident". 

For the later part I say disable auto connect open wifis, use ssl, use e2e.

Does "walled garden" detect general connectivity to the Nc instance? (Which some also consider a security issue since the rogue hacker wifi would get to know the server address...)

**Comment by tobiasKaminsky** [comment]
> Does "walled garden" detect general connectivity to the Nc instance?

Yes, as otherwise we would have to use some other url which then can track all the user. 
"Revealing" the nextcloud server address is no security issue in my opinion as every single call to our app reveals the address.

In general, this request is similar to #436, and in my opinion out of scope of the app.

**Comment by AndyScherzinger** [comment]
I'll agree with you with you on this issue, yes.

**Comment by OlivierBondu** [comment]
> User sets up Nc in a LAN so the only time it makes sense to try to upload would be when connected to that LAN

This is exactly my use-case, my ISP doesn't allow for remote access of my private network, but in practice I don't care much. However I do care, for my battery life, that the app tries to connect whenever I am plugging my phone and there is a wifi network somewhere... I do not happen to only plug my phone at home.

> I think this overcomplicate things and we want to avoid too many manual config options.

I do disagree this overcomplicates things, but in any case it could be part of the 'expert' options

I'm happy to help, but I don't know java :smile:

**Comment by bene64** [comment]
I also have the usecase of a local NC instance without access to the internet (blame my ISP). 

Is this still an issue (when it's in expert settings) which could be considered to be merged into the official app if there is somebody working on it?

**Comment by AndyScherzinger** [comment]
@bene64 that is hard to tell since we never asked the designer's feedback. That said... @nextcloud/designers and @nextcloud/android any opinion on this? Asking for feedback

**Comment by strugee** [comment]
So, it's not my decision to make since I'm not involved in the day to day of the Nextcloud Android app, but I do want to provide some context for those asking for this feature and note that UI complexity is only one of several costs new options bring. http://neugierig.org/software/blog/2018/07/options.html is a good explanation of the factors that go into a decision to add or not add a new option :)

**Comment by AndyScherzinger** [comment]
Thanks for the input @strugee :)

This rquest has even more implication than the obvious one mentioned in the issue's description because this is basically a request for a wifi filter because one could argue that the same applies for manual uploads and that they need to be queued until the allowed wifi connection is available, same goes for showing that the client is not connected to this wifi since 3.3 will introduce "no internet" and "no server connection" messages for the users.

Furthermore to make it just a bit more complicated is that one might say "just for a list of SSIDs" or "not for a list of certain SSIDs". 

What I am trying to say is that this is a quite complex matter and we also have to take into account that _if_ we decide to implement such a mechanism that we need to come up with a good solution UI wise which is a tricky as to decide if and how to technically implement such a feature.

Personally I still think it is rather an edge case looking at the whole user base while I am aware that this doesn't make it any better for the people who might benefit from such an implementation :/

**Comment by bene64** [comment]
Depending on the „no server connection“ message in 3.3 my specific usecase could be resolved.
If an automatic upload doesn‘t fail because it simply isn‘t triggered because it can‘t connect to my local server, then I probably can life with it.

**Comment by AndyScherzinger** [comment]
The message is just shown while browsing,the uploads would still fail at that moment. @tobiasKaminsky correct me if I'm wrong but the client should just restart the uploads when connected to the wifi thus it'll upload later when possible,right?

**Comment by tobiasKaminsky** [comment]
This is the expected behaviour, yes

**Comment by AndyScherzinger** [comment]
> This is the expected behaviour, yes

@bene64 than you should be fine

**Comment by jancborchardt** [comment]
Closing this hence. We simply can not add settings for every little thing as we need to test all settings and make sure _everything_ works. Testing all these different settings would take a lot of resources from our already limited pool.

@strugee good read! :) I can recommend [Choosing our preferences](https://ometer.com/preferences.html), which is a bit older and always holds up.
