### ISSUE TITLE
It's confusing that you delete your account and not log out

### ISSUE THREAD

**Issue by mnag-hoststar** [nextcloud/android#2108]
### Actual behaviour
Users we tested this with find it confusing that you have to delete your account.

### Expected behaviour
That you log out instead of delete the account. It basically amounts to almost the same. It would just be a matter of wording.

Feel free to close this issue as won't fix, if this is not something you plan to change.

### Environment data
Android version:
7.0

Device model: 
Moto G5 Plus

Stock or customized system:
Customized version, but only colors and icons/logos have been altered.

Nextcloud app version:
2.0.5

**Comment by AndyScherzinger** [comment]
@jancborchardt @nextcloud/designers @comradekingu any input welcome :) 

We started out with "remove" then changed it to "delete". I am unsure about "log out" since that isn't quite the truth. We do log out but also delete any synced data on the client so it is is more than just a log out where as a user one could expect all synced files, settings, etc. to then be still there when logging in again. Which isn't the case since for reasons like security we remove the data from the device which includes any account configuration related to the client app itself.

**Comment by jancborchardt** [comment]
@AndyScherzinger based on your description it sounds like we could remove the "Log out" function cause it results in exactly the same as account deletion.

**Comment by mario** [comment]
@jancborchardt we don't have "Log out" function :)

**Comment by jancborchardt** [comment]
Right, just saw. I would say this is wontfix then?

**Comment by mario** [comment]
I think so too :)

**Comment by mnag-hoststar** [comment]
Thanks, I assumed that would be the case. :) But I had to ask anyway.

**Comment by jancborchardt** [comment]
@mnag-hoststar sure, thanks for your understanding. Feedback always helps though so keep it coming. :)
