### ISSUE TITLE
Image & Preview not loading correctly

### ISSUE THREAD

**Issue by Django3** [nextcloud/android#2121]
Hello,

i installed right now the new app. If i click on a picture and swipe through, sunddenly the preview and image are not loading anymore.

A video from the issue: https://vimeo.com/254868826

Best regards,
HANNES 

Android version: 7.0
Device model: Huawei Mate 10 Lite
Nextcloud app version: 3.0.0.

**Comment by tobiasKaminsky** [comment]
Instead of downloading the whole file, a screen adapted image is shown. This is computed by the server.
Are the preview/thumbnails on web ui are working for this specific files?

**Comment by Django3** [comment]
Yes, in the web ui is everything fine. In my opinion they are preloading in the app until i click on a file/picture.

So if i open a folder in the app, i can see per example 20 thumbnails were loading in the first few seconds and then click immediately on a picture. I can swipe until i reach the photos without thumbnails.
Then not the screen adapted image is shown/loading first - i recognized it is immediately loading the full size picture and is showing the black placeholder. What in my opinion is the wrong way, cause the thumbnail/screen adapted image should bridge the time of loading the full file or allow to swipe through.

**Comment by Christian-U** [comment]
I have the same problem. At folders with many files, no thumbnails were loading and if i click on a photo, i only can see the placeholder even if i wait a while.

**Comment by hoellen** [comment]
Same here. Android 7.1, Nextcloud App: 3.0.0, Nextcloud Server 13.0.

**Comment by Django3** [comment]
@tobiasKaminsky : any steps we can test for you to find the issue?
Most times, neither the preview nor the full picture itself will be loading. So it is only showing the placeholder.

**Comment by tobiasKaminsky** [comment]
Logcat would be nice to see why the preview generation is not working.
ttps://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Django3** [comment]
@tobiasKaminsky - heres my logcat in the attachment.

... i used nextcloud from 9:50 about 1 minute.

[logcatOutput.txt](https://github.com/nextcloud/android/files/1726898/logcatOutput.txt)

**Comment by tobiasKaminsky** [comment]
Hmm, I tried this:
- enter e folder with ~1k images
- fast swipe to a point where no thumbnails are available
- click on this image -> placeholder -> wait a moment -> resized image
- continue to browse through other images, all behave the same

I am using https://apps.nextcloud.com/apps/previewgenerator to have previews nearly instantly.
Otherwise you would have to wait until the server processes the resized image with the right dimensions.

All in all, I do not see a reason why the thumbnails/resized images are not shown. Yes, it could take a while, but if you do not browse the folder, the thumbnails must appear...
Or is there something special with the folder? Shared? Read-only?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by hoellen** [comment]
I just wanted to create the log file today, but I tried it 4 times times and the thumbnails works every time when I tried. 
Perhaps this is due to the phone restart I did yesterday?
I use also the previewgenerator. And it works fine (and fast) on the web-ui. 
If i get again into this problem I will provide a log file with (hopefully) more information.

**Comment by Django3** [comment]
OK, i will make a few other tests and can create a test account tomorrow.
I recognized, it seems to skip the resized image in my case. 

Here is my flow:

- enter e folder with ~162 images
- fast swipe to a point where no thumbnails are available
- click on this image -> placeholder -> wait a long moment -> image (no resized image).

or

- enter e folder with ~162 images
- swipe to a point where thumbnails are available
- click on this image -> resized image -> wait a moment -> image

So only if i click on a image with loaded thumbnail, everything is fine.

**Comment by tobiasKaminsky** [comment]
> click on this image -> placeholder -> wait a long moment -> image (no resized image).

Do I understand correctly that in your first case the whole image is downloaded?

**Comment by Django3** [comment]
Yes correct! I hope i will find today some time to make a few tests.

**Comment by tobiasKaminsky** [comment]
Strange, the complete image should never be downloaded automatically.

**Comment by Django3** [comment]
Hmm ... @tobiasKaminsky , i think we misunderstand each other. ;) Maybe i used a wrong word for something or misunderstand something.

- enter a folder with ~162 images
- fast swipe to a point where **no** **thumbnails** are **available**
- click on this image -> placeholder (low-res one skipped) -> wait a long moment -> image

In this case, user with a not so fast connection see the placeholder for a long time cause the low-res one skipped. Maybe you are using the thumbnail for it? If yes, the thumbnail should load immediately if you click on a image without one.

![case1](https://user-images.githubusercontent.com/33788078/36422119-330a8ade-163b-11e8-8f6d-1ec0448cce47.jpg)

- enter a folder with ~162 images
- swipe to a point where thumbnails **are available**
- click on this image -> resized image -> wait a moment -> image

![case2](https://user-images.githubusercontent.com/33788078/36422150-47f38e6e-163b-11e8-97e7-95b722a264ba.jpg)

**Comment by tobiasKaminsky** [comment]
To clarify first the wording:
![case1](https://user-images.githubusercontent.com/33788078/36422119-330a8ade-163b-11e8-8f6d-1ec0448cce47.jpg)

left: file list with placeholder (dummy image icon) as thumbnails (little square images)
middle: shows thumbnail as long as it takes to load the resized/screen adapted image.  As you show on your second case, you see a real square image (thumbnail) if it is already downloaded.
right: show resized/screen adapted image (~50-100kb) instead of the downloaded image (5-10Mb), which is shown via a green download arrow.


So the problem is that if you click on an image which has no thumbnail and no resized image, the app tries to fetch directly the resized images as otherwise you would have to wait a bit for thumbnail fetching and then get the resized image afterwards.
This is done to preserve time and data.

Right now I do not have a better idea. I had once the idea to download all recent thumbnails when on wifi to have those immediately, but this will also not really work due to limited cache...

**Comment by Django3** [comment]
Ok, thanks a lot for this explanation.
Then i have a other problem if the resized image is really only about 100kb. Cause it takes in my case about 5 seconds (best case) to 40 seconds to load the resized image. The average time is about 25 seconds. With a 56k modem that should be faster. ;)

This is the reason why i thought, it is downloading the full (5-10MB) image ...

**Comment by tobiasKaminsky** [comment]
@Django3 the resized image first must be created by the server and this depends on the image size and how fast your computer is.
You can use preview generator, but this will consume a large amount of space, in trade of faster previews.

**Comment by loic12305** [comment]
I think I've got the same issue. I had already opened a issue about that :
https://github.com/nextcloud/android/issues/1281

**Comment by nero120** [comment]
Using v3.5.1 with a nextcloupi server always that image previews take a very long time to load. Does the android app not use the same previews generated by the default configuration for nextcloupi @tobiasKaminsky @rullzer?

**Comment by nero120** [comment]
Any updates guys?
