### ISSUE TITLE
'latest backup' not fit in russian

### ISSUE THREAD

**Issue by boingo-00** [nextcloud/android#2191]
![s80217-103127](https://user-images.githubusercontent.com/10793815/36339070-39d8a1a8-13b5-11e8-8aeb-4e819928d329.jpg)

### Environment data
Android version:
5.1
Device model: 
Meizu M3
Stock or customized system:
Flyme 6.3.0.0A
Nextcloud app version:
3.0.1
Nextcloud server version:
13.x.x

**Comment by AndyScherzinger** [comment]
@boingo-00 thanks for the report, all translations are handled via transifex: https://www.transifex.com/nextcloud/nextcloud/translate/#ru/android since none of the developers speaks Russian, could you fix the string over there? That would be really great, it'll then be automatically part of the next feature release 3.1.

**Comment by boingo-00** [comment]
> could you fix the string over there?
No, your link is 404

**Comment by AndyScherzinger** [comment]
Whoops https://www.transifex.com/nextcloud/nextcloud/android/

**Comment by boingo-00** [comment]
Translated untranslated as I could

**Comment by AndyScherzinger** [comment]
Thanks a lot @boingo-00 ❤️
