### ISSUE TITLE
m3u File not open with VLC or other Mediaplayer

### ISSUE THREAD

**Issue by pierre1977** [nextcloud/android#2204]
since the new update 3.01 i cant open .m3u Files with othe Mediaplayer. 
on older version is will be works.

### Environment data
Android version:
6.0

Device model: 
LG G3 & ZTE A510

Stock or customized system:
no

Nextcloud app version:
3.01

Nextcloud server version:
OwnCloud 9.x

**Comment by xXSTrikeXx** [comment]
Is the old version 9.x of Owncloud cross compatible with nextcloud? @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Not sure if the client is still compatible since we don't test Oc server versions. 

@pierre1977 can you check the path setting in the Nextcloud client settings screen?

There has been a change in the storage management so it might be that the files are now located in a secured file system area where other apps can't access them so you might have to change the location in the settings.

cc @tobiasKaminsky @mario - Any comment?

**Comment by tobiasKaminsky** [comment]
Some more context, how @pierre1977 is doing this is needed.
If he clicks on the m3u file within our app, it should be independent from the storage settings.
We changed the way how to send/share a bit when we combined both. Maybe now m3u is not recognized correctly anylonger.

**Comment by tobiasKaminsky** [comment]
One quick test on 6.0.1 / 7.1.2:
- download a m3u file
- select open with
- select vlc
-> working

On both I first had to start VLC to allow access to storage.

**Comment by Olen** [comment]
Just another note - if the built in player is able to play all the files referenced in the m3u, it should also be able to parse the m3u file itself, and just enqueue the actual media files and play them.

**Comment by mb-bibi** [comment]
The built-in player is able to play all mp3 files separate using newest version of the Nextcloud Android app (version 13.0.2 of Nextcloud, labeled as latest because 13.0.3 isn't offered for built-in web updater up to now) but on Android 6.0, 7.0 and 8.0 it doesn't work with m3u, using VLC or MX-Player app doesn't work, too.

With Android 6 and 8 VLC player app works if m3u-file is opened using Firefox to login to cloud, with Android 7 it doesn't, see attached screenshot. Nearly the same with MX-Player and Google Play Music apps: black or white screen and showing opening action endless.

I guess this is a topic regarding the developer of the built-in player but this thread already exists, so I post it complemental.

![screenshot_20180610-123611](https://user-images.githubusercontent.com/40139562/41200935-537e38e8-6c9d-11e8-87de-fb22971c2cd9.png)
