### ISSUE TITLE
[3.0.2] Login Loop 

### ISSUE THREAD

**Issue by salomonisch** [nextcloud/android#2267]
### Actual behaviour
-Login Loop

### Expected behaviour
- Login without asking again and again

### Steps to reproduce
1. Reboot / Force to Stop and Start App Again
2. Wait for Login Prompt
3. Login (with correct data and active nextcloud server) -> Login Prompt Again

### Environment data
Android version: 
7.0

Device model: 
LG G5 (LG-H850)

Stock or customized system: 
Stock

Nextcloud app version:
3.0.2

Nextcloud server version:
11.0.3

**Comment by guoyunhe** [comment]
Maybe the same issue on my Moto G 5. Try to login but spinner rolling forever. I have cleaned cache and reinstalled the app for several times. No effects.

Nextcloud 3.0.2

Android 7.0

Nextcloud server 13.0.0

**Comment by xXSTrikeXx** [comment]
Can you check your bruteforce table in the MySQL? Maybe this is a relict of previous errors.

**Comment by Superkikim** [comment]
Hello. 

Fairphone 2.0 Android 6.01, Server 11.03.

I had this problem with 3.0. 3.0.1 fixed it, 3.0.2 brought it back. 

I upgraded the server to 12.0.5, and now it works.

**Comment by alainbebe** [comment]
Idem
Moto G 5. 
Nextcloud 3.0.2
Android 7.0
Nextcloud server 12.0.0

**Comment by dim2on** [comment]
same on 10+ samsung tablets

**Comment by mclois** [comment]
I am experiencing the same issue with Nextcloud 3.0.2. If I uninstall the app and reinstall it clean, it asks the server URL, login name and password once and works ok for a while, until it breaks again. I don't know what makes it break. 

I have a Xiaomi Redmi 4X, with Android 7.1.2 y MIUI 9.2.3.0. The server is OwnDrive, 11.0.2, based on NextCloud.

**Comment by xXSTrikeXx** [comment]
@mclois I suggest to update the server core, because 11.0.2 will be EOL.

**Comment by DAveShillito** [comment]
I too am experiencing this issue.

Android client 3.0.2
Wileyfox Spark+
Android 7.0

I'm connecting to Nextcloud 11.0.3 running on a Raspberry Pi2.
I do intend to update to Nextcloud 13 when possible, but when I tried updating to 12.0.5 I was not able to access Nextcloud from the web interface at all so I had to revert back to the pre-upgrade backup.

It looks to be the same issue as this https://github.com/nextcloud/android/issues/2133 which appeared in 3.0.0 and was fixed in 3.0.1.

If not the same issue it manifests in the same way in that the user is constantly asked for their credentials, although it feels as if it takes longer between requests, but have no evidence that that is true.

**Comment by hkyq** [comment]
I was getting this as well on NextCloudPi 12.xx on my Google Pixel 1 with latest on Play Store. After I updated NCP to 13.00, I no longer get the issue.

**Comment by AndyScherzinger** [comment]
Hi everybody, who is still experiencing login loop issues with latest server releases of 11, 12, 13?
Please re-open the issue if you still experience issues with login.

Also consider upgrading to the 3.1 release candidate :-)

**Comment by martinsauter** [comment]
+1, Running Nextcloud 10.0.3 (yes, I know, old, but works), Nextcloud Android app 3.0.1 works well, broken with 3.0.3 on a Samsung Galaxy J5 (2017) and LineageOS running on a Samsung S6 as described above. Trying to get the 3.0.1 apk but haven't found it yet.

**Comment by martinsauter** [comment]
Thanks for that! I extracted the 3.0.1 apk from my S5 running Lineage OS (about 1 month old Android image) and put it on the S6 running Lineage OS (brand new Android image). While 3.0.1 runs on the S5 it ends up in the same error as 3.0.3 on the S6. I then used your link and downloaded some 3.0.x versions and also the 3.1 release candidate to the S6-Lineage and all would experience the same error. Then I removed the app and installed 2.0.1 via your link. This one works, I can go into directories and download files to the phone without getting kicked out to the login screen.

I don't understand this, why does 3.0.1 work on the S5-Lineage but not on the S6-Lineage (same apk, extracted from the S5)??? Does one month of Lineage OS development make a difference??? (Both indicate Android 7.1.2). Hardly, because 3.0.3 also keeps dumping me to the login screen even on a Samsung J5 2017 with a stock Android (Android 7.0)

Really puzzled here, I must be missing something here...

**Comment by AndyScherzinger** [comment]
Afaik you are locked on 2.0.1 since 3.x isn't compatible with Nextcloud 10 and requires at least 11.0.8 to work due to a newly introduced user agent string which was necessary for the e2e feature support.

Other than that I strongly recommend to upgrade the server to 12 or 13 since 10 is end of life and doesn't receive any updates thus also doesn't get any security fixes.

**Comment by martinsauter** [comment]
Nice theory but 3.0.2 is just working fine on one phone in my setup which contradicts the whole thing and leaves me puzzled. But since Android Nextcloud 2.0.1 seems to work for me at the moment, that's a fix for me until I upgrade to OC13 once Ubuntu 18.04 LTS is released later this month. Thanks!

**Comment by alainbebe** [comment]
It's OK for me

**Comment by tobiasKaminsky** [comment]
@martinsauter does the failing devices have an sdcard where the apps can be moved to?

**Comment by Pedulla** [comment]
Update....

nextcloud-dev-20180409.apk seems to resolve the issue.

**Comment by peteromero** [comment]
nextcloud-dev-20180409.apk resolved the issue until its update today. Now both dev and non-dev are broken on my Lineage OS (Android 7.1.2/ LOS 14.1-20180407-NIGHTLY-osprey/ Moto G3 with SD card/ NextCloud Dev 20180410/ NextCloud 3.1.0 RC1). 

After entering all details, the app just closed and forgets all entries.

**Comment by peteromero** [comment]
@AndyScherzinger I know, and it's weird, but I could reproduce it several times after re-installing all NextCloud instances anew, rebooting the device, clearing all caches, etc. I even moved all NextCloud apps from SD card to internal memory. No difference.

**Comment by AndyScherzinger** [comment]
@peteromero some users reported that the login flow and further use of the app depends on case sensitivity, not sure if that helps but worth a try.

**Comment by peteromero** [comment]
@AndyScherzinger that worked like a charm. Thank you very much! 
I can't thank you guys enough for NextCloud; it's the backbone of my migration from Apple to GNU/ Linux and Lineage OS.

**Comment by AndyScherzinger** [comment]
@peteromero Happy to help and glad we got the matter resolved for you :+1:

**Comment by AndyScherzinger** [comment]
That is strange indeed...
@mario @tobiasKaminsky any ideas why log outs might be happening here?

**Comment by peteromero** [comment]
@AndyScherzinger , @mario, @tobiasKaminsky  - I had some problems with spontaneous logouts in the web version & it seems to be my provider (df.eu), which many people report problems with, despite they're otherwise quite decent. Mobile apps were always very stable, and I love it :)

As said, since the update, I either cannot login, or I'm logged out after a new start. Then, my username will not be accepted unless I change it from lower to upper or vice versa (e.g., if I had 'USERNAME' before, it's now 'username' that allows me to log in). Weird...

**Comment by vaderf** [comment]
Hello everyone,

I have started following this thread since few weeks now because I am encountering the same login loop problem as @peteromero. But I am able to log either into my account with the Nextcloud dev app or into a test account with the Nextcloud production app. However I was not able to log into my account with the production app until today when using my username all uppercase (I was not very confident when I tried it but it surprisingly worked). So far I did not experienced any log out.

My account is 5 year old, migrated from ownCloud. However I don't think this has anything to do with the problem because I have another account with the same kind of history and I was always able to log into it for test purpose (I never use this account on my phone). So this seems very account specific.

In case, here are information related to my configuration:
* Nextcloud server version: 13.0.1 (self hosted)
* Nextcloud production app: 3.1.0 RC1
* Nextcloud dev app: 20180414
* Phone: Samsung G3
* Phone OS: LineageOS 7.1 (unofficial build)

**Comment by tobiasKaminsky** [comment]
My assumption of this bug is described in https://github.com/nextcloud/android/issues/2032#issuecomment-371503315

So if you change anything of the saved account (username@server, e.g. tobi@cloud.example.com), then the android device thinks it is a new account.

**Comment by peteromero** [comment]
Thanks for pointing us to #2032 (comment), @tobiasKaminsky. Also, @vaderf, good to know we're not alone :)

As said earlier, both combinations (lower/ upper case) worked occasionally, and sometimes altering it enabled the log-in. So maybe there's something else.

Also, I moved all (dev/ RC version from F-Droid) to internal storage; sometimes it worked, sometimes not. Maybe there's another factor.

However, I figured out that after each update, the login-information seems to be erased. So maybe there's some part of the system that overwrites the login information or triggers a security logout? When I normally reboot, I couldn't reproduce the log-out. To be frank, I din't try meddling with the sqlite database, so that option is still open. Maybe is that it?

Last, I had a few VPN apps on my phone, of which I only used one (Disconnect; great for privacy, but not known for best stability). When I log-in to NextCloud with VPN deactivated, it worked. Again, I didn't try various options, but all points towards some instability; either from the update, or from a VPN. 

@vaderf - do you use a VPN? And do you encounter this problem after re-installing the system? Maybe we could reduce my list by one point? :)

**Comment by vaderf** [comment]
Below some info from my side:
* Only login with uppercase works, I don't have to alternate.
* I never moved the app on external storage.
* Regarding updates, here are two things:
    * I had a problem during an update of the app few months ago which was not able to install properly. But I did not try to solve this because I was on the way of resintalling my OS.
    * After building my unofficial LineageOS with my own keys, I forgot to update the signatures of some apps on the phone so I had a bunch of dead apps (NC was among them). I reset all signatures and then reinstalled the dead apps. All app worked except NC. So to be sure that I did not generate any kind of incompatibility, I deleted all the app data from the data directory.
* Regarding the use of a VPN, I use OpenVPN when on unsecured network and don't have any problem with NC app.

So the bottom line here is I don't experience any instability (neither with the NC app nor any other apps) and the only way to solve my login problem is to use uppercase username.

**Comment by pichouk** [comment]
I confirm that I have the same issue and it worked only by using uppercase username.
My server is running `13.0.2` and application is version `3.1.0`.

**Comment by jhf2442** [comment]
Same here, 13.0.2 / 3.1.0 but uppercase trick is not working
Login attempt is logged to oc_bruteforce_attempts table (which I clear prior to next trial)

without a fix the NC app is useless ! :-(

**Comment by Lufthomas** [comment]
I am still experiencing this issue today:
My server is running 16.0.1
Both the nextcloud app (3.6.2) and the nextcloud dev app (20190524) are experiencing the login loop as described by other users above.
My phone: Moto G3 with Lineage 14.1. I use the SD card for storing apps (including the nextcloud app). 
Likewise changing the username to full caps has (temporarily) solved this issue. 
Has this issue been solved elsewhere?

**Comment by Beeez** [comment]
I am also experiencing this.

**Comment by Detzi88** [comment]
same for me on a Xperia Z5 Compact with Nextcloud and Owncloud App on Lineage14.1 connection to either  Nextcloud 13, Nextcloud 15 or  Owncloud X.
First connection always works for a fresh installed server until i reboot my phone, then it is stuck asking for server address then username and password *crashing* asking for server address again.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by Beeez** [comment]
Here is my own logcat dump. Everything works fine from browser, but Android, Desktop App and IOS all seem to have the same login loops for me. Sorry for the formatting. 

`07-23 08:35:30.431  1552  2006 I clp-JNI : Add pinfo.  (channel) 260973e com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity (server) (pkg) AppWindowToken{8348eeb token=Token{a38c23a ActivityRecord{7118565 u0 com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity t4840}}} 26498 10294 (action) 1
07-23 08:35:30.431  1552  2006 I clp-JNI : Add pinfo end.  1
07-23 08:35:30.431  1552  2006 I InputDispatcher: Delivering touch to (26498): action: 0x1, displayId: 0, '260973e', toolType: 1
07-23 08:35:30.431 26498 26498 D ViewRootImpl@94b078b[AuthenticatorActivity]: ViewPostIme pointer 1
07-23 08:35:30.446 26498 26498 D InputMethodManager: HSIFW - flag : 0 Pid : 26498
07-23 08:35:31.560 26498 26498 D OperationsService: Starting command with id 3
07-23 08:35:31.574 26498 26546 D OwnCloudClient #0: REQUEST GET /status.php
07-23 08:35:32.163 26498 26546 W HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
07-23 08:35:32.165 26498 26546 I GetRemoteStatusOperation: Connection check at https://nextcloud.XXXX.biz: Operation finished with HTTP status code -1 (success)
07-23 08:35:32.165 26498 26546 D GetServerInfoOperation: Trying empty authorization to detect authentication method
07-23 08:35:32.166 26498 26546 D OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/
07-23 08:35:32.924 26498 26546 I AuthChallengeProcessor: basic authentication scheme selected
07-23 08:35:32.925 26498 26546 I HttpMethodDirector: No credentials available for BASIC 'XXXX Files'@nextcloud.XXXX.biz:443
07-23 08:35:32.926 26498 26546 D ExistenceCheckRemoteOperation: Existence check for https://nextcloud.XXXX.biz/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
07-23 08:35:32.926 26498 26546 D DetectAuthenticationMethodOperation: Authentication method found: BASIC_HTTP_AUTH
07-23 08:35:32.926 26498 26546 D OperationsService: Called 1 listeners
07-23 08:35:32.926 26498 26546 D OperationsService: Stopping after command with id 3
07-23 08:35:32.930 26498 28065 D OwnCloudClient #2: Creating OwnCloudClient
07-23 08:35:32.931 26498 26498 D Dialog  : mIsSamsungBasicInteraction = false
07-23 08:35:32.931 26498 26498 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
07-23 08:35:32.935 26498 28065 D OwnCloudClient #2: REQUEST HEAD /remote.php/webdav/
07-23 08:35:32.938 26498 26498 I DecorView: createDecorCaptionView >> DecorView@bef343[], isFloating: true, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false`

**Comment by Detzi88** [comment]
My Raspberry bricked its file system and took the nextcloud with it. I am now using a hosted solution from goneo.de which works fine so far.
I have al lot of work atm but when i can make some room i will try to reproduce the issue on a fresh install.
The Nextcloud 13.02 was running on Minipibian
The others on Raspian Buster. All on a Raspberry 3B. Thats all i can tell you so far.

**Comment by Beeez** [comment]
@tobiasKaminsky Is that logcat helpful?

**Comment by Lufthomas** [comment]
@tobiasKaminsky 
using the Logcat Reader app and filtering for com.nextcloud.android.beta I have the following results for the login loop:

```

_> <<< log_count = 12 >>>
> [08-01 13:00:53.495 2605:4113 I/ActivityManager]
> START u0 {flg=0x10800004 cmp=com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10207 on display 0
> 
> [08-01 13:01:25.671 2605:2745 I/ActivityManager]
> START u0 {act=RESTART flg=0x4000000 cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10207 on display 0
> 
> [08-01 13:01:25.674 2605:2745 W/ActivityManager]
> startActivity called from finishing ActivityRecord{ad2ecff u0 com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity t5780 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=RESTART flg=0x4000000 cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity }
> 
> [08-01 13:01:26.164 2605:2773 W/ActivityManager]
> Activity pause timeout for ActivityRecord{ad2ecff u0 com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity t5780 f}
> 
> [08-01 13:01:26.321 2605:11892 I/ActivityManager]
> START u0 {act=RESTART flg=0x4000000 cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10207 on display 0
> 
> [08-01 13:01:26.344 2605:11892 W/ActivityManager]
> startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=RESTART flg=0x4000000 cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity }
> 
> [08-01 13:01:26.437 2605:2744 I/ActivityManager]
> START u0 {flg=0x10800004 cmp=com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10207 on display 0
> 
> [08-01 13:01:26.858 2605:10517 I/ActivityManager]
> START u0 {act=RESTART flg=0x14000000 cmp=com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10207 on display 0
> 
> [08-01 13:01:26.950 2605:2773 W/ActivityManager]
> Activity pause timeout for ActivityRecord{5cc3e39 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity t5781 f}
> 
> [08-01 13:01:27.291 2605:11194 I/ActivityManager]
> START u0 {flg=0x10800004 cmp=com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10207 on display 0
> 
> [08-01 13:01:27.677 2605:23768 I/ActivityManager]
> START u0 {cmp=com.nextcloud.android.beta/com.nextcloud.client.onboarding.FirstRunActivity} from uid 10207 on display 0
> 
> [08-01 13:01:27.986 2605:2780 I/ActivityManager]
> Displayed com.nextcloud.android.beta/com.nextcloud.client.onboarding.FirstRunActivity: +182ms (total +1s816ms)
> 
>_ 

The behaviour observed during this loop is the following: 
I start the app, enter the url of my server. Then I press the login button. 
Then enter my username and password. 
Then I press the Login button. 
A screen with a button "Grant access" shows up. 
As I press the button a loading animation shows up on the button. 
Then what looks like a screen overlay shows up making the screen darker and showing the difficult to read text "trying to log in" for a second or less. 
Then the app reverts to the login page from the beginning. 

Only upon entering a changed username (playing around with the capitalization of some letters) does the login work. After some time however I am back to the login loop and soon I won't have any username variations left to circumvent the login loop. 

```

**Comment by Beeez** [comment]
There are two Login Loop issues in Android Nextcloud (and more in Nextcloud Server), both of which are in the top 5 most commented open issues. There's plenty of people giving information and data to help get this resolved but it is all ignored.

**Comment by Samhamsam** [comment]
Same problem here with Xiaomi Redmi Note + Nextcloud Server 16.0.3 + Nextcloud 3.7.2

**Comment by derekblankmccoy** [comment]
I've updated the other issue with my findings. I think we're getting closer to finding the cause.

**Comment by dgtlmoon** [comment]
Is anyone experiencing this when the passwod on NC is changed the app cant login and doesnt offer me to change the password?

**Comment by derekblankmccoy** [comment]
> Is anyone experiencing this when the passwod on NC is changed the app cant login and doesnt offer me to change the password?

Yes, but with LDAP accounts. When the person is changed on AD, Nextcloud kicks the user out. When the new password is entered, the loop starts.
