### ISSUE TITLE
"Improve Nextcloud" notification is cut off and not expandable

### ISSUE THREAD

**Issue by chk1** [nextcloud/android#2302]
### Actual behaviour
I am unable to read longer notifications within the Nextcloud app, specifically [this one](https://github.com/nextcloud/survey_client/blob/master/lib/Notifier.php#L64) which appears after upgrading the server while anonymized data sharing is turned off. 

I tried to tap on it (nothing happens) or swipe down to expand it (reloads notifications).

[Link to screenshot](https://user-images.githubusercontent.com/828496/37058774-d3d50448-218b-11e8-9937-3e96018489ff.png)

### Expected behaviour
The whole text should appear or I should be able to somehow expand the notification by either tapping or swiping.
 
### Steps to reproduce
1. Trigger a long notification, e.g. upgrade from Nextcloud 12 to 13.0 while anonymized data sharing is turned off
2. Navigate to Nextcloud app Notification area

### Environment data
Android version: 7.1.2 (LineageOS 14.1)

Device model: Xiaomi Redmi 4X

Stock or customized system: 
- Customized Android, 
- Stock/official Nextcloud server and app without modifications

Nextcloud app version: 3.0.3

Nextcloud server version: 13.0.0

**Comment by tobiasKaminsky** [comment]
The problem is that the TextView displaying the message is limited to 3 rows.
This should be changed so that text of any length can be shown.

It is not related to anonymized data stuff.
You can just log into server and fire a long notification with
`
php /var/www/nextcloud/occ  notification:generate test "test" -l "iaeiaeaiefgiae9fvchvfg4c5nrt243ns324fdg234h234svaisdte vfg iagesvhgf viahge siaeiake k89iak89ea ifgeiasfe iaf esia e89iaeai89ek iaia ia iaeai eia9e8 iakeia9e8 iakeia9eia9e "
`
