### ISSUE TITLE
Automatically logout after the connection with owncloud (10.0.2) for around 5 seconds

### ISSUE THREAD

**Issue by yanggis** [nextcloud/android#2378]
### Actual behaviour
-Tell us what happens

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. Install owncloud server 10.0.2
2. Connect owncloud server using this app 
3. It will automatically logout  for no reason, after the connection with owncloud (10.0.2) for around 5 seconds.

### Environment data
Android version:
7.0

Device model: 
Samsung s7 Edge
Stock or customized system:
Stock
Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @yanggis it logs you out for a simple reason. The client is sending a user agent string in case of the nextcloud client it contains "nextcloud" while the ownCLoud client send "owncloud". This leads to the file firewall within the ownCloud server to block the client's calls. So the easiest way is to install a Nextcloud server especially since we don't support or even test ownCloud servers for obvious reasons.

We might find a solution for this in the future but I can't give any guarantess that'll it'll come back or won't break again.
