### ISSUE TITLE
Add contacts and calendar support to mobile

### ISSUE THREAD

**Issue by GIJack** [nextcloud/android#24]
The problem: I need three diffrent apps to sync all my data

owncloud, CalDav Sync Adapter and DAVDroid.

DAVdroid has the problem is you need two accounts, one for calendar, the other for contacts. It also chokes on my calendar.(a little large). It also needs a long not-obvious string that is mentioned nowhere in documentation except third party sites.

So, I would like calender and contact support in the official app, so one account will sync everything. Also makes it somewhat easier for novices.(non-technical friends/customers/employees), who merely use someone elses owncloud install.

**Comment by AndyScherzinger** [comment]
Thanks for the request @GIJack 

CalDAV and also CardDAV are definitely on our radar and has been requested by several people, see also https://help.nextcloud.com/t/desktop-mobile-apps/129/15

Concept wise to be discussed though is how this feature(s) should work in the context of the app's multi account capabilities, so the question is then to which account should this be synced, should it be possible to sync to more than one account, should calendar and contacts even be synced to different accounts.

**Comment by affanse** [comment]
Please add "notes" too. I'm a big note taker, if theres a possibilty it will be great.. Thanks..

**Comment by tobiasKaminsky** [comment]
@affanse is there already an existing app? Please open for it a new issue.
Maybe we can co-op with the dev of this app.

**Comment by AndyScherzinger** [comment]
DAVDroid can be found here https://github.com/bitfireAT/davdroid

**Comment by rfc2822** [comment]
> DAVdroid has the problem is you need two accounts, one for calendar, the other for contacts.

This is not true. If well-known URLs are set up correctly, you need only one account.

> It also chokes on my calendar.(a little large).

If there is a problem, please report it. DAVdroid synchronizes only the events of the last 90 days (+ future events) by default, so the set shouldn't be too large.

> It also needs a long not-obvious string that is mentioned nowhere in documentation except third party sites.

This is wrong. You just need to enter the `/remote.php/dav` entry point; or if well-known URLs are configured (very recommended), you only need to enter the hostname.

> DAVDroid can be found here https://github.com/bitfireAT/davdroid

DAVdroid is not on Github. Please see its official homepage: https://davdroid.bitfire.at, where you can also find a link to the source code.

In general, I would not recommend integrating "all things" into one large monolithic app, because that's not how apps should be designed, and it would be much more complicated to maintain them.

**Comment by cwmke** [comment]
```
In general, I would not recommend integrating "all things" into one large monolithic app, because that's not how apps should be designed, and it would be much more complicated to maintain them.
```
While I agree with @rfc2822's statement to a certain extent, particularily since I'm not a developer and can't really speak about the difficulties of maintaining and building software, I do belive a single uniform app for nextCloud would be extremely desireable from a user's perspective.  

I use Davdroid myself and have found it to be a wonderful solution.  If I needed to get someone with little knowledge or interest in technology to setup nextCloud's caldav and carddav themseleves though, this would become an issue.  I have found friends and family tend to have little patience for figuring things out so this becomes a barrier to adoption.

Maybe a solution could be not to have one monolitic app but for a way for app developers to create something more akin to a plugin that would allow their app to integrate into the main nextCloud app.  This would be similar to what already happens with the web interface and would allow for very quick movement between nextCloud apps without becoming a truely monolithic app developed by one head group of developers.

I can only speak for myself, but I believe doing something like this would greatly improve the average user's experience in the future and starting with calendar and contact itegration would be a great start!  Thanks to all of the developers and people who have created this already wonderful software!  This in no way is meant to be disparaging to them.

**Comment by GIJack** [comment]
> In general, I would not recommend integrating "all things" into one large monolithic app, because that's not how apps should be designed, and it would be much more complicated to maintain them.

What? this is a phone, this is not a UNIX application, and the year is not 1985. This really is how apps should work, and its how android works, and its part of the android methodology.  Its how google apps work with an android phone.

Speaking of which, I would really like to see nextcloud aim for feature parity in this regard with google apps. Adding a nextcloud account should be as easy as adding a google account. Don't assume that the only person using owncloud is the sys-admin who sets it up.

**Comment by affanse** [comment]
I agree with GIJack. It is better in anyway to have one account for multiple services. Like google of course. It is better in management and for future development of nextcloud.

**Comment by EDavidF** [comment]
I am not a coder, so apologies in advance, but could a script be written that would:

a) grab NextCloud, DavDroid, other apps from F-Droid;
b) take URL, login and password and pass them to all apps;
c) if needed, grab CAdroid for the many who use self-signed certs;
?

Maybe as an in-between until the many bits (pun intended) get combined...

**Comment by AndyScherzinger** [comment]
We now have a "simple" DAVdroid integration so I am closing this issue for now since the remaining discussion is rather a meta discussion than an issue. Feel free to further discuss though!

**Comment by EDavidF** [comment]
That's exciting to hear! In the process of moving but will check it out as soon as the server is relocated.

Thanks for the great work!

On September 28, 2016 7:06:29 AM MST, Andy Scherzinger <notifications@github.com> wrote:
>We now have a "simple" DAVdroid integration so I am closing this issue
>for now since the remaining discussion is rather a meta discussion than
>an issue. Feel free to further discuss though!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/24#issuecomment-250176486

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by awesome-manuel** [comment]
The new discussion is https://github.com/nextcloud/android/issues/748
