### ISSUE TITLE
No Photos, No Favourites

### ISSUE THREAD

**Issue by deljones** [nextcloud/android#2407]
Hi connected to a NC 13.0.1 instance. Using a Sony Xperia phone and a Samsung Galaxy S2.

Not able to see the Favourites or the Photos.

Both devices are using the latest Android OS.

What further info would be required to find a solution?

Thanks

Dj

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by MeiRos** [comment]
I have exactly the same problem now with rc2. 
Here are my bug hunt stories around this behaviour.
https://github.com/nextcloud/android/issues/2400 and https://help.nextcloud.com/t/nextcloud-app-on-android-keeps-loading/29283/11

**Comment by nickoffff** [comment]
I have the same issue regarding photos. It spins forever. On iOS it is working correctly.

**Comment by gradinaruvasile** [comment]
Same issue here. Never worked for me on Android since i use nextcloud. Now i use 3.1.0 RC1 from F DROID, but was the same from the Google Play version. On IOS it was working.

**Comment by astucieux** [comment]
I can match-up with this bug as well. I have built a new Nextcloud 13.0.2 LAMP setup with only port 443 and SMTP open to the WAN. All desktops+laptops are working okay using the ownCloud client. The WebGUI is great......
However, the Nextcloud 3.1.0 Android app is operational for (upload/downloads/shares/activities) and other stuff. The exception being that the main menu "PHOTOS" or "FAVOURITES" option just spins the blue "Loading..." circle endlessly. The NC server remains idle. This bug affects my Sony Xperia XZ (Android 8.0.0), Sony Xperia Z2 (Android 6.0.1) and even an old Samsung Tab3 (Android 4.4.2).
BTW: I use port translation on my router and the NC Android app and NC clients must therefore use my stated Port number for HTTPS.

**Comment by astucieux** [comment]
The recent release of Nextcloud app 3.2.0 has fixed this issue for me. FAVOURITES works fine as I only have a few flagged. However the PHOTOS option takes well over 10 minutes to be displayed on the mobile screen. There is zero activity with my NC server as it appears that the app is kept busy decrypting the 1,200+ thumbnails images NC has stored in the mobile. This design approach is flawed. I still have another 1,000 or more pictures to transfer onto NC. How long would that take to process, I wonder. My Sony XZ is a powerful mobile but this decrypt and tile display workload is too resourceful, slow and impractical.

**Comment by gradinaruvasile** [comment]
Yes, the favorites menu is working. 
It still has a smaller issue: if i tap on a favorite folder from that list, it will show the folder empty. But if i tap back (which takes me to the parent directory of the favorite folder) i can select the favorite folder and i see the contents...

**Comment by astucieux** [comment]
Ooops @gradinaruvasile you are correct. There remains a gremlin in 3.2.0 of the NC app. The full screen display of my FAVOURITE pictures (JPG's) or when tapping one of the tiled images on the PHOTO panel, it produces a blank (white) screen with a grayed out bar at the top faintly showing the file name. 
Rats, I was too hasty in thinking this was all fixed now.

**Comment by tobiasKaminsky** [comment]
We have already an idea how to improve photo "search", #2250.
What makes me wonder is, that you say that there is no server traffic at all. 
First the search query should be returned and then the app queries every search result for metadata and then for the thumbnails…

@astucieux / @gradinaruvasile can you open up a new issue for this with at way howt to reproduce it?

**Comment by astucieux** [comment]
Greetings @tobiasKaminsky.... 
I have been using the KDE KSysGaurd on my Nextcloud system to watch and gain an idea as to the NC activity. When I touch the app PHOTOS option in the menu list there is a 1 second burst at 2MiB/s sent out of the NC server. For the next 10+ minutes the KSysGuard graph is flat. The NC phone app spins around while it appears to decrypt my 1,200+ encrypted thumbnails* that have already been built from several days earlier. These must have been created the first time I had the patience to let the PHOTOS option run its full course and download processed pictures from the NC server. When the app finally displays the tiled pictures on the phone there is another blip of traffic with the server. The graph goes flat again as network traffic drops to near zero (~1KiB/s).
If those metadata queries involves very small network packets then the KSysGaurd graph probably isn't going to react sufficiently to show them.

It would appear that the NC app on my mobile is processing/decrypting about 1.5 thumbnails* per second.  :-1: 

The thing is, no matter how quick your metadata + search with the NC host is at validating and updating the thumbnail cache. **If** you are then expecting the smartphone to decrypt thousands of mini-pictures each time PHOTOS is selected on the menu, it will continue to be prohibitively slow.
Am I correct in thinking that this is the NC app PHOTOS processing strategy?
And even if the app processed just one tiled multi-picture screen display at a time, it could still take about 50 seconds to decrpt and build each large screen on my Sony XZ. _(Do mobiles have AES firmware assist, I wonder)_

@tobiasKaminsky I assume you would like a new issue opened for the problem of the selected FAVOURITE or PHOTOS not being displayed. The "White Screen with Grey Top Bar"......

It looks like your #2250 work may improve the slow PHOTOS handling with a large JPG file-count. It's a case of, I shall wait and see how that turns out...... My gut feeling is that an option to maintain an unencrypted thumbnail photo-cache is needed on the mobile device to overcome this. The NC app could allow this if a code-lock was in force and wipe the cache if a series of failed access attempts were made.

* Android folder: com.nextcloud.client/thumbnailCache/

With my regards, Pete


.

**Comment by nickoffff** [comment]
The issue is still not resolved.
