### ISSUE TITLE
Improved Upload Status

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2414]
Currently when you are uploading multiple files the status is for individual file itself, this is somewhat confusing because it does not show any information about the total files still awaiting upload:

https://i.imgur.com/CeUg2lp.png

Dropbox Android application works in a different way showing the status of the total remaining:

https://i.imgur.com/QLTXFsf.png

If a file errors out during upload a second notification should open showing the details of which one.

**Comment by toger5** [comment]
I totally agree that there shpuld be information about total upload progress.
I also realized, that nextcloud has huge timeouts/brraks between uploading the next file.

**Comment by Spartachetto** [comment]
I like the actual behaviour: it maker much more simple to detect connection problems, expecially if I am uploading several files at once. Yet having the overall percentage would be an useful addition

**Comment by c0fe** [comment]
@Spartachetto I would suggest a separate notification appear should an error occur, though I do not feel trying to debug this on the Android phone would be preferred. An error message should be sent to log for the user and admin(s).

**Comment by tobiasKaminsky** [comment]
There are/were several discussions regarding notifications in general and upload notifications in particular.

Personally I like the idea to enhance the notifications, while in contrast there are also ideas to remove them completely. Therefore I am really unsure how to proceed here.

**Comment by AndyScherzinger** [comment]
Notifications have been discussed for quite a while now, yes. I agree with this issue and to some extend with the proposed solution. I'd also say this is definitely an enhancement of today's solution for a simple reason: There is no advantage of a single Notification per file.
So to sum up from what I understood and think would be a good way to go is:
* show a single notification for the overall auto upload status
* show a single notification for the overall auto upload errors

Looking at the Amazon drive upload notification I do like their approach since it shows you an overall progress
* in % -> progress bar
* in number of files
* in MB
![device-2018-04-03-133533](https://user-images.githubusercontent.com/1315170/38247295-09671d16-3745-11e8-9870-6bab525fc694.png)

This way you know the actual status and can also anticipate how long it might take to finish. The preview image on the left is also nice while I'd say that would be another increment.

**Comment by c0fe** [comment]
@AndyScherzinger though i do not think that this would be a big issue I do recommend switching from MB to GB once GB is reached. though I cannot possibly think of someone uploading anything this large from their phone.

**Comment by AndyScherzinger** [comment]
>  though i do not think that this would be a big issue I do recommend switching from MB to GB once GB is reached. though I cannot possibly think of someone uploading anything this large from their phone.

of course that would be the case then, also happening for KB, GB, PB, etc. like we do in other places already :)

**Comment by tobiasKaminsky** [comment]
![resized_IMG_20200115_124318](https://user-images.githubusercontent.com/5836855/72431426-1b8b7300-3795-11ea-8b3c-3e3169e2c2c5.jpg)

as agreed with @jancborchardt and @Shagequi

**Comment by BluePixel4k** [comment]
Are there any news for the implementation of this feature? :)
A progress bar would be a nice improvement for the Nextcloud app.

**Comment by BluePixel4k** [comment]
The team is working on this feature 🎉: https://github.com/nextcloud/android/pull/12907

**Comment by jancborchardt** [comment]
@alperozturk96 considering https://github.com/nextcloud/android/pull/12907 has been merged, solving https://github.com/nextcloud/android/issues/12256 – can this be closed too?

**Comment by alperozturk96** [comment]
Added [via](https://github.com/nextcloud/android/pull/12907)
