### ISSUE TITLE
Improve uploading/sharing options

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2443]
I am running Android 8.1.0 and have found the options currently there in the app for example when you press the "share" button in the application for a specific folder:

https://i.imgur.com/5Jq4VXH.png

My recommendation would be the following:

Change "share" option to Share Settings"
Remove the options below "share" and "link" and add "send file" option instead.

Also if you press the Messages button and the file is extremely large as my file is 646.7MB this would cause issues in the sending the actual files, I feel that Nextcloud app should have some kind of limit to prevent the user from inadvertently causing themselves issues when sending files too large.

**Comment by c0fe** [comment]
@AndyScherzinger what are your thoughts on this?

**Comment by AndyScherzinger** [comment]
@c0fe not having a conclusion yet since this "screen" is a work in progress by @tobiasKaminsky where "share" and "link" will have different actions in the future while the options below the line will likely stay since this is the sharing with other apps that support it on the device itself and opening another bottom sheet for sending file seems to me like an unnecessary steps for the user to actually send it. So share/link need some more love while I'd vote to keep the other part as is, if possible add a "send file" heading there. Beware that the other applications shown don't show up for folders but just for files (since we can't send a folder to another Android app, just a file(s)"

**Comment by c0fe** [comment]
@AndyScherzinger honestly, I thought "share" could just be renamed since it does bring up the share options.

**Comment by AndyScherzinger** [comment]
@c0fe Ah, sorry for the misunderstanding.  CC @tobiasKaminsky @jancborchardt for the "name change" feedback

**Comment by c0fe** [comment]
One more thing @AndyScherzinger I think there should be some kind of warning for sharing large items via text since it can cause some weird issues on older phones or may not show up correctly on the receiver or worse may cause quite extensive charges for the end user.

**Comment by AndyScherzinger** [comment]
@c0fe could you create another issue for that to keep the issue small and tidy for discussions and people/contributors to possibly pick them up? Please :heart:

**Comment by jancborchardt** [comment]
Renaming it to »Share settings« would be a bit confusing since it seems like you »Share [the] settings« – but which settings? ;)

We always have to speak the language of what people want to do. And what they want to do is »Share«, not »modify share settings« – so that wording would not be understood.

I’m happy with the wording for now, as @AndyScherzinger said the sharing view is still a work-in-progress.

**Comment by AndyScherzinger** [comment]
@c0fe we revamped the sharing screen and options quite a bit with the latest releases. Please reopen if the issue still remains in you point of view.
