### ISSUE TITLE
Add splash screen for Nextcloud

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2444]
When you do not have Nextcloud app running already on your Android phone and you turn it on, you will receive a blank screen initially while the application starts up. My recommendation is to add a splash screen which can then be customized by anyone who wishes to compile their version. This splash screen would show up while the application initializes.

**Comment by ardevd** [comment]
I agree! I'll try and look into this tonight.

**Comment by AndyScherzinger** [comment]
Thanks @ardevd - cc @nextcloud/designers @jancborchardt for approval of implementing this and also my personal opinion: _splash screen suck, we should add them anyways but should also look into speeding up the main screen loading/rendering since good app's don't need a splash screen_ see https://androiduipatterns.com/splash-screen-with-any-other-name-is-still-a-splash-screen-and-they-suck-bab7f3b5850c for example

@ardevd can you post a screenshot first? I'd say if a splash screen is implemented we should "just show the logo" while of course designers might have a different opinion. "Just the Logo" would be in line with GDrive, YouTube etc.

**Comment by c0fe** [comment]
@AndyScherzinger I hope it doesn't sound like I was intentionally requesting a bad feature but I know my employees here would be confused by the prolonged white screen and figure there is a glitch with their phone.

**Comment by AndyScherzinger** [comment]
@c0fe not at all, imho this is completely valid! I just wanted to state two aspects here, adding a splash screen is fine in general and as a first step of the solution while it should just be shown very, very quick/short while the more important second step would be to speed up the rendering of the main stream (so a splash screen wouldn't even be necessary). Imho a splash screen shouldn't add extra waiting time since that is bad UX and will just enjoy people (like me;)

**Comment by ardevd** [comment]
I'll implement the splash screen according to Google's developer documentation like I did with one of my own apps recently. There shouldnt be any additional startup time but hopefully you'll stop seeing the white splash screen on startup. :)

**Comment by AndyScherzinger** [comment]
Are you fine with this @jancborchardt ?

**Comment by ardevd** [comment]
Keep in mind that I haven't yet looked at the parts of the code I need to integrate with yet so no promises. :) The Nextcloud Android app code base isn't structured the way I typically do it (MVP) so I'm still getting my bearings :)

**Comment by ardevd** [comment]
PR created as promised ;)
