### ISSUE TITLE
Error Uploading

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#245]
### Actual behaviour
-Tell us what happens
When a file is selected it errors out.

Video: https://vid.me/gDCC
Download Video: https://www.dropbox.com/s/wl21qsajpvblenr/nextcloud.mp4?dl=0

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
7.0
Device model: 
Google Nexus 6P
Stock or customized system:
N/A
Nextcloud app version:
1.2.0
Nextcloud server version:
9.0.53
#### Web server error log
```
Insert your webserver log here
```
**Web server:** HostGator Shared Server

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
http://hastebin.com/potucehubu.log
http://imgur.com/a/cFYIL

**Comment by AndyScherzinger** [comment]
@c0fe this is not a Nextcloud bug (unfortunately because then we could fix it...) but an Android Camera bug. You have chosen a folder to be uploaded which seems to be no true folder, etc, etc.
To make things short, scroll down on your camera folder and you will see actual pictures. These can be uploaded (works on my phone Nexus5X Android 7). I am really hoping that Google fixes this soon, since their creation of a folder simply spams my DCIM folder too... :rage:
