### ISSUE TITLE
Contacts Backup: Wrong theme color + can´t be disabled

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2484]
### Actual behaviour
- I have multiple Nc instances with differen theming colors but the contacts backup dialog doesn´t use the correct theming color all the time
- I enabled contacts backup some time ago and disabled it afterwards but Nc still backups the contacts

### Expected behaviour
- The correct theming color should be used
- Contacts shouldn´t be backuped anymore
 
### Steps to reproduce
1. Switch between Nc instances with different theming colors
2. Enable contacts backup
3. Disable contacts backup

### Environment data
Android version: 8

Device model: Nexus 6

Stock or customized system: Custom ROM

Nextcloud app version: Dev from F-Droid

Nextcloud server version: latest 13 from git / latest 14 from git

![contacts backup](https://user-images.githubusercontent.com/1869584/38919515-1642ec24-42f1-11e8-83c8-632548b895a8.png)

**Comment by tobiasKaminsky** [comment]
Thank you for this bug report. Indeed the problem was if the color is so bright that a dark font color is used, then the theming misbehaved.
I will push a fix, which then looks like:
![2018-04-18-133539](https://user-images.githubusercontent.com/5836855/38929753-b1712438-430d-11e8-99bb-2201e331866d.png) ![2018-04-18-133555](https://user-images.githubusercontent.com/5836855/38929754-b18facaa-430d-11e8-8815-14c96f2863fd.png)

Regarding your second issue: The contact backup is per account. So if you have multiple accounts, it will get uploaded multiple times. On the other side you have to disable it on every account, if you do not want to have any backup.

**Comment by splitt3r** [comment]
I enabled it only for one of the three accounts and disabeld it after some time. But the app still backups the contacts regularly.

**Comment by tobiasKaminsky** [comment]
I found one issue, which is fixed in #2488.
Once both PRs are merged, it will be soon in dev version, if you want to give it a try :+1:

**Comment by splitt3r** [comment]
Sounds good. Will give it a try.

**Comment by AndyScherzinger** [comment]
Merged for 3.2
