### ISSUE TITLE
Crash when hitting photo menu

### ISSUE THREAD

**Issue by leolivier** [nextcloud/android#2497]
Each time I hit the photo menu on nextcloud android 3.1 on my oneplus 5 with Android 8.0.0, the application crashes.
I sent comments from within the phone when it happened last time.

**Comment by niemalsnever** [comment]
Same here, on Nexus 5X, App Version  3.1.0, LineageOS 15.1-20180409-nightly (Android 8.1.0). I will provide logs of the crash with a reply tomorrow when I'm back at my PC.

**Comment by tobiasKaminsky** [comment]
@niemalsnever that would be great.
I tested it here, and while sometimes the search keeps spinning / times out, I at least do not experience any crash.

**Comment by niemalsnever** [comment]
@tobiasKaminsky I'm very sorry, but logcat is being super spammy at the moment with things not related to the Nextcloud app, I'm generating some 100 lines of logs every few seconds. Do you have an idea how I would filter the output to just the Nextcloud app?

Otherwise I'm looking at reinstalling my phone later this week anyway, and hopefully be able to provide more readable logs after that.

**Comment by tobiasKaminsky** [comment]
Logcat is always very very verbose. While using AndroidStudio you can limit it very easily to output only infos for an app, but on command line it is a bit tougher:
`
adb logcat | grep "$(adb shell ps | grep com.nextcloud.client | awk '{print $2}')" 
`

Basically, we first find the process id, and then use this to filter logcat.

**Comment by leolivier** [comment]
No crash anymore with version 3.6.0rc1 but it keeps spinning forever
