### ISSUE TITLE
Auto uploaded files are not deleted

### ISSUE THREAD

**Issue by jj-uk** [nextcloud/android#2554]
### Actual behaviour
- Tell us what happens
Files upload from the camera folder but are not being deleted even when delete is set.

### Expected behaviour
- Tell us what should happen
 Uploaded photos and videos should be deleted from the phone after upload. 
### Steps to reproduce
1. Enable auto upload.set to delete after upload.
2. Set camera to use SD card as storage.
3. Take a photo or video and then wait for it to auto upload. This usually fails and it never uploads but on the rare occasions it does upload, the original photo or video isn't deleted.

### Environment data
Android version:
5.1.1
Device model: 
Samsung j3
Stock or customized system:
Stock
Nextcloud app version:
3.1.0
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ardevd** [comment]
Probably a duplicate of #2505

**Comment by mario** [comment]
I always said this is tricky and the behaviors should be removed as I don't want to touch things outside our own directory even IF it was possible to do it.

**Comment by jj-uk** [comment]
It should be possible.  I use plex app too and that writes to the SD card.

**Comment by gjanssens** [comment]
I would very much like behaviours to be retained and fixed rather than removed. I have based my image management on the idea that uploaded images are moved to a separate directory. That way I can see at a glance which ones still need to be synced.

I have the same issue that I can't make this work for folders on the SDCARD, but I'm happy already if it works from internal storage (and NextCloud data on SDCARD). Unfortunately at present even that isn't working right, but that's another bug (or two).

**Comment by gjanssens** [comment]
I don't think anything new can be added. It seems to me the issue is clear though the solution unfortunately may not be.

**Comment by gjanssens** [comment]
Automatically closing lingering issues may be good for statistics but not good for user satisfaction :(

I can imagine this is tricky to do right in all circumstances. However unless the sync mechanism is 100% reliable I really need an efficient way to figure out which files have been synced successfully. Manually browsing through hundreds of images on the server and mobile phone side by side is very cumbersome. I have had to do that in the past several times and I can't recommend it. Being able to move files that are synced out of the original directory is much more efficient.

**Comment by tobiasKaminsky** [comment]
> Automatically closing lingering issues may be good for statistics but not good for user satisfaction :(

It is more to see which bugs are still active.
Is this still valid for you?

I read that it is/was working for you when images are on internal storage?

**Comment by jj-uk** [comment]
I cannot comment as i've moved to Android 9.

**Comment by gjanssens** [comment]
> > Automatically closing lingering issues may be good for statistics but not good for user satisfaction :(
> 
> It is more to see which bugs are still active.
> Is this still valid for you?
> 

It still is, though the app is more clear about it upfront than it used to be. It now won't allow me to choose a behaviour if it detects the source directory is read-only.

> I read that it is/was working for you when images are on internal storage?

True, though to my mind that's a workaround, not a full solution. Internal storage is typically pretty limited in free space. So if time between network accesses is long enough, that free space may get used up before the next sync run (I have experienced this when out of town several times). At that point the camera switches over to SD card automatically, and I get back into this messy situation requiring manual checks of what was synched and what wasn't.

Again, I appreciate this may be a hard problem to solve, especially if Samsung won't allow users to control the access restrictions to folders on the SD card.

Still I'm confused about this: what I understand from other threads is the issue is each app is only allowed to access (or at least write access) its own directories. That would explain why Nextcloud can't (re)move files from the Camera directory. Yet the Gallery app can ? And more even the Gallery app can still delete pictures from Nextcloud's directory ? How does that fit with the initial explanation of this problem ?
