### ISSUE TITLE
We need single android account for all nextcloud apps

### ISSUE THREAD

**Issue by danialbehzadi** [nextcloud/android#2606]
### Actual behaviour
- We need to authorize for each of files, talk, notes, etc. apps.

### Expected behaviour
- It should just set up an android account for nextcloud, and other apps should use it for authentication.

### Environment data
Android version: 8.1

Device model: Xiaomi Redmi Note 4X

Stock or customized system: LineageOS 15.1

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.0

**Comment by mario** [comment]
You can already use your Nextcloud accounts in Talk.

As for the rest, there are some plans to make it easier to use central
account storage

**Comment by danialbehzadi** [comment]
Oh, I would be glad to read about these plans. Where can I find them?

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/ownCloud-Account-Importer/issues/3

This is one idea, there is already a proof of concept. 
I hope I can find some time after 3.2 to push this further.

**Comment by tobiasKaminsky** [comment]
In short the idea is to have nextcloud files as a central app, which allows other apps to re-use the account, similar to google play.
If a 3rd party app requests access, you would have to grant it within a popup (provided by nextcloud files app).

**Comment by danialbehzadi** [comment]
That's cool!

**Comment by AndreAle94** [comment]
What do you think about a separate application that manages the user's account independently? In this way all the applications that want to interact with the server can use this app as a basis. Exactly how GooglePlayServices works with all Google applications. 
I think that it should not be included in the application Nextcloud but in a separate apk because of the disk space. For example on a certain device I may not need to access the files but only to use Talk or Passman (or any other application).

**Comment by tobiasKaminsky** [comment]
I would start with having it in Files app. It is only ~8Mb big.
If you only want to have one app installed, then you do not need such "single account" system.
If this then gets popular and there is need for a separate app, we still can do this.
(or put it also in talk; as both are official apps and only official apps should serve as an account provider)

**Comment by AndyScherzinger** [comment]
feature has been shipped and is already being implemented in third-party apps, more to follow I guess, thus closing.
