### ISSUE TITLE
Click on icon, open file

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#2607]
Here is my suggestion, in Android application when the user touches the file icon that can be opened on the phone, be it a image file, documentation, pdf, video or music then that file is opened. If the user presses on the check box then the checkbox is selected.

**Comment by AndyScherzinger** [comment]
@c0fe which screen are you referring to? Because in case you are in a file list and multi select is turned on than your suggestion would be something I'd consider an (UX) antipattern since you are in the context of selecting things.

Whenever someone has the time to implement the multi select differently I'd even go as far as saying clicking on the icon-> select it, clicking on the item(the text) open it. If we ever get to that point then there wouldn't even be a checkbox anymore, since the preview icon/image would incorporate the checked state visually.

What do you think @mario @tobiasKaminsky @ardevd ? (I know that Nextcloud Talk has this kind of selection mode, like gmail)

**Comment by AndyScherzinger** [comment]
Also cc @nextcloud/designers

**Comment by tobiasKaminsky** [comment]
I would keep it the way we have it now, as long-press for multi-select is a common and well known feature, which we would have to support anyway, I think, even if we would use the new idea by @AndyScherzinger (starting multi-select by clicking on icon).

**Comment by c0fe** [comment]
So should I close this issue out?

**Comment by AndyScherzinger** [comment]
I think for now we can close this and if one finds the time to move to a different multi-selection pattern then we can take care of this issue or even have a completely different approach.
