### ISSUE TITLE
Syntax Errors in SQL

### ISSUE THREAD

**Issue by gupta1anubhav** [nextcloud/android#2629]
### Actual behaviour
- There are various syntax errors in FileContentProvider.java  which are affecting the functioning of SQL database.

### Expected behaviour
- These errors should be removed .

### Environment data

Nextcloud app version: latest build version

![screenshot from 2018-05-28 11-33-15](https://user-images.githubusercontent.com/31107831/40600140-e0c0ab12-626d-11e8-80e8-6bc1386d7413.png)

### Would you like to work on this issue?
Yes , I want to work on this issue.

**Comment by tobiasKaminsky** [comment]
The last time I checked this, it was more due to our way of concatenating the sql queries, but not a real sql syntax problem.
:tada: that you want to fix it.

As this is a crucial part of the app, it would be great, if you can also add test cases for your changes. I am happy to help you with it (or write some, if you have not the time for it).

**Comment by gupta1anubhav** [comment]
@tobiasKaminsky I am learning android test implementation so it would be hard for me to write test cases for the changes, if you could help me in doing that would be great.

**Comment by joshtrichards** [comment]
Closing as "wont fix" per discussion (and the associated decision) that occurred in the connected  PR (#2664).
