### ISSUE TITLE
Import DavDroid settings

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/android#266]
Hi, 
I just installed app Version 1.3 and found about the integration of contacts and calendars with DAVDROID.
I like it   3:thumbsup:
On my device DAVDROID 1.3 (latest version) is installed, setup and synchronized with several calendars in NC 10.0. However, how to import the DAVDROID settings into the ANDROID app V1.3 or later ??

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Hi @hitam4450,

there is no way for DAVdroid (or any other app) to call our login screen and have the fields pre-filled. This is something we are implementing right now as in offering this possibility. Problem is though, in order do use something like this the application that would trigger such a pre-filling would need to actually implement this. So this would then be up to other apps.

So this issue is imho postponed until we release such a feature which is a work in progress and is still in discussion/detailing on the final technical design. So hang in there :)

Best regards,
Andy

**Comment by hitam4450** [comment]
@Andy: Thanks for your comprehensive answer, which i really appreciate.

I do have time for waiting...    :smile:

It is just to start the discussion!

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Thanks @hitam4450 :smiley: Nevertheless this will then be an issue to be raised with other apps, where it would be way better if users raised such an issue :wink:

**Comment by tobiasKaminsky** [comment]
With https://github.com/David-Development/ownCloud-Account-Importer/issues/3 we plan to have this app as the central authenticator for all nextcloud related apps, so you have only login once in our app.
I think this is the best way as the common workflow will be 1) install NC app 2) install other apps and not the other way around.
