### ISSUE TITLE
Auto upload On device directory

### ISSUE THREAD

**Issue by qoheniac** [nextcloud/android#2670]
I would like to sync the On device directory an I guess it works as follows: I activate the Expert mode and then set up Auto upload to sync the Local directory $STORAGEPATH/nextcloud/$USER/ with the root Remote directory. My expectation is that after that every change I make in that directory will be synced with the server while only the files selected in the client are downloaded. I did not try this up till now because I am not sure if I am really right about how this works. So can anyone tell me if it is safe to set up the client this way and if it will work as I expect?

**Comment by AndyScherzinger** [comment]
Hi @qoheniac,

the short answer is: Don't do this!

the long answer is: if you setup a custom auto upload folder pair, the client will watch that folder for any changes from that point in time onward. If the client then detects a changed or newly created file it'll upload it to the configured folder on the server. $STORAGEPATH/nextcloud/$USER/ in the client's very own storage path and should not be used in any way because whenever you download a file the client would then auto upload it!

So the question to me is what are you trying to achieve? Knowing that we might be able to suggest how to set up the client.

**Comment by qoheniac** [comment]
I sometimes use my phone to work locally on LaTeX documents via Termux while traveling when I have no internet connection to do it over ssh on another device. So what I want to archive is that when I work on a document sometimes on my phone and sometimes on my computer that nextcloud takes care of the document beeing synced.

**Comment by AndyScherzinger** [comment]
Ah, understood.

So if these documents are residing in a certain folder on your device (outside of the Nextcloud folder on the device) you can simply use the auto upload for that folder (while changes via other clients won't be synced back to the device!)

If you use multiple devices (your scenario) you can simply mark these files as "available offline" in the Android client then the client will also sync them with the server state. At the moment keeping files available offline is only possible on a per-file basis and can't be activated for a folder in general.

Hope this helps.

**Comment by qoheniac** [comment]
Ah, I just checked it and yes the normal "available offline" syncs in both directions. I wasn't aware it works like that. So on a per-file level it does exactly what I want. Offline directories would be a bit more comfortable but this way it also works for me. Thank you for your help! :)

**Comment by tobiasKaminsky** [comment]
There is already a feature request for this, but due to time, we did not developed it yet: #269.
