### ISSUE TITLE
How to copy share link

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/android#2705]
### Actual behaviour
- The new files details / sharing screen looks great but i can´t find a way to copy the link. Am i doing sth. wrong?

### Expected behaviour
- The context menu should show sth. like "copy link"
 
### Steps to reproduce
1. Share a file from the web browser via link
2. Try to share the url from within the Nc App

### Environment data
Android version: Android 8.1

Device model: OnePlus 6

Stock or customized system: Stock

Nextcloud app version: 3.2.0

Nextcloud server version: 13.0.4

### Screenshots

From the Nc Blog post:

![share](https://nextcloud.com/media/2018-06-08-084554.png)

**Comment by AndyScherzinger** [comment]
@splitt3r you can click on "Share link" ;)

@jancborchardt @nextcloud/designers how should we improve this one? Add a menu item like suggested or add a "copy icon" next to "Share link" as a hint?

**Comment by tobiasKaminsky** [comment]
"copy icon" :+1:, similar to web ui would be:
![image](https://user-images.githubusercontent.com/5836855/41416838-13ae8a9a-6fec-11e8-81fb-41301d1dcc0b.png)

or android way would be:
![image](https://user-images.githubusercontent.com/5836855/41416998-719bf886-6fec-11e8-9b7b-ce2488b64c93.png)

or in overflow menu: copy and share as two options

--> I am totally uncertain ;-)

**Comment by AndyScherzinger** [comment]
Well, the Android copy icon (which should be used instead of the Nc copy icon) would be:
https://materialdesignicons.com/icon/content-copy

which would just copy it to your clipboard.
The share icon would make sense if we want to share the link (directly), like we do wenn clicking on the action.

Since the share actions also always contain a "copy to clipboard" entry in the available options I'd say it is enough if we add the share icon right next to the text to suggest that there is a click action available.

**Comment by jancborchardt** [comment]
Yes, there should be the `content-copy` icon to the left next to the 3-dot icon. :)

And as confirmation, both when you check the »Share link« checkbox and also when you click that content-copy icon, there should be a toast saying "Link copied to clipboard".

**Comment by AndyScherzinger** [comment]
@jancborchardt wouldn't it be better to launch the _Andoird_ share actions like we do now (when you click on the text next to the check box) since that is way more comfortable than the clipboard in my opinion.

Android share would basically present you this:
![device-2018-06-14-194813](https://user-images.githubusercontent.com/1315170/41428964-e7e2f9d0-700b-11e8-99ed-2a5b74d22776.png)

So I'd argue that "copy to clipboard (see item in the list) is rather a desktop-ish action because being a mobile user you want to use this link in another application (usually) so why not just launch it right away?

**Comment by AndyScherzinger** [comment]
Problem with the share icon I forgot to mention is that this is already in use in the list view to define sharing with Nc/federated/mail users, so that might be an issue. 
Nevertheless I think we shouldn't drop the screen I showed above because that is already in our app, built in since forever and in my opinion for a good reason.

**Comment by tobiasKaminsky** [comment]
What about splitting it up?
Have a real "copy to clipboard" and the share dialog to send the link to another app.

**Comment by AndyScherzinger** [comment]
@jancborchardt I put the screenshots and the explanation for the design decisions into the PR #2730

**Comment by jancborchardt** [comment]
Right – so there's 2 slightly different things which should both happen:

- Directly when you check the "Share link" box, it should open that dialog for sharing/copying link.
- There should be a copy/share icon next to the 3-dot-icon for subsequent copies, because clicking the "Share link" text is not really discoverable for that. (In most cases, clicking text next to a checkbox _unchecks_ that box.)

**Comment by AndyScherzinger** [comment]
> Directly when you check the "Share link" box, it should open that dialog for sharing/copying link.

That's how it is working at the moment

> There should be a copy/share icon next to the 3-dot-icon for subsequent copies, because clicking the "Share link" text is not really discoverable for that.

The copy icon has been added via #2730 but next to the checkbox label due to the layout of the elements for shared folders.

> (In most cases, clicking text next to a checkbox unchecks that box.)

This isn't the case at the moment but we could easily change it to this behavior (which makes sense since we now have a copy/send action directly available to the user. (I can just do this if you decide to go that way)

**Comment by jancborchardt** [comment]
@AndyScherzinger cool – it's ok like this. The issue if tapping on the text would unshare is of course that it might not be wanted. So let's keep the "Share link" text tap to open the dialog as you did. :)

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger cool – it's ok like this. The issue if tapping on the text would unshare is of course that it might not be wanted. So let's keep the "Share link" text tap to open the dialog as you did. :)

IO unfortunately changed that acording to your comment right after your comment... So should we roll back that change or keep it that way?

**Comment by jancborchardt** [comment]
@AndyScherzinger now with the more padding on the copy icon I think it’s fine. But if we notice issues ourselves we can always change it. :)

**Comment by AndyScherzinger** [comment]
Sweet, then let's wait and see 👍
