### ISSUE TITLE
Improve share link handling

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2742]
as discussed in the forum with @jancborchardt and @jasonbayton: https://help.nextcloud.com/t/nextcloud-android-app-update-with-improved-user-interface-and-sharing/32900/15?u=jan

When a share link is created, copy it to the clipboard directly for fast sharing while not showing the "Send to" dialog anymore. This way the experience is smoother and the user can still edit the links permissions etc. without having to close the send action dialog but can do that anytime afterwards via the newly introduced menu item.

Upon initial creation when the link is auto copied into the clipboard show a Toast saying: "Share link copied"

**Comment by jancborchardt** [comment]
Yup! And showing a toast/snackbar (always mixing up the names … :D) with "Share link copied" for feedback.

**Comment by jasonbayton** [comment]
Yes! Far better, thank you!

**Comment by AndyScherzinger** [comment]
> Yup! And showing a toast/snackbar (always mixing up the names … :D) with "Share link copied" for feedback.

@jancborchardt I extended the issue's description

In this case it'll be a Toast since Android still uses a Toast for clipboard while all other placed have been replaced Toast->Snackbar already :)

**Comment by AndyScherzinger** [comment]
implemented via #2730 / #2739 shipping with 3.2.1

**Comment by jasonbayton** [comment]
Nice on Andy!

**Comment by AndyScherzinger** [comment]
Thanks @jasonbayton, let's see if it works the way everbody wanted it to be :)

**Comment by AndyScherzinger** [comment]
Sorry, prematurely closed... the details view still launches the send link to dialog when activating share by link... :(

**Comment by ardevd** [comment]
@AndyScherzinger care to elaborate on what's not working as intended?

**Comment by tobiasKaminsky** [comment]
- open details on a file, e.g. an image
- go to sharing tab
- share a link
- after successful link creating, a dialog is shown 
	![2018-07-13-113204](https://user-images.githubusercontent.com/5836855/42684445-6a43e606-8690-11e8-9228-cc713100bcc3.png)
- instead only a "Share link copied" should be shown.

**Comment by ardevd** [comment]
It's the FileDisplayActivity that triggers the `ShareLinkToDialog` when a link is created. I'm assuming we dont want to use that dialog at all when a link is created?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger as you changed quite a lot there, maybe you have an hint, how to do this?

**Comment by AndyScherzinger** [comment]
Well, @ardevd nailed it pretty much ;) Afaik @jancborchardt wanted the ShareLInkToDialog to pop up in case the link is created via the bottom sheet and copied to clipboard in case the link is created via the files details fragment. So like @ardevd mentioned we would need to have to actions like `ACTION_CREATE_SHARE_VIA_LINK_SEND_TO` and `ACTION_CREATE_SHARE_VIA_LINK_COPY_TP_CLIPBOARD` :/

**Comment by tobiasKaminsky** [comment]
Then let us wait for confirmation by @jancborchardt and then we have to do it this way and implement two actions…

**Comment by jancborchardt** [comment]
We mostly talked about the detail view I think. For consistency reasons and to fit the expectations, it’s best to do it the same in either view. Or do you have other feedback?

And instead of only a toast saying "Link copied" we could show a snackbar saying "Link copied" and the action for "Send to", which would launch the share sheet, if needed. This would enhance the way we want to do it in the detail view, and also improve it if we want to use the same method when the link is created via share bottom sheet.

And because the bottom sheet already has all these "Send to other apps" options listed below our "Share" and "Share link" icons, we don’t need to have the ShareLinkToDialog directly show when using the "Share link" way. (Because then it just seems like a weird 2-step process for sharing a link, where for sharing with another app you might as well just use those direct icons in the bottom sheet which share the file itself, not a link.)

Does that make sense?

**Comment by AndyScherzinger** [comment]
> Does that make sense?

Took me a while do understand it :laughing: but makes sense to me now :+1:

**Comment by jancborchardt** [comment]
@AndyScherzinger also added a quick illustration of the Snackbar for better understanding. :D

**Comment by AndyScherzinger** [comment]
Thanks @jancborchardt 

@tobiasKaminsky @ardevd I am fine with Jan's proposal, well, I even think that is the best solution :+1:
