### ISSUE TITLE
Add "upload existing"-option to autoupload

### ISSUE THREAD

**Issue by saibotk** [nextcloud/android#2812]
Hello guys,

I wondered if there is any reason, why the auto upload is just uploading new files, which from my perspective does not fulfill a good UX. As an example, i recently showed NC to my parents and the first expected behaviour was, that it would automaticially upload the whole folder and new files. 
So that is, why i'd like to suggest to either add an info to the screen, stating that only new files will be uploaded, or add a "upload existing"-checkbox in the autoupload UI.

I think this could improve the UX on this significantly, because uploading a folder manually is not as easy as the autoupload interface, which seems to be more intuitive.

Just a suggestion, id like to hear your opinions on this,
Keep up the good work 👍

Greetings

**Comment by AndyScherzinger** [comment]
Hi @saibotk, hi @harrisonland - This is on the roadmap, see #285 but nobody had the time to implement it just yet and being a open source project contributions are always welcome :heart:

**Comment by harrisonland** [comment]
Thanks for response, @AndyScherzinger . Frankly, I wish I had more time to learn some programming and be able to contribute, but my wife would kill me! ;-)

Be assured that your efforts are really appreciated.

**Comment by saibotk** [comment]
Thank you, I wish i had more time and less concurrent projects too, but i'll see...

**Comment by javaisbetterthanpython** [comment]
@AndyScherzinger 

What determines the prioritization of these feature requests? Seems like this is a high requested feature. 

I looked at how this would be implemented, and my guess is basically, in the function to add a new directory to the auto-upload watchlist, these two steps would simply need to be taken:

- Perform a directory listing of files in the target directory
- Iterate through the list and add a new job for each existing file

I'm thinking this could be added either to SyncedFoldersActivity.class or actually even earlier in the MainApp.java between 538 and 539, just after dialog.dismiss() before context.startActivity(folderSyncIntent).

`                try {
                    new AlertDialog.Builder(context, R.style.Theme_ownCloud_Dialog)
                            .setTitle(R.string.drawer_synced_folders)
                            .setMessage(R.string.synced_folders_new_info)
                            .setPositiveButton(R.string.drawer_open, (dialog, which) -> {
                                // show Auto Upload
                                Intent folderSyncIntent = new Intent(context, SyncedFoldersActivity.class);
                                dialog.dismiss();
                                context.startActivity(folderSyncIntent);
                            })
                            .setNegativeButton(R.string.drawer_close, (dialog, which) -> dialog.dismiss())
                            .setIcon(R.drawable.nav_synced_folders)
                            .show();
                } catch (WindowManager.BadTokenException e) {
                    Log_OC.i(TAG, "Error showing Auto Upload Update dialog, so skipping it: " + e.getMessage());
                }`

Would this approach make sense or am I missing something?

**Comment by AndyScherzinger** [comment]
@javaisbetterthanpython yes something like that while @mario is the expert on this matter and I am sure if you would be happy to take on this task he'll sure be around to support you. Triggering this initial part within the SyncedFolderActivity seems fine while I can't say if it shouldn't be done within the Job itself directly since large, existing folders might be an issue if you do this within the activity...

As for prioritization that is hard to tell, @tobiasKaminsky and @mario both work for Nextcloud as a company so their priorities are a mix of community feedback and customer feedback. I am on the othr and do this in my spare time besides my day job so for me priority is rather looking at what I can get done within this limited timebox.

**Comment by javaisbetterthanpython** [comment]
Thanks for the reply. 

@mario do you have any thoughts about the best approach to implement this capability?  Does what I outlined seem reasonable, or should we take a different approach?

I looked at the code more today and am thinking that a "FilesSyncJob" needs to be created for existing files in the directory when it is first added to the "auto-upload" list in "SyncedFoldersActivity"? Is that right?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky due to time constraints and work load, can you help out @javaisbetterthanpython? :)

**Comment by tobiasKaminsky** [comment]
Is "upload existing" meant to be a one time action? E.g. a button in the settings of the synced folder?

Overall the main problem is if there are already images in the target folder, to distinguish if they need to re-upload or not:
- We could simply compare them by name, but this will not work on devices which name their image img_001, img_002.
- we could simply upload everything, leading to have duplicated files, which is a bad UX

An idea, which is not perfect, is to use some kind of hash:
- first check file name
- if file name already exists, check hash
- if hash is the same do nothing, else upload, but append (2)

**Comment by javaisbetterthanpython** [comment]
Agree with @AndyScherzinger - Also, I think the complexity to manually trigger this at-will would be unnecessary. 

From my perspective, just getting a one time action to trigger whenever a new auto-upload is configured for a folder for the first time would be sufficient.

@tobiasKaminsky Does it make sense to include that one-time action in the updateToAutoUpload() function in MainApp.java?  Or is it better off in the SyncedFoldersActivity.java?

I've only spent a couple hours reading the source and am starting to get an idea of how things work, but any thoughts or advice would be appreciated.

**Comment by AndyScherzinger** [comment]
Afaik it should be fine to include it in the `SyncedFoldersActivity` for a one-time action. If I remember correctly anything else is about restarts so if the auto upload queue gets filled with the existing files then we are all set.

**Comment by tobiasKaminsky** [comment]
SyncedFoldersActivity is good.
We still need some sort of file check, as it might that in the target folder on server are already files named the same.
(on fresh installations chances are not that high, but on re-installations of the app this might happen)

**Comment by AndyScherzinger** [comment]
> We still need some sort of file check, as it might that in the target folder on server are already files named the same.
(on fresh installations chances are not that high, but on re-installations of the app this might happen)

Definitely especially since this also will happen on new devices if you had a device before that used the same naming schema for images.

**Comment by javaisbetterthanpython** [comment]
What about requiring the destination folder to be empty? Would that be too much negative impact on the user experience?

**Comment by mario** [comment]
Honestly, I always thought either that OR requiring a Checksum plugin on the server (to generate file hash) in order to see if files are the same. But you still lack other things - e.g. timestamps, etc etc.

**Comment by AndyScherzinger** [comment]
Checking if the folder exists/is-empty might be a first step and maybe then if this is not the case renaming the files appending a (1) for the filename might work since a non-empty folder is probably happening quite often, for example when you have a new phone and activate the auto upload for the camera folder.

**Comment by Redsandro** [comment]
I've just started using the Android app, and this is a bit of an UX fail. You get to _visually_ confirm the folder you choose to upload. Your brain automatically thinks: _"So these are the files that will be syned huh."_

Then you click the cloud icon, and nothing happens. So you click the options menu. No option to sync existing files.

The whole reason for syncing is so you can easily access your files and/or remove them from your phone, right? That's why I installed this app, but it doesn't sync anything, because the files pre-existed on my phone. :sweat_smile:  I need to find another way to copy the media folders off my phone, because this app only works if I had installed the app as the absolute first thing when I bought the phone. :joy: 

That's why I'm happy with https://github.com/nextcloud/android/pull/2873 :+1:

**Comment by AndyScherzinger** [comment]
to be released with 3.11. via #4788
