### ISSUE TITLE
add ability to remotely log out (i.e revoke) a specific session within the mobile app

### ISSUE THREAD

**Issue by GLLM** [nextcloud/android#2826]
Hi,

on desktop, through the WebUI, I'm able to remotely log out any session (i.e. revoke a selected session)

I'd like to have such a feature in the android app : be able to revoke a _specific_ session (i.e. remotely log out a specific session in any browser).

**Use case :** 
I opened a session at work (I dont take my pro computer home). 
I forget to log out. 
While going home (long trip in train), within the app, I can kill this session (and not forget to do it later from home through the WebUI ... or avoid logging from the android browser device to do so).
By being able to select the specific session I want to kill, when I arrive home, my personal computer is still logged in and I dont need to bother logging in again (which I would have had to do if the feature had logged every session out)

Thanks
GLLM

**Comment by GLLM** [comment]
Hi @tobiasKaminsky 

Yes, that's right : keep the mobile session logged in and be able to remotely revoke a specific session (not all of them) ... the same way I can do it in the GUI !

Thanks

**Comment by MorrisJobke** [comment]
> @nextcloud/server-triage is this possible?

Possible only if app-tokens are used, because if not they just authenticate again with the stored password. Don't know if there is an API for the sessions.

cc @juliushaertl @ChristophWurst @rullzer

**Comment by rullzer** [comment]
There is no API for that.

I'm also a bit hesitant to add it.

1. It is a very specific use case. Doing this will happen very rarely but yet it is an extra feature added to the app.
2. The only thing we know if that you once logged in with the app. There is no extra checks etc (since that would kill the whole flow). If really needed you can login from your mobile browser.

My main concern is that I'd like to keep the authentication API parts as locked down as possible. And from where I'm sitting this really is a very limited use case.

**Comment by joshtrichards** [comment]
Closing after >5 years due to:

* Insufficient interest (this doesn't mean it isn't an interesting idea, but there hasn't been enough interest in it from anyone else to justify engineering time)
* There are reasonable alternatives: Use the browser on your Android device (can even add a bookmark/direct link from your home screen to make it convenient)
* https://github.com/nextcloud/android/issues/2826#issuecomment-405248605
* https://github.com/nextcloud/android/issues/2826#issuecomment-405539610
* Numerous other priorities which make it highly probable this enhancement Issue will just sit for another >5 years

Thanks for contributing and sharing your idea, however, @GLLM!
