### ISSUE TITLE
Android 9 High Batteryuseage

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/android#2827]
Hello,

On Android 9, When the App is running in Background, the Batteryuseage is top much. Yesterday for me 37% in 18 Hours.
![screenshot_20180714-055049](https://user-images.githubusercontent.com/3295104/42720594-e34c5d0a-8729-11e8-9b9d-8ed43056d342.png)

**Comment by dfsmith** [comment]
I also have high battery use since 3.2.1 (similar to the picture above: i.e., roughly halving my battery life).  Android 8.0.0, LG V6, kernel 3.18.71, version H87121c.
NextCloud is set for automatic uploads on wifi, while charging only.  The sync directory is on MicroSD (it's bigger than the phone's internal flash).
Attempting to downgrade back to 3.2.0 results in "unknown installation error" from Fdroid.

**Comment by Happyfeet01** [comment]
@erdeved sorry for late Response. But, the batterydrain is gone for me since I made an Reset of the Phone. Android 9 stable and Nextcloud 3.2.1.

I have enabled autoupload from Camera and Screenshots. With WiFi only.

**Comment by herrkirk** [comment]
Same here, it uses a lot of battery and cellular data because it keeps refreshing the file list (I have a large amount of files). There should be a way to disable this for some directories, or do on demand.

**Comment by tobiasKaminsky** [comment]
> keeps refreshing the file list

This is done each time you enter a folder, but the file list is only transferred in total, if there is a change.
