### ISSUE TITLE
AutoUpload does not work on all folders

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/android#2849]
### Actual behaviour
- Some folders sync successfully using the AutoUpload feature (confirmed setup)
- Images from [seek thermal camera](https://play.google.com/store/apps/details?id=com.tyriansystems.SeekThermal) are not automatically uploaded.
- The files do not pop up in the upload section of the app, thus they seem not be detected.
- The folder is marked for auto upload but all check boxers are disabled to avoid side effects.

### Expected behaviour
- Some time after the images have been taken they are queued for upload. Further steps depend on state (WiFi?, Error during upload etc).
 
### Steps to reproduce
1. Take an image and wait a few minutes/hours. No upload will be tried.

Unfortunately there is no log of the app (is there?) as far as I saw. Further a manual sync from android settings seems not to help. Same when I click on rescan in the app in expert mode.

Adding a text file in the folder to be uploaded using another app (ES file explorer) also did not make the app start syncing anything.

### Environment data
Android version: 6.0

Device model: Ulefone Power

Stock or customized system: Stock

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.4

### Logs
No server side logs are provided as the problem is purely inside the app.

**Comment by Toakan** [comment]
+1

Android version: 8.0.0

Device model: ONEPLUS A3003

Stock or customized system: Stock

Nextcloud app version: 3.2.1

Nextcloud server version: 13.0.5

**Comment by aghering23** [comment]
Same problems here but the configuration of AutoUpload is a bit different.

Actual behaviour
•	Automatic upload configured for DCIM, Whatsapp & Screenshots
•	Tried various destination directories; Groupfolder(s) & User folder(s) 
•	Tried all variation of AutoUpload options; Upload only with wifi, while charging, use subdirectories, etc.
•	A manual upload of a file/photo is possible to the destination directories.
•	Upload section show no upload activities related to AutoUpload

Expected behaviour
•	All current and new images that are in chosen directory will be queued for upload depending on the your options.

Steps to reproduce
1.	Configure AutoUpload  choose your destination folder and options
1a. Test: Do manual upload of a file photo to the destination directory. 
2.	Take an image and wait a few minutes/hours. No upload will be tried.

Environment data
Android version: 8.0.0
Device model: Samsung Galaxy S7 Edge
Stock or customized system: Stock
Nextcloud app version: 3.2.1
Nextcloud server version: 13.0.3

**Comment by AndyScherzinger** [comment]
@Toakan @aghering23 please see #2834 since you seem to have a general issue with auto upload.

@christianlupus did you configure the seek thermal camera folder via the "standard" auto upload setup (as in the folder is displayed within the list and you activated the auto upload) or did you configure it via the activated expert mode (app's settings) and manually configured the folder to be auto uploaded to the server?

**Comment by christianlupus** [comment]
@AndyScherzinger The folder popped up by itself in the app once some images were taken. Then I just activated the synchronization and adopted the path to match my wishes of a structured saving of files.

**Comment by christianlupus** [comment]
@AndyScherzinger Yes, I had 2 sessions of images so far. After the first session I set up the nextcloud app. A week later I started the second session and on the next day the images still were not transferred. I copied them manually over to the destination folder then.

**Comment by aghering23** [comment]
@AndyScherzinger i have read the comments in issue #2834 and from my understanding a 3th party app ‘syncthing’ is currently a solution to fix this issue. 

To be honest I don’t think this is a nice ‘workaround’ where users are asked to use/configure a 3th party app to enable automatic uploads. This solution may be workable for technical users but like in my case where i have added non-technical users to nextcloud and asked to sync stuff in groupfolders it can be difficult to explain or configure without help. 

For now I’ll stick to manual sync instead of configuring and maintaining a new 3th party app. Can you tell me if this issue is acknowledged as a bug and is being worked on?

**Comment by AndyScherzinger** [comment]
Hi @aghering23, my intention wasn't to imply syncthing as a workaround but rather referring to the other issue since I'd think auto upload doesn't work at all and does not work for some folders have different causes.

The issue itself is acknowledged while I am not aware of anybody actively working on this at this very moment. While Nextcloud being OSS contributions are always welcomed. I can't really work on this since I am pretty busy with my day job at the moment and it is working just fine on my device so I can't reproduce this issue. I also think it works for all other active code contributors so it is rather hard to find the cause of this :(

**Comment by AndyScherzinger** [comment]
> As far as I understand, this issue is not going to be addressed soon as it is not reproducable for the dev team, right?

Right :disappointed: 

> Nevertheless it will take me some time in order to get things done (day job :-) )

Same here ;-)

> Do you have a suggestion where to start looking to get an overview of the code?

@mario is the expert on this part of the app's code. @mario can you give @christianlupus some hint where to look?

**Comment by mario** [comment]
Look into https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/jobs/FilesSyncJob.java and https://raw.githubusercontent.com/nextcloud/android/7e5ee956e948858c279870b1cec0fe65cb879c37/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java.

Let me know if you need additional help.

**Comment by dknx01** [comment]
I have the same problem, too. I configured the app and selected for example the Telegramm-Images folder, but no automatic uplaod started.
Android: 8.1.0

**Comment by AndyScherzinger** [comment]
@dknx01 does it work for images received _after_ you activated the auto upload? Currently the auto upload doesn't auto upload existing images just new ones created after the folder has been configured for auto upload.

**Comment by vszadera** [comment]
Unfortunately I'm on Android 5.0.2, it also closes the startup or in the background, or from within the app. The first time you have specified which folders to download - the download was successful, but only for new files. 
Then he again held a photo session, but after 2 hours, the files in the cloud did not appear.
While the solution is unknown, maybe we should make a button to force synchronization?

**Comment by dknx01** [comment]
@AndyScherzinger I didn't tried it with a new image, but with a new pdf file. So I copied manually a new pdf file into the folder and waited, but no upload/sync was triggered.
I just found a pdf file on my phone, that's why I used it :wink:

**Comment by rwat1** [comment]
I FOUND A SOLUTION GUYS.... @christianlupus @AndyScherzinger @dknx01 @vszadera It worked for me. I just purchased brand new Android **Samsung S9 plus**, and struggling this for a long time.

**My steps:**


I deleted my NC account from NC app, completely deleted NC app, reinstalled from Google Play store.

I deleted the customized Gallery app from f-droid. (If you don't have Gallery app from F-droid, then ensure you are using the original plain vanilla Gallery app, no other gallery app as it may interfere)

Then Start NC app, go through usual process of Logging into account, giving permissions to app to read/write access, you know, the vanilla process of getting Set-up again on NC app. 

Next, I went to Power Saver settings, and I added NC to "Unmonitored Apps" where they won't put to sleep.  Instructions: "Device Management" > "Battery" (on bottom left corner) > " Unmonitored Apps" (e.g. select apps that won't be put to sleep)  > Add NC app to this list >  Click Done/Save. 


Now I got the auto-upload to work on my Samsung S9 Plus running latest software (as of 8/17/18).

**Comment by christianlupus** [comment]
For now I can no longer verify this problem. It might have been closed by some side-effect in the meantime. So I close this issue now and reopen in case anything related is going to arise again.

**Comment by daehruoydeef** [comment]
I tried syncing a music folder via the auto update function. While I was getting the image folder to work fine there is no way I can get my music synced with the autoupdate feature. I tried the guide @rwat1 posted below but it still does not seem to work. It does not even try to sync.
I tried
* creating the folder without content and enable auto sync 
* moving files into the folder while autosync is off then enable it
* moving files while autosync is on
I am running the latest Nextcloud App 3.6.0 with Nextcloud 15

**Comment by christianlupus** [comment]
Seems like the problem is still there although I have no current problems. Reopening this issue thus for further discussion.

**Comment by christianlupus** [comment]
@daehruoydeef What do you think, if I close this issue for now and you open a new one under your own name. Otherwise the stale bot will continuously grouse all the time.

**Comment by christianlupus** [comment]
@daehruoydeef I ask you once more to either take over this issue or I will have to close it. So **please** give me you opinion how we should proceed. Otherwise I will let the bot close the issue in 6 weeks.

Thanks
