### ISSUE TITLE
can't change storage path with mine.

### ISSUE THREAD

**Issue by multiplateform** [nextcloud/android#2855]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @multiplateform, you can choose the space as in internal, sd card via the app's settings screen. A special path within these spaces can't be set.

In general for any kind of support questions please consider using the forum where ou probably get quicker answers since there are more people around: https://help.nextcloud.com/c/clients/android
