### ISSUE TITLE
Apply auto upload changes to the upload queue

### ISSUE THREAD

**Issue by torrbox** [nextcloud/android#2863]
### Actual behaviour
When changing the auto upload to upload not only on unlimited wifi, the existing files in the upload queue do not upload. Not even tapping the files in the queue can force an upload.

### Expected behaviour
The existing files in the upload queue should upload on any connection when I change the auto upload settings. This is necessary because I am suddenly forced to use a mobile hotspot for wifi (my tablet with a sim card that has unlimited data, yet is not recognized by the app as unlimited), and now some of my uploads are stuck in the queue.

Is there any way for me to fix this?
 
### Steps to reproduce
1. Switch from wifi to a mobile hotspot or to mobile data
2. Take pictures that are added to the upload queue by auto upload
3. Change the settings to upload files even when not on an unlimited connection

### Environment data
Android version:
LineageOS 14.1 (Android 7.1.2)
Nextcloud app version:
3.2.1 (appears to be the newest from Google Play)

Update: I solved my specific problem (WiFi hotspot that was not recognized as unmetered) by going to "Data usage" in the settings, then "Network restrictions", then marking my WiFi hotspot as unlimited connection. However, this would not have worked with a mobile data connection.

Hence, it would be nice to be able to manually force an upload, even on a connection with limited data.

**Comment by AndyScherzinger** [comment]
Hi @torrbox and thanks for the report. The obeying of the latest settings for auto uploads is a work in progress, see #2257 as for a manual forced upload: @nextcloud/designers any idea if and how this should be offered? A way mentioned in this issue would be to have it as a tap action on the item in the upload list not sure if this is necessary if the auto uploads start to obey the latest setting changes while I think it would still be nice and easier to discover if the user has some power over the upload queue. What do you think?

Also cc @mario @tobiasKaminsky @ardevd for further develepment input :)

**Comment by jancborchardt** [comment]
@AndyScherzinger if I understand the requirement correctly, then a "pull to refresh" in the uploads view to trigger any remaining uploads would be a solution here?

**Comment by AndyScherzinger** [comment]
@jancborchardt well, from my point of view: two things actually:

* simply obey auto upload changes: the uploads should be triggered automatically if the config changes and queue items match that changed rules for upload
* "pull to refresh" in the uploads view to trigger any remaining uploads while the items should still respect the auto upload settings

There has also been the request to force the app to upload certain files in the queue no matter the settings. I personally consider that an edge case which might do more harm than good or needs to be done on a per item basis since a force upload all items in the queue no mater the config might be a real issue if you are on a very limited but expensive data plan and you have a large upload queue.

So for me both things are fine mentioned in the bullets while the pull-to-refresh is rather a workaround since it should just work. But since it doesn't and some devices/OS versions have issues detecting the change and restarting the auto upload I think it would be good to have the pull-to-refresh.

What do you think @tobiasKaminsky ?

**Comment by Sputnick85** [comment]
Had the same problem/idea. Want to upload some files via 4G instantly. Changed the auto upload settings and nothing happend.


But my problem would have been solved with this. Love the idea!

> Hence, it would be nice to be able to manually force an upload, even on a connection with limited data.

> a tap action on the item in the upload list 

If i want to i could upload selectet items immediately.

Environment data
Android version: 8.0.0
Nextcloud app version: 3.2.1

**Comment by uusijani** [comment]
This is still an issue; a newer (and still open, as of writing this) issue number for reference: #4312
