### ISSUE TITLE
Data on sd-card only readable for other android apps under android 6.0x

### ISSUE THREAD

**Issue by JSoko** [nextcloud/android#289]
### Actual behaviour

If you use the storagepath on sd, other apps, p.e. keepass2Android or Gallery can only access to the files readonly. Only Nextcloud itself can write to its directories.

Path to sd is /storage/9016-XXXX/Android/data/com.nextcloud.android.beta/files
Path to memory is /storage/emulated/0/Android/data/com.nextcloud.android.beta/files

I think this issue is by security design of android 6.0x, but makes the storing to sd-card nearly useless, because, you can't change or delete files using other apps.
### Expected behaviour

Also other apps should be able to change or delete files in the Nextcloud sd-directory
### Steps to reproduce
1. try to access to a file witch is stored in the Nextcloud Directory on the sd card with gallery or keepass2android
2. you can read but not write or delete the files with other apps
### Environment data

Android version:
6.01
Device model: 
Samsung Galaxy S7
Stock or customized system:
Stock
Nextcloud app version:
beta 20160922
Nextcloud server version:
10.0.16
#### Web server error log

no error

**Comment by AndyScherzinger** [comment]
Hi @JSoko yes this is afaik by security design since you are referring to the app's data directory which is protected by Android. As soon as we have implemented #285 step 2 (step one is a instant upload replacement, step 2 would be a "sync any kind of folder pair") this problem should be solved. But again, the app's data directory is protected.

**Comment by su-ex** [comment]
It would be great to have the possibility to choose the sync directory just in a way it's possible with the Desktop client. Furthermore it seems to not be possible for the current beta to write it's directory somehow, all downloads fail. 
Maybe wrong place, but new instant upload does nothing also.
Step two: If I think of the desktop client, it's possible to disable sync of directories, with the app it would be great to have this inversed meaning select those which will be synced the others won't because there's usually less space.

**Comment by tobiasKaminsky** [comment]
As in other issues also requested we will change the sd storage path to ".../media/..." to allow other apps to access to the downloaded files.
