### ISSUE TITLE
NextCloud app - Manual sync path error

### ISSUE THREAD

**Issue by zslukacsik** [nextcloud/android#2910]
### Actual behaviour
- When sync a folder manually, after tap on sync menu(at Camera folder, "3 dots" menu), an another folder created with same albumname but different path. Then two "Camera album" appeared in phone.

### Expected behaviour
- Manually sync folder
 
### Steps to reproduce
1. Open Nexcloud app in phone
2. Tap 3 dots in a folder
3. Select sync

### Environment data
Android version:
4.4.2
Device model: 

Nextcloud app version:
2.3.3

Nextcloud server version:
13.0

Original path:
![screenshot_2018-08-22-13-36-52](https://user-images.githubusercontent.com/42573324/44464475-33e87400-a61b-11e8-968f-fa0690a2230e.png)

Sync path:
![screenshot_2018-08-22-13-32-47](https://user-images.githubusercontent.com/42573324/44464498-3d71dc00-a61b-11e8-9ea4-86b80a4f1ae1.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please see the screenshots within the issue's descriptions. I thought we implemented a filter for hiding Nc internal files from the auto upload but it seems that is either broken or gone.

@zslukacsik thanks for taking the time to extract this into an issue and reporting it. One side note though. If you would have to camera apps installed which name their folder exactly the same (with different storage paths) then they would and will still show up as two entries because they are two different folders :)
