### ISSUE TITLE
Make "delay" auto uploading

### ISSUE THREAD

**Issue by wawont** [nextcloud/android#2922]
Configure photo synchronization.
It would be nice if the option to delete after uploading to the server had a delay setting.
Those. the removal of photos occurred not immediately, but after a specified period of time. During this time, you can use them in social networks and other things.
Thanks!

**Comment by wawont** [comment]
Good.

**Comment by AndyScherzinger** [comment]
basically a duplicate of #1167 which we closed as-in rejected.

What do you think @tobiasKaminsky @mario ?
:-1: I still vote to not go down this road. It add major complexity for an edge case where I think one needs to decide for "delete" or "keep and share with manual housekeeping" while I am aware that this will make some users sad since they'd like the app to take care of that but for me this is not wihtin scope of a files app.

**Comment by apapenko** [comment]
@AndyScherzinger such cleanup feature is available in Google Photos, I switched from Google Photos to NextCloud and I'd like to see this happen. Is it possible to develop at least a brute-force solution where we'd walk entire file-system and check file-by-file if it's uploaded? Something what's currently done with "Also upload existing files"?

**Comment by AndyScherzinger** [comment]
@apapenko can you tell me where to find this in Google Photos? The tree walker to check if uploaded to the server would technically be possible, sure, while I think it is not a priority by the other devs like @tobiasKaminsky @ezaquarii @ArisuOngaku @JorisBodin @Shagequi (while I myself don't have much time in general atm).

**Comment by joshtrichards** [comment]
Duplicate of #2323
