### ISSUE TITLE
Share dialog: user list not really visible

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3022]
- open image
- click on share/send
- open share dialog

![2018-09-12-074909](https://user-images.githubusercontent.com/5836855/45406350-7cb5aa80-b666-11e8-8942-44f29f6593ee.png)

--> User list is too narrow

@AndyScherzinger and me discussed to split this view into "user" and "link" via tabs (same like on file detail). Also height should be adjusted to have ~80% of visible space.
Then every tab has more space and it will also work better on landscape mode on mobile.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky on the other hand, wouldn't it be even better to launch the file details fragment instead of this (legacy) dialog? Since the file detail screen allows for any share action/details to be specified (can edit/delete, expiration, etc). So I think it would be even better if we can launch the file details :)
While that might be quite an issue since the file details fragments depends on the filedisplayactivity. SO another discussion would be to get rid of the 2 pane layout and make file details its very own activity to be launched which could then also be used in this scenario (or any other sharing scenario).

**Comment by AndyScherzinger** [comment]
cc @nextcloud/designers for feedback since my latest comment would imply quite a change in the UI/interaction flow...

**Comment by AndyScherzinger** [comment]
Well, then we need to move the sharing logic to a separate class and work with delegation, also define an interface for the dialog's share actions that need to be implemented by the dialog calling activity since the search callback due to the search provider implementation will hit the activity not the dialog (that is how the OS handles the provider). other than that we might even have to refactor parts of the file details sharing fragment since we don't want to duplicate the whole thing. We could of course, like done of the fragment simply not have a scrollview embedded but let the whole thing scroll that way the UIs would be the same and the scrolling issue would also be solved. Besides we should probably do it that way anyways since having two different types of sharing UIs with different functionality/scope would be weird too...

I'll think about how we can get this done :)

**Comment by tobiasKaminsky** [comment]
This one would be ideal to move it to MVP concept, so that we have two different views (standalone dialog and tab in file detail) for exact the same functions, or?

If you agree, I would give it a try :-)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger while the other ideas are great for longer term, can we have some kind of a quick fix?
Like trying to get the dialog to ~80% of the screen and thus the list is more visible?  Can you maybe give it a try?

**Comment by jancborchardt** [comment]
Yeah, the dialog sizing is cool as a quick fix, if possible.


For the long-term, it still seems good to keep the dialog-like appearance and not switching to a full-screen view so you still have a sense of place. Is it possible to simply use the share list though as we use in the share tab of the sidebar?

(And we should not split sharing and link, the new design handles it way better too. :)

**Comment by tobiasKaminsky** [comment]
Already fixed :tada: 

![2020-11-17-132056](https://user-images.githubusercontent.com/5836855/99389710-bbdf8600-28d7-11eb-9fff-e88bb6fcebae.png)
