### ISSUE TITLE
Open a (downloaded) file with Nextcloud app

### ISSUE THREAD

**Issue by Phyks** [nextcloud/android#3036]
Hi,

### Actual behaviour

Sometimes I download files with Firefox for Android for instance and want to push them to Nextcloud. Once the file is downloaded, I can click on the "download is complete" notification and this opens an "Open with" dialog but Nextcloud is not in the available apps.

![screenshot_20180913-110313](https://user-images.githubusercontent.com/3856586/45479070-c32e0680-b745-11e8-9146-18f36d66ef53.jpg)

If I then manually browse to the downloaded file with a file manager and choose to "Open with", same thing, Nextcloud is not available.

### Expected behaviour

I would have expected to be able to directly open the file with Nextcloud app, which would have been the same as opening the Nextcloud app and choosing to upload this specific file.
 
### Steps to reproduce

1. Download a file with Firefox for Android
2. Click the notification "download is complete", Nextcloud app is not listed there
3. Browse to the file using a file manager and choose "open with", Nextcloud app is not listed there

### Environment data
Android version: 7.0

Device model: Asus Zenfone 3 max

Stock or customized system: Stock + Asus overlay

Nextcloud app version: 3.2.3 from F-Droid

Nextcloud server version: 14.0

I found a couple of related issues for using Nextcloud as a storage provider (basically "open from"), but did not find any issues related to opening files with Nextcloud.

Thanks!

**Comment by AndyScherzinger** [comment]
Hi @Phyks,

thanks for the report. Actually this is an issue with firefox, not with Nextcloud since "open with" refers to applications that can actually open (as in read/display/play/execute/etc) a given file and Nextcloud can't do that so Nextcloud will only show up as an option for "share/share with" from any app for a file.
Unfortunately firefox doesn't offer the share action (no idea why...) so you are bound to use a files application (usually comes with any Android system and go to downloads and share it from there).

So your third point work when choosing a different action:
Browse to the file using a file manager and choose "Share", Nextcloud app is listed there

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what do you think? I'd vote to close this issue since Nextcloud supports the share_with action (to upload files to Nextcloud) but shouldn't support this for "Open with" for any file type since "Open with" is a completely different context on Android where in my opinion the user expected the app to actually open the file.

**Comment by Phyks** [comment]
Hi @AndyScherzinger,

Oh, thanks for the clarification about "open with" vs "share with". I wouldn't actually mind much to have "open with" nextcloud which would actually offer to upload the file rather than actually opening it (I would actually quite expect it this way), but I might have some special use case here. Not sure what is best UX for most users…

**Comment by AndyScherzinger** [comment]
Hi @Phyks, 
the problem with the open with would be that in oder to support this like we support share we would have to support any file type, so whatever file type in whataver scenario you are trying to open, Nextcloud would always be a choice, so if you try to open an image Nextcloud besides all your galleries would show up as an option while any other cloud provider wouldn't 8same for any other file type).

So while the "Open with" use case might work in your case and for your case within firefox we would also corrupt your UX since the app would show app anywhere on your phone if you open any kind of file and the app asks for applications that can handle this file type :/

Even though this might never happen (just a guess!). The right solution would be firefox supporting the share action...

**Comment by Phyks** [comment]
Ah ok, indeed, I see the point. I'll open an issue to Firefox and see. :) Thanks for the explanations!

Feel free to close this one then.

**Comment by AndyScherzinger** [comment]
Alright @Phyks , thanks for giving it a trying with firefox.
