### ISSUE TITLE
Items added using 'Add to Nextcloud' from the 'On Device' page are not added to the device.

### ISSUE THREAD

**Issue by grazing-llama** [nextcloud/android#3071]
First let me say that I have just started using Nextcloud, and it is awesome!
Keep up the good work!

### Actual behaviour
When creating new folders or uploading files from the 'On Device' directory tree, the newly created/uploaded items do not then appear in the current 'On Device' directory. Instead they are created on the server and require you to navigate back out of 'On Device' and locate them in 'All Files' and perform a manual sync. Then the new items are visible from 'On Device'.

### Expected behaviour
If a user performs an 'Upload files' or 'Create new folder' action from an 'On Device' directory, the item should be created on the server (as it currently is) and then synced/pulled down to the device so it is immediately visible/available in the current 'On Device' directory.
I believe this to be the appropriate behavior since the item is being created from 'On Device'. If the user did not want it to be immediately available on the device, I think they would create it from 'All Files'.
 
### Steps to reproduce
1. Select 'On Device' from the main menu.
2. Push the + button and use 'Upload files' or 'Create new folder' to add content to Nextcloud.
3. Observe that the item does not become visible in the current 'On Device' directory
4. Select 'All Files' from the main menu and navigate to the same directory you were viewing from 'On Device'
5. Observe that the file does exist in this 'All Files' location and is not synced.

### Environment data
Android version: **6.0**

Device model: (**Generic**)

Stock or customized system: **Stock**

Nextcloud app version: **3.3.0**

Nextcloud server version: **14**

**Comment by tobiasKaminsky** [comment]
First, welcome to Nextcloud :-)

I think there is a wrong expectation. 
On devices lists all files and folders which are downloaded, e.g. if /A/b.txt is downloaded you will see folder A.
If there is a folder B on server, but none of its content was downloaded, you will not see it "on device".

Creating a new folder is always "in sync" with the server as otherwise it would show an error.

I would most of the time work with "all files" and not with "on device".

**Comment by nickleverton** [comment]
I agree this is a confusing difference.  I would expect "On Device" to contain all the files which are on this device.  To say that files which originated on the device are not included in "On Device", only those which were downloaded from elsewhere, is counter-intuitive and requires the user to keep long term knowledge in their head of where a file originated from, in order to keep track of what they actually have.

My use case is knowing how much data is actually in my owncloud folders on the device, as compared to all that available from "All files".  The "On device" feature as implemented only tells me how much of what is on the device has been downloaded from other devices, and at the moment I'm struggling to think of a use case for that.

**Comment by tobiasKaminsky** [comment]
On device means simply that it shows what files of all your files in the cloud you have downloaded.
So you can see which folder is too big and then remove it locally. 
Or if you are offline and know that you have music/video, you can find and play it.



> My use case is knowing how much data is actually in my owncloud folders on the device, as compared to all that available from "All files".

This is working, or?
