### ISSUE TITLE
Delete uploaded photos after some time/Keep last X photos

### ISSUE THREAD

**Issue by L0sted** [nextcloud/android#3103]
### Actual behaviour
After photo being autouploaded you can only delete it immideately or move to nextcloud directory 
### Expected behaviour
Uploaded photos should be deleted after specified amount of time, not immediately (e.g. week or month). Also useful option could be keeping last X photos.

**Comment by eapetitfils** [comment]
That is something I would really love to have as well. In my use case, I do not want to keep all my pictures/videos on my phone, but I would like ot browse the recent ones.

The problem with deleting the old photos manually is that I am never sure they were correctly uploaded to nextcloud, and since #667 is not closed, I have to manually transfer the files to my PC and let the Desktop client sort the missing ones.

**Comment by cowai** [comment]
@eapetitfils You are exactly right. I have exactly the same problems.
To make sure all photos bare backup I have chosen to delete/move on upload, but that means that if I am not fast enough I can not see pictures in the camera app before they are deleted/synced. Having a more staggered approach would help in this case.

**Comment by jakommo** [comment]
Would love to see this feature. In addition to time / keep X, it would also be great to only delete uploaded files when storage on the phone gets low, similar to what the google photos app does with "smart storage".

**Comment by joshtrichards** [comment]
Duplicate of #2323 

I suggest subscribing to that issue to track progress and/or giving it an upvote :+1:
