### ISSUE TITLE
Android mobile app high background data usage

### ISSUE THREAD

**Issue by rabner** [nextcloud/android#3123]
### Actual behavior
- Tell us what happens
High background data usage of android mobile app. About 150MB per day. When I noticed that couple weeks ago I switched off background data and after few days switched on thinking that Nextcloud might not work properly. As you can see on the chart, until end of the month usage curve did get flat. Now it ramp up again. From the chart it seems that something happened around last week of August and after that data usage started to go up. I remember resetting Davdroid and some other apps in August... 
I am not heavy user of Nextcloud on my mobile, mostly I use Nextcloud News (90%).

![image](https://user-images.githubusercontent.com/40382662/46662982-c08fc700-cbb4-11e8-88b4-cbd541967621.png)

### Expected behavior
- Data usage should be with in tens of MB per day as it was before.
 
### Steps to reproduce
???

### Environment data
Android version:
8.0.0

Device model: 
Samsung Galaxy S7

Stock or customized system:
Stock

Nextcloud app version:
3.3.0

Nextcloud News:
0.9.9.16

Nextcloud Bookmarks:

Notes:
0.21.0

Davdroid (calendar & contacts):
2.0.3

Nextcloud server version:
14.0.1 and 13.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you have anything like auto upload or contact backup enabled?

**Comment by rabner** [comment]
Yes, photos autoupload only on wi-fi (so shouldn't affect that) and contacts/callendar which I had before. It seems now with background data disabled 'drain' stopped. Do I need background data for proper Nextcloud functioning anyways?

**Comment by krombel** [comment]
If you have enabled contact backup #1626 might be your real issue.

Background data is needed to use the auto upload funktionality. If you don't use that, I think it should be safe to remove that permission

**Comment by AndyScherzinger** [comment]
@rabner to get a better idea of what might go wrong here, do you see anything in the server log as-in requests done by the Android client and also what kind of request since for some reason the client seems to gone nuts in your setup. No actual idea at the moment. I am also running a Nc14 Server, Android client with auto upload on wifi only and I do not experience this behavior. Nevertheless we need to find out what happens here to come up with a solution.

**Comment by rabner** [comment]
@krombel this would be crazy as my contacts are 200kB max and set to sync every few hours (default DAVdroid)
@AndyScherzinger if you can help me what logging I should setup please? At the moment I have level 3 logging in nextcloud. FYI I still have background data disabled and data usage is reasonable. I didn't notice any functionality degradation. Since 1st Nov Nextcloud 1MB, DAVdroid 1.6MB, News 4.3MB.
Question: If DAVdroid is used as bridge for data synchronization, contacts sync data should show under Nextcloud or DAVdroid?

**Comment by AndyScherzinger** [comment]
> If DAVdroid is used as bridge for data synchronization, contacts sync data should show under Nextcloud or DAVdroid?

This would show up for DAVDroid

> Not a server expert, but you should see some kind of "Android" log statement that (based on the URL they access) show you what kind of action the client is actually performing.

**Comment by Neugebam** [comment]
Hi,
same Problem here. I had to disable "background data" in the System Options.
Before disabling tons of "propfinds" in the Server log:

x.x.x.x - USERNAME [13/Jan/2019:05:24:56 +0100] "PROPFIND /owncloud/remote.php/webdav/<DIFFERENT FOLDERS>  / HTTP/1.1" 207 858 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.4.1"

It crashed my amount if mobile data (1.6 GB since 3.1.2019 for the NC-app).
I remember that I put a large external folder (pictures) via SMB into my nextcloud Server settings before.

I never used auto-upload and so my solution at the moment is to disable "background data" for the NC-app.


Android version:
8.0.0

Device model:
Sony H3213 (xperia XA 2 ultra)

Stock or customized system:
Stock

Nextcloud app version:
3.4.1

Nextcloud server version:
15.0.2.0

**Comment by tobiasKaminsky** [comment]
@rullzer do you think this can happen due to external storage which is not capable of etag, and thus scans too often?

**Comment by rullzer** [comment]
Why would it? The scanning doesn't affect android right?

**Comment by arucard21** [comment]
I just noticed that my Nextcloud app on Android seems to have suddenly gotten much higher data usage as well. Suddenly used 400+ MB since yesterday though I hadn't even used it myself. Normally it uses almost no data except for when I manually use the app to access my cloud and my auto-uploaded pictures (but I had only taken about 3 pictures since yesterday so that shouldn't have been the cause of this problem). My auto-upload is configured for Wifi only and only when charging.

I did notice one strange thing. When I go to the Activities section (from the left-side menu) I see some activities from Today and Yesterday and then Today and Yesterday again and again. Seems to repeat infinitely, I only see that for as far as I go down (it only stops when it needs to lazy-load the rest). So I was wondering if there might be an infinite loop going on in the Activities that might be causing the app to continuously download an infinite list of looping Activities. I can imagine that this would be put on a normal background data usage, not wifi-only, but with an infinite list it could easily get up to 100's of MB's per day. 

I also checked the server log (from the admin settings page) and didn't really see anything except for this `"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php#321` which has always been in there, I think. I hope this helps figure out where this data leak is coming from.

**Comment by felix-walter** [comment]
I can confirm this issue. I encounter extremely high mobile data usage (700MB+), although only photo uploads over WiFi are enabled and I sparingly download something using the app on mobile data. An increased battery drain can be observed as well (did not even open the app today or take a photo, though it's listed as having consumed 89 mAh today).

I noticed in my server logs that almost everyday there are literally _thousands_ of `PROPFIND /remote.php/webdav/<directory>` entries, seemingly listing any directory available on my Nextcloud instance (I have a _lot_ of them, on external storage as well as in the regular tree. The `PROPFIND` messages refer to both.). Is it the case that the Android app regularly scans the _whole_ directory structure, even if it is not actively accessed? If so, can it be disabled? As I'd like to use photo uploads, disabling background data (which "fixes" the issue) is not an option.

**Comment by felix-walter** [comment]
Here's an example logcat, obtained just now and filtered for messages concerning a single directory (in this case not on external storage):

```
04-02 15:53:19.594 22905 26792 D RefreshFolderOperation: Checking changes in <user>@<url>/<dir>
04-02 15:53:19.596 22905 26792 D OwnCloudClient #5: REQUEST PROPFIND /remote.php/webdav/<dir>
04-02 15:53:19.761 22905 26792 I RefreshFolderOperation: Checked <user>@<url>/<dir> : changed
04-02 15:53:19.765 22905 26792 D OwnCloudClient #5: REQUEST PROPFIND /remote.php/webdav/<dir>
04-02 15:53:20.038 22905 26792 I ReadFolderRemoteOperation: Synchronized /<dir>: Operation finished with HTTP status code 207 (success)
04-02 15:53:20.038 22905 26792 D RefreshFolderOperation: Synchronizing <user>@<url>/<dir>
04-02 15:53:20.101 22905 26792 D RefreshFolderOperation: Remote folder /<dir> changed - starting update of local data 
04-02 15:53:20.213 22905 26792 D FileDataStorageManager: Saving folder <dir> with 9 children and 0 files to remove
04-02 15:53:20.353 22905 26792 D FileDataStorageManager: Sending 10 operations to FileContentProvider
04-02 15:53:20.353 22905 26792 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@af9ff1a (temporary: false)
04-02 15:53:20.415 22905 26792 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@af9ff1a
04-02 15:53:20.538 22905 26792 D FileSyncAdapter: Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
```

Note: The contents of the directory have not changed since years. I'm using the app since ~6 months on the same phone. The same directories are scanned over and over again (e.g. after turning WiFI off and on again) with the same messages in the log. Server version is 15.0.5.3, app version is 3.5.1 (stable channel).

**Comment by felix-walter** [comment]
I can confirm that deleting all app data resolves the high data usage.

**Comment by amalon** [comment]
If I go to android settings, accounts, nextcloud, account sync, and turn Files off, it stops syncing, and restarts when I enable again (logcat shows it). I was under the impression nextcloud app couldn't yet sync files down automatically, and could only sync new files upwards (i.e. auto-upload), so what is the point of the file sync thing? Is it just unfinished?

Is there any disadvantage to disabling file sync? (maybe auto-upload stops too?) If not, maybe the option shouldn't even be there in the first place?

Nextcloud was using 15GB/month (3/5 of my wifi data usage), so I'd appreciate some clarity about this if anybody can offer it.

**Comment by amalon** [comment]
Still happens when I enable sync on nextcloud app v3.6.2 from nextcloud.

**Comment by felix-walter** [comment]
This behavior is still present in 3.9.0 and appears after some point in time (as far as I can tell in the order of weeks to months) after clearing all app data.

When you have a large directory tree, this will completely drain your battery and, besides that, it uses a lot of data.

**Comment by vKnmnn** [comment]
This is still present in 3.10.1
No auto-upload except daily contacts backup (300KB)

I haven't tried app-data deletion because of a weird login-bug that would prevent me from re-adding my account.

**Comment by tobiasKaminsky** [comment]
Please use: https://github.com/nextcloud/android/issues/4511
