### ISSUE TITLE
Animated GIFs still broken!

### ISSUE THREAD

**Issue by AnsuRio** [nextcloud/android#3125]
The issue [https://github.com/nextcloud/android/issues/3020](url) here says it fixed, but it's not. Because the error is still there for me.

### Actual behaviour
- Animated GIFs are still broken!

### Expected behaviour
- Should be playing!
 
### Steps to reproduce
1. Install latest 14.0 and upload images.
2. Browse files thru the Android app.
3. GIFs are still static!

### Environment data
Android version: 8.1

Device model: OnePlus 5

Stock or customized system: Stock

Nextcloud app version: 3.3.0

Nextcloud server version: 14.0

**Comment by AndyScherzinger** [comment]
Hi @AnsuRio, just tested it and it works like a charm. One question did you explicitly download the gif to the phone (green checkmark) or did you simply click on the file in the list. In case of the gif not being downloaded to the client you'll simply see a preview image provided by your server like it is done for any kind of image.

If the gif isn't animated for a downloaded gif, please reopen this issue.

**Comment by AnsuRio** [comment]
Why on earth are we forced to waste space on the phone for a preview of the GIFs!?
I wanted to give Nextcloud one more try, but this is not a good solution to waste space when you have about 30GB of GIFs...

**Comment by AndyScherzinger** [comment]
Simply because a preview is a smaller image for previewing purposes while a gif is a number of frames which get played by a viewing component. So in order to animated an animated gif you need to get an animated gif and as such download it to actually animated it.
Your browser would do the exact same thing! 

So to not having to download all images to just preview them we request the preview image from the server but for previews the server doesn't ship smaller versions of the animated gif but png (or jpeg, not sure).
So this would then rather be a server issue, correct @rullzer @oparoz?

Just out of curiosity what is your use case since 30GB of animated gifs seems like a rather incredibly large number.

Also looping in @tobiasKaminsky for a second Android dev opinion

**Comment by tobiasKaminsky** [comment]
Previews are only cached and cache size is limited to 200mb.

What would be your suggestion @AnsuRio? Directly download the GIF?

**Comment by AnsuRio** [comment]
> Previews are only cached and cache size is limited to 200mb.
> 
> What would be your suggestion @AnsuRio? Directly download the GIF?

Like the behavior of OneDrive, Google Drive and similar cloud services. There you are not forced to download the images to the phone for a working preview of the image. ^^

**Comment by tobiasKaminsky** [comment]
I fear that we are talking about different things:
- preview is working on all video, image files if the server supports it 
- seeing an animated gif requires to download the file

**Comment by Frechetta** [comment]
@AnsuRio is right. Most online media platforms (OneDrive, Google drive, Tumblr, Facebook, etc.) support gif animation without the user having to download the gif explicitly and keep it on their device. Yes - this works because the app downloads it to the device - but it is cached and cleaned up later. This is a common feature and NextCloud should be able to do this.

**Comment by YamiYukiSenpai** [comment]
Bummer that we still don't have this.

**Comment by AverageHelper** [comment]
I know very little about how gifs work, and I'm also new to Nextcloud, but I may as well ask... is there any possibility of pregenerating an animated preview of a gif such that only a limited number of frames are played and each frame is tiny enough to constitute a preview?

**Comment by Blakestandal** [comment]
Yep, this seems to be a wanted feature for years but still doesn't seem to work (while browsing only, downloading to my phone being different.). Any updates planned to change this?? lol
