### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by ewuoso** [nextcloud/android#3141]
Don't you think having an about us section will make people know more about your project.  If you don't mind, I can write it for you

**Comment by tobiasKaminsky** [comment]
Thank you for your idea.
What kind of information do you have in mind and where do you want to place it? 
We already have the "participate" menu and in settings an about section.

**Comment by ewuoso** [comment]
I meant to say a Faq section. 

a section where frequently asked question will be. It will be in the app probably under contact us or about us

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage do you have something like a FAQ section, we could link to?
@nextcloud/designers do you think this is something we need?

I am unsure if we need a FAQ section. We intend to build complete NC so that it is self-explaining. 
Also the FAQ must be maintained and translated.

What kind of questions would you answer? Maybe it is the "better" approach to enhance UI/UX so that those questions will get answered/be shown directly in UI?

**Comment by MorrisJobke** [comment]
> @nextcloud/server-triage do you have something like a FAQ section, we could link to?

Not really. At least not within the server. We have a little thing in the support section with "We are a community which is active in the forums and on GitHub", but nothing I would link to, because it's easier to put directly into the app instead of redirecting to show two sentences.

**Comment by juliushaertl** [comment]
We have some more detailed about section since 14 which is the firstrunwizard, that is now always available in the users menu under About:
![image](https://user-images.githubusercontent.com/3404133/46998561-2fc06a80-d123-11e8-8b0e-0f55906b72c4.png)

![image](https://user-images.githubusercontent.com/3404133/46998515-15868c80-d123-11e8-8b95-492e10e1d6ec.png)

@tobiasKaminsky Maybe it makes sense to integrate those core values into the android about section?

**Comment by ewuoso** [comment]
Cool.  But if you need me to do any form of copywriting for you, I'll be
around.  Go guys

**Comment by jancborchardt** [comment]
The place where we have this "first run wizard"-esque showcase is in the initial run, with the icons etc.

A separate section does not really seem needed. Even worse, it will have to be maintained and the text might get outdated quickly and we then spend time working on that instead of the actual app.

We do have the "Participate" section already with more info.

**Comment by jancborchardt** [comment]
@ewuso if you want to get involved with copywriting, maybe you’d like to help with the documentation? :slightly_smiling_face: https://github.com/nextcloud/documentation/

Also, we have a forum at https://help.nextcloud.com where people help each other. :tada:

**Comment by ewuoso** [comment]
Thabksb

**Comment by tobiasKaminsky** [comment]
Thanks for the input, so closing this for now.
