### ISSUE TITLE
FR: Please revert back the external apps behavior

### ISSUE THREAD

**Issue by gerroon** [nextcloud/android#3158]
Hi

I used to be able to open all my external apps (NC external apps addon) inside the Nextcloud app internal browser or whatever implementation it is, now after last couple updates in dev version it has changed. Now some of the external apps/urls open in the default Android browser instead of the the app itself.

You might say what difference does it make, well originally it felt like the external apps were integrated since Iw as not leaving the app, now it feels like a bookmark manager more or less. The nice thing was that I put a screen lock to the NC Android app, so all were contained within.

I am using LineageOS 7.1, app version 20181016

thanks

**Comment by AndyScherzinger** [comment]
Hi @gerroon, there is nothing to revert back since this is a new feature. The client now respects the server's setting per URL.
In the server for the defined URLs you can now explicitly set if the should be opened externally or internally. So depending on this setting the client behaves accordingly. 
So you should be able able to configure this in the server and all should then be just as is has been before from a client behavior point of view. 

What I am not sure of is this is a Nc14 feature but @tobiasKaminsky might be able to answer this.

So closing the issue for now. Please reopen if the suggested solution doesn't solve the behavior.

**Comment by gerroon** [comment]
Well the thing is that, some web sites cannot be shown in the Nextcloud's own interface as mentioned by the external apps documentation. The Android app did not care about it which was great. Now it seems like it is directing those urls to an external browser. 

What I am saying is that as of now it feels like some open in the app and some does not, which from user perspective, plain confusing.

**Comment by tobiasKaminsky** [comment]
I do not know with which intention this options was built in, but I assume that was more a question if the user should stay on NC site or leave it, than a question if it is technically possible to embed it in a frame.

@nickvergessen as I guess that you added this?

**Comment by nickvergessen** [comment]
Yeah, it was added for websites which don't allow iframing, so you can still have them in a link and we just redirect for them instead.

I have no really strong opinion on this. you can argue in all directions. The default browser you use might have the password already saved. the web view feels less disconnected ¯\_(ツ)_/¯
