### ISSUE TITLE
Text overflow in French in the auto-upload feature settings

### ISSUE THREAD

**Issue by vincib** [nextcloud/android#3165]
### Actual behaviour
- When editing the settings of an auto-upload folder with the FRENCH version of NextCloud for Android, part of a message is larger than the window. As a result

### Expected behaviour
- The text should word-wrap and follow on the next line
 
### Steps to reproduce
1. install NextCloud on a French android
2. configure it
3. go to menu > envoi automatique (automatique upload) > "..." menu on any folder
4. look at "Envoyer uniquement si le charg.."

### Environment data
Android version: 7
Device model: Samsung S6
Stock or customized system: Stock
Nextcloud app version: 3.3.0
Nextcloud server version: 14.0.1

Picture as a proof : 

https://aide.octopuce.fr/wp-content/uploads/2018/10/Screenshot_20181019-124056_Nextcloud-576x1024.jpg

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger do we want to make these labels support two rows?

@tobiasKaminsky actually I am not sure. The issue described is the expected behavior. Our layouts are mimicking the standard preferences layouts where the preference headline is always a ellipsized single line... I do vote two go for 2-line headlines since we cannot QA the headline strings for all the available translations for several reasons (like not speaking the language) and have the trade-off of multi line headlines but a better UX.

**Comment by AndyScherzinger** [comment]
PR is #3170
