### ISSUE TITLE
Add home screen folder/file shortcut widget

### ISSUE THREAD

**Issue by Dho100** [nextcloud/android#3175]
Requesting the ability to drop a shortcut on Android home screens that link to specific folders or files. Thanks!

**Comment by tobiasKaminsky** [comment]
We discussed whether to go for widgets or actions (long press on icon and have multiple options). Those actions can also be placed on work space.

Would this also be a way? Then we can avoid to support both systems.

(dev note: according to https://developer.android.com/guide/topics/ui/shortcuts/ these actions can be done dynamic, so that is should be possible to let user pick their folder)

**Comment by Dho100** [comment]
I'd personally prefer a dedicated shortcut vs. long hold on the app icon. I didn't even know you could long hold on an app, and akso I don't think it's intuitive.

**Comment by tobiasKaminsky** [comment]
This is also only available with 7.1.
The main reason is just that there are not enough resources to have both…

**Comment by Dho100** [comment]
I migrated from Dropbox where where shortcuts were available, which is what prompted me to post this feature request. Personally, I think the shortcut would be the most intuitive and most popular feature vs. the other options mentioned.

**Comment by tobiasKaminsky** [comment]
To clarify the wording.

This is called app shortcuts:
![image](https://user-images.githubusercontent.com/5836855/47430176-f1692200-d798-11e8-89e8-3b7a81de97bb.png)

This is a 1x1 widget from Dropbox, next to the app launcher
![screenshot_20181024-142914_trebuchet](https://user-images.githubusercontent.com/5836855/47430470-b9aeaa00-d799-11e8-9cb8-94b176f100bf.png)


At least on my test device, Dropbox only has the 1x1 widget.

**Comment by Dho100** [comment]
1x1 widget is what I think would be the most useful. Thank you

**Comment by Dho100** [comment]
Any ETA for this feature? Thanks!

**Comment by notpushkin** [comment]
At least for me, app shortcuts can be added as separate icons as well (just long tap the action and drag it somewhere :-) So if those can be implemented, they can be used in either way.

**Comment by 10bias** [comment]
Any news about this?

**Comment by tobiasKaminsky** [comment]
Not really, due to limited dev capacity, we prioritize and this is not top priority.
However, if there is a PR, I am more than happy to review it (or help integrating it)

**Comment by Dho100** [comment]
> Not really, due to limited dev capacity, we prioritize and this is not top priority.
> However, if there is a PR, I am more than happy to review it (or help integrating it)

My primary interest in this is for storing my password vault in a location I can access from multiple devices.  Everytime I want to access it I have to open next cloud, navigate to folder, open the password vault file, the password vault app opens. 4 clicks that could be 1. Thanks for your consideration! I think this could be an attractive feature for people to use this app to enable streamlined personal password storage management.

**Comment by AndyScherzinger** [comment]
> use this app to enable streamlined personal password storage management

That rather sounds like using something like keepass2android and let the vault app deals with it (the mentioned app can connect to Nextcloud itself and managed the vault(s) and keeps them in sync).

**Comment by Dho100** [comment]
> > use this app to enable streamlined personal password storage management
> 
> That rather sounds like using something like keepass2android and let the vault app deals with it (the mentioned app can connect to Nextcloud itself and managed the vault(s) and keeps them in sync).

I'll open a new feature request for Keepass2Android. It looks like it doesn't support Nextcloud's TOTP feature. I get error "Unsupported auth scheme"

**Comment by Dho100** [comment]
I was able to get Keepass2Android working with Nextcloud's TOTP authentication by creating an App Password on this page on my Nextcloud server: /index.php/settings/user/security

I found this solution based off of this thread: https://github.com/PhilippC/keepass2android/issues/1

This gets me the solution I was looking for, so I no longer have an interest in this feature request.

Thank you!

**Comment by AndyScherzinger** [comment]
Glad to hear you found a solution @Dho100 👍

**Comment by wiwie** [comment]
I was interested in this feature as well, so I implemented a version using dynamic+pinned shortcuts. However, only a pretty low number of dynamic shortcuts (10) are allowed per activity. I believe this is too restrictive for the average user. I could easily come up with more than 10 shortcuts I wanted to pin to my home.

So I'd vote to try implement this feature using widgets. Other opinions? Should I go ahead?

**Comment by newhinton** [comment]
I have taken a look at this issue, because it seems to me this is rather important/useful.

My take was to use the Details-Fragment to 'hide' this button.

@wiwie I have taken some of your core code to make my code work. Are you okay with that? Otherwise i will rewrite or otherwise get the code in a way that keeps your contribution in the git-history.


![grafik](https://user-images.githubusercontent.com/25279821/177724180-da6f8c6d-d90f-44e3-b7a7-efc3ac65ed81.png)


@jancborchardt I abused the share dialog for this, but i dont know how bad/good this is. Could you give a judgement if this is the way to go? My other option would be to put a new menu entry in the threedot menu above the tabs, but this would be way more hidden.

Maybe in the future we need a picker in addition to this, but in my opinion we have to add some way to create shortcuts to each folder. My reason for that is that most of the time a user is doing something, and then thinks: "Well, it would be good to quickly access it because i have to do it often!" while beeing in said folder. If there is no quick option to pin it, the user will not use the shortcut feature.

**Comment by wiwie** [comment]
Fine by me

**Comment by newhinton** [comment]
Great!

![grafik](https://user-images.githubusercontent.com/25279821/177730024-63f9dfd0-f99b-4212-872a-628c9e190356.png)
This is how it looks for files. After clicking the 'Pin to Home' it opens the android-default view for adding shortcuts.

**Comment by maranov** [comment]
@newhinton, @AlvaroBrey, nice addition, thanks. There's an old bounty at <https://app.bountysource.com/issues/65131277-add-home-screen-folder-file-shortcut-widget>, BTW.

**Comment by newhinton** [comment]
@wiwie @AlvaroBrey  If you dont object, i'd claim this bounty. However @wiwie, if you want to take credit, just mention it in the next days!

**Comment by AlvaroBrey** [comment]
> @wiwie @AlvaroBrey If you dont object, i'd claim this bounty. However @wiwie, if you want to take credit, just mention it in the next days!

No objection from my side!
