### ISSUE TITLE
not work auto sync xiaomi redmi note 3 pro

### ISSUE THREAD

**Issue by PEAKT0P** [nextcloud/android#3191]
not work auto sync xiaomi redmi note 3 pro miui 10 Global 8.10.18 Android 6.0.1 MMB29M

**Comment by tobiasKaminsky** [comment]
Do you have any battery saving optimization running that you can try to disable for this app?

**Comment by eduard-sukharev** [comment]
I have same issue with Xiaomi Redmi 4a, MIUI Global 10.1, Android 7.1.2
Android app version 3.4.1 and 20181222 dev version.
Server version: 15.0

On automatic uplaod screen I enabled Camera dirs, both video and pics, tried both WiFi only and 4G.
Nothing happens - files do not appear in the upload queue screen and cannot be triggered for upload manually.
Moreover, even when I send file from external app to NextCloud app for upload, it allows me to select a dir to upload file to, but no file upload starts.

I have granted all permissions and set the battery saving to No restrictions at all for this app. No luck.
Might that be due to my server misconfiguration? It's 256 RAM VPS.
Any hints would help

**Comment by eduard-sukharev** [comment]
Ok, new info: today i made a photo which was saved into one of the auto upload folders and the dev build app 20181222 attempted to upload it to the server. Looks like the sync app tries to upload only new images, not existing ones. Can you confirm and fix that?

**Comment by AndyScherzinger** [comment]
That's correct and uploading existing files is on our roadmap, see #285
