### ISSUE TITLE
Disable Theming Colors

### ISSUE THREAD

**Issue by supportreq** [nextcloud/android#3204]
### Is your feature request related to a problem? Please describe.
There should a setting in the setup.xml file which will allow disabling theme colours like the one in iOS

### Describe the solution you'd like
If the XML option is disabled it will take the app defined colours

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'd be fine with having a feature flag for theming while I can't say how much work this would be to implement.

**Comment by AndyScherzinger** [comment]
@supportreq that wouldn't fit the theming implementation, nor the standard theme. A feature toggle in the xml file would rather disable the theming thus everything would be default Nextcloud colored with the action bar being blue. Your requrement would need a specific implementation just to support this which I think is rather unlikely to be implemented.

You could of course use such a (not implemented/decided on) feature toggle and _also_ manually change the theme definition so it supports your use case while that should then be done on your very on fork.

Any opinion on this @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
@supportreq what would be the purpose of a flag in setup.xml? 
We/NC would always keep it enable, as theming should be enabled for all users.

As we would have to maintain and test everything we implement into the app, I only want to have something in it, that is needed/used.


Regarding inverting color scheme, I doubt that this will look good at all, if used in  combination with theming app, because this can lead to any strange color combination.

**Comment by AndyScherzinger** [comment]
from my point of view we might better postpone this since we just started to upgrade the UI implementation to the latest UI components...

**Comment by tobiasKaminsky** [comment]
I would not postpone it, but do not want to include it at all.
Please don't get me wrong. If there is a good use case for users, why theming should be allowed to be enabled/disabled, I am fine to include it.
But settings in setup.xml, which we do not need, will not go in.
