### ISSUE TITLE
Keypass Error info

### ISSUE THREAD

**Issue by tanvir1414** [nextcloud/android#3251]
Only via nexus cloud file syncing properly. I use dropbox previously,there it automatically syncing. But here sometimes get problem. Everytime I have to open nexus cloud and then open file and  syncing.

**Comment by EugenVau** [comment]
Same here: Nextcloud Android 3.3.0, Nextcloud Server v13 latest, KeePass2Android.

When opening a *.kdbx file from the Nextcloud App directly to KeePass2Android, changing something in the Database and synchronize, KeePass says: "changes already synchronized", but the changes actually never get to the server and other clients. Same behaviour if opening files with built-in file manager from "Android/media/com.nextcloud.client/nextcloud/[username]/Documents/xyz.kdbx" - local changes are never saved to the server without error messages.

**Comment by AndyScherzinger** [comment]
@EugenVau I also use KeePass2Android while I configured it to use the DAV protocoll and it then sync the file itself with the Nextcloud server :) 
Other than that, did you configure the fiel within the NExtcloud Android client to be "available offline"? Else it won't be synced to the server (in general).

**Comment by EugenVau** [comment]
Hi @AndyScherzinger, 

I think DAV would work, but it's less convinient than opening KDBX files directly from the Nextcloud App. I'd have to enter my Nextcloud credentials in KeePass2Android everytime I open a KDBX file, search the right file inside Nextcloud... Or is there a way to save the credentials in KeePass? Even if so, this would still mean another app token and another saved credentials on my smartphone, thus another possible attack vector against Nextcloud...

As for your second point, it seems just the other way round for me: if I mark a file as "available offline", local changes are never synced to the server - otherwise (just found out yesterday) they are! Really weird...

**Comment by tanvir1414** [comment]
I use available offline to make the synchronization.But as I said it did not work.
