### ISSUE TITLE
Is it possible to make the server link static?

### ISSUE THREAD

**Issue by dotrozn** [nextcloud/android#3264]
Hi there.
I'm wondering if it would be possible to remove the "Server URL" window and just make it static, so the user is redirected automatically to the login.
Is that possible? I looked around the code, but I'm just getting more confused by keep browsing it.

**Comment by AndyScherzinger** [comment]
@dotrozn This is something @tobiasKaminsky might be able to answer while he is not available for the next two weeks. Afaik you should be able to accomplish that via the right settings in the setup.xml but since I didn't work on that part I don't really know. So you can either play around with the setup.xml or wait for Tobias to be back to answer your question.

**Comment by dotrozn** [comment]
Okay, thanks @AndyScherzinger ! I'll try that, maybe it works. Otherwise I'll wait for @tobiasKaminsky 's answer! :)

**Comment by dotrozn** [comment]
Hi there @AndyScherzinger ! I tested it out and it works perfectly fine!
You can close this issue now.
Thanks again! :)

**Comment by AndyScherzinger** [comment]
Sweet, glad I could help and it's working for you.
