### ISSUE TITLE
Upload existing files

### ISSUE THREAD

**Issue by tkintenn** [nextcloud/android#3270]
### Is your feature request related to a problem? Please describe.
Setting up auto upload, it shows thumbnails from that folder. I would expect that it would sync everything in the folder... OR have the option to do so. It just seems like something that should be there or that the app should do. Other sync apps do this. 

### Describe the solution you'd like
To be able to sync everything in a folder on my phone. Not just new files. It does this on the linux desktop sync. 

### Describe alternatives you've considered
Manually uploading the files via sftp and doing an occ scan... 

### Additional context
I LOVE LOVE LOVE LOVE LOVE next cloud. I've got my wife and i using it. Keep up the great work!

**Comment by Viveur** [comment]
Just looked into this myself and appears to be multiple similar references to adding this functionality, including (at least): #285, #2691 & #2812.

There is also a pull request under discussion at #2873 

Additional Note: It does seem as if the current UX situation is dangerously broken as Autoupload shows thumbnails of all images in the camera folder which leads users to assume that images that don't already exist on the server are due to be uploaded. 
Spent many hours confused by this under the assumption 'I was doing it wrong' and it was an issue at my end, either with the phone or Nextcloud installation.

**Comment by zukunft** [comment]
I agree with tkintenn. There should at least be a "force upload of existing files" button. Or switching off and on the autoupload icon should force to upload "old" files.

**Comment by AndyScherzinger** [comment]
As discribed by @viveur. Die is actually a duplicate since this feature is describe din the auto upload roadmap in #285 and there is a work in progress / discussion in #2873.
So I am closing this issue, please follow up on #2873. If you discuss this feature please take into account the complexity of this request since it is not as easy as to "just upload the existing files" since you have to consider the various scenarios like the folder isn't empty on the server _and_ has files with the same names (who wins? rename the to be uploaded files). At this very moment we are unable to implement a true sync since we can't compare file hashes (not provided by the server). So this feaure is tricker than one might expect.

**Comment by AndyScherzinger** [comment]
to be released with 3.11. via #4788
