### ISSUE TITLE
Add buttons in the notification for twofactor_nextcloud_notification

### ISSUE THREAD

**Issue by GLLM** [nextcloud/android#3272]
Hello !
I use NickV's twofactor_nextcloud_notification app ever since it was released :)
It is very helpful BUT ...

When I attempt to login, I expectedly get a notification telling me about it.
I then need top open this notification : it opens the Android app and then I have a choice : _Accept_ or _Reject_ the connection, thanks to 2 buttons.

A better solution :
I'd really like to _Approve_ or _Reject_ connection from within the notification, thanks to 2 buttons.
(Messaging app often have 2 buttons in notification : _Reply_ and _Mark as read_)

I initially booked an issue on the app repo (https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/48) but I was told this should be managed by the Android app.

If this F.R. should only be about buttons, please let me know, I'll amend the Issue :)

What do you think ?
Thanks
Guillaume

**Comment by AndyScherzinger** [comment]
Hi @GLLM, this is something we already started to discuss, see  #1276 so I'll close this as a duplicate. Nevertheless it is from my point of view something of low/mid priority due to other features people are currently working on but is definitely something that makes sense but might tak a while until somebody finds the time to implement it.

**Comment by GLLM** [comment]
Thanks for your reply Andy !
Will follow #1276 :)
