### ISSUE TITLE
Preview markdown files

### ISSUE THREAD

**Issue by jangmarker** [nextcloud/android#3302]
### Is your feature request related to a problem? Please describe.
Markdown files are an easy way of structuring some quick notes.
Although their plain textural representation is already well structured, adapted rendering for phones would allow these files to be even more useful.
That way one could take down notes on the computer, sync them with Nextcloud to the phone and have an easy to read representation on the phone.

### Describe the solution you'd like
The android app is currently displaying text files within the app. It would be nice if it could render Markdown files in preview mode, i.e. similar to HTML.

### Describe alternatives you've considered
There are apps on the Android app store that allow editing and preview of Markdown files, however using them for preview is rather cumbersome compared to previewing Markdown files within the Nextcloud Android app.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I am fine with the assessement that this is a feature while I'd like to disuss it and it's implications so I'd also like to get @stefan-niedermann's input on adding "just the rendering".

* adding markdown rendering will likely lead to the next feature request: editing capability and then we basically copy the notes client 
* I wouldn't want to re-invent the wheel or create a competitor here for no good reason since the notes client is part of the eco system and a good prodcut where I don't see a reason to attack that

So to be discussed (from my point of view) and rendering would be fine with me (scope of this feature request) while editing capabilities is somethign I'd rather not add to the files client. (same arguments would also apply for deck, bookmarks, you name it)

**Comment by thomas-mc-work** [comment]
> There's no smoke without fire

I think write support would still be different. Notes are notes and can live in the notes app, which provides more specialized features for that task. But if there is much demand for simple read/write support in the client – why not?

But that demand hasn't been claimed yet. I'd also love to see the markdown rendering feature in the android app.

Also, there is no right to deliver all feature requests. So personally I wouldn't care too much about this virtual threat.

Another point for possible subsequent feature requests for write support: There isn't even write support for simple plain text files. So then write support for markdown files is much further away.

**Comment by AndyScherzinger** [comment]
PR adding initial support is #4692
