### ISSUE TITLE
3.4.0RC1 system font not used

### ISSUE THREAD

**Issue by mlaverdiere** [nextcloud/android#3348]
I'm not sure if it's supposed to be a feature or if it's a bug, but on current 3.4.0RC1, the font used is not the same as the Android system font. I'm on Pixel 2, with Android 9,, with the regular system font and no special configuration. I think that for integration purpose, the ND app should stick with system font, like other apps.

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers @jancborchardt there you go ;-)

@mlaverdiere this is not a bug, but a feature :rofl: 
NC15 switched also to use Nunito font, and @jancborchardt came up with the idea to have this also on all clients.

**Comment by jancborchardt** [comment]
There's other apps who also use a different typeface from the system one, like Duolingo, Spotify, and even the Google Apps themselves now (with the new rounded geometric font).

But as we talked about, this is not something we have strong feelings about. If more people complain we can always change it. Let's see how it goes.

**Comment by tobiasKaminsky** [comment]
Ok, I'll keep this open, so that other can easily join.
(also it is not a bug, but an enhancement to change it again :rofl:)

**Comment by AndyScherzinger** [comment]
> also it is not a bug, but an enhancement to change it again

First it needs to be decided if this is valid

> even the Google Apps themselves now

Not quite... these are the newly introduced materrial fonts :-)

> But as we talked about, this is not something we have strong feelings about. If more people complain we can always change it. Let's see how it goes.

Agreed while no matter the decision and the forn change already available I would have suggested to move on to the new material fonts anyways ("system font" is dead with the latest material design changes by Google), while Nunito isn't too far away from them.

**Comment by mlaverdiere** [comment]
Maybe I miss something, but as I look at my Google apps on my Pixel 2 (with the latest Android 9 update), I don't see that they're using different fonts...

Anyway, I can't say that I have strong feelings myself about that, but I tend to prefer a good level of integration with the base OS, which includes the system font. My first thoughts when I opened the 3.4.0RC1 was that, due to the different font used, it looked weird/awkward and that it needed more polish...

**Comment by tobiasKaminsky** [comment]
> it looked weird/awkward and that it needed more polish...

Oh, this is a pitty. Personally I like the new font, but I also have no strong feelings if we revert it…

**Comment by mlaverdiere** [comment]
I should have added: thanks for the good work on this app., whatever the font!

**Comment by mario** [comment]
@AndyScherzinger mind linking to new "rules" regarding fonts?

**Comment by AndyScherzinger** [comment]
@mario sure thing

In general you can basically now do "whatever you want", se the examples here: 
* https://material.io/design/typography/the-type-system.html#applying-the-type-scale

typical fonts defined within Material as in different styles are:
* https://material.io/design/material-studies (overview)

examples:
* https://material.io/design/material-studies/basil.html
* https://material.io/design/material-studies/shrine.html
* https://material.io/design/material-studies/rally.html
* https://material.io/design/material-studies/crane.html
* https://material.io/design/material-studies/fortnightly.html
* https://material.io/design/material-studies/owl.html

we are probably (some point) close to Crane (https://material.io/design/material-studies/crane.html)

**Comment by mikebabb** [comment]
Would it be possible to add an option to the app's settings for those of us who'd prefer to continue using the system font? I'm finding the new one a little harder to read. If there aren't many requests to revert it, an option for the user to set their preferred one might be a good solution?

**Comment by jancborchardt** [comment]
> Would it be possible to add an option to the app's settings for those of us who'd prefer to continue using the system font?

Hehe, nice try. :wink: I know we all loved Geocities, but we won’t add a setting for something as basic as the font.

> I'm finding the new one a little harder to read.

This is very valuable feedback, thank you! Also in other regards I’m seeing some issues with the font, like it not really looking too serious on the new business cards we want to do. (We’ll also (separately) consider the typeface of the server, and whether to switch back to Open Sans or related, but this time the more readable Regular + Bold.)

Considering there’s more feedback now – @tobiasKaminsky @AndyScherzinger if you feel like we should rather use the new Material fonts as default on Android, I’d support that. @mario same for the Talk Android app.

**Comment by Hund** [comment]
So this is not a bug, it's a feature? I downgraded and I'm not upgrading until it get fixed.

The new typeface is blurry, thin, weirdly shaped like someone fused two typefaces together and it's also hard to read.

I would appreciate it if you could fix this. Preferable via a setting as I'm sure there's some weirdo out there who likes the new typeface. :)

**Comment by github-tomster** [comment]
from the perspective: this is all a joke!
to see one is dictated to use a font someone wants him to use -> HAPPiNESS AND FREEDOM => GONE!
so one is looking for answers...
search-fu - et voila: it is a feature, silly me!

lets see what could have happened:
imagine there are only two fonts available in the world.
the design team is unsure whichever font to choose and creates a poll.
so the result is very clear: 51% voted font1. hurray!
from now on, 49% of the users are forced to see an unwanted font
because the design-team-skills were only able to destroy system-font,
create a poll, code font1 instead of the system-font into the application
and not sufficiently enough to code a font-switch/option!?
it is impossible to let the user choose a font! isnt it?
hardly believable that the systemfont works in 3.3.2; really, wow, really...

is there another possibility why this happend? arent there
enough real issues to solve? i even digged that material-bible-religion-site,
and look what i have found:
https://material.io/design/typography/understanding-typography.html#system-fonts
System fonts
System fonts come pre-installed on your computer or device.
They typically have wide language support and no licensing costs for developers.
Using the system default font in your app font unites the consistency 
of the platform with your app’s look and feel. 
However, because they appear in many places on devices, they may not stand out.

so why are thou coding this bug into the application?
do i read it wrong? what could  be the logic for
dictating a font to a user and not providing a switch
to turn it off or even an option to choose an other font than the system-font?

considering the amount of fonts available,
who dares to choose nunito font?


what a pity, silly me missed that poll. my vote would have been the one
that prevented this bug-feature. so as i am a non-coding-being
i wrote this feedback and downgraded to 3.3.2.
also ill watch this topic and hope that there come more to complain.

and yes i know, silly me is only one of 100.000 users.
99.999 wont even notice this bug!

**Comment by jancborchardt** [comment]
@github-tomster tone down the sarcasm please. We want to communicate respectfully, and your comment does not help to solve anything. Take some time to read the Nextcloud Code of Conduct: https://nextcloud.com/code-of-conduct/

--------------------------

As said above already:

> @tobiasKaminsky @AndyScherzinger if you feel like we should rather use the new Material fonts as default on Android, I’d support that. @mario same for the Talk Android app.

No further inflammatory comments needed.

**Comment by AndyScherzinger** [comment]
I'd personally go with the new material design font but wouldn't do this before we are done with the revamp of the theme in general (open PR).

Still this impliew material design over OEM stuff, like OEM fonts... I'd strongly advise to stay with material design fonts, simply since the amount of devices we have at hand is limited and thus we can't test OEM font cases.

**Comment by github-tomster** [comment]
-.- <- this is my speechless face!
i dont know the bubble those responsible exist in,
destroying the consistency of the font-style on my device,
THAT i call disrespectful and it makes me very, very uncomfortable and sad.
sarcasm is the only way to bare this.
nice code-of-conduct b.t.w.

so lets look at this technically:
- the system-font is working
- someone DiCTATEs a font to the user though
- user asked for an setting to stop that constraint
and here we go!
the very pragmatic answer is: 
'... we won’t add a setting for something as basic as the font' 
this sounds very collaborative and skilled.
but: this inflammatory statement,
contains the most important fact at all: BASiC!
so first think, then code...

or can i be enlightened, is there hope:
what ist the need to force a font over the user?

and to be more impolite at all:
to read that nc is compared to be like spotify. really? facepalm!

**Comment by jancborchardt** [comment]
Thanks @AndyScherzinger, good plan! So after https://github.com/nextcloud/android/pull/3237/ we can switch to Material font.

As the Material font is round/geometric it's fine to use it in combination with the round pill-style buttons. :)

**Comment by skjnldsv** [comment]
I also really dislike having the new font enforced.
I'm using a specific font for my whole system and I'm actually quite surprise the new material guidelines now allow devs to choser their own (thanks @AndyScherzinger!)

So, On one hand opening the nextcloud app is really weird for me, on the other hand, I do not use the nextcloud app that much to really have strong feelings about this :woman_shrugging: 🤔

**Comment by AndyScherzinger** [comment]
Well, Android always allowed for custom fonts to be used in apps, with proper font support since Android 4.1.
The standard material font in the past was Roboto which most OEMs picked too in case their OS customization stayed at a minimum. With the latest changes to material design there are now a number of material designs like Crane and thus also a series of newly intruduced fonts. I specifically mentioned Crane since the font used by Crane is. Possibly the closest one of the new material fonts when being compared to Nunito. So also looking at the latest updates of some UI wise up to date Google they also switched fonts to the newer ones and also enforce them. So the times of "the system font" seem to come to an end on a larger, OS level scale. In other words looking at material 2.0 it encourages a certain degree of font diversity throughout the Android ecosystem of apps.

**Comment by github-tomster** [comment]
the question can not 'be wich font?'!
a pity to see this.
try to answer the question: 
how do i code an app, the user can choose the font he wants to see in?

@'contributors'
u have no strong feelings about to revert this mess.
we have actually more than three free human 'beings asking
for reverting/add an option/code proper settings.
how many complains are necessary?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger with these new material fonts: can they then got overridden by users? Or is this also "forced" like it is now?

**Comment by AndyScherzinger** [comment]
@jancborchardt which one is the "normal" font? Before this change we didn't set any font, thus the app used the system's font which in many cases was likely to be Roboto and in some cases a special OEM font in case OEM shipped a different font. With the latest guide updates Roboto is kind of depricated. So if you look at the Gmail app it'll still use Roboto (no UI refresh yet) if you look at the News app it enforces the new material font.

So I guess this mean: just revert and don't set any font (like it has been before the change)

cc @tobiasKaminsky

Upside: this will make having the right font weights again easier :)

**Comment by github-tomster** [comment]
@tobias
exactly! thats what happened, the font is not customizable by the user in **ANY WAY EVER!**
at least one is getting the point...

**Comment by jancborchardt** [comment]
> So I guess this mean: just revert and don't set any font (like it has been before the change)

Yup, this is definitely a good first step and quick fix.

Then we check if it uses the new Material font for phones / Android versions which support it. If necessary we need to make additional adjustments to enforce the new Material font like e.g. the News app you mention.

**Comment by tobiasKaminsky** [comment]
> additional adjustments to enforce the new Material font

As far as I read, most critism was that we enforced user to use a specific font. So while we can promote a different app than the default one, it still should be allowed to override it.
(however, I have no real experience how to do this)

**Comment by skjnldsv** [comment]
I just wanted to say that you're doing an amazing job here! Custom font or not! :hugs:

**Comment by AndyScherzinger** [comment]
Thanks @skjnldsv this is highly appreciated, also appreciate your feedback and input (as always) ❤️

**Comment by jancborchardt** [comment]
Also sorry from me for suggesting we go for Nunito in the mobile apps. 😉

**Comment by github-tomster** [comment]
i am looking forward to have a nice user-experience again,
and go back to hell again now...

**Comment by mario** [comment]
@jancborchardt no sorry needed. While I personally don't have a font preference from a product point of view I don't see how we take away any freedom if we set a font. Nextcloud Files app is but a one build of the open source code presented here, and we make decisions based on educated guesses and input from both customers and users. You are always free to make your own build and do something else with the font.

That being said, the few of you discussed it and decided to revert which is also fine by me so I'll do the same for Talk.

But I just wanted to say that, for once, I completely support you in selecting a default font - even if it might not be the best one, whatever that means.

**Comment by github-tomster** [comment]
@mario
imagine the following:
today one woke up and decided to wear a dark blue t-shirt.
tomorrow one wakes up and is maybe in the mood to dress  with a green t-shirt.
the day after tomorrow one wakes up and is being told to wear a brown t-shirt.
one doesnt even likes brown t-shirts nor one has ever bought some.
he has to wear it though! every day from now on.

and i love to read that one is FREE to make his own build.
take a closer look! this issue is an **outstanding** example...

@noone
well i guess last train to hell was delayed... ;-)
