### ISSUE TITLE
Don't automatically download songs when selected

### ISSUE THREAD

**Issue by susobaco** [nextcloud/android#3351]
In version 3.3.2 the songs are not automatically downloaded when they are selected. A message appears that the media player cannot play the file. If you are given the option to download the file, it downloads smoothly and can already be played. I guess it's a customer problem. Thank you.

**Comment by tobiasKaminsky** [comment]
The new default behaviour is to stream the video/audio files instead of downloading it and then playing it.
The question is why it fails to play a mp3(?).

**Comment by susobaco** [comment]
Ah, I didn't know, if the file is mp3, but it also happens with ogg audio.

**Comment by susobaco** [comment]
Attach log.
[logcatOutput.txt](https://github.com/nextcloud/android/files/2779440/logcatOutput.txt)

**Comment by susobaco** [comment]
Hello, version 3.5.0 still has the same problem. Any news?

**Comment by susobaco** [comment]
I don't know what else I can contribute, the problem remains unresolved.

**Comment by DPTJKKVH** [comment]
@tobiasKaminsky Yes this is about mp3 files (and as seen here #3061 all other media) failing to stream. Both issues are only lightly touched on and then ignored. Providing logs is difficult since it contains tons of sensitive information on all other sync activities and the corresponding file names.

If you could give us a hint what information exactly you are looking for I can create a logcat and provide an excerpt with only the relevant log entries.

**Comment by susobaco** [comment]
Now, with the version 3.7.0.RC3, directly closes, tastes a crass. It doesn't even let reproduce the downloaded ones, this is already a serious problem.

**Comment by susobaco** [comment]
#4208
