### ISSUE TITLE
server side thumbnail cache is not used

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#3444]
The server side, by occ command created thumbnail cache, is not used in the android client.
Or should be ok that the android client creates the thumbnail cache regularly.
Like with new uploads or at every night at same time or so.

**Comment by tobiasKaminsky** [comment]
With which command/app do you create the thumbnails on server? Preview generator?
Otherwise it could happen that thumbnails for the "wrong" dimension are created and thus they cannot be used.



> Or should be ok that the android client creates the thumbnail cache regularly.

We are doing this currently on demand as the cache is limited on client and thus we cannot cache all thumbnails an user has on its cloud (imagine if you have shared folders, you can easily have 100k images, which then would be 100k *50kb = 5Gb of thumbnails on device)

**Comment by tobiasKaminsky** [comment]
@rullzer you are the expert here…for an image all needed sizes are generated, or?

**Comment by rullzer** [comment]
by default yes.
But how do you know this cache is not used?

**Comment by Siggi0904** [comment]
Hi, sorry for late answer.

I felt, that thumbnails was loaded very slowly.
If it is configurable for mobile devices smaller thumbnails could be used.
How it is configurable to get smaller thumbnails for mobile phones?

Thanks.

**Comment by iGamerHD** [comment]
So it doesn't make a difference which preview size settings are choosen in the preview generator?

**Comment by rullzer** [comment]
If you use the defaults it should just work

**Comment by iGamerHD** [comment]
Is there a way to reset the value to the defaults?
I changed it once and don't know them anymore...

**Comment by nachoparker** [comment]
Hi, could we know what is the exact preview size that the Android client tries to fetch? That way we can configure our servers accordingly. 

Thanks!

**Comment by tobiasKaminsky** [comment]
> Hi, could we know what is the exact preview size that the Android client tries to fetch? That way we can configure our servers accordingly.

This depends on your screen resolution, but as far as I know server has previews with power of 2 and rounds to next available preview size.
