### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by c0fe** [nextcloud/android#345]
I would like to propose to change the icons as they are a bit confusing as they are now when you click on the "+" (plus) icon to upload items.

For example the files icon (where you can search the whole Android directory to use this icon:

http://i.imgur.com/ZUUKm0L.png

For images to use the following icon:

http://i.imgur.com/MniGKZB.png

I can provide vector files for icons unless the developers want to use one of their own

**Comment by AndyScherzinger** [comment]
Hi @c0fe doe you mean the three icons in the FAB:
![device-2016-10-17-165146](https://cloud.githubusercontent.com/assets/1315170/19442578/0c567f3a-948a-11e6-983d-8c142cfb6e2f.png)

cc @nextcloud/designers 

I am not sure I understand the issue, so let's see

* Do you propose the "file/document" icon for the upload action?
* Where should the image icon being used? That isn't an action

**Comment by c0fe** [comment]
**Do you propose the "file/document" icon for the upload action?**

Yes

**Where should the image icon being used? That isn't an action**

I propose to use image icon for "Content from other apps" since all I have seen are images that have either been attached in other apps or is in my phone's photos.

**Comment by AndyScherzinger** [comment]
> I propose to use image icon for "Content from other apps" since all I have seen are images that have either been attached in other apps or is in my phone's photos.

tricky :wink: that is probably due to your personal/specific phone, because the drawer menu should also give you the possibility to "only see audio" and "only see video" etc. etc.

**Comment by c0fe** [comment]
Perhaps creating an icon that would be "media" and incorporates image, audio and video, what are your thoughts?

**Comment by AndyScherzinger** [comment]
Hmmm, even that wouldn't be true, since it is basically a so called "document provider" interface, e.g. when you click on downloads in the drawer menu you will then see any kind of file that you downloaded. 

I am not an UI / UX expert that is why I cc'ed the designer :smiley_cat:

**Comment by c0fe** [comment]
Yes but what would that button be used for primarily? Even though there are more document types it could be said that the majority would be images, audio and video.

**Comment by AndyScherzinger** [comment]
Okay, I get that.

As for the document icon what is the argument for dropping the upload icon which I would argue is commonly known thus people would expect an upload action and would argue that a document icon is something where I would expect a new file to be created or a file to be opened.

**Comment by c0fe** [comment]
My reasoning for dropping it is that Dropbox app uses the same icon. That icon that they use in reality is "Content from other apps". So basically they use the same icon to upload files from different apps. Personally for me this has been very confusing and the few sales men I have also find it confusing.

**Comment by eppfel** [comment]
I can understand @c0fe reasoning, that upload actually kind of creates a new file on your nextcloud. But being consistent with Dropbox is not as strong as an argument, especially because @AndyScherzinger correctly stated that the upload icon is well known in the Android ecosystem.

**Comment by AndyScherzinger** [comment]
@c0fe @eppfel this is a screenshot of the actual dropbox client and the also use the "standard" upload icon and use the photo icon for the photo/video upload which then only gives you the option to upload photos:

![device-2016-10-18-095251](https://cloud.githubusercontent.com/assets/1315170/19468842/ddcf873a-9518-11e6-846b-b4d9f61a1d11.png)

As for the photos/video issue, we are currently implementing a new instant upload feature for Android5+ which might help with this issue since the 1st iteration will be media focused. One thing that always kind of bugged me is the "Content from other apps" icon, since there isn't a truly fitting one, at least not in the material icon set: https://materialdesignicons.com/ - So feel free to find a better fitting one, I am more than happy to replace it :+1:

**Comment by c0fe** [comment]
I would make the following suggestion:

**"Upload" be this icon:** https://materialdesignicons.com/icon/android

**"Content from other Apps" one of these icons:** https://materialdesignicons.com/icon/image-area **or** https://materialdesignicons.com/icon/file-video

**Comment by AndyScherzinger** [comment]
Well, personally I would still vote to keep the actual icons.

as for "from other apps" https://materialdesignicons.com/icon/image-area would then have to be at least https://materialdesignicons.com/icon/image and again to me it is not upload image/video. If a use download/audio/etc. as the stuff I would regularly upload, this will be my recent so the fab button always opens that and not photos/videos. 

As for upload I strongly suggest to stay with the upload icon and especially the Android icon is something I (again personally) strongly disagree since it stands for Android/OS/System/etc. but imho not for upload.

**Comment by c0fe** [comment]
My reasoning for change it is that that button gives you the ability to browse the Android system or at least to the extent that it is possible.

**Comment by AndyScherzinger** [comment]
That's true @c0fe but then I would rather choose a device icon, e.g. https://materialdesignicons.com/icon/cellphone-android may then combine it with the upload icon the way we did for "make available offline": https://github.com/nextcloud/android/blob/master/res/drawable-xhdpi/ic_action_available_offline.png

**Comment by eppfel** [comment]
> My reasoning for change it is that that button gives you the ability to browse the Android system or at least to the extent that it is possible.

Sry, but I really don't think this is how people would perceive this.

@AndyScherzinger: Just a quick question? Do we even need both separate buttons? On my device, i can browse the filesystem as well, after I tap "content from other apps"?

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger: Just a quick question? Do we even need both separate buttons? On my device, i can browse the filesystem as well, after I tap "content from other apps"?

Hard to tell, there is a difference since "upload" gives you a in-app file browser for the phone, where you can also choose how the file(s) you will have chosen should be handled during upload (move, delete, just upload) while the "other apps" gives you a document provider implementation (Android OS feature) where you can choose files from your device and from any app/remote that support the document provider, so I can upload files chosen via this mechanism from my Google Drive or Dropbox directly... So there is a huge (and probably not well known, since document providers are still a bit rarely used, but heavily used by some users). So it is a big difference and ultimately a matter of what we want to support.

Dropbox for example does it the other way around by offering photo/video (only) and the document provider (what we name "upload from other app") but they don't offer the upload behaviors we do (which is something many users have requested in the past).

So while writing all this I guess my point of view is: yes, we need both imho

**Comment by AndyScherzinger** [comment]
Just for support the document provider argument, this is how "my" upload from other apps looks like:
![device-2016-10-18-174257](https://cloud.githubusercontent.com/assets/1315170/19485163/83600828-955a-11e6-854e-d8b9fa3b80a5.png)

**Comment by c0fe** [comment]
I just gave my opinion, sorry to have wasted other people's time.

**Comment by eppfel** [comment]
@c0fe 😁 Not at all. You gave some good insight and help me question the way we do it now. I totally agree that there is room for improvement.

**Comment by AndyScherzinger** [comment]
@c0fe no waste at all, I highly value such discussions and also think there is room for improvement. Thinking into another direction picking up @eppfel's input we could discuss if uploading from other apps should be put into the three dot menu in the top right menu in the toolbar...
