### ISSUE TITLE
Android App crashes instantly

### ISSUE THREAD

**Issue by RobinWolfrath** [nextcloud/android#3469]
### Actual behaviour
The Nextcloud App (3.4.2 RC1) crashes instantly after trying to open it. There is no error message after this happens. I can see the app opening, but it closes instantly.

### Expected behaviour
After touching the app icon the app should stay open.
 
### Steps to reproduce
1. Install Nextcloud 
2. Try opening it

### Environment data
Android version: 8.1.0

Device model: Huawei P20 Pro - CLT-L29

Stock or customized system:
Stock (EMUI 8.1.0)

Nextcloud app version:
3.4.2 RC1 also happening with older Version
https://github.com/nextcloud/android/files/2776511/logcatOutput.txt

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by tobiasKaminsky** [comment]
Stange. 
There is only one time when we add this column, and this was when upgrading to 3.4.

Although it is not good, but can you try to manually uninstall the app and install it again?
This should fix it, however you will have to setup everything again…

**Comment by RobinWolfrath** [comment]
I wasn't able to get the app running since I have the Huawei P20 pro (November 2018). Reinstalling the app was the first thing I did, but unfortunately without effect.

**Comment by tobiasKaminsky** [comment]
Have you used some backup app to transfer settings?
If you do a fresh installation, after manually removal, this "should" not happen…

**Comment by RobinWolfrath** [comment]
The app had been installed automatically when I registered my Google account on first startup. I haven't used any other backup tools and deleted the appdata while trying to get it working.

**Comment by tobiasKaminsky** [comment]
Maybe the automatic installation done by google is the problem.
Can you manually uninstall the app and see if the error then happens again?

**Comment by odoooooo** [comment]
+1

Same issue here. I have this problem since a few days. With 3.4.1 and 3.4.2.
I usually install/update via F-Droid, but also tried directly from Github with no sucsses.

**Comment by odoooooo** [comment]
However, if the nextcloud server is in maintenance mode, it is possible to start the app. Yes, obviously then there is no synchronisation, but you can change settings in the app without crashing.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by RobinWolfrath** [comment]
@tobiasKaminsky I just reinstalled the current version 3.5.0 RC 1 and everything works fine now. Thanks for your help.

**Comment by tobiasKaminsky** [comment]
@RobinWolfrath good to hear.
@odoooooo can you also try this?

**Comment by tobiasKaminsky** [comment]
Ok, please feel free to re-open.

**Comment by chymian** [comment]
both, 3.5.0 and dev (20190301) version crash instantly on login, after asking for right to access NC.
Device: moto G4+
LOS 7.1.2
Account A (mowie)

* deleted/new installed apps several times
* rebooted MOB sev. times (after delete, after install)
* auth tried with weblogin and token
* gets an entry in NC -> Settings -> Security  on every try

on another device, MotoZ play, LOS 7.1.2, same server, diff account this runs w/o problems (Account B)

Logging into the working account B (of the MotoZ), with the G4+ worked! So it seems to be a Server(/Client) issue

[NC-server14.log](https://github.com/nextcloud/android/files/2926319/NC-server14.log)

[logcatOutput.txt](https://github.com/nextcloud/android/files/2926285/logcatOutput.txt)

**Comment by tobiasKaminsky** [comment]
So Account A (mowie) on G4+ is not working.
To rule out that Account A is a problem, can you test Account A on MotoZ play?

**Comment by chymian** [comment]
1. true
2. could log in from MotoZ to mowie (A)
3. the wired thing I forgot to mention was, that G4+ was working with mowie (A) this morning, and stopped working, which brought me into that failure/install loop.
4. in between, I deleted all G4+ entries from mowie@NC -> Settings -> security (Devices & Sessions, D&S) – but since I afterward tried to auth with a new token, I think it should not make a diff., since the auth seems do not be the pbl., since every try is lodged in D&S.

from the see-able behavior, it's like: instead of showing a new screen with the Dir-List after login, it jumpes back to the login screen.

**Comment by odoooooo** [comment]
The issue for me still exists, too.
Only one account is affected so far. When I try to log in with another account on the same device, it works.

However, auto-upload works on the 'not working account'. And when a notification pops up because of an auto-upload and I tap on it, I get to the Uploading section of the app and the app does not crash. I can still move around in the app, modify settings an so on, but when I tap on 'All files' or 'Fotos' the app crashes again.
