### ISSUE TITLE
Dynamically increase upload chunk size for videos/fast wifi

### ISSUE THREAD

**Issue by allcoolusernamesaregone** [nextcloud/android#348]
### Actual behaviour

Direct upload of videos is incredible slow compared to uploading of photos
### Expected behaviour

I would expect that the upload will run with about 1-3mb/s which my phone usually transmits in the private wifi network e.g. ftp or samba. Instead upload speed is about 200kb/s which results in long upload times for videos with e.g. 300-400mb.
While a normal picture with size 1-2MB uploads within about or a less than a second, the videos don't have this speed.
### Steps to reproduce
1. activate direct upload for picture and video
2. take picture or video
3. watch them uploading.
### Environment data

Android version: 6.0 custom rom. 

Device model: 
Nexus 5

Stock or customized system:
Custom

Nextcloud app version:
1.3.1 - the current one

Nextcloud server version:
10.0.1 - the current one
#### Web server error log

n /a
#### Nextcloud log (data/nextcloud.log)

n/a

Insert your Nextcloud log here

```

I'd like to support investigation with answering questions, taking tests, etc. as requested and needed.. :)
```

**Comment by iskradelta** [comment]
Ill try reproduce this soon,

The first hunch what could be causing this, is maybe the chunked upload code - it opens and closes tcp/http connections for every 1mb uploaded - making any TCP congestion algorithms unused, from experience the initial tcp stream is slower and it adjusts as transfer progresses based on many parameters. 

So a quick workaround could be to increase the chunk size, but that may cause other failures if your server is not configured to support that - both the web-server, any proxies and php have a maximum allowed upload-size and timeouts for http-streams settings. 

Another quick better workaround would be to try to reuse the initial http-connection, set it to keep-alive, and send the chunks over that one.

**Comment by allcoolusernamesaregone** [comment]
>.... it opens and closes tcp/http connections for every 1mb uploaded....

Sounds reasonable as I observed the upload/download speed in the
notification bar - goes like 0bs - 1,5kb/s - 1,2mb/s - 300kb/s - 0b/s (just
an examble, values are shown for about 100ms until next value) again and
again. So up to some expected value in the 1-x mb/s area and back to 0...

2016-10-19 14:19 GMT+02:00 Iskra Delta <notifications@github.com>:

**Comment by tobiasKaminsky** [comment]
Desktop client sync is using 10mb chunks, but mobile uses 1mb as the connection is (maybe) more instable and retransferring a big chunk is not desired to data plans on mobile.
But yes, this might be the problem, although I would expect that open/handshake/close of a tcp connection takes very little time in comparison to upload of 1mb.

**Comment by iskradelta** [comment]
Ah I see actually the problem is my server setup, I have lighttpd frontend, with mod_proxy to another lighttpd, which then asks php-fpm over a unix socket to do work... front lighttpd recieves PUT /thing HTTP/1.1... but tells the backend HTTP/1.0... and 1.0 is not persistent by default, so the backend lighttpd ads a "Connection: close" to the response, then the httplib on android client closes the connection, instead of reusing it.

But even when I removed this setup, it went only slightly faster, so... ¯\(°_o)/¯

Maybe increase chunk size to 10mb when its on WiFi?

**Comment by allcoolusernamesaregone** [comment]
My setup is nginx running on a banana pro in my lan. It delivers a decent
performance for a single user setup, but is maybe not the fastest setups
for a lot of repeating http requests and chunks. So I'd like to test an
android client with 10mb chunks :)

2016-10-20 0:04 GMT+02:00 Iskra Delta <notifications@github.com>:

**Comment by iskradelta** [comment]
Have a try here, https://github.com/iskradelta/android/blob/debug_apk/build/outputs/apk/nextcloud_beta-debug.apk

That one has ~9Mb as chunk size and will not do a local copy before uploads when it is a manual upload. It didnt fix the issue for me though, at least on 4G, but am not home yet to test with good wifi.

**Comment by allcoolusernamesaregone** [comment]
Test failed :(

Upload of ~220mb not possible. Retried different times, fails sooner or
later..

10-27 19:46:17.444   860   951 I WifiHAL : Got channel list with 13 channels
10-27 19:46:17.445   860   951 I WifiHAL : Got channel list with 4 channels
10-27 19:46:17.447   860   951 I WifiHAL : Got channel list with 15 channels
10-27 19:46:17.491  1462  2809 E ctxmgr  : [AppIntervalImpl]closeInterval:
ongoing
10-27 19:46:17.504  1462  4022 I GCoreUlr: Successfully inserted 1 locations
10-27 19:46:19.555  5750  5750 D ExpandableUploadListAdapter: refreshView
10-27 19:46:19.557  5750  5750 D ExpandableUploadListAdapter:
loadUploadItemsFromDb
10-27 19:46:19.575  5750  5750 D FileUploader: Starting command with id 2
10-27 19:46:19.580  5750  5750 V UploadsStorageManager: Updating
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 with
status=UPLOAD_IN_PROGRESS
10-27 19:46:19.599  5750  5750 D UploadsStorageManager: updateUpload
returns with: 1 for file:
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4
10-27 19:46:19.601  5750  5750 D UploadsStorageManager: notifyObserversNow
10-27 19:46:19.620  5750  5750 D ExpandableUploadListAdapter: refreshView
10-27 19:46:19.621  5750  5750 D ExpandableUploadListAdapter:
loadUploadItemsFromDb
10-27 19:46:19.652  5750 23722 V UploadsStorageManager: Updating
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 with
status:UPLOAD_IN_PROGRESS and result:UNKNOWN
(old:/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4
status:UPLOAD_IN_PROGRESS result:-1)
10-27 19:46:19.654  5750 23722 V UploadsStorageManager: Updating
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 with
status=UPLOAD_IN_PROGRESS
10-27 19:46:19.669  5750 23722 D UploadsStorageManager: updateUpload
returns with: 1 for file:
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4
10-27 19:46:19.671  5750 23722 D UploadsStorageManager: notifyObserversNow
10-27 19:46:19.677  5750  5750 D ExpandableUploadListAdapter: refreshView
10-27 19:46:19.679  5750  5750 D ExpandableUploadListAdapter:
loadUploadItemsFromDb
10-27 19:46:19.686  5750 23722 D SimpleFactoryManager:
getClientFor(OwnCloudAccount ... :
10-27 19:46:19.703  5750 23722 D OwnCloudClient #38: Creating OwnCloudClient
10-27 19:46:19.711  5750 23722 V SimpleFactoryManager:     new client
{user@ip:port, 182044586}
10-27 19:46:19.728  5750 23722 D OwnCloudClient #38: REQUEST HEAD
/remote.php/webdav/Camera%20Uploads/Video/
10-27 19:46:20.217  5750 23722 D ExistenceCheckRemoteOperation: Existence
check for https://ip:port/remote.php/webdav/Camera%20Uploads/Video/
targeting for  existence finished with HTTP status 200
10-27 19:46:20.254  5750 23722 D UploadFileOperation: Checking name
collision in server
10-27 19:46:20.257  5750 23722 D OwnCloudClient #38: REQUEST HEAD
/remote.php/webdav/Camera%20Uploads/Video/VID_20161027_175830.mp4
10-27 19:46:20.879  5750 23722 D ExistenceCheckRemoteOperation: Existence
check for https://ip:port/remote.php/webdav/Camera%20Uploads/Video/VID_20161027_175830.mp4
targeting for  existence finished with HTTP status 404(FAIL)
10-27 19:46:20.884  5750 23722 V UploadsStorageManager: Updating
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 with
status:UPLOAD_IN_PROGRESS and result:UNKNOWN
(old:/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4
status:UPLOAD_IN_PROGRESS result:-1)
10-27 19:46:20.886  5750 23722 V UploadsStorageManager: Updating
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 with
status=UPLOAD_IN_PROGRESS
10-27 19:46:20.903  5750 23722 D UploadsStorageManager: updateUpload
returns with: 1 for file:
/storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4
10-27 19:46:20.905  5750 23722 D UploadsStorageManager: notifyObserversNow
10-27 19:46:20.908  5750  5750 D ExpandableUploadListAdapter: refreshView
10-27 19:46:20.910  5750  5750 D ExpandableUploadListAdapter:
loadUploadItemsFromDb
10-27 19:46:20.929  5750 23722 D ChunkedUploadRemoteFileOperation:
uploadFile, chunkId 12230066
10-27 19:46:20.931  5750 23722 D ChunkedUploadRemoteFileOperation:
uploadFile, successfulChunks [0, 1]
10-27 19:46:20.933  5750 23722 D ChunkedUploadRemoteFileOperation:
uploadFile, CHUNK_SIZE 10240008
10-27 19:46:20.947  5750 23722 D ChunkedUploadRemoteFileOperation: offset:
0, totalLength: 260539783, chunkCount: 26
10-27 19:46:20.952  5750 23722 D ChunkedUploadRemoteFileOperation: 2nd:
offset: 0, totalLength: 260539783, chunkCount: 26
10-27 19:46:20.955  5750 23722 D ChunkedUploadRemoteFileOperation:
Skipping, sharedPrefs said chunk already there
10-27 19:46:20.956  5750 23722 D ChunkedUploadRemoteFileOperation: 2nd:
offset: 10240008, totalLength: 260539783, chunkCount: 26
10-27 19:46:20.958  5750 23722 D ChunkedUploadRemoteFileOperation:
Skipping, sharedPrefs said chunk already there
10-27 19:46:20.959  5750 23722 D ChunkedUploadRemoteFileOperation: 2nd:
offset: 20480016, totalLength: 260539783, chunkCount: 26
10-27 19:46:20.962  5750 23722 D OwnCloudClient #38: REQUEST PUT
/remote.php/webdav/Camera%20Uploads/Video/VID_20161027_175830.mp4-chunking-12230066-26-2
10-27 19:46:21.008  5750 23722 D ChunkFromFileChannelRequestEntity:
mchannel.position is 20480016 and maxCount 30720024
10-27 19:46:25.241  5750 23722 D ChunkedUploadRemoteFileOperation: executed
put method, without throwing up
10-27 19:46:25.244  5750 23722 D ChunkedUploadRemoteFileOperation: Upload
of /storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 to /Camera
Uploads/Video/VID_20161027_175830.mp4, chunk index 2, count 26, HTTP result
status 201
10-27 19:46:25.246  5750 23722 D ChunkedUploadRemoteFileOperation: 2nd:
offset: 30720024, totalLength: 260539783, chunkCount: 26
10-27 19:46:25.248  5750 23722 D OwnCloudClient #38: REQUEST PUT
/remote.php/webdav/Camera%20Uploads/Video/VID_20161027_175830.mp4-chunking-12230066-26-3
10-27 19:46:25.255  5750 23722 D ChunkFromFileChannelRequestEntity:
mchannel.position is 30720024 and maxCount 40960032
10-27 19:46:28.059  5750 23722 D ChunkedUploadRemoteFileOperation: executed
put method, without throwing up
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:
Exception reading exception from server
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:
org.xmlpull.v1.XmlPullParserException: expected: START_TAG {null}d:error
(position:START_TAG <html>@1:7 in java.io.InputStreamReader@10bff9b)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.common.operations.InvalidCharacterExceptionParser.readError(InvalidCharacterExceptionParser.java:88)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.common.operations.InvalidCharacterExceptionParser.parseXMLResponse(InvalidCharacterExceptionParser.java:71)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.resources.files.ChunkedUploadRemoteFileOperation.uploadFile(ChunkedUploadRemoteFileOperation.java:135)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.run(UploadRemoteFileOperation.java:110)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:371)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:92)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:921)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:866)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
android.os.Handler.dispatchMessage(Handler.java:102)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
android.os.Looper.loop(Looper.java:154)
10-27 19:46:28.062  5750 23722 E ChunkedUploadRemoteFileOperation:      at
android.os.HandlerThread.run(HandlerThread.java:61)
10-27 19:46:28.064  5750 23722 D ChunkedUploadRemoteFileOperation: Upload
of /storage/emulated/0/DCIM/Camera/VID_20161027_175830.mp4 to /Camera
Uploads/Video/VID_20161027_175830.mp4, chunk index 3, count 26, HTTP result
status 400

2016-10-27 15:47 GMT+02:00 Iskra Delta <notifications@github.com>:

**Comment by iskradelta** [comment]
Oops, try this one, https://github.com/iskradelta/android/blob/debug_apk_2/build/outputs/apk/nextcloud_beta-debug_2.apk

I got it faster now, and was wrong previously (or is it my wifi messing with me!?), the chunk size does matter, and Ive set it to 6144000 (6mb) as a good compromise of speed and not having to re-upload much on a failed chunk, and avoid errors when peoples servers are configured to only accept a body size/upload-at-a-time of 10mb or so, which I guess is common. (this can be both set in nginx/lighttpd/apache, and php-fpm I think). Also I think if most routers give at least 54mbps, 6mb chunks fit well.

With chunk size 6mb, and changing to use Channels, instead of what was previously done - read into buffer and write to outputstream, 4096 bytes at a time, now the new Channel interface can optimize this and avoid copying parts of the file into the process then writing it to the network - now it will let Linux copy as much as is requested, ie a chunk size, from one stream to the other directly.

**Comment by allcoolusernamesaregone** [comment]
Yes, this one looks good. Much faster. Will compare the upload speeds of
beta and play store apk this evening..

2016-10-27 23:21 GMT+02:00 Iskra Delta <notifications@github.com>:

**Comment by iskradelta** [comment]
Hm, sounds good, can you also compare with the nextcloud_beta-debug_2.apk from the link above? The beta app from f-droid doesnt have this pull-request yet. And maybe try to upload new/different big files for each attempt, because the server takes the chunks and caches them between retries.

**Comment by tobiasKaminsky** [comment]
@iskradelta :+1: for helping here in such a great way.
Just writing quickly my thoughts:
So to enhance this in a real way we should try to figure out what kind of connection we currently use.
If it is wlan we can use bigger chunks; otherwise smaller chunks.
Open questions
- is it possible to get the connection speed
- upload starts with 6mb chunk, but switch to 1mb chunks as the connection is getting worse...Still working as the chunk numbers are now not correct. Possible solution: instead of chunk numbers use starting byte as chunk identifier.

**Comment by tobiasKaminsky** [comment]
https://developer.android.com/reference/android/net/NetworkCapabilities.html

**Comment by iskradelta** [comment]
Indeed, the NetworkCapabilities looks interesting. But there are problems, such as this

File X selected big chunk size of 10MB because NetworkCapabilities says "very good", uploaded say 3 chunks (total file is 100mb). Lost connection/router-got-restarted/toddler threw the phone out of the house... Now when retrying upload, if NetworkCapabiliteis says "poor shitty connection", we pick chunk_size 1mb, but now those chunks are not stored in SharedPreferences, so it would resend the whole parts already sent. So to solve that we would have to remember not the chunks_successfuly_sent, but also the size of them, or bytes_successfully sent, or whatever, and then do calculations on that. It gets hairy and messy. And better yet, skip remembering how many and size of chunks sent, or remembering bytes sent, but ask the server "how many bytes of the file do you already have", is there such an server API already?

I would say just "big_chunk_size of 10mb, when file size is > 5mb. else use small chunk size of 1mb." So, if user has enabled "instant upload of videos even when out of wifi", we just assume that user has really good 4G LTE, and can suffer the bandwidth loss when chunks are resent. So chunk_size dependent on file size, which shouldnt change, so to avoid having to recalculate or ask server for how much of file it has stored already, or change the rest of the code to handle adaptive/varying chunk_size for same file. So this solution seems too simple but provides good enough return on investment.

**Comment by xpgdk** [comment]
Is there any active progress on this? It sounds to me that the suggestion @iskradelta has made, to have two chunk sizes is a relatively easy way to improve the situation. Or am I missing something=
