### ISSUE TITLE
Custom folder auto-upload is not triggered

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3670]
### Actual behaviour
I'm not sure what is happening, but my auto-upload is not triggered

### Expected behaviour
Auto-upload should be triggered when I make new photo
 
### Steps to reproduce
1. checkout master
2. run on emulator
3. login as usual
4. set up **custom** auto-upload folder DCIM/Camera -> Something
5. open android camera and make a photo

Nothing happens.

I found this crash in logs - could be related:

```
2019-02-23 18:35:23.568 10053-14293/com.nextcloud.client E/JobExecutor: Crashed job{id=2, finished=true, result=FAILURE, canceled=false, periodic=true, class=OfflineSyncJob, tag=OfflineSyncJob}
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
        at com.owncloud.android.jobs.OfflineSyncJob.recursive(OfflineSyncJob.java:145)
        at com.owncloud.android.jobs.OfflineSyncJob.onRunJob(OfflineSyncJob.java:91)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### Environment data
Android version: 9
Device model: emulator
Stock or customized system: emulator with google apps
Nextcloud app version: git master
Nextcloud server version: 15.0.2

**Comment by ezaquarii** [comment]
```
        final boolean skipCustom = bundle.getBoolean(SKIP_CUSTOM, false);
        FilesSyncHelper.restartJobsIfNeeded();
        FilesSyncHelper.insertAllDBEntries(skipCustom);
```

It looks like `skipCustom` is `true` and my custom folder is excluded from sync.

**Comment by AndyScherzinger** [comment]
This is something that @tobiasKaminsky (OfflineSync) and @mario (custom folder upload / auto upload jobs) might be able to answer. If I remember correctly than custom folders are a different mechanism when it comes to detecting changes and triggering uploads, but @mario knows best ❤️

**Comment by ezaquarii** [comment]
@mario  can you pls comment on this?

**Comment by mario** [comment]
@ezaquarii first of all, thanks for all your contributions to date - I don't comment much, but I follow your work closely :)

So the OfflineSyncJob crash is not related to this particular issue (but should be fixed, of course) since it's not related to auto upload or new images detection. So to clarify:

- the intent of Custom auto-upload folders was to support uploading folders other than what traditional Android content providers provide (e.g. photos)
- to do that properly, we have to walk the directory tree as other methods are not good enough for various reasons
- intent was to disable adding Custom auto-upload folders IF a content-provider folder with the same path exists, but this functionality was never implemented

Since we have no way of automatically knowing if a file appeared in your custom folder, we query this every 15 minutes via a job. Now, the reason why FilesSyncJob fired anyway is because:

- you took an image
- we have a Content Observer - https://github.com/nextcloud/android/blob/92df32e664489a7e87be13bb84a2561fc847bb05/src/main/java/com/owncloud/android/jobs/NContentObserverJob.java that starts FilesSyncJob  AND uploads the image if it's in one of the Content-Provider provided folders (for which we can use the DB, of course)

Walking the FS tree every time an image is shot is not optimal, therefore custom folders only support interval-based uploads/change detection.

There are of course workarounds that might help, one of which comes to mind:
    - on content observer fire, check if the path of a new image/video has a parent in one of the enabled custom folders
    - if it does, upload it there

But this was not implemented.

Let me know if I didn't clarify something good enough.

**Comment by mario** [comment]
@ezaquarii ^_^
