### ISSUE TITLE
Error when navigating: Photos, Shared and Favorites.

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#3729]
### Actual behaviour
- There is no correct navigation between "Photos", "Shared" and "Favorites".

### Expected behaviour
- View your "Photos", "Shared" and "Favorites" files.
 
### Steps to reproduce
1. Go from the menu to "Photos".
2. Go from the menu to your "Favorites".
**ERROR:** no favorite files, even though they are.
3. Go from the menu to your "Shared"
**ERROR:** no Shared files, even though they are.

No description change in the top bar of the application.

![obraz](https://user-images.githubusercontent.com/47037905/54067959-dc23fa00-4246-11e9-8c29-14edf062fd19.png)

The error described can be associated with #3648

### Environment data
Android version: 6

Nextcloud app version: dev 20190309 bde010b

Nextcloud server version: 15.0.4

**Comment by Stam21** [comment]
I have the same issue in my phone(android 8.1/nc 3.6.1). May I try to fix this?

**Comment by AndyScherzinger** [comment]
@Stam21 you are most welcome and thanks for giving it shot.

@tobiasKaminsky and @mario might be good sidewings since I guess this might be related to event/messaging magic.

**Comment by Valdnet** [comment]
> May I try to fix this?

@Stam21 It would be great 😉 

This error makes it very difficult to use the application.

**Comment by tobiasKaminsky** [comment]
This seems to be still a problem, so re-oping.

**Comment by AndyScherzinger** [comment]
I'll try to add my finding here. (Probably on a slow connection)...

OPen the app and go straight to favorites sometimes leads to a overlay of 2 empty list visuals:
![device-2019-08-26-081638](https://user-images.githubusercontent.com/1315170/63669445-51c25900-c7da-11e9-992e-c41aa67d0e2a.png)

Then navigating to "Shared" leaves me with an endless spinner (I only have 2 shared folders, nothing else)

Then navigating to "On device" right away, leaves me with 2 endless spinners (toolbar and bottom):
<img width="540" alt="device-2019-08-26-082143" src="https://user-images.githubusercontent.com/1315170/63669560-a4037a00-c7da-11e9-9baa-2e80576b1adc.png">
Also the menu beig active is still "Shared" instead of "On Device"

Other than that the navigation time (duration between hitting a navigation item and it actually opening the screen) is incredibly slow (seconds...)

Server is 16-latest, App is today's master, Device is Lineage 16.0-20190824-NIGHTLY

**Comment by Valdnet** [comment]
> OPen the app and go straight to favorites sometimes leads to a overlay of 2 empty list visuals:

I have the same error: #4400.

@AndyScherzinger I also have a problem with infinite charging. Described in: #4401.
