### ISSUE TITLE
Dependency Injection solution

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3751]
### Is your feature request related to a problem? Please describe.
This is a follow-up on #3600. After removing static preferences helpers from the code, we can start injecting it properly.

We're currently not using any fancy DI framework.

### Describe the solution you'd like
I believe it is a time to start thinking about dependency injection solution of some kind, to avoid manual deps creation everywhere.

### Describe alternatives you've considered

1. choosing existing solution (pretty much only Dagger 2, fortunately maintained by Google)
2. rolling own, simpler solution, such as a flat service registry

**Comment by AndyScherzinger** [comment]
Both have their pros and cons I guess.
Even though a simple yet custom might be simpler it is a custom solution to a common problem so for the sake of keeping the entry barrier low for new contributors I'd vote for going with dagger since it is a known solution with documentation and tutorials. 

What do you think @tobiasKaminsky? 
@ezaquarii any preference?

**Comment by tobiasKaminsky** [comment]
I also vote for dagger 2.
If we do this step by step as proposed by Chris this is a really really good idea :+1:

**Comment by ezaquarii** [comment]
Dagger 2 integration with Android. For initial evaluation it is used in 1 activity and 1 fragment, where 1 instance if `AppPreferences` is injected.

**Comment by ezaquarii** [comment]
We've made a choice.

**Comment by AndyScherzinger** [comment]
I'll see that I'll take a look and test drive next week 👍

**Comment by ezaquarii** [comment]
I closed it accidentally. Reopening.
