### ISSUE TITLE
can't login: not access to untrusted domain

### ISSUE THREAD

**Issue by banphi** [nextcloud/android#3769]
![android-3](https://user-images.githubusercontent.com/48705968/54581219-ff4f6600-4a0b-11e9-9b79-3289e57d0651.png)

Hi, 
i try to connect to a localhost following this instruction 

> : The Nextcloud app will test your connection as soon as you enter it and tell you if you entered it correctly. If your server has a self-signed SSL certificate you’ll get a warning that it is not to be trusted. Click the OK button to accept the certificate and complete your account setup.

After i press Yes it replace me:
(translated by google translate)
Access via an untrusted domain. See the documentation for more information.

I search online and i can't find any voice in the documentation

(https://docs.nextcloud.com/android/android_app.html#connecting-to-your-nextcloud-server)

Also i try to find the qr code on the server but i didn't see.

Please help me :)

Thank you

**Comment by tobiasKaminsky** [comment]
Hm. According to the message, the url does not match the certificate.
Even if it is a self-signed, this should not happen and I think it is quite ok to warn.
Can you double check your certificate?
If you still think that this should/need work, then can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by ardevd** [comment]
@banphi if I understand you correctly the Nextcloud app is functioning as expected. First it prompt's you with a hostname warning for your SSL certificate since the hostname you're using to access your Nextcloud install does not match the SSL certificate common name. 

What happens next is not an issue with the Android app but rather the fact that the hostname you're using to accessing the Nextcloud instance is not configured as a trusted domain. Read more [here](https://help.nextcloud.com/t/adding-a-new-trusted-domain/26)

**Comment by tobiasKaminsky** [comment]
> What happens next is not an issue with the Android app but rather the fact that the hostname you're using to accessing the Nextcloud instance is not configured as a trusted domain. Read more [here](https://help.nextcloud.com/t/adding-a-new-trusted-domain/26)

Thanks for pointing this out, I overread this.
@banphi if you have further questions on how to set up the server, please ask on forum.
