### ISSUE TITLE
Remember zoom state in photo view

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3805]
- open an image
- zoom into it
- switch to another app & back
- zoom is reset

**Comment by tobiasKaminsky** [comment]
I gave it a quick try, but it is not that easy, I fear.
We call initViewPager() and this recreates new PreviewImageFragments that do not have any reference to the previous zoom

**Comment by ezaquarii** [comment]
This information can be saved in instance state, but have some doubts if this is a valid approach.
The whole concept of re-building the world when you come back from the background is fishy to me.

1. What is the purpose of `onAccountSet()`? It looks like it's called every time we hit `onStart`, even if account did not change at all.
2. What is the genuine use case for an account change? How can I test this?

**Comment by ezaquarii** [comment]
I created 2nd account and tried to switch to it and it looks like entire activity stack is switched on account change.

This immediately raises a question if we really need this code path in the first place. The code is from 2013 and some lines are commented out since day 0.

I'd seriously use this opportunity to see if we could potentially delete it.

**Comment by tobiasKaminsky** [comment]
I tried this, and even when I get the correct zoom from previous state, lib is refusing to zoom correctly.
--> closing as cannot fix :/
