### ISSUE TITLE
Data migration service

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#3885]
### Is your feature request related to a problem? Please describe.
Data migration is handled in few places in ad-hoc way, by calling static methods here and there. Data migration is spread over `MainApp` and poorly documented.

### Describe the solution you'd like
Centralize data migration under 1 component called in 1 place.

### Describe alternatives you've considered
Alternative is to just drop the migration code altogether, if we believe there is no more any clients left that use this code path. I believe that the mantra "just clear the app data and resync" was used quite often to fix issues.

I'm keen on understanding what is our apetite for keeping link with legacy state, as testing around this is very challenging and I don't really believe we're putting real effort to address this. IMO it is just holding us back.

### Additional context
A path to #3600

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger Let me know what you think - there is potential to retire a lot of cruft. Otherwise we need to have a viable testing strategy.

**Comment by AndyScherzinger** [comment]
I don't really know my way around the storage migration code (since I never worked on storage). Most of the changes were introduced by #1998 I guess but hopefully @tobiasKaminsky and @mario can say more about this part.
"just clear the app data and resync" is a workaround to hopefully self-heal the app if someone reported an issue. I tend to write code to fix thing if the issue hits many users since most won't report this on github or know how to clear the app data. So due to 300.000+ users we have such measures in place here and there :(

So depending on their feedback I'd been fine with both of your suggestions.

**Comment by ezaquarii** [comment]
This has been implemented in form of `MigrationsManager`
