### ISSUE TITLE
Question: Nextcloud or ownclou beta?

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#39]
I can recognize some names, so would like to ask. 

Is this nextcloud app still compatible with owncloud? Will it remain so?

What is the relationship between the apps? (meaning if you're going to continue to cooperate on both or are the apps going to diverge eventually..)

I was really fond of your work and I got used to using many features from the beta app (with the stable one serving as a back up) and I was happy when I could contribute in a meaningful way..

That is why I would like to know what the current situation is..

**Comment by AndyScherzinger** [comment]
The Nextcloud beta is compatible with ownCloud as of now. For how long it will stay compatible is hard to tell since this depends on the server side, so if Interfaces change or new features are added that won't work for ownCloud we will loose the compatibility. So for now both clients work, at some point in time my guess would be that the clients will be linked to the corresponding platform.

The Nextcloud client is based on the ownCloud client. I will continue to to support both platforms for now but the point is rather will the changes done by me or anyone else end up in the product with the same speed because if not features would come with different release dates so they will diverge anyways.

Hope this gives you an impression. @tobiasKaminsky is probably the right person to answer your questions since he is the one maintaining the beta client in both worlds :+1:

**Comment by tobiasKaminsky** [comment]
As I have not so much free time to spend for open source projects I have decided to help nextcloud and not maintain the owncloud beta app any longer.

**Comment by AndyScherzinger** [comment]
So closing since the answer is: beta-wise we will only support Nextcloud
