### ISSUE TITLE
TLS 1.3 is not supported

### ISSUE THREAD

**Issue by outis151** [nextcloud/android#3932]
TLS 1.3 is not supported

**Comment by janusjanusjanus** [comment]
"enhancement"? C'mon, that's almost a security bug.

**Comment by Schmuuu** [comment]
> "enhancement"? C'mon, that's almost a security bug.
You should tell Google. Hardly imaginable how someone using Android could name this an "almost security bug".

@outis151 Only a few apps pack their own SSL libraries (like Firefox) and most apps use the libraries the operating system ships (Android). 
If you have the chance for Android updates, Android 9 might provide TLS1.3 support. I couldn't find any quick proof for that however. The only thing I found was a German site mentioning that Android Q will ship TLS1.3 support. So not clear if that is really the first Android version then or if Android Q just ships the support like earlier versions.
However, you can test the support of TLS1.3 of your device by executing the following test with your stock browser (shipped with your phone, not an additionally downloaded browser on your phone):
https://www.ssllabs.com/ssltest/viewMyClient.html

If that test tells you, your device does indeed support TLS1.3, please provide more information to your device, the used browser and so on. It might then be an issue with system calls or something like that. 
If your phone doesn't support TLS1.3 yet, you could ask the developers to ship their own openssl library, but I doubt a little, that they will do.

**Comment by outis151** [comment]
I did not know that apps don't always ship their own libraries and rely on system libraries. 
However I think that these security relevant libraries should always be included and kept up to date.

The test with the website you provided showed that my phone does support TLS1.3 (using the stock browser) but it is not working with the nextcloud app. I think the fact that I run Lineagos might probably be the reason for that though.

**Comment by DPTJKKVH** [comment]
Considering that many users cannot connect to their servers if they configure secure TLS1.2 cyphers (there are bug reports as old as two years!) I wonder why Nextcloud does not ship their own libraries.

There are complaints of the app developers that cipher support is unpredictable and confusing since it relies on the OS which can be further modified by vendors like Samsung.

So there are several reasons for shipping your own libraries. It enhances security as well as provides a controlled environment where devs always know what their app is capable of doing.

**Comment by Schmuuu** [comment]
I totally agree that it is actually very annoying to rely on mobile phone vendors. While it already takes Google quite a lot of time to ship new ssl libs, there are also the mentioned vendors like Samsung who change things and make it sometimes even worse. And as soon as the phone is around two years old, there are no more updates to the phone at all, leaving the users with old and outdated versions of ssl libs (just as an example).
I'm personally affected as well because I have to enable very insecure CBC ciphers on my server just to support 3-years old Samsung phones.

Therefore I totally support the idea to ship ssl libs with very important apps (like the Mozilla does with their Firefox browser).

The thing is though: it's not a bug and should be addressed as a feature request. So the title should maybe be something like:
"Feature Request: pls ship the NC app with their own ssl libs"

Best would be to have all the arguments for that in the first post, so that devs and others don't have to scroll all the way down to actually find the reason for that request.

@tobiasKaminsky is this something which could be considered and maybe even prioritized a little higher then?

**Comment by Schmuuu** [comment]
TLS 1.3 feature is now available in the latest release
https://github.com/nextcloud/android/releases/tag/stable-3.8.0

I think this issue can be closed then.

**Comment by outis151** [comment]
Thanks for adding!
