### ISSUE TITLE
Crash on openning app on Android 7.1 (android.app.RemoteServiceException: can't deliver broadcast)

### ISSUE THREAD

**Issue by NeoTheFox** [nextcloud/android#413]
### Actual behaviour
-App crashes after logging in

### Expected behaviour
-It should open the root of the cloud
 
### Steps to reproduce
1. Be on my ROM (Android 7.1, RR)
2. Enter credentials and server name
3. Crash

### Environment data
Android version: 7.1

Device model: kenzo

Stock or customized system: custom rom (Resurrection Remix)

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: can't deliver broadcast
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6095)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

************ DEVICE INFORMATION ***********
Brand: Xiaomi
Device: kenzo
Model: Redmi Note 3
Id: NDE63X
Product: cm_kenzo

************ FIRMWARE ************
SDK: 25
Release: 7.1
Incremental: 98c0f57ee4

```

What is weird is that I can tell that app is somewhat working - I uploaded this log just fine. But I cant open it - it results in instant crash and this log being displayed.

**Comment by AndyScherzinger** [comment]
Hi @NeoTheFox did you also post this on the tracker of the ROM itself, since I'd say this is most likely a bug in the ROM itself. We had the same "issue" reported by a user who is running a custom Android 6 ROM which renders notifications in a Android 7 style, so the broadcast then also crashed the app on the users phone.

**Comment by AndyScherzinger** [comment]
according to https://github.com/ResurrectionRemix/android_frameworks_base/issues/144#event-877919550  _cm14.1 issue due to zygote patches_

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario This issue is still present in the developer console on Google Play :/ for quite some devices (not happening a lot though):

* Pixel (sailfish)
* Nexus 5X (bullhead)
* Nexus 6P (angler)
* Redmi Note 3 (kenzo)
* Xperia XZ (SOV34)
* UMI_PLUS
* Mi 5 (gemini)
* Xperia Z5 Compact (E5823)
* Galaxy S5 (klte) 
* Redmi 3 (ido) 
* Moto G (3rd Gen) (osprey_u2) 
* OnePlus2 (OnePlus2)
* LG G5 (h1)
* X9077 (FIND7)
* Pixel XL (marlin)
* Galaxy S7 Edge (hero2lte) 2
* Galaxy S7 Edge (hero2qltetmo) 1
* Galaxy S7 (herolte)
* HTC 10 (htc_pmeuhl)

All devices running Android 7+

**Comment by tobiasKaminsky** [comment]
Do we have more infos about the os, e.g. if all are using a custom mod?

**Comment by mario** [comment]
Doesn't seem like it.

**Comment by AndyScherzinger** [comment]
No, we can only see the Android version which is always 7 or 7.1 no further details :(

**Comment by tobiasKaminsky** [comment]
This is still present even in RC4...
We need to finde out (somehow) which broadcast is the problem.

**Comment by saurabhtanu** [comment]
.android.app.RemoteServiceException: 
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1725)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:154)
at android.app.ActivityThread.main (ActivityThread.java:6334)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

is my stacktrace with 85%crashes on oneplus 5, Have no idea why is this happening or what should I do get this off the radar in the vitals. Need help.

**Comment by tobiasKaminsky** [comment]
Maybe you want to try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

But after all I am really out of clue...

**Comment by asheesh-gupta-kranti** [comment]
I was facing the same issue with my app, what I do is use LocalBroadcastManager instead of context. Android documents also suggest using LocalBroadcastManager for sending in-app broadcast receivers.

//register your receiver like this
LocalBroadcastManager.getInstance(this).registerReceiver(mMessageReceiver,
          new IntentFilter("custom-event-name"));

// unregister  like this
LocalBroadcastManager.getInstance(this).unregisterReceiver(mMessageReceiver);

// broadcastlike this
LocalBroadcastManager.getInstance(this).sendBroadcast(intent);
Hope this will help. Thanks! :)

**Comment by tobiasKaminsky** [comment]
What do you think @mario @AndyScherzinger? Currently we use 
https://github.com/nextcloud/android/blob/948f3bd2f2d534a54bb2eb846aa870fbe3a71b17/src/main/java/com/owncloud/android/files/services/FileDownloader.java#L676-L676

to notify within the app.

**Comment by AndyScherzinger** [comment]
Not an expert on broad casts so would have to take a deeper look. @mario any ideas?
