### ISSUE TITLE
Shouldn't sync via public WiFi !

### ISSUE THREAD

**Issue by gloschtla** [nextcloud/android#4216]
Nextcloud should only upload files, if "Sync" is activated in Android. I don't want to expose my personal meta-data through unencrypted wLAN.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jancborchardt @ezaquarii what do you think? We had the whitelist/blacklist discussion before and especially in this (generic) case: technically speaking there is no such think as public wifi, there is only wifi. The only way at the moment is to set a certain wifi to "metered" within Android itself since we don't trigger auto uploads on metered wifi connections.

**Comment by ezaquarii** [comment]
We could potentially implement some extra conditions:

1) Sync on whitelisted wifi
2) Sync on encrypted wifi (wpa2, etc)

I need to dig the docs to see if it is trivially possible or requires some karate gimmicks.

**Comment by AndyScherzinger** [comment]
The issue with the whitelist is that we decided against such mechanisms since they raise the complexity from a UX perspective while not providing a benefit for the larger user base (read: edge use case)

**Comment by ezaquarii** [comment]
Sadly, our job scheduler does not support network encryption constraint.

```
    public enum NetworkType {
        /**
         * Network does not have to be connected.
         */
        ANY,
        /**
         * Network must be connected.
         */
        CONNECTED,
        /**
         * Network must be connected and unmetered.
         */
        UNMETERED,
        /**
         * Network must be connected and not roaming, but can be metered.
         */
        NOT_ROAMING,
        /**
         * This job requires metered connectivity such as most cellular data networks.
         */
        METERED
    }
```

That means it's not trivial to implement. I don't claim it is difficult - just not a 5-liner.

**Comment by jancborchardt** [comment]
Agree with @AndyScherzinger here. If you don’t want it to be synced, best set the Wifi to "metered"?

What is meant by `if "Sync" is activated in Android`? Is there a setting in Android? If so we could also simply honor that.

Because otherwise we end up with people needing to manage wifi info in the Nextcloud app which is not really what we want to do or spend time maintaining.

Also, a lot of common wifis are open, and we don’t want regular people to do extra steps to get that to work.

**Comment by tobiasKaminsky** [comment]
Manually setting the wifi to metered is a good way.
We will not have wifi management system within our app.

For most user the settings are good enough and for some privacy aware people there are multiple options,  also including VPN on unencrypted wifis, not using them, enabling upload only on charging (assuming you are charging only at home…)

> I don't want to expose my personal meta-data through unencrypted wLAN.

I really do not want to sound harsh, but if this is your concern, then you can also do not use email/chat, etc. on unencrypted wlan.

I am happy to discuss further privacy aware ideas, but adding such an option is not feasible.
