### ISSUE TITLE
Autoupload (move to app folder) deletes files on device

### ISSUE THREAD

**Issue by k4ffee** [nextcloud/android#4220]
### Actual behaviour
I configured a folder for autoupload (Screenshots) and selected the option to move files to the App Folder. But if I access the "On Device" in App Menu and navigate to that folder, the files get deleted. 

### Expected behaviour
The files should last there till I delete them.
 
### Steps to reproduce
1. Configure a Screenshot folder
2. Configure that folder for autoupload, with option move to app folder active
3. Take a screenshot
4. Access screenshot folder through App -> On Device

### Environment data
Android version: 9

Device model: ONEPLUS A3003

Stock or customized system: LineageOS

Nextcloud app version: 3.7.0

Nextcloud server version: 16.0.3

### Logs
logged nothing

#### Nextcloud log (data/nextcloud.log)
logged nothing

**Comment by icasdri** [comment]
I think this is a duplicate of #2131

**Comment by x86dev** [comment]
Looking forward giving the fix a try! Thanks!

**Comment by feutl** [comment]
I tested this, because I had problems with it like mentioned in my [comment](https://github.com/nextcloud/android/issues/4454#issuecomment-537806803) and it worked over the last 7 days without issues.

Even deleting files locally available in the app folder, on another device, removed the files on the device where it was moved to the local app folder correctly.

Device: Samsung S9+
NextcloudClient: 3.9.2
Nextcloud: 16.0.4 and 17.0.1
Android: 9.0

Thanks
