### ISSUE TITLE
Fix navigation menu 

### ISSUE THREAD

**Issue by Stam21** [nextcloud/android#4316]
### Actual behaviour
- Choosing favorites in the navigation menu, shows the content of the previous      category that has been chosen.
- Choosing photos in the navigation menu, shows a loading screen. 

### Expected behaviour
- Choose favorites and show everything I have marked as favorite.
- Choose photos and show every photo in my account. 
 
### Steps to reproduce
1. Open the app(All Files is the starting point) 
2. Visit Favorites
3. Visit Photos
4. Reproduce it with other categories too(e.g. Visit shared first and then photos or favorites) 

### Environment data
Android version: 8.1.0 / 9.0

Stock or customized system: Stock / Customized 

Nextcloud app version: 3.8.0 Alpha1

Nextcloud server version: Latest

**Comment by tobiasKaminsky** [comment]
Photo will be fixed with #2250, can you give it a try? (there is a APK you can install in parallel)
Favorites is working for me, though it shows briefly "no files/folders".

![2019-08-13-084502](https://user-images.githubusercontent.com/5836855/62920652-aa3f3280-bda6-11e9-9e1c-0e0236defd76.png) ![2019-08-13-084456](https://user-images.githubusercontent.com/5836855/62920653-aa3f3280-bda6-11e9-8356-2e9246eb60db.png)

**Comment by Stam21** [comment]
It works perfectly at version 3.6.2 and broke at 3.7.0 RC1. Until now I get the same behavior from these 2 fragments. Maybe I forget something while I'm building the app? It is strange that there is no issue at favorites on you.
(By the way if its possible to inform me about the method setPhotoSearchNoNew(), where is it initialized? I found it in the parallel branch photoSearchLimit , in java class PhotoSearchTask. line 107)

**Comment by tobiasKaminsky** [comment]
Photo view is working for you in 3.6.2? For most of the users this spins forever as it tries to load all photos at once.


> Maybe I forget something while I'm building the app?

There is nothing to forget. All dependencies are fetched automatically.



> (By the way if its possible to inform me about the method setPhotoSearchNoNew(), where is it initialized? I found it in the parallel branch photoSearchLimit , in java class PhotoSearchTask. line 107)

Please ask all photo related question in the PR, otherwise it will get too complicated.

So, let us focus here on favorites: I do not fully understand the problem. Is favorite working for you? 
If not, what happens, can you show a screenshot?

**Comment by Stam21** [comment]
![Nextcloud](https://user-images.githubusercontent.com/32773128/63071113-97ec0280-bf26-11e9-822c-c460830e1db3.gif)

**Comment by Stam21** [comment]
![Nextcloud](https://user-images.githubusercontent.com/32773128/63071316-793a3b80-bf27-11e9-8132-77adc6a397da.gif)

**Comment by tobiasKaminsky** [comment]
> AllFiles -> Favorites-> Shared-> Favorites

Ah, now I see "your problem".
Swipe to refresh always defaults to "show all files", which of course is a bug.

Can you wait a bit longer when switching to favorites?

**Comment by Stam21** [comment]
No matter how long I wait no favorites are shown on me
