### ISSUE TITLE
Photo view stops after 95 pictures

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4353]
OK, i just tested the 10427 build: no crash to report yet, but still stops after 95 pictures...

_Originally posted by @mlaverdiere in https://github.com/nextcloud/android/pull/2250#issuecomment-522237938_

**Comment by tobiasKaminsky** [comment]
@mlaverdiere how many images do you have in your cloud?

**Comment by mlaverdiere** [comment]
@tobiasKaminsky: More than 12 000...

**Comment by tobiasKaminsky** [comment]
Strange…
Saying that it is working on my cloud is not a help ;-)

Can you 
Can you create us a test account, add 200 sample images, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by mlaverdiere** [comment]
@tobiasKaminsky: OK, I tried with a test account and a set of pictures other than mine (a package of 500 jpg National Geo pictures of the day), and it seems to work fine, i.e. it can go over the first 95 pictures and load everything....

The main differences I can think of between this test account and my real one are the following: 

1) My jpg pictures are larger in size (i..e. +/ 5mb each) than the pictures on the test account (+/- 400 kb each); 
2) I have a mix of jpg and raw (dng and nef) files (maybe it's not a good idea at this time for the ND app. to try to render/show raw files, since this is not natively supported by the ND server?)

**Comment by mlaverdiere** [comment]
Another observation with my test account: it seems that when all pictures are loaded, when you scroll down to the last picture to be shown, the ND app is still trying to load more (spinning wheel), giving the (false) impression to the user that there is more to come...

**Comment by mlaverdiere** [comment]
I'm on version 3.8.0 of Android app and I still experience this bug with my regular account (with +/- 70 GB of images in various formats, like jpg and raw: dng, nef, raf, etc.), but not with my test account (500 jpg files). Right now, the loading stop after 19 pictures, but this number may change if I load new pictures on my ND account, so it seems that there is a particular picture file somewhere that makes the loading/display hang... I will continue to investigate and come back later if I find something useful.
