### ISSUE TITLE
Need of the 'read phone status and identity' permission

### ISSUE THREAD

**Issue by jpggithub** [nextcloud/android#443]
The version 1.4 RC2 of nextcloud app (on F-Droid) asks for the 'read phone status and identity' permission.

Why is this permission needed?

Android version : 5.1.1 (cyanogenmod 12.1)

**Comment by AndyScherzinger** [comment]
Hi @jpggithub we unfortunately need to have this (course grained) permission to work with Androids account manager and if I am not mistaken to also read the connection states (connected to wifi, charging, etc) but due to Google's permission design this all ends up being part of the 'read phone status and identity' permission so there is no other way to get this information then to request the given permission :(

**Comment by krayon** [comment]
Isn't there separate permissions for that? DavDroid for example, doesn't require identity and has ones called "Add or remove accounts", "create accounts and set passwords" and "find accounts on the device".

For wifi there's "view network connections" and "view Wi-Fi connections" that provides that info I think.

**Comment by AndyScherzinger** [comment]
Hi @krayon, thanks for the hint. I'll have a deeper look into it and yes we shouldn't ask for permissions we don't need for the app to work.

**Comment by AndyScherzinger** [comment]
@jpggithub @krayon the permission isn't needed and has been removed with the latest release 1.4.2, currently only available via the Play store :/

**Comment by krayon** [comment]
@AndyScherzinger : Thanks a lot :D I was meaning to look into this myself but hadn't had the time.

**Comment by AndyScherzinger** [comment]
@krayon you are very welcome and thanks for pointing this out so we could analyze and fix it :)
