### ISSUE TITLE
NextCloud Conflict error with OwnCloud

### ISSUE THREAD

**Issue by Zombie-Ryushu** [nextcloud/android#4507]
### Actual behaviour
NextCloud Android App gives the error: Conflict when attempting to upload anything to an OwnCloud 10.1 server.

### Expected behaviour
NextCloud Android App should upload data to an OwnCloud 10.1 server.,
 
I use the NextCloud Client with an up to date version of OwnCloud 10.1, and in the past, despite the warnings of version obsolecance, it still worked. I do this because the proper OwnCloud Client for Android costs 99 Cents where the NextCloud App is free. 

Recently, the NextCloud App has started to say "Conflict" when using it to upload to OwnCloud. They used to be fully compatible. Can someone help in restoring this compatibility?

**Comment by tobiasKaminsky** [comment]
Due to limited amount of dev time we can only make sure that client is working fine with all supported NC versions. Additionally server functions diverged a lot since the fork.
While it was a nice side effect that our client worked with oC, we will not put any effort to make it effort in it.
If you or another want to test/debug and provide a PR, I am happy to review it.

I am closing this as out of scope of the goal of this client.

**Comment by schiessle** [comment]
If you like the Nextcloud client, I'm sure you will also like the Nextcloud server with all its improvements and additional features. Upgrading your ownCloud is super easy: https://nextcloud.com/migration/
