### ISSUE TITLE
Search icon shown when opening text file

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#454]
@nextcloud/android the search icon is shown in the header when you open text files but it does nothing. I guess it’s not intended to show it there? ;)

In any case Search inside of text files #211 would be good :)

**Comment by ronak5279** [comment]
hey! i would like to know more about this issue

**Comment by tobiasKaminsky** [comment]
hey,
thank you for wanting to contribute.
As @jancborchardt described the problem is that the search icon (magnifying lense) is shown when you download and open a plain text file (e.g. test.txt).
To solve this the search icon must be disabled when entering the text preview fragment and enabled again when showing the regular file list.
If you need any help, do not hesitate and join us on #nextcloud-mobile on IRC.

**Comment by tobiasKaminsky** [comment]
Edit: Just saw it seconds ago: this is already covered by @mario PR #565 
So, if you still want to contribute, please search for another "starter issue".

**Comment by AndyScherzinger** [comment]
@ronak5279 the PR of interest for you is #565 then

**Comment by mario** [comment]
This is fixed.
