### ISSUE TITLE
Unable to change the account password on the phone.

### ISSUE THREAD

**Issue by alexivanou** [nextcloud/android#4643]
A couple of days ago I changed my password through the Nextcloud web interface. The Nextcloud application for Android when trying to access files began to produce an error. 

I looked through all the menus, I could not find the ability to change the password on the phone.

It seems to me that this function needs to be either added or displayed to where it can be found, if it already exists.

**Comment by szaimen** [comment]
@alexivanou I think it isn't possible to change rhe password, because the app doesn't store the real password but only app tokens. By using them the connection is valid without the need to change your password every time you change it on another device or via the web interface.
So your error is probably not related to the password change...

**Comment by szaimen** [comment]
> Could it be that the problem is due to server version 13.0.4.0 ?

I honestly don't know. But since NC 13 isn't officially supported anymore you should consider upgrading your server in my opinion...

**Comment by tobiasKaminsky** [comment]
Yes, this is due to the outdated server, I guess.
Newer server use a weblogin flow which create an app token, which stays valid even if you change the real password.

Please upgrade your server and re-setup your app.
