### ISSUE TITLE
Fast scroll list view

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#47]
Enable a handler that allows fast scrolling to easily scroll to the bottom, e.g. when navigate to the oldest file.

Bug:
- [ ] fast scroll vanishes after switching to subfolder

**Comment by squiggie** [comment]
I'm a fairly new android developer and especially new to the nextcloud community. I would like to break in and contribute. I'd like to take a crack at this enhancement. 

Are you talking about some kind of 'fast scroll' feature where the velocity of the scroll allows a user to quickly go up or down the list view? Something like faster the fling velocity on the list view the faster the scroll?

**Comment by przybylski** [comment]
I think this is to introduce indexable scrolling like in contacts or using this: https://github.com/andraskindler/quickscroll

**Comment by squiggie** [comment]
Is a library wanted for this or is this something you want to implement on our own?

**Comment by tobiasKaminsky** [comment]
Best would be if we need no external library, but I do not know if this is possible.
The scrollbar should either show the date or the first character while scrolling, depending on the chosen sort order.

**Comment by AndyScherzinger** [comment]
I agree with @tobiasKaminsky we should not have to use a lib for such a small UI enhancement.

**Comment by tobiasKaminsky** [comment]
@squiggie are you still up to and want to contribute?
If you have any question you can just join #nextcloud-mobile on #freenode and ping me.

**Comment by tobiasKaminsky** [comment]
Idea: http://androidopentutorials.com/android-listview-fastscroll/ for listview only as we use a special implementation for gridview that does not work with fast scroll (but for this is pinch zoom)

**Comment by AndyScherzinger** [comment]
Look good to me, especially since we can use a standard sdk implementation. As for grid view (and also list view) this fast scroll issue for grid might be save when we get to the point of having the time to implement a recyclerview.

**Comment by AndyScherzinger** [comment]
c&p #3167 

_______

### Expected behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
a “Scroll Bar” so I can quickly scroll down through my thousands of pictures on the Android app.

![image](https://user-images.githubusercontent.com/13740715/37007559-d908285e-20ab-11e8-995f-276838df49b2.png)![image](https://user-images.githubusercontent.com/13740715/37007575-f0d53c6a-20ab-11e8-8e49-b48e53979a40.png)


### Actual behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

This is the actual behavior:

![image](https://user-images.githubusercontent.com/13740715/37007595-08c72c2a-20ac-11e8-869f-8fd90fde8d5f.png)

I don't want to swipe a hundred times or more just to look at older photos on NC. It's so much swiping! I have thousands of photos, and if I want to back in time, it would be nice to have a "Scroll bar" that will accelerate quickly and let me see photos down the list more quickly.

Please, this is a make-or-break feature, it's not a proper photos app without a scroll bar. :(

**Comment by Nebukadneza** [comment]
May i suggest
https://github.com/timusus/RecyclerView-FastScroll
As a great drop-in replacement? It works quite well in a lot of FOSS projects, and provides a user-experience just like regular users would expect from a view that can show a huge amount of files ….

**Comment by Shagequi** [comment]
Up

**Comment by AndyScherzinger** [comment]
> Up

@Shagequi what do you mean? This is basically an issue ready to be picked up :) Like @Nebukadneza suggested I'd say https://github.com/timusus/RecyclerView-FastScroll should be fine (also supporting Grid Layouts 😁) while I can't say if this works with our list/grid views (read: haven't looked at the code)

Also commented by @tobiasKaminsky 
> depending on sorting order we can show the date/name/size on the scroll handler

**Comment by Shagequi** [comment]
@AndyScherzinger 
I'm "upping it" for four reasons : 
- Determine if the issue is still desired today
- See if someone wanted to implement it before I pick the issue
- See if there are some news since 8-10 months, like a specific implementation or some things to "not do"
- Prevent a possible bot from closing the issue

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for feedback, from my POV:
* still desired
* not aware of anybody picking it up (except you atm)
* nothing I am aware of
only bugs get checked by the stale bot

**Comment by Shagequi** [comment]
And do you want a "Bubble" Scrollbar ? like these one : 
![image](https://user-images.githubusercontent.com/7050479/77347807-b164f080-6d38-11ea-8b7e-4e993faa96f6.png)

Or something more "customized" ?

**Comment by AndyScherzinger** [comment]
Bubble should be fine, while it needs to be checked if this can be themed dynamically or at least in a grey-ish style so it works for most/all themes. Dynamic theming would be best of course :)

**Comment by tobiasKaminsky** [comment]
Having this for A-Z is quite easy I guess.
But we can also sort by date, by size, etc.
Then this fast scroll should also work.
I am not sure if this is possible, but it should be kept in mind.

Last, but not least, I am unsure if there is a need for a random 3rd party library…

If you have any question, just ping me :-)

**Comment by AndyScherzinger** [comment]
> Last, but not least, I am unsure if there is a need for a random 3rd party library…

If the fast scroll including the bubble can be done without an additional library than that is of course the preferred way to implement it, yes 😃

**Comment by Shagequi** [comment]
I think we need a library for the bubble

**Comment by tobiasKaminsky** [comment]
True :-)

**Comment by Shagequi** [comment]
Yes sure, I'll let you know when I start working on this feature :)

**Comment by tobiasKaminsky** [comment]
This is done via #9985
