### ISSUE TITLE
Setting to hide new media folders notification only visible when disabled

### ISSUE THREAD

**Issue by doits** [nextcloud/android#4738]
I have on phone A, android 10, with nextcloud desktop app 3.8.1. There in settings I have the option to disable the notification about new media apps, in German it says "Benarchrichtigungen der Mediensuche anze..." and I can toggle it off. (Just below "Show hidden files".)

On a second phone B I don't have this option below "Show hidden files". It is again android 10, nextcloud app 3.8.1. When I make a new photo in portrait mode it always reminds me that a new folder has been found, which is annoying.

Both phones upload images correctly, so autoupload works.

Why is this option not visible on my phone B? I want to turn that notification off on my phone B, too.

**Comment by doits** [comment]
Yeah sorry, should have done it in the first place:

Here Phone A (Photo of it, was faster):

![IMG_20191029_114354](https://user-images.githubusercontent.com/148003/67760582-d8492000-fa41-11e9-820d-3cf529840bc0.jpg)

Phone B (Screenshot):

![Screenshot_20191029-114333](https://user-images.githubusercontent.com/148003/67760437-a041dd00-fa41-11e9-9498-b5d3b4c03e30.png)

Phone A hast the setting below "Versteckte Dateien anzeigen", Phone B not.

**Comment by AndyScherzinger** [comment]
Ah, got it. This settings item is only shown in case you clicked the hide option within the new media detection notification.

The screenshot I think would be more important is the one of the new media found notification from the device where you don't see this option in the seetings (Phone B).

**Comment by doits** [comment]
I just managed to disable those notifications directly through the notification and I think now I understand the current logic:

- If the setting is *enabled*, do *not* display it in settings
- If the setting is *disabled*, *do* display it in settings
- If *enabled*, it can only be disabled through the notification (which I did right now successfully)
- If *disabled*, it can only be enabled through the settings (otherwise it could never be enabled again)

Why is there this sophisticated setting hiding process? I had to make a fake portrait photo only to disable that notification (OK, I could have done it the next time after I shoot a real one ... but this also feels weird, I want to disable them now.)

When there is a setting I think it should be *always* displayed under settings. I understand the idea of not overwhelming a user with too many settings (which I assume is the reason it behaves like this, please correct me if I am wrong). But there *is* that setting, only it is not *visible* sometimes - really confusing for me.

Having two places to disable it (directly in notification and in settings, where you can enable it again) would be the way to go here IMO.

**Comment by AndyScherzinger** [comment]
Hi @doits, you summed it up pretty nicely while I'd say all the bullets would nned to be inverted since from my point of view the setting is to "hide" the notification, but that's just details.

Other than that the reason this behaves the way it does is like you jusst wrote: The designers (and developers) don't want to clutter the UI with a larger amount of settings. So when I implemnted this feature (since people wanted it) the way to get this aligned with the general settings paradigma auf the app I went for the actual solution to have a "go" from the designers.
It sometimes might seem strange (you are not the first person to fall into this trap) the alternative would be to not offer such a hide mechanism at all, so the behavior is the trade-off we went for.

CC: @jancborchardt @nextcloud/designers 

@doits I'll close the issue then, feel free to further comment/discuss though.

**Comment by doits** [comment]
Thanks for the explanation. Again, I understand the main reasoning: It should make the UX better, though I definitely feel it makes it *worse*. I mean, the *feature* is there, it is just hidden from settings *sometimes* ...

---

Just one more first hand experience I just remembered where it feels weird and which also happened to me some months/maybe a year ago (I might simply be haunted by that feature ;-)):

My wife told me about those annoying notifications, every time she shoots in portrait mode. I didn't had them that time (probably because I had hit that "Disable" in the notification before by chance). So I looked under my settings: Indeed, there was a setting to disable them. I told her about that setting, she can disable them there. Well, she didn't have that setting ... probably I thought it some kind of A/B feature rollout where I was already rolled out and she wasn't, or because I had the beta version and she not etc.

---

But now I know, and probably (hopefully ;-)) will remember the next time I upgrade to a new phone or help a friend with it.

**Comment by AndyScherzinger** [comment]
Glad I could be of any help. As for the Portrait issue, yeah that is another issue that is rather different. It's on our radar to have a more sophisticated mechanism due to portrait, live images, cover art music folders, etc. But that then shouldn't trigger a notification no matter the setting but nobody had the time yet to work on this...

**Comment by tygill** [comment]
I know this is closed, but I agree that hiding the setting when these notifications are enabled feels wrong. I looked for a setting to do exactly this, but only thought to try disabling the notification itself when I saw this thread. I expected to see a 'Notifications' section in the app with a list of which notifications should be enabled or disabled - and since I didn't see anything there, I just assumed that it wasn't supported.
