### ISSUE TITLE
Rename camera uploads like Dropbox

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#480]
### Suggestion
When pictures taken from camera are uploaded, an option to have files renamed to date and time when picture was taken (like Dropbox) would be great.

### Environment data
Android version: 6.0.1
Device model: E6553
Stock or customized system: Stock
Nextcloud app version: v1.4.0
Nextcloud server version: v11

**Comment by rseek** [comment]
Options to have files renamed would also be great for another case:
I have two indentical android phones with nc client and I want them to backup photos to one Nextcloud directory. Since there is no option to change naming convention in my stock camera app, I suppose I will have collisions with photos from different phones but with same name.

So I have to backup photos to different directories and than manually merge them into one photo-archive. If I was able to set unique file-prefix for each android client, it would solve the problem

**Comment by detly** [comment]
See also [issue #12 for the iOS client](https://github.com/nextcloud/ios/issues/12).

**Comment by joshtrichards** [comment]
Let's consolidate this into #10103 since that's where the activity is.
