### ISSUE TITLE
Why search icon in media preview app bar ?

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#4862]
Hi,

Why is it a search icon in Video/Media preview ? 
It creates a "bug" when you type something in it.

I let you watch :

https://x467kzhzu.preview.infomaniak.website/index.php/s/mwGLp7WHNYmdYNR

Should we not remove it ? 

App version : 3.9.0

**Comment by AndyScherzinger** [comment]
hmm, tricky question I guess :/
As for the "phone variant" I guess so, for the tablet variant (search should then work on the file list of the list fragment) I guess it still be fine but needs to work on the list fragment. Still tricky since it belongs to the activity and the fragment open/close woul dnned to trigger a show/hide.

cc @tobiasKaminsky for feedback

**Comment by Shagequi** [comment]
@tobiasKaminsky ?

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
I would disable it on both, phone and tablet.

**Comment by Shagequi** [comment]
Working on it today

**Comment by Shagequi** [comment]
Fixed by : https://github.com/nextcloud/android/pull/5214
