### ISSUE TITLE
Make Instance Selection Button editable

### ISSUE THREAD

**Issue by Tuffiglig** [nextcloud/android#4929]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
![NC_Mobile](https://user-images.githubusercontent.com/15114290/70082339-81b79e80-160a-11ea-8afc-97377f3bf9b6.jpg)
I would like to have the round buttons at the top left, with which I can change the NC instance, editable.
It would be lovely it was possible to change the color and / or the letter, in my case "J".

Everytime i want to change the instance, i press the wrong button, because all three are blue with an J.
Sometimes it takes me up to 8 clicks, till i got the correct one, because i don't know which button is swiching to which position.

Thank you very much,
Tuffi

**Comment by AndyScherzinger** [comment]
Hi @Tuffiglig,
Just one question, why aren't you uploading an avatar via the web UI? The blue J avatars are coming from the server, so the client fetches and displays whatever it gets from the server. 
Other than that, like Gmail, you can hit the small triangle which flips the menu to show all account (since you might even have more than the 3)

**Comment by Tuffiglig** [comment]
Hey Andy.
> Just one question, why aren't you uploading an avatar via the web UI?
I nearly never use avatars.
And also didn't even know, until now, that this is possible. Never looked this up.

> you can hit the small triangle which flips the menu to show all account
Thank you very much!
That was to obvious. (-.-)

Thanks again,
Tuffi

**Comment by AndyScherzinger** [comment]
You are very welcome! Happy we got this sorted out 😊
