### ISSUE TITLE
Cannot share a folder I am currently viewing

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/android#5033]
### Actual behaviour
When I am in a folder there is no way to access the share or details information about it. Currently you have to go back up to the parent folder to be able to access the share icon or context menu.

### Expected behaviour
From the current folder I should be able to access both the share menu and the details menu. The most logical place I would expect to find this is from the "3 dots" in the upper right corner (next to the search icon).
 
### Steps to reproduce
1. Open any folder
2. Try to share the folder from the current location

**Comment by AndyScherzinger** [comment]
cc @nextcloud/designers @jancborchardt @tobiasKaminsky for feedback

**Comment by juliushaertl** [comment]
Makes sense to me, we also have this in the server (in the breadcrumbs) and I personally use that a lot.

**Comment by jancborchardt** [comment]
It would be nice if tapping the folder name in the heading would open the same actions menu that is opened on the 3-dot menu when you are outside of the folder?

As this is slightly obscure and might not be very discoverable, we should add a specific "Share" action into the 3-dot menu of the header, as the very first item. Yes, only "Share" and none of the other actions for now as otherwise it will get totally overloaded. :)

Same for iOS cc @marinofaggiana

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/android/issues/2428 which has more info
