### ISSUE TITLE
[3.10 RC1] Standarddesign should be: use System defaults

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5123]
When updating to [3.10 RC1]: 
The Standarddesign should be: use System default. But bright is enabled by default:
![Screenshot_20200108-124536_Nextcloud](https://user-images.githubusercontent.com/42591237/71975892-60ebf580-3215-11ea-8ca9-610345647c3d.png)

**Comment by tobiasKaminsky** [comment]
The reason I chose to default to "bright" is that there still might some slight ui glitches in dark mode and thus to play safe, it is an opt-in.

what do you think? @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I'd also keep it on light-as-default since the app isn't one that is "always on" like map/navigation or such so it is rather explecitely chosen and "light" would lead to the opt-in as descibed by @tobiasKaminsky.

I'd also be fine with changig it to system-default but woul dask for @nextcloud/designers / @jancborchardt's feedback since this would "auto-activate" the dark theme (which as stated still has some glitches) and thus I am unsure about the initial user experience.

**Comment by szaimen** [comment]
I would propose letting this behavior for 3.10 and changing it to "system default" for 3.11 or 3.12...

**Comment by AndyScherzinger** [comment]
> I would propose taking "bright" for 3.10 and changing it to "system default" for 3.11 or 3.12...

@tobiasKaminsky can we detect if this setting has been explicetely chosen so we could switch thge default-behavior like suggested by @szaimen? ...which I think would be a nice way to solve this (kind of a "soft-launch" of the dark theme feature).

**Comment by tobiasKaminsky** [comment]
Yes, this is possible.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky then I vote for @szaimen's approach to make "system default" the new with release 3.11. What do you think?

**Comment by tobiasKaminsky** [comment]
Good idea.
I'll create a PR, which we can merge to master right away (as we branched off already).
