### ISSUE TITLE
Users can not change password in Android APP

### ISSUE THREAD

**Issue by kokotko1337** [nextcloud/android#5206]
Im using user trough LDAP. I got policy that users need to change password every 3 months. After 3 months they are forced to change their windows password, which means that NC passwd changed too.
Android app trying to log into Nextcloud with old password, which means it lock user account out.

in the App, i found no possibility to change password, only REMOVE account.

Could you please implement future: Change password in the app ?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky shouldn't the app prompt for a password /re-authentication in this case ?

**Comment by kokotko1337** [comment]
it is definitely not working, ill be happy when i have the possibility to change PW in APP but this is not possible ...

**Comment by tobiasKaminsky** [comment]
Normally there is no need to change the password, if the underlying password is changed, as we use app passwords.
@blizzz do you have an idea?

**Comment by blizzz** [comment]
@kokotko1337 which NC version do you run?

Normally, the app would let Nextcloud create an app token, which is then used by the app. When a login fails, it is marked as unavailable, and new login attempts are avoided. 

Once a successful (web) login with the main password was done, the apptoken is being updated and enabled again.

It sounds like you would be using the real password instead of an app token, but then the app should indeed deal with invalid password and request a new one. I don't know whether the app makes a difference between password and token?
