### ISSUE TITLE
Link to a list of Nextcloud providers on the setup screen

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/android#53]
I bet many new users are unfamiliar to the concept of ownCloud/Nextcloud requiring URL/user/pass and not just user/pass.

To improve usability, I suggest that we put a link next to the server address box in the setup screen, saying: "Looking for a server? Get it here." And we link it to "https://owncloud.org/providers/" or the equivalent Nextcloud page when it is ready.

Apart from making it usable for Dropbox-minded users, this has the extra benefit of pointing more customers to the own/Next-cloud providers in that list, and this in turn increase the licensing fees Nextcloud can negotiate to get from the said providers.

PR: #561

**Comment by mabkenar** [comment]
This is very much related to #16

**Comment by AndyScherzinger** [comment]
@mabkenar Thanks you for your input! :smiley: 

@jospoortvliet and @jancborchardt would this be something you would like to be added? Personally I would vote against it to keep the login screen as minimal as possible but would implement it if you guys decide to have it in there.

**Comment by mabkenar** [comment]
I made a mockup:
https://iffcloud.fz-juelich.de/index.php/s/Rv51TxWrjPwHT4O

**Comment by tobiasKaminsky** [comment]
For me nextcloud is all about *my* data on *my* server.
So adding links to providers that can host the server for me is exactly the opposite and would look more like advertisement for me and maybe scares new user?

**Comment by jancborchardt** [comment]
I think this is a good point and we should make it easier to sign up to Nextcloud providers directly from the apps. It’s something @karlitschek @jospoortvliet and I talked a bunch about in the past.
It is very important that we cater to normal people as well, not only folks who can host their own server.

In the first iteration, we could make the »New to Nextcloud« text at the bottom slide up and expose a quick description »blabla you can host it yourself or get from a provider« and then a quick list of the 3 most popular ones, with a link at the bottom to a site with a more detailed description.

What do you think?

**Comment by AndyScherzinger** [comment]
I have to say I am with @tobiasKaminsky on this, to me it feels like advertising but I get it with regards to user adoption even though I am not sure if the app is the entry point or the web and then people install die app afterwards, but yes it helps with conversions.
GMail also does this everytime you create an account it gives you a list of providers (Google, Yahoo, Outlook Mail, Exchange, own server) to choose from. For my as a "I host my own server" user this will really annoy me every time I add an account in the app.

Who are the three to choose from and how have they been chosen? How would you support registration from within the app or phone except going through the browser. One Drive, Dropbox etc. do this nicely but they own the complete eco system, we don't. So a seamless experience is close to impossible. Plus the register accounts and don't order instances of Nextcloud.

I would ultimately need to see some mockups and flow since I get the idea but don't see any added value in this since it is going to be complicated and not seamlessly, you just going to get routed to a website in a browser...

**Comment by jancborchardt** [comment]
Especially now that the app is non-paid, it will for sure become an entry-point even more. So we need to make it behave like one.

> GMail also does this everytime you create an account it gives you a list of providers (Google, Yahoo, Outlook Mail, Exchange, own server) to choose from. For my as a "I host my own server" user this will really annoy me every time I add an account in the app.

Why though? There is the option »own server«. And the rest just makes it much easier for the »normal« majority of people.

> One Drive, Dropbox etc. do this nicely but they own the complete eco system, we don't. So a seamless experience is close to impossible.

It’s close to impossible, but we should still try. We do the same with federated sharing, and not attempting would be foolish.


> Who are the three to choose from and how have they been chosen?

That’s the crucial question here. We need to have some simple sort of ranking/rating system for the providers.

**Comment by AndyScherzinger** [comment]
> Why though? There is the option »own server«. And the rest just makes it much easier for the »normal« majority of people.
true, but like my other issue with dropbox etc. they all offer accounts for a service while in order to have it working the same way you would need to have a list of providers who do the same thing --> offer accounts to an existing Nextcloud instance but not the ordering of your own Nextcloud instance.
The later would mean
* open a browser
* order a Nextcloud instance (which might cost money, might need a credit card, jada jada jada)
* get an email,....
* login in
* add a user
* open your app again
* put in all the info
* use the app

I still don't see a value in this. The only thing that makes sense to me in regards to this would be the account creation variant which means "preferred provider". The Nextcloud instance thing is weird, that would mean someone actually installed an app and has no idea what it is except "cloud" maybe "storage" and surely does not expect to having to order a Nextcloud instance with some provider...

To me the question (still) unanswered remains who chooses the providers on which grounds?

**Comment by mabkenar** [comment]
The idea of explicitly listing providers in the setup screen and also in-app account registration are both great. But those are not the main point of the issue that I first opened. My point is about a serious bug in the overall UX of Nextcloud.

People naturally expect this app to behave just like Dropbox/OneDrive etc. and I'm afraid they become very confused when they see the empty text field for the server address, to the point where they give up right then. All I say is that there should be a hint next to the 'server address' text field.

**Comment by jancborchardt** [comment]
@AndyScherzinger oh there would of course need to be an API for this to streamline it. If we seriously want to add providers, then only those who offer this easy integrated signup will be considered for inclusion in the app listing.

The clear value is to get more people using Nextcloud who would otherwise not do it or have difficulties doing so. It’s easing the onboarding process. Those who want to set up their own server of course can always do it, and there’s no real danger in centralization since there is no central provider offering hosting.

> To me the question (still) unanswered remains who chooses the providers on which grounds?

Likely this would be done by a consortium or a team from the community who is interested in doing that. :)

@mabkenar your specific case is what the »New to Nextcloud« link on the bottom is for. What we went to discussing in this issue is how to make that even better.

**Comment by mabkenar** [comment]
> your specific case is what the »New to Nextcloud« link on the bottom is for.

I disagree. That link is too little too late. There need to be specific hint about the server, or generally about "how to make a Nexcloud account". Otherwise, I believe the first-time user gets lost. The "New to Nextcloud" link at the very bottom can still be reserved for general information about the project, the company, ways to contribute, etc.

Look, if I want to make my friend switch to own/Nextcloud, I have to give her a long speech about (a) what is Nextcloud, (b) the decentralized nature, (c) which provider/server to choose, and (d) which app to download and how to use it. I know this because I have recently converted someone to ownCloud, and my communication to her was not smooth.

But if there is help on finding the server built into the client, I only need to point her to the app. She will simply follow the app to find a server and configure her account. (Possibly later, she can learn more about Nextcloud or even about migrating all her data to her own server. But this can happen only if she has tried Nextcloud for some time.)

> What we went to discussing in this issue is how to make that even better. ;)

Both of those suggestions are great extensions to my original suggestion. I think we are better off tracking them in separate issues, as each of them is very involved. At the moment, I insist that we fix this UX problem for all the people who have heard the name of Nextcloud in the news and want to give it a try on their own. We should not lose them.

**Comment by AndyScherzinger** [comment]
Well there is another option which might help with your task @mabkenar and is slightly different, helping you to not having to describe everything but also making it easy for a user to get setup and running.

Idea:
What we can implement as what I would call namespaced URLs (as in app-"hyperlinks"). So we could popssibly create our own links with the necessary information, see http://www.techrepublic.com/blog/software-engineer/web-to-app-interoperability-launch-your-android-app-from-the-web/ put this into emails, the user clicks on it (and hopefully didn't choose "open every URL with chrome" at some point) chooses Nextcloud to open the link, Nextcloud reads the URL parameter and prefills the server address :D

**Comment by mabkenar** [comment]
@AndyScherzinger As I mentioned [here](https://github.com/nextcloud/server/issues/211#issuecomment-228307179), this is impractical. And it also doesn't cover people who find the Nextcloud client on their own and want to try it.

**Comment by mabkenar** [comment]
Let me clarify this proposal. We don't need to do any kind of endorsement or advertisement for the providers, hence no need for ranking/evaluation/etc. It's fine if it is merely a web link, with many (not just 3) providers listed. The list can be as neutral as the current list maintained by ownCloud [here](https://owncloud.org/providers/). 

We may even warn the users that this list is compiled only for your convenience and we don't take any responsibility about pricing, TOS, support, and the server quality. 

Nevertheless, if Nextcloud regularly charges money from providers to put them on that list, there is a good chance that non-maintained and poor-quality providers are naturally removed from the list, because there will be nobody to pay the charge.

**Comment by jancborchardt** [comment]
@mabkenar so I definitely agree we need to improve the flow. But a button directly next to the server address input I think is a bit confusing. Maybe a slideshow before just like on the iOS app, and then a choice of providers with »your own server« in it as well« is a good solution here.

**Comment by mabkenar** [comment]
@jancborchardt I've never seen the iOS app but I like the idea to show a slideshow the first time user runs the app. All the "education" part can be done in the slideshow, including a list (or a link to a list) of providers.

**Comment by tobiasKaminsky** [comment]
So, it is related to #50 
Can you @jancborchardt make a mockup for @przybylski ?

**Comment by jancborchardt** [comment]
It’s already in the branch `whatsNew`, see https://github.com/owncloud/android/pull/1375

**Comment by Gomez** [comment]
>For me nextcloud is all about my data on my server.
> So adding links to providers that can host the server for me is exactly the opposite and would look more like advertisement for me and maybe scares new user?

@tobiasKaminsky This is only valid for servers at your home. If you rent a server somewhere its almost the same as you rent a nextcloud. And SaaS has many benefits, especially for private users.

**Comment by tobiasKaminsky** [comment]
@Gomez you are right, it is just my personal opinion and it can be different for other users and for them such a list is a good idea.

**Comment by pierreozoux** [comment]
As a provider, I'm all for that also.

We (as FLOSS community) need to do better.

Imagine you managed to convince somebody that free software is the only way to make a world a better place.
Before he was using dropbox:
 - landing page
 - email/pass
 - bim, he got the service
You convinced him, he goes to Nextcloud:
 - landing page
 - call to action: "Download"

You lost, game over, we'll not convince the 99% like this.
We need a sane default for a user/pass experience.

We agree that there is a list of providers. This list has to be curated somehow. Maybe with some metadata like:
 - uptime
 - security
 - user feedback
 - language
 - Timezone
 - price

Nextcloud could say, ok, if you are in this price range, this uptime, and https, you get listed. Once listed, the android app could choose the "backend" based on language/timezone of the mobile, and if many provider, random.
This would mean the default server is choosen and we get a user/pass experience :)

Then, there is an "advanced" button, where you could specify which server you want from the list, or put your own.

But it is needed! Really nice to see this moving forward!

**Comment by jancborchardt** [comment]
@pierreozoux great stuff, good thoughts! :) The only thing I would do a bit different is that the apps should not choose the provider, but ultimately there should be a short list so people can choose themselves. Just getting a random provider will not make you feel at home at the service or like you’re in control. :)

So @Gomez @pierreozoux as you are providers and also involved in the community, would you like to lead the efforts on getting this onboarding forward? I’ll of course help with design and flows.

**Comment by mabkenar** [comment]
>  the apps should not choose the provider
I agree. While we make it easy for the users to find a provider, they should always be explicitly informed that they do have a choice in picking one. Even if we include top N providers in the list (based on uptime, user rating, timezone, etc.) there should always be a (N+1)-th item for "Choose other providers..." and (N+2)-th item for "Use your own server...".

**Comment by Gomez** [comment]
Count me in. @pierreozoux Will you help too? 
First step will be to get the provider list back on the website.

**Comment by jospoortvliet** [comment]
The provider list is on the website again. Please, @Gomez get me your details through https://nextcloud.com/providers/apply ;-)

We still have no way of rating providers, so a top-3 is hard. Yes, I'd vote for @Gomez but we'd need a transparent process imho and us picking here isn't really open or transparent ;-)

**Comment by Gomez** [comment]
thanks @jospoortvliet :) Done

A basic check for best practice installation could be that "Security & setup warnings" in the admin panel are all gone.

**Comment by mar1u5** [comment]
> A basic check for best practice installation could be that "Security & setup warnings" in the admin panel are all gone.

How do you want to check this 😁

**Comment by owndrive** [comment]
@jospoortvliet, @jancborchardt  @mar1u5 and others:
In our opinion, the long term providers of ownCloud should be given highest priority on the listing when they now also provide or migrate to NextCloud. 
OwnDrive has been providing ownCloud for quite some time and as far as we can tell, we have been providing proper free plans to users from day one and still keep doing it. By proper i mean the free offer is almost equal to other paid plans. This of course creates significant load on our infrastructure, but it's one of our way to give back something. 
This is in contrast to other providers that start out by providing free plans and all of a sudden stop such offers users depend on. 
Remember providers also contribute to making ownCloud/NextCloud more known to the world by different methods and thereby spreading the word.  We have seen customers getting involved with the community after using some of the apps we provide that they rely on :)
That said, in our opinion PortKnox, as a long term and reliable provider, should also be given the right priority. 
Such bigger providers can't over night start to migrate their infrastructure to NextCloud since it implies a whole lot of planning and testing prior to the final migration. In the meantime, it would also be totally unfair if we risk being placed at the very bottom of the NextCloud providers list. After all, there is little or no difference between current version of NextCloud and ownCloud 9.0.   

Our suggestion is therefore when providers listed at owncloud.org/providers need to be listed at nextcloud.com/providers, please use the same listing priority that is already in place.  
Otherwise it would be unfair.

Thanks.

cc @fossxplorer

**Comment by jospoortvliet** [comment]
@owndrive I agree we need some way of ranking, not based on who comes first. We have discussed this before, and the filtering on countries and free plans or not is a first step, something we could do easily as it is objective. The same goes for adding text, so providers can explain what they offer. But it gets more complicated with sorting providers. We've discussed picking a top-three but with what objective criteria? You will almost always make many people angry and only a few happy :8ball: 

We thought about letting users rate (but that is probably easy to game) or doing a survey (I tried but got little feedback). We can pick manually but that is so subjective...

Thoughts are welcome!

**Comment by jospoortvliet** [comment]
At least, for starters, we could make it random.

**Comment by mabkenar** [comment]
@jancborchardt 
> @mabkenar so I definitely agree we need to improve the flow. But a button directly next to the server address input I think is a bit confusing. Maybe a slideshow before just like on the iOS app, and then a choice of providers with »your own server« in it as well« is a good solution here.

Let's make this happen step by step, since this important UX issue is not fixed after a long time. 

**What does not work:**
- It seems that making a list of providers and selecting 3 top ones is too complicated; there are too many things to consider for selecting the top 3, and at the end some providers will always be angry.
- The welcome screen (as it stands [right now](https://github.com/nextcloud/android/pull/84#issuecomment-262634838)) gives no hint about finding a provider or setting up a server.
- @AndyScherzinger 's idea for prefilled links for the client doesn't seem to work in all cases (see [this](https://github.com/nextcloud/server/issues/211#issuecomment-228307179)) and also doesn't work for independent app installs (i.e. when someone discovers Nextcloud by their own in the app store).

The original idea was to help new random users in finding the server in the initial setup.

**What may still work as a first step,** tow options:
- update welcome screen to educate the user about the option of using third-party providers as well as their own server.
- put a link next to the text field "Server address" in the setup screen, something like this: 
![login_cropped](https://cloud.githubusercontent.com/assets/3006332/22082728/34382f20-ddc9-11e6-92f7-3a1561cc34ac.png)
and link it to the [providers page](https://nextcloud.com/providers/).

What do you think? Which one should we go for?

**Comment by jancborchardt** [comment]
@mabkenar great idea! :+1: The only thing I would change is adjust the button label and maybe place it elsewhere because otherwise it seems like a »locate server« button which is an action on the server address you put in.

How about saying in the footer:

> Don’t have a server yet? **[Get one from a provider](https://nextcloud.com/providers/)**

That’s similar to how other proprietary apps do it. cc @AndyScherzinger @tobiasKaminsky @jospoortvliet what do you think? It’s way better than the generic »New to Nextcloud?« link to the frontpage in the bottom. I mean … you already downloaded the app, so they are already deeper in the funnel.

**Comment by eppfel** [comment]
> Don’t have a server yet? Get one from a provider

This is a quick win and should be done, before we discuss anything more complex.
