### ISSUE TITLE
NextCloud client 1.4.0 cannot erase local files

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#533]
### Actual behaviour
Trying to erase a local file ends with an error. Deleting both files leaves the local file in place.

### Expected behaviour
Local file should get erased.
 
### Steps to reproduce
1. Files stored on a SD card
2. Try to erase a file.

### Environment data
Android version:
6.0.1
Device model: 
Huawei Y6II
Stock or customized system:
Stick
Nextcloud app version:
1.4.0
Nextcloud server version:
11.0.0.10
#### Web server error log
```
N/A
```

**Comment by Ertain** [comment]
I have found this behavior, too. I'm also using the NextCloud app version 1.4.0 on Android 6.0.1 (on a Nexus 7 tablet), and I can't delete the local files, either.

**Comment by AndyScherzinger** [comment]
Does this also happen with 1.4.1 RCs?

**Comment by Ertain** [comment]
I tried a recent version (a daily build) and it did work. FYI, the build was from January 11.

**Comment by AndyScherzinger** [comment]
@Ertain daily build as in ```master``` branch or the ```beta``` ?

**Comment by Ertain** [comment]
I think it's `beta`; I got it off of F-Droid, and the app was marked as `beta`.

**Comment by AndyScherzinger** [comment]
Ah. Well the beta is a second app sharing the same code basis but includes all feature complete changes (in review, not fully tested, etc.) and can be installed in parallel. So the info can't give a hint if the 1.4.1 RC fix for deletions is working since other changes might have fixed it for you ;)
As I said, you could also install the stable/RC too right next to it (should activate instant uploads in both though *g*)

Would you mind checking if e.g. 1.4.1 RC2 also works for you? 🙏

**Comment by Ertain** [comment]
I can try that, though where can I get it, exactly?

**Comment by AndyScherzinger** [comment]
Also on f-droid :) 
https://f-droid.org/repository/browse/?fdfilter=Nextcloud&fdid=com.nextcloud.client

**Comment by elpraga** [comment]
It didn't install in my case. It just ended up with a message "application not installed". It was going to update the 1.4.0 from play store, but it didn't go through 

Unfortunately I don't have time today to uninstall the app and regenerate all the application codes..

**Comment by AndyScherzinger** [comment]
@elpraga you can alternatively join the beta program on Google Play which unlocks the RCs and is not linked to "real"  beta!

**Comment by Ertain** [comment]
As I mentioned, I used the `beta` version on F-Droid, and that version worked for me.

**Comment by elpraga** [comment]
@AndyScherzinger , just joined the beta program on Google play, and I can confirm that on 1.4.1 RC3 deletes files correctly as expected. 

Do I understand it correctly that the beta program on Google play receives RCs? In your opinion is it reliable enough for everyday use or would you rather recommend going back to the stable?

**Comment by AndyScherzinger** [comment]
@elpraga yes, the Google beta program just ships stable and RCs. 
Usually I'd say the RCs are rather stable but the RCs give us the opportunity to tackle the fragmentation is as in number of different devices/Android-versions/Server-versions/setups which we can't test ourselves. Sometimes there are issues like we had in RC1 and also in early RCs of 1.4.0. Postive thing is that if the stable has bugs that are fixed in an upcoming release which bug you then RCs get you the fixes sooner rather than later. 
As a general rule I#d say you are save with the RCs. If you want to be super save I#d say it is a case by case decision as in: stay with the stable, if you have any issue which blocks/annoys you and you know it'll be fixed in the upcoming version then temporarily move to the RCs. For "production use" I'd say: stable only.

**Comment by elpraga** [comment]
Thank you for explaining Andy! I'll try to stay in beta program and help some of the bugs squeeze.
