### ISSUE TITLE
creating files with special characters fails

### ISSUE THREAD

**Issue by jakejoh** [nextcloud/android#5416]
### Steps to reproduce
1. Create any kind of file (e.g. .md, .xlsx...) with special characters (e.g. "Grüße")
2. Error "Error creating file from template"
3. File is created nonetheless (characters replaced by "?"), but can neither be opened not deleted.

### Environment data
MIUI 11.2 (Xiaomi.eu, Android 10-based) on Mi 9T
Nextcloud app version: 3.10.1

Nextcloud server version: 18.0

### Logs (from admin panel, deleting file)
> Error
> 
> remote
> 
> 2020-02-06T13:56:36+0100
> 
> Exception: The requested uri(/remote.php/webdav/Meine%20Dokumente/gr%3F%3Fen.xlsx) cannot be processed by the script '/remote.php/webdav/Meine Dokumente/gr??en.xlsx')
> 
> /var/www/virtual/username/meinenextcloud/lib/private/AppFramework/Http/Request.php - line 808: 
> 
> OC\AppFramework\Http\Request->getRawPathInfo()
> 
> /var/www/virtual/username/meinenextcloud/remote.php - line 127: 
> 
> OC\AppFramework\Http\Request->getPathInfo()

### Log (creating file)

> Warning
> core
> 2020-02-06T13:49:37+0100
> normalizing failed for "files/grüße.md"

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky, maybe another encoding issue?

**Comment by mr-bolle** [comment]
### Steps to reproduce
1. Open Nextcloud Android App
2. Create a new Spreatsheet Document
3. Enter the Name (first no Template available, later Error Message **Error creating file from template**

## with special characters
<img src="https://user-images.githubusercontent.com/22414212/75614553-385bea00-5b3a-11ea-8864-71367d7546cd.jpg" alt="Screenshot_20200229-204435_Nextcloud" width="450"/>

<img src="https://user-images.githubusercontent.com/22414212/75614551-37c35380-5b3a-11ea-9b7d-184d13c7cbb2.jpg" alt="drawing" width="450"/>

## without special characters

<img src="https://user-images.githubusercontent.com/22414212/75614958-54618a80-5b3e-11ea-845d-1c9295994e6e.jpg" alt="drawing" width="350"/>

<img src="https://user-images.githubusercontent.com/22414212/75614970-65aa9700-5b3e-11ea-9eb7-0ac2396340cc.jpg" alt="drawing" width="350"/>


### Expected behaviour
Create a new Document File, and after give them a Name (with special characters ex G**ä**ste] a empty File will be opend. 

### Actual behaviour
Im not able to create new Document Files over the Android App. **If i give the file the Name ex. test.xlsx this behavor not exist**.


## Server configuration detail

**Operating system:** Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** nextcloud:latest

**Where did you install Nextcloud from:** [official Docker Image]

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.9
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.raiko.ddnss.de"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "overwrite.cli.url": "http:\/\/nextcloud.raiko.ddnss.de",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** 

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```



```
</details>

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky
