### ISSUE TITLE
Integrate Calender and Contacts better

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#5421]
### Is your feature request related to a problem? Please describe.
The integration of Calender and Contacts is at this point of time not so user friendly and complete:
1. Installing a seperate App (davx5)
2. Configure this app and give your credentials once again
3. No Push Sync on change
4. The general nextcloud functions are missing: Share a calendar/contact list, Invite a nextcloud user on a meeting, ressource booking, free/busy view, 

### Describe the solution you'd like
My proposal after reading https://github.com/nextcloud/android/issues/4691 is to implement Calender and Contacts (if installed on the Server) as webview in the Android App. Like tutanota and fastmail doing it.

### Describe alternatives you've considered
Working with davx5 or using a mobile browser

Thanks for your work!

**Comment by jakobroehrl** [comment]
@jancborchardt @stefan-niedermann 
What are your thoughts about this?

**Comment by stefan-niedermann** [comment]
I have no strong feelings about this one. About your 1. point: Personally i think "do one thing and do it well" - DavX5 is already there and works great for me. I also see no need to integrate notes, deck, news and all into the main app. So why contacts and calendar?

- Maybe one can open issues for them to use SSO when nextcloud is installed for a better UX?
- Maybe one could also reuse the sync code, but this would cause huge maintenance and support efforts and would be a bit unfair since they are selling the app and want to earn a few bucks, too...

Webviews always provide a bad UX imho and are missing native integration into contacts and calendar apps, therefore 👎 from me for that idea.

**Comment by jakobroehrl** [comment]
Let's close it for now, it's working good with dav
