### ISSUE TITLE
Activity Tab visible though deactivated? No comments Tab?

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/android#5463]
### Steps to reproduce
1. Deactivate Activity on nextcloud-server
2. Click on details of any folder/file in nextcloud-android
3. Activity tab still visible
4. Comments Tab not visible

### Expected behaviour
- Activity Tab should not be visible
- Comments Tab should be visible 

### Actual behaviour
- Activity Still visible
- Comments Tab not visible

### Environment data
Android version: 7.1.2

Nextcloud app version:3.10.1

Nextcloud server version: 18.0.1

nextcloud server:

![Bildschirmfoto_2020-02-13_11-49-56](https://user-images.githubusercontent.com/12480617/74427693-dd4aa780-4e57-11ea-9a5a-8adacf73545a.png)

nextcloud-android:

![Screenshot_20200213-115112](https://user-images.githubusercontent.com/12480617/74428109-ab861080-4e58-11ea-870e-067c8608b7bd.png)

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @jancborchardt @nextcloud/designers I am not sure about the expected behavior. According to the screenshots sharing is shown for web and Android. COmments are part of the Activity tab, so that is just fine in my opinion.

**Comment by tobiasKaminsky** [comment]
In long term we want to have a combined activity/comment stream also on web, so I did this already on Android.
To be honest, it is kind of a hack as it only shows activity stream, which also includes comments.

So for now, until this is also changed on server, we will stick to this.
As a drawback you have to keep activity enabled.

**Comment by ochealaaf** [comment]
Hi, I read this thread and it made me quite unhappy. I am voluntary administering some nextcloud installations for schools. For reasons of confidentiality it was decided to deactivate the log of activities because this content cannot be fine tuned regarding its access rights.

So as a consequence those students using an iphone can comment and discuss their homework with their teachers (because there is a separate comment tab), those using an android device see nothing (as described above) and they are not able to participate. 

Mixing up activities with comments does not seem a good idea to me and I would appreciate very much if you could re-evaluate this issue, hopefully reopen it by adding the same comment tab as in the ios app where it is working perfectly fine.
