### ISSUE TITLE
nextcloud android application error

### ISSUE THREAD

**Issue by jvvarghese** [nextcloud/android#5514]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@jvvarghese please add some information to the report, like what happened, error message, stack trace etc. 🙏

**Comment by AndresJ551** [comment]
Hello, I don't want to create another ticket so I'm reusing this because it seems empty and the title describes the error I'm having:

### Steps to reproduce
1. Install Nextcloud App from the Play Store.
2. Open the Nextcloud App and login to local Server.
3. Enjoy the crash.

### Expected behaviour
- It should open the app without crashing.

### Actual behaviour
- As soon as the Server's address is added the app crashes.

### Nextcloud log (data/nextcloud.log) {Not much, mostly local usage, not from the APP.}
```
{"reqId":"3gHT9liqptWhcm7VRVmX","level":2,"time":"2020-02-28T04:17:47+00:00","remoteAddr":"192.168.1.6","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Login failed: admin (Remote IP: 192.168.1.6)","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}
{"reqId":"6LuVfBIK9qHaXaoD2AGh","level":2,"time":"2020-02-28T04:23:16+00:00","remoteAddr":"192.168.1.6","user":"andres","app":"appstoreFetcher","method":"GET","url":"/settings/apps","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 514688 out of 4452141 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}
{"reqId":"KK6Fze7FPYT9BkHXBhOf","level":2,"time":"2020-02-28T04:23:29+00:00","remoteAddr":"192.168.1.6","user":"andres","app":"appstoreFetcher","method":"GET","url":"/settings/apps/list","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 950272 out of 4452141 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}
{"reqId":"KK6Fze7FPYT9BkHXBhOf","level":2,"time":"2020-02-28T04:23:39+00:00","remoteAddr":"192.168.1.6","user":"andres","app":"appstoreFetcher","method":"GET","url":"/settings/apps/list","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 922688 out of 4452141 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}
```

It seems like the Android App is not even trying to connect to the server.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@d35b4fa
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=9405, uid=1010171 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3863)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1358)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1411)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:23082)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3523)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: PLE
Model: TA-1039
Id: PKQ1.181105.001
Product: TA-1039_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_6_17H

Thanks, love the nextcloud server so far!

**Comment by AndyScherzinger** [comment]
@AndresJ551 are you by any chance using "Android for Work" (since the stack trace point into that direction), which isn't supported by the app.

**Comment by AndresJ551** [comment]
Hi! Thanks for the fast response,
I'm not familiar with that version of android:
https://micronotas.cl/images/Android_Screen/android_nokia.jpeg

With "Android for Work" do yo mean the android profiles?:
https://micronotas.cl/images/Android_Screen/android_nokia2.jpeg

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see comments above "Android for Work" == Profiles ? To me it looks like the profiles lead to the issue as shown in the stack trace

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky see comments above "Android for Work" == Profiles ? To me it looks like the profiles lead to the issue as shown in the stack trace

Yes, could be the same problem…
But I am unsure how to resolve it, as this might be a problem of Nokia? For Android for Work I can only test it with MDM…

I tested it with two profiles on Android 10 and it worked…

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
