### ISSUE TITLE
Sidebar menu redesign

### ISSUE THREAD

**Issue by mario** [nextcloud/android#556]
I am aware of the ongoing discussion regarding the menu redesign, and I'm opening this issue to both get an understanding of the current state of things, as well as clarify the new features I need to implement so we can all see how it'd work together.

My suggestion:
- Remove All files and On device from the sidebar menu
- Add a footer on the page with a filter icon in the left corner which would open a filter page (and contain "All files" and "On device" (among others). Since filter is whole other issue, we'll discuss this elsewhere.
- The top menu items would be:

- Home (webdav root)
- Favorites 
- [Photos](https://github.com/nextcloud/android/issues/556#issuecomment-273897162)

- Activities
- [Notifications](https://github.com/nextcloud/android/issues/559)
- Uploads

- Settings
- Participate

I will open an issue for both activities and notifications separately, but maybe @karlitschek or @MorrisJobke can clarify the Photos - would it simply open a "Photos" directory (should the item be removed then if the user removes the dir) or will it show all photos on your instance? (in that case, I assume search API will be useful here - just need to know which extensions to use for searching).

@nextcloud/designers - your input is more than appreciated.

Also involving @AndyScherzinger and @tobiasKaminsky

**Comment by jancborchardt** [comment]
Gooood stuff! :)

So I don’t think this is as radical as you describe it:

- »Home« will just be like the old »All files«. And I’d prefer if we call it »All files« just like we do in the web interface
- Activities, Notifications and Uploads should be one and the same view. The mistake to split them up was made in the desktop client and it’s sooo confusing to have so many views for the same thing: chronological info.
- »Shared« is an entry we need, which shows a flat list of all elements shared by you, to you, or by link. (Not separate like on the server, we need to keep stuff simple and quickly accessible here.
- Photos could be a simple filter on everything which only shows the photos, and defaults to the grid view.
- Settings and participate are already there and will stay like now. :)

**Comment by mario** [comment]
@jancborchardt hehe. So will "All files" revert to webdav root anyway (because if it is, it's not the same way as currently)? I'm all for having one view for activities, notifications and uploads - but I'd appreciate a mockup of how this should look before I actually start working on this.

Shared - do you have any knowledge about the server side of this? (API and stuff) Maybe @MorrisJobke can shed some light on this? :)

Thoughts on the filter positioning as I've described it?

**Comment by tobiasKaminsky** [comment]
> @jancborchardt Activities, Notifications and Uploads should be one and the same view

We should rethink this as in the current uploads view you have options like "retry failed", "delete failed", "delete successful", "remove all".
This will conflict with activities/notifications.

**Comment by tobiasKaminsky** [comment]
> Add a footer on the page with a filter icon

the footer of the navigation drawer/sidebar is currently used for displaying the quota (if available)
![screenshot_20170119-173055](https://cloud.githubusercontent.com/assets/5836855/22115463/5bbf61c2-de6d-11e6-88c0-eb387917a1fe.png)

**Comment by mario** [comment]
@tobiasKaminsky I meant the main screen, not sidebar.

**Comment by tobiasKaminsky** [comment]
> @mario  Shared - do you have any knowledge about the server side of this? (API and stuff) Maybe @MorrisJobke can shed some light on this? :)

This is an overview issue which should only target the restructure of the navigation drawer. Any questions/ideas regarding the "content" like "Shared" or "Photos" should be taken into a new issue which is then linked to this one

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky I meant the main screen, not sidebar. [Filtering position]

I would not take away space to add a footer. Instead I would put it in the overflow menu (three dots in the upper right corner) as it is an option related to the file list

**Comment by mario** [comment]
@tobiasKaminsky we can definitely discuss this - I think the menu is becoming overwhelming as-is anyway, and you need somewhere to show how is the list being filtered (and footer is a good place to put it).

**Comment by MorrisJobke** [comment]
> Photos could be a simple filter on everything which only shows the photos, and defaults to the grid view.

Correct. 👍 

> Shared - do you have any knowledge about the server side of this? (API and stuff) Maybe @MorrisJobke can shed some light on this? :)

We have an OCS API for all incoming/outgoing shares of an user: https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html

> We should rethink this as in the current uploads view you have options like "retry failed", "delete failed", "delete successful", "remove all".
> This will conflict with activities/notifications.

Yes. I would also like to keep them separate. Uploads is really only relevant for this device and has very little to do with the other activities on the server.

**Comment by tobiasKaminsky** [comment]
Upload view should stay separate.
But maybe we can combine notification and activity view?

So we need extra issues for 
- photo view
- share view

**Comment by MorrisJobke** [comment]
> photo view

Photo view is basically what we already have: the grid view of photos.

**Comment by eppfel** [comment]
In #559 I propose to ditch a notifications from any view inside the app.

> I actually think, when we integrate the notifications in Android natively, is there still the need to show them in any view inside the App? Choosing to act on the notification should directly transfer to it's content: Incoming call: open spreed.me, Update available: open admin settings, etc.

**Comment by eppfel** [comment]
> »Home« will just be like the old »All files«. And I’d prefer if we call it »All files« just like we do in the web interface

The Android sidebar is not similar to the files sidebar in the web application (Participate, Activity, dynamic menu item, ...) . All the option in the files web app will/should be filters, inside "All files". Therefore I think we should call it, just "Files".

**Comment by AndyScherzinger** [comment]
I agree with @eppfel's idea to simply call it "Files" 👍

**Comment by jancborchardt** [comment]
Here’s what @mario and I talked about for the sidebar:

- **All files**: Always shows the root of all files when clicked. Important to name it »all« because the other entries like favorites etc. are also files.
- **Activity**: Merged Activity & notifications etc, much like the unified timeline in the sidebar of files https://github.com/nextcloud/server/issues/658. Most of these entries will at some point be interactive, like accepting a share, reverting to a version, or commenting etc. Actionable items like failed uploads or shares to be accepted will be shown up top. They will be separated by intermittent headers:
	- **Failed uploads** is first cause it’s local and most important cause it can lead to data loss. Will have a »Retry« and »Clear« in the header with text+icons. Then icons for each individual item.
	- **Requires attention** (working title) are the notifications and activities with interactivity which come from the server. For example incoming shares you need to accept. (Or in the future comments where you were mentioned with an action to reply.)
	- **Activities / History** where all the activites go in the end, and where also the things you act upon from **Failed uploads** and **Requires attention** go to → which is a big reason why this is a single view instead of separate ones. It’s the same things.
- **Favorites**: Just like on the server, showing all favorites. Clicking it always shows the flat list of favorites.
	- Opening a favorite folder should open the folder as a normal list of files, including non-favorites.
	- Because the favorites are already nicely sorted up top https://github.com/nextcloud/android/pull/302
	- Search will filter this view, so only show favorites. In the future we could show results from other places below, but that’s for a future version.
- **Photos**: Flat list of photos, sorted by most recently modified first and with the grid view by default.
- **Shared**: All files shared by you, with you, and by link, in a single flat list. This will be a future thing since we don’t have that at all at the moment.
- **On the device**: Like now. But it should really show every file which is already downloaded and viewable offline, not only what has been marked as »available offline«.
- **Auto upload**: Like in master already.
- List of links: Because a customer requested to insert an arbitrary number of links here. This would only be in combination with a server app and is not part of the default UX. cc @MorrisJobke
- **Settings**: As now.
- **Participate**: As now.


@eppfel @AndyScherzinger @tobiasKaminsky will anyone of you be in Stuttgart at the hackathon today or tomorrow? It’s always easier to talk in person about this.

**Comment by AndyScherzinger** [comment]
Unfortunately no....day job....

Two questions though:
* Favorites: At the moment the thing (on the Android client) that looks like favorites is actually "available offline" which marks files to be kept in sync with the server, while the server side favorites are more like bookmarks. My question is: Should we keep it this way because we decide that a user who wants to have a file as a favorite also wants it to be kept in sync (always) - which would be my guess btzw.
* List of links: should this be one menu item which then shows a list of links, a hierarchy of links (one menu item "Links" which acts like a collapse-able, all links flat? I would suggest not to go for the 3rd option since this might lead to a very long menu list where the user would have to scroll all the time and that seems impractical (but I am not a UX guy).

**Comment by jancborchardt** [comment]
> Favorites: At the moment the thing (on the Android client) that looks like favorites is actually "available offline" which marks files to be kept in sync with the server, while the server side favorites are more like bookmarks. My question is: Should we keep it this way because we decide that a user who wants to have a file as a favorite also wants it to be kept in sync (always) - which would be my guess btzw.

I totally agree with that. I was always against separating this because it introduces another layer of complexity and it resulted in us still not having the simple synced favorites.

> List of links: should this be one menu item which then shows a list of links, a hierarchy of links (one menu item "Links" which acts like a collapse-able, all links flat? I would suggest not to go for the 3rd option since this might lead to a very long menu list where the user would have to scroll all the time and that seems impractical (but I am not a UX guy).

This would be a flat list of links directly in the sidebar, as I understand from @MorrisJobke @mario. I guess we can make it collapsible, right? Again, this is mainly for a customer and will not be part of a default installation (basically it would be a config option of some sort).

**Comment by mario** [comment]
@jancborchardt since this is a client requirement I'd say just put the links there without the "collapse" action - if they're silly enough to put 10 links in there, let them be. Collapsing in a sidebar is a bit no-no for me.

**Comment by jancborchardt** [comment]
Btw @AndyScherzinger the specific issue is https://github.com/nextcloud/android/issues/555

@mario agreed :)

**Comment by AndyScherzinger** [comment]
@jancborchardt sounds good :+1:

**Comment by MorrisJobke** [comment]
> List of links: Because a customer requested to insert an arbitrary number of links here. This would only be in combination with a server app and is not part of the default UX. cc @MorrisJobke

Yes. As already stated: flat list (only title and url), no collapsing and will be provided via an OCS api endpoint (and a capability flag) by an dedicated app.

**Comment by AndyScherzinger** [comment]
![device-2017-03-31-014716](https://cloud.githubusercontent.com/assets/1315170/24530706/094d89b8-15b4-11e7-9747-ed404f57611c.png)

actual master, work in progress :)

**Comment by jancborchardt** [comment]
Is there a new issue already about consolidating Activity & Notifications? :) Let’s not forget that for the future. ;)

**Comment by mario** [comment]
No, feel free to create it.
