### ISSUE TITLE
File search

### ISSUE THREAD

**Issue by mario** [nextcloud/android#558]
Implement file search which would be similar to what the server frontend does. I'd definitely like to know more about this so involving @MorrisJobke, @tobiasKaminsky and @AndyScherzinger. Feel free to suggest whoever you think can clarify more on the API (endpoints, data to send, returned data) and the requirements of this task.

@nextcloud/designers - I'd appreciate your input and mockups on how this should work.

**Comment by jancborchardt** [comment]
Regarding interaction design, it should be the same as the search we do right now. But instead of only filtering the current folder (which should of course be prioritized to be very quick) other folders should be searched too. Basically exactly like we do on the server.

**Comment by tobiasKaminsky** [comment]
@jancborchardt two more questions:
- filtering is immediately, but searching should have either a) some delay or b) require user interaction as it is data intensive and maybe not wanted by the user?
- should search also be in the navigation drawer (I think yes, as it promotes this feature).

The search results should show a list with
- name
- folder name
- when clicking on it it should directly open this file (just like clicking on it in the file list)
- long clicking on the file should show "go to folder" (?)

as reference the current web view:

<img width="1254" alt="bildschirmfoto 2017-01-11 um 14 52 07" src="https://cloud.githubusercontent.com/assets/5836855/22114934/60bd2878-de6b-11e6-98d6-353d82cdac26.png">

search api will be done by @MorrisJobke

**Comment by tobiasKaminsky** [comment]
For server tracking: https://github.com/nextcloud/server/issues/676

**Comment by eppfel** [comment]
> should search also be in the navigation drawer (I think yes, as it promotes this feature).

Actually, when I open files, there is a nice search icon beside the three dot menu. This is most prominent. IMO no need for cluttering the sidebar with another option.

---

@mario in #556 :
> I think the menu is becoming overwhelming as-is anyway, and you need somewhere to show how is the list being filtered (and footer is a good place to put it).

I would rather introduce a second bar on the top, than a footer for this. And we have to think about the amount of filters, because I fear we won't fit them horizontally anyway.

Do we need a dedicated issue for filter view?

**Comment by tobiasKaminsky** [comment]
> Do we need a dedicated issue for filter view?

Yes please!
Please always only one topic per issue (and later also only one issue per PR).

**Comment by supportreq** [comment]
@mario @tobiasKaminsky on the android app we already have a filter which will search only in the opened directories. for the time being can we have a way in which we can atleast filter in all folders and not just the folders which are opened by the user.. This is an important feature which is pending since years and with filter the major searching file pain is resolved.. please share your thoughts..

**Comment by mario** [comment]
@supportreq I've implemented the feature you requested as a playground, but really the best way to go forward with this is proper search based on the server API so that's the only thing that will go in the app. I'm hoping we can have this in for 1.5, but no promises. Once the actual search works, I am sure you will be more than happy with it.

**Comment by tobiasKaminsky** [comment]
@supportreq a "deep filter" like you suggest is not working as e.g. the sub-sub-folder might already have changed on the server and the app is not in sync with it, or imagine that someone is sharing a folder with you. In both cases the app will only "know" once you have entered these folders.
So the only valid solution is to use a real server-wide search like on the webUI.

**Comment by supportreq** [comment]
@mario with the server api now live are we having an integration soon?

**Comment by mario** [comment]
Will be done for 1.5.0

**Comment by jancborchardt** [comment]
@tobiasKaminsky regarding your questions:

> filtering is immediately, but searching should have either a) some delay or b) require user interaction as it is data intensive and maybe not wanted by the user?

It can have some delay, but should be in the same view, below the other results, as it is on the server. No extra user interaction. It’s not sooo data intensive as it’s only a list of files, right?


> should search also be in the navigation drawer (I think yes, as it promotes this feature).

No, as it’s in the header already. As @eppfel said too.

> The search results should show a list with
> - name
> - folder name

Yep, second line will be folder path instead of the size and modified date info as normally. But same layout/design. Only show the folder path in the second line, not repeat the file name (also needs to be fixed in the server, issue opened).

> - when clicking on it it should directly open this file (just like clicking on it in the file list)

Yes.

> - long clicking on the file should show "go to folder" (?)

Long-clicking should initiate multiselect I’d say, as usual. :) No reason it shouldn’t work on search results either, like if you want to delete a bunch of searched files.

Every search result will also have the 3-dot-menu for the actions, and in there should be »Go to folder«. For folders of course this doesn’t need to be there.

Sounds good?

**Comment by tobiasKaminsky** [comment]
@jancborchardt thanks for clarifying, although @mario will probably do the most of the implementation ;-)

**Comment by mario** [comment]
Any of you two @tobiasKaminsky and @AndyScherzinger have time to do the library side of things while I work on other issues? 

https://github.com/nextcloud/server/pull/3360

**Comment by AndyScherzinger** [comment]
Uuh sweet. Never actually did any library work myself related to connect new interfaces or extend existing ones :/ - @tobiasKaminsky could you cover this area?

**Comment by mario** [comment]
I would appreciate it.

**Comment by MorrisJobke** [comment]
PR:

* main #3360
* favourite search #3772
* fix ordering #3824

Pending issues:

* [x] #3815

**Comment by MorrisJobke** [comment]
PR: https://github.com/nextcloud/android/pull/742

**Comment by supportreq** [comment]
@MorrisJobke @mario is this working? by when can we test it in beta release..

**Comment by mario** [comment]
@supportreq I don't know, hopefully soon. It works, but there are a bunch of small issues unrelated to the search itself that are really, really hard to debug.

**Comment by AndyScherzinger** [comment]
how should we progress here? #742 has been implemented, does it cover everything or parts of this requirement still open? cc @mario

**Comment by mario** [comment]
@AndyScherzinger all done as far as this issue goes.

**Comment by supportreq** [comment]
@mario I am on the Android Dev Build from F-droid... i m not sure if search entire server is implemented on that build [server version is 12 final release].. can you confirm..

**Comment by mario** [comment]
It should be working in v12. Is it not? What's the issue?

**Comment by supportreq** [comment]
@mario somehow it didnt work on wifi but on mobile data it is working.. taking some time to get the list though

**Comment by mario** [comment]
That sounds strange @supportreq ? Why would it not work on wifi, but work on mobile?

**Comment by supportreq** [comment]
Uploading files is also returning with connection error on wifi [using browser it is working]

mobile data it works fine..

**Comment by mario** [comment]
o.o

Do you have a special wifi connection? Capture portal or something?
