### ISSUE TITLE
Unreadable color on dark mode

### ISSUE THREAD

**Issue by Dragnucs** [nextcloud/android#5656]
### Steps to reproduce
1. Change to dark theme
2. Go back to main screen

### Expected behaviour
- HeaderBar and some other components should display text with with or a light color on dark blue.

### Actual behaviour
- HeaderBar and some other components display text in black on dark blue making difficult to read.

### Environment data
Android version: 9

Device model: Redmi note 7

Stock or customized system: Stock

Nextcloud app version: 20200311 (Dev branch)

Nextcloud server version: 17

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
N/A
```

### Screenshot
![Screenshot_2020-03-13-13-22-38-157_com nextcloud android beta](https://user-images.githubusercontent.com/6125772/76621026-6243e200-6526-11ea-84e3-5c29669428bb.jpg)

**Comment by szaimen** [comment]
@Dragnucs I guess this is the manually set dark mode? System default should work fine...

**Comment by szaimen** [comment]
This is probably the same issue like https://github.com/nextcloud/android/issues/5346 which was closed but actually not solved.

**Comment by AndyScherzinger** [comment]
> which was closed but actually not solved.

@szaimen did you actually test 3.11.0RC2 before making this statement? (because if so then the issue needs to be reopenend!)

**Comment by szaimen** [comment]
@AndyScherzinger yes, I am currently on 3.11.0 RC2 and the issue still persists:
1. set theme to dark mode (not system default)
2. now the font on the top is dark but should be white
3. open a folder -> the back button changes to white

But I think this issue here is describing the problem better, so I think it doesn't have to get reopened.
Because I think I haven't outlined good enough that the real problem was that the font changes to dark if manually set to dark mode.
