### ISSUE TITLE
Server URL Autocomplete.

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#5677]
Feature request already opened at https://github.com/nextcloud/ios/issues/1186

**Comment by joshtrichards** [comment]
Interesting idea but closing for now for the following reasons:

- it hasn't gained any traction in either repo after being visible for 3+ years
- QR codes are an option for some use cases
- there are almost certainly some standards based ways of accomplishing something like this rather than reinventing the wheel
- original poster disappeared from GitHub 

Also see https://github.com/nextcloud/ios/issues/1186#issuecomment-600080848

We can always reopen later if someone comes up with a reasonable proposal. 

P.S. I'd also suggest starting it at the server repo not the clients, but that's just my opinion.
