### ISSUE TITLE
Videoplay problem

### ISSUE THREAD

**Issue by matze2090** [nextcloud/android#5852]
I have the problem that MP4 videos are no longer played in the Nextcloud app.  I have also tried with other players.

**Comment by tobiasKaminsky** [comment]
Are those downloaded or streamed?

**Comment by szaimen** [comment]
@tobiasKaminsky You can of course use the account that I've sent to you to debug this issue as well.
I uploaded a mp4 video file of around 200MB to the testaccount which is playing fine but needs around 2min or so to start the playback with the app. Since there is no problem in the browser I think this is also a nextcloud android app bug...
BTW: with that file the stream option doesn't work as well (also if first downloaded)
But the open with option with vlc is fine.

And if I download the file first, then playing with the nextcloud android app works without flaws.

**Comment by szaimen** [comment]
ping

**Comment by szaimen** [comment]
Ping

**Comment by szaimen** [comment]
Ping
