### ISSUE TITLE
Remove mail_feedback

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/android#59]
There is the mail_feedback thingy implemented which goes to apps@nextcloud.com, this mail address is not routed at the moment.

I'd advise that we maybe link them to our bug tracker or a new category in our forum instead. Any thoughts?

cc @nextcloud/android

**Comment by AndyScherzinger** [comment]
I would then probably go for the forum. 

ATM it is named feedback so the forum seems to be more appropriate, barrier in comparison to mail though is the fact that you need to register (same would apply for GH) while you don't for mail.

**Comment by LukasReschke** [comment]
> ATM it is named feedback so the forum seems to be more appropriate, barrier in comparison to mail though is the fact that you need to register (same would apply for GH) while you don't for mail.

Yeah. Though we support all kind of social logins… Twitter, Facebook, GitHub, Google etc. on our forums :-)

So let's change it to the https://help.nextcloud.com/c/feature then ?

**Comment by AndyScherzinger** [comment]
Works for me, so yes let do that :)

**Comment by tobiasKaminsky** [comment]
This is ok, but the beta allows to send the crash report and some users suggested to have a predefined email address.
So this should be done, something like: android-app@nextcloud . com?

**Comment by AndyScherzinger** [comment]
@LukasReschke for the beta a good way would be to keep it, have the mail alias forwarding the mails to Tobias and me so we can check it out and open beta issues

**Comment by AndyScherzinger** [comment]
@LukasReschke we now also have this as review in the play store
>The Help button does not work. It leads to the home page, where there is a "page not found" error is. Then I will send feedback via e-mail, but the registered address is unreachable. ???

Should we then just use the forum link or:
* Help --> https://help.nextcloud.com/c/feature
* Feedback --> google@nextcloud.com (since this is also visible on the play store app page?)

Else we would have to go for just one item in the settings "Help / Feedback" which routes you to  https://help.nextcloud.com/c/feature

This is a bug so I rate it high prio and we should schedule it for 1.1.0 stable or 1.1.1 but would rather say it is a minmal impact, easy to test change so I recommend putting it into 1.1.0 stable. Any opinion on this @tobiasKaminsky ? Anyhow we should still keep the mail setting internally to be used in the beta :) But replace it with google@nextcloud.com

**Comment by tobiasKaminsky** [comment]
Solution (1) is fine for me.
Are you reading this forum? Ore do we should also include github issue tracker?

**Comment by tobiasKaminsky** [comment]
Better email address is: android@nextcloud.com

**Comment by tobiasKaminsky** [comment]
Talked with @LukasReschke: we get android@nextcloud.com which is maintained by him, @AndyScherzinger and me.

**Comment by tobiasKaminsky** [comment]
Please see #86
