### ISSUE TITLE
Android auto upload never triggered

### ISSUE THREAD

**Issue by ctkcoding** [nextcloud/android#5947]
### Steps to reproduce
1. Open nextcloud app and navigate to sidebar option "auto upload"
2. Configure settings for a folder to upload
3. Save settings to upload existing files regardless of wifi and charging states
4. enable auto upload for desired folder
5. Files do not upload even after refresh, force stop & reopen, etc
6. To test connection, I uploaded a new file on another client & refresh on Android. I also tried uploading a photo from camera on my Android & refreshing on other client. files propagated in these scenarios but auto upload still did not trigger

### Expected behaviour
- files should be immediately scanned and uploaded

### Actual behaviour
- no auto upload was ever triggered

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
3.11.1,

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ctkcoding** [comment]
Also - I have excluded nextcloud from battery optimization
![Screenshot_20200427-195225](https://user-images.githubusercontent.com/43896808/80431884-aa457b00-88c0-11ea-83c0-ca2387d4be3f.jpg)

**Comment by tobiasKaminsky** [comment]
> Android version:
> 
> Device model:
> 
> Stock or customized system:

Please give us this info

**Comment by GnaXi** [comment]
Having the same issue as the guy above.
Android version: 9
Device model: OnePlus 5T
Stock system, OxygenOS

I have another OnePlus device. OnePlus 6T running Android 10 and it is working just fine on that one.

**Comment by tobiasKaminsky** [comment]
Damn…I then fear that this is a OP 5T / Android 9 related problem…
Do you see anything in logcat?

**Comment by GnaXi** [comment]
@tobiasKaminsky False alarm! :)
Today it all of a sudden started uploading. I have no idea what the issue could have been, as I tried installing, setup and reboot several times without success.
Could it be that the Nextcloud server was busy? I've just recently set it up and had several other clients syncing a lot of data to the server at the same time?

**Comment by tobiasKaminsky** [comment]
Hm. Server should not matter, at least all uploads should show up an upload queue.

**Comment by ternite** [comment]
I have this problem, too.
Android version: 9.1.0
Device model: HUAWEI P30 Pro
Stock system

I installed the client a few days ago, connecting it to a NextCloudPi instance running in my house. I activated Auto Upload for my photos, and first wondered, because no upload started. I then took a photo, and from then on the App started to upload photos as expected. There were several suspicious pauses but finally all files were uploaded successfully.
After all photos were transferred, I noticed that videos were not included and I added another auto upload configuration for my videos. This upload never started in the last two days. Worse, new photos don't get uploaded now, too.
I deactivated battery optimization for the NextCloud app, as I was instructed while entering said settings. (Additional info: the info that battery optimization must be deactivated is even shown, when it already IS deactivated. This is irritating, as the user is lead to the thought that he did something wrong before.)
I checked if there may be any connection issue with the server, but it is running and can be operated from the web client both as a normal user, as well as admin. 
Best regards
Thomas

**Comment by ternite** [comment]
I knew it would be good to report this. Everything was uploaded tonight.
I have no idea why it took the NextCloud app several days to start the upload process.

**Comment by DD8372812** [comment]
I do have this problem for a while too. My system: OnePlus 3T, LineageOS 17.1, Connection through OpenVPN to my home network, where Nextcloud is hosted.

How is the wifi-check technically implemented?

**Comment by nicbou** [comment]
I have the same problem. _Old_ photos won't upload. If I open the camera and take a picture, it gets uploaded. I can't find any way to trigger the upload of old files.

Here's what happened, as I recall it:

1. I installed the app and turned sync on for many photos
2. I changed the upload destination some time after the upload started
3. The app kept uploading files to the old location, so I opened the Uploads panel and pressed the "x" button
4. I saw conflict notifications (without any description), possibly because I deleted the original folder.
5. None of the old pictures will upload, no matter what I try.

**Comment by e-alfred** [comment]
The problem still exists on Lineageos 17.1 on BQ X Pro, Wileyfox Swift and Moto G3.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Gonna piggyback off this and say we need a "manual rescan" option or something to force the app into rescanning and resyncing folders. Sucks having to wait 5 minutes sometimes for the app to finally realize I took a picture, meanwhile with Google Photos I can open the app and trigger a backup manually.

**Comment by DavHau** [comment]
Same problem with LineageOS 16.0 on BQ Aquaris X Pro.
It would be nice if there was some kind of system log of the app to see what errors happen in the background.
How to debug this?

**Comment by devvykid** [comment]
I am having this issue too on my Samsung Galaxy Note FE w/ android 9. 
Also, I turned off battery optimization and the app keeps warning me about that.

**Comment by quancs** [comment]
I have met this issue years ago. Now, when I back to nextcloud, this issue is still there. This really sucks.

**Comment by tgp1994** [comment]
Another OnePlus user checking in with the same (or similar) problem. If I take a few photos in relatively quick succession, usually the first photo or two is auto uploaded and the rest remain ignored.

**Environment data**

Android version: 9.0

Device model: OnePlus 6T

Stock or customized system: Stock, OOS 9.0.17

Nextcloud app version: 3.12.1 F-Droid

Nextcloud server version: 15.0.5

Reverse proxy: N/A (direct LAN connection)
