### ISSUE TITLE
Toto, I've a feeling we're not in Kansas anymore

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5964]
### Steps to reproduce
1. wait for GitHub notification email
2. see the timestamp
3. WAT?

### Expected behaviour
Emails timestmamp should have ~local time zone. By "local" I mean somewhere near where most Nextcloud developers live or work. Or UTC, if we want to be neutral.

### Actual behaviour
Emails coming from Kansas, USA (-0700)

![kansas-email](https://user-images.githubusercontent.com/1426823/80533901-3c6b8300-8996-11ea-8c6d-669351faeb66.png)

**Comment by ezaquarii** [comment]
I think this can be configured in org or repo preferences.

**Comment by AndyScherzinger** [comment]
No idea, any insight @jospoortvliet @rullzer @MorrisJobke?

**Comment by blizzz** [comment]
Wild guess: It is the time on the AWS(?) datacenter in Kansas where the mail is being sent from. I have not spotted any settings. Why does it matter?

**Comment by ezaquarii** [comment]
On Tue, Apr 28, 2020 at 03:10:17PM -0700, blizzz wrote:
> Wild guess: It is the time on the AWS(?) datacenter in Kansas where the mail is being sent from. I have not spotted any settings. Why does it matter?

I'm using e-mail to stay in touch with other members
and I use GitHub web interface only when I need advanced
editor features. I'm not the only one, btw.

E-mail with your message shows as written 3:10:17PM -0700,
which is not very convenient to read.

I thought it could be tied to my profile TZ settings
but I don't see anything there as well.

Worth escalating to GitHub support?

**Comment by MorrisJobke** [comment]
Not a Nextcloud problem at all. Also all is fine. It has a timezone in it. That's how time works. One can calculate the local time out of this. Changing it would only move the problem, because we have people in our community from around the world.

I would think that GitHub will also close this as "won't fix" but if you really want to give it a try, feel free to report to them. There is nothing on our side to do here.
