### ISSUE TITLE
Nextcloud beta 20170202: Passcode key fills entire screen

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#618]
### Actual behaviour
-Tell us what happens
The new passcode window has much bigger keypad that it used to. On my phone, it almost occupies the entire display.
It seems I can get the smaller keypad version if I select the Back-softkey... button.
I think if keypad layout be chosen, I would rather give it a "Settings" option.
As of now, the bigger keypad is the default size presented but it is not persistent, meaning that on the next passcode entry, it would have reverted to its larger size.
In general, I do not like to have my fingers go past the upper portion of the scree because it is not easily done. For that I must hold the phone from one hand and type the code with the other.
The second reason is exposure to the outside world. With such area, it is easy to expose the code to outsiders because of the extra gesture needed.

### Expected behaviour
-Tell us what should happen
The option to select the keypad size should be done under "settings" and should be persistent rather than always displaying the larger version of the passcode then altering keypad everytime it is requested.

 
### Steps to reproduce
1.  Accessing the content of Nextcloud Beta app.
2. Large passcode keypad appears occupying the entire display area.
3. 

### Environment data
Android version:
6.0

Device model: 
LG G3

Stock or customized system:
Stock

Nextcloud app version:
Beta 20170202

Nextcloud server version:
NC 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by mario** [comment]
Thank you for your report. We'll definitely investigate - this is something we're still discussing if it's worth having.

**Comment by tobiasKaminsky** [comment]
The new behaviour is introduced by #497 for beta (and #620 for master).
So we enhance this PR prior to merging it.

**Comment by tobiasKaminsky** [comment]
After testing it myself (I do not use the passcode feature) the best in my opinion is that the app just remembers the state of the virtual keyboard, as @OlivierS1 said.

The remaining design question is how to switch back from "small" to "big" keyboard.

![screenshot_1486197894](https://cloud.githubusercontent.com/assets/5836855/22617184/b6a177ee-eabe-11e6-85a4-922eaa00b123.png)
![screenshot_1486197874](https://cloud.githubusercontent.com/assets/5836855/22617185/b6a3c918-eabe-11e6-8e6b-3d84cd4712b6.png)

cc @jancborchardt @eppfel

**Comment by AndyScherzinger** [comment]
cc @zmatsuo

**Comment by zmatsuo** [comment]
> how to switch back from "small" to "big" keyboard.

@tobiasKaminsky
Push back button (◁key or ↵key)
to close small(soft)keyboard and switch "big" keyboard

I will add codes to save state of keyboard or/and change the size of the keyboard.

**Comment by eppfel** [comment]
Looking at #497  I am not convinced to introduce a new pin keyboard, just because the softkeyboard is hidden sometimes. That's not a fix, but a new feature and we should think about it that way.
And this issue and the question of switching from one to the other shows we force complexity onto the user instead of delivering an awesome product.

If we decide to introduce it, we have to design it properly. It should never take more than 50% height of the screen. Would solve this issue.
And the input field should not be a continues line, but 4 lines, it is 4 numbers. So basically the only thing that changes, should be the the keyboard.

Could we move the whole input dialog down, so that it's centered in the upper half of the screen? And do we need `abc`, `def` and so on. The passcode is just numbers, right?

And we could actually invert the screen, because it is more like a login, which would users faster to realize.

I feel Passcode does a great job. 
![](https://lh3.googleusercontent.com/eXxAtqmk0DGgpVvLFXWXAubi1GjoMGfO0W6Waxt1_G70ZAlDUu_8GIvsZpz_3oarQA)

In the end there should be no need to switch between two solutions. And the keyboard should be responsive and not resizable.

**Comment by mario** [comment]
Can we copy Passcode? :P

**Comment by zmatsuo** [comment]
I think that the goal of UI is simple. (in my opinion is that galaxy's keyboard is not simple.)

![1h](https://cloud.githubusercontent.com/assets/6488847/22795107/cd4b2462-ef38-11e6-8db4-e6fbe34955c6.png)
sumsung Japanese Keyboard(docomo Galaxy S4 preinstall IME)

![2h](https://cloud.githubusercontent.com/assets/6488847/22795155/fbc2f8d8-ef38-11e6-9f86-92400de83894.png)
google japanese imput

![3h](https://cloud.githubusercontent.com/assets/6488847/22795167/0967c61c-ef39-11e6-8982-470cfb3003c9.png)
Keepass2Android

Designs of SoftKeyboards are different for each IMEs.
I think that we want to choose the numeric keys by us so that we can choose IMEs.
Also, I think some people think that the Soft Keyboard is too small to push.

I am implementing it little by little.
Please wait a little more  :sweat_smile:

About "abc","def"...
Please refer to next URL.
https://en.wikipedia.org/wiki/Phoneword

I use TextInputLayout for input field.
This is useful because you can see the passcode if you need.
(I made it impossible for clipboard to copy/paste. but it is easy to change @mario :-)
But we can not understand that we need four numbers.

So, we can use counterMaxLength and counterEnabled.
Please look next URL.
https://guides.codepath.com/android/Working-with-the-EditText#adding-character-counting
How do you think, @eppfel?

I wish that TextInputLayout can display as follows.
●－－－ → ●●－－ → ●●●－ → ●●●

**Comment by mario** [comment]
You can create a nice animated image view @zmatsuo :)

**Comment by eppfel** [comment]
> So, we can use counterMaxLength and counterEnabled.
Please look next URL.
https://guides.codepath.com/android/Working-with-the-EditText#adding-character-counting
How do you think, @eppfel?

Sry, what is the question here?

> I am implementing it little by little.
Please wait a little more 😅

I'll wait then.

Only thing I have to add: This will be shown a lot to users that use the passcode feature. Therefore we should make it super fast i.e. the fourth number already sends the code, so we can skip "enter".

**Comment by eppfel** [comment]
Ah, wait. Is it 4 numbers or can it be more?

**Comment by tobiasKaminsky** [comment]
I think it is hard set to 4 numbers.

**Comment by AndyScherzinger** [comment]
It is 4 numeric digits. Just an idea and meant as an inspiration, why don't we mimic the Android pin login like this implementation does? https://material.uplabs.com/posts/homesecurityui

**Comment by jancborchardt** [comment]
We should use the system default keyboard (number pad) always instead of inventing our own. Or what issue did we want to solve with it?

It will just lead to look and feel inconsistencies otherwise. We don't want to maintain that.

Also, the inputs should be 4 separated ones like now to make clear it's 4 numbers. :) We could change to empty/filled circles for a nicer look maybe but not if it's too much customization.

**Comment by eppfel** [comment]
@AndyScherzinger @tobiasKaminsky Can we not solve this issue without introducing a new keyboard. Like limiting the height of the softkeyboard?

**Comment by zmatsuo** [comment]
I will study next project.
https://material.uplabs.com/posts/homesecurityui

Which is better system default keyboard or new material keypad?

**Comment by zmatsuo** [comment]
I try to design passcode activity.
Please give me advice.

![out](https://cloud.githubusercontent.com/assets/6488847/23825730/6cba9068-06d2-11e7-9bb4-947e59dcb3b2.gif)

This activity has no edittext.
So now, when soft keyboard is displayed, soft keyboard is full keyboard .
I want to show numeric soft keyboard.I found next page.
http://stackoverflow.com/questions/28978225/how-to-show-number-keyboard-on-custom-viewf
Maybe I will able to change numeric soft keyboard.

**Comment by eppfel** [comment]
> Maybe I will able to change numeric soft keyboard.

Again:

> Can we not solve this issue without introducing a new keyboard

**Comment by zmatsuo** [comment]
I did the implementation.
Please look at gif anime.
Would you give me advice?

# passcode with soft(vertual) keyboard

- Keyboard type is InputType.TYPE_CLASS_NUMBER
- Accept from Hardware keyboard
- Accept KeyEvent.KEYCODE_DEL
- Push back, soft keyboard -> numeric buttons

![1 softkey](https://cloud.githubusercontent.com/assets/6488847/24864354/ea0dcd7c-1e3e-11e7-9dc8-76e7dab6f77a.gif)

# passcode with numeric buttons

- Long tap `back` button, numeric buttons -> soft keyboard
- Accept from Hardware keyboard
- Ripple effect
- Shake anime when passcode is bad (and guard time is 5sec)

![0noraml](https://cloud.githubusercontent.com/assets/6488847/24864339/dbedb126-1e3e-11e7-83d8-3f2b4942ea98.gif)

**Comment by eppfel** [comment]
That is some progress!
Although your material numeric buttons look fancy, I really don't feel we need it. Especially now it's hidden under a long press on the back button, so users would not find it anyhow.

What do you think?  @nextcloud/android 

For design: the shaking animation looks too slow (could be the gif).

**Comment by zmatsuo** [comment]
Thank you @eppfel 

I thought of same ideas.

1. How to switch keyboard on passcode activity
    1. add '...' to back button.
     (Slightly not good?)
     ![add_dots_small](https://cloud.githubusercontent.com/assets/6488847/25072149/9ddb24fe-2302-11e7-9a05-bda1b067af2a.png)
    2. add 'switch KB' button.
     (Where should the button be placed?
      But it is easy to understand)
    3. add menu 'switch KB'.
     (but function is hidden)

2. Add to preferences
   User select keyboard(soft(vertual)keyboard or buttons).
   Default is soft keyboard.
   (Now last selected keyboard is used)

I captured the screen of the emulator on my PC and converted to gif.
The animation may be different speed from real device.  :sweat_smile:
I will make it a bit faster next time I commit.

**Comment by zmatsuo** [comment]
Hi, @eppfel

I research other apps.
https://play.google.com/store/apps/details?id=com.authy.authy
Authy was pin code lock.

This pincode activity has actionbar.
(I can not get screenshot because Authy does not allow)
I think It seems nice.

I will try add actionbar on our passcode activity
and add "switch keyboard" item.

(I am studying because I do not know well about the action bar.
 It will take some time. Sorry :sweat_drops: )

**Comment by jancborchardt** [comment]
It looks a bit confusing that the number buttons have the same style as teh white circles which are placeholders for the pin code. 

I’d really prefer if we can just show the Android-looking number-only keyboard.

**Comment by zmatsuo** [comment]
Hi, @eppfel @jancborchardt

I wrote prototype.

- Add actionbar(toolbar) and 'switch key' menu
- Remove 'CANCEL' button (We can back by actionbar)
- Add delete key(button) 
- Remove 'clear' and 'back' key(button)

Please look next gif anime.
![out](https://cloud.githubusercontent.com/assets/6488847/25621836/81bfda8e-2f8d-11e7-969e-01312446bcba.gif)

I will add this modify to PR #620


Delete button uses U+232B (https://www.compart.com/en/unicode/U+232B)
This character may not be displayed on some real devices.
I looked for drawable* folder, but I could not find suitable png.
Please tell me if there are good parts.

**Comment by AndyScherzinger** [comment]
latest dev version being released from master branch don't ship this (now closed) PR anymore, thus closing.
