### ISSUE TITLE
Client creation must not be blocking

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#6215]
Ref: https://github.com/nextcloud/android/pull/6214

- streamline OwnCloudClientManager and OwnCloudClientFactory

**Comment by ezaquarii** [comment]
The issue is with `AccountManager.blockingGetAuthToken()` request that potentially goes over the network.


Generally, `getAuthToken()` API is asynchronous because it supports use cases when user is prompted via notification to provide credentials.

```
     * <p>In that case, you may need to wait until the user responds, which
     * could take hours or days or forever.  When the user does respond and
     * supply a new password, the account manager will broadcast the
     * {@link #LOGIN_ACCOUNTS_CHANGED_ACTION} Intent and
     * notify {@link OnAccountsUpdateListener} which applications can
     * use to try again.
```

If we don't use this functionality (and the use of a blocking getter suggests tells me that this is the case), then we'd probably need to cache the token ourselves in user data.

Looks like something that should be provided via `UserAccountManager`.

**Comment by tobiasKaminsky** [comment]
In our case the password is an app token, which is retrieved during setup and then never can change again.
So for us there will never be a blocking (to retrieve a new password) nor there should be any delay (as the "password" is always cached in AccountManager).

We could use AccountManager.peekAuthToken(…)
I guess we do not need to change it for legacy owncloudClient, but for NextcloudClient.

**Comment by tobiasKaminsky** [comment]
This is done for new NextcloudClient.
For old ownCloudClient we will not change it.
