### ISSUE TITLE
Automatic upload erratic behavior

### ISSUE THREAD

**Issue by KnallbertLp** [nextcloud/android#6273]
### Steps to reproduce
1. open 'automatic upload'
2. try to upload something 

### Expected behaviour
- Things should get queued for upload sooner or later 

### Actual behaviour
- Nothing, sometimes the app freezes upon trying to open 'automatic upload'

### Environment data
Android version: 10

Device model: Galaxy S9 

Stock or customized system: stock

Nextcloud app version: newest dev build (20200611)

Nextcloud server version: latest docker container (version 19.0.0)

Reverse proxy: none, direct ip

Edit: and sometimes it starts working ages after I told it to

Edit2: and then locks up the app for 7 minutes before finally working fine again (to be fair, I told it to upload about 17k files)

Edit3: It apparently crashed in the background, I restarted it and now I get 'nextcloud dev ist not responding' messages all the time

Something is really messed up

Edit4: Now it uploads if I open the app (as the notifications tell me) but the app interface freezes and stays frozen if I don't force stop the app :))

**Comment by StormTrooper** [comment]
Having similar issues. Enable auto upload on a folder with 20 files and I get "Nextcloud isn't responding"  

Click on wait and after 10-15 mins it eventually becomes responsive again but even after leaving overnight it fails to sync anything

**Comment by tobiasKaminsky** [comment]
Do you have excluded the app from power saving?

**Comment by cholzer79** [comment]
Besides the first sync of 6k+ files [simply crashing the app](https://github.com/nextcloud/android/issues/6004), Auto Upload is just extremely unreliable. 

I shot 4 pictures today at 7:59, now it's 12:53 and they still did not get sync'ed (phone is connected to WiFi). While @tobiasKaminsky suggested that it should not take longer than 15minutes for newly shot images to get sync'ed......

https://github.com/nextcloud/android/issues/6159
https://github.com/nextcloud/android/issues/6153

But all issues I created on that subject just got closed by @tobiasKaminsky with next to no discussion. Guess that happens when an issue does not plague the dev....... (I have auto upload issue on 4 different Android devices but it seems like it's "just me"....)

**Comment by 120e314** [comment]
I have the same problems with multiple Samsung Galaxy S10e.
And on multible Samsung Galaxy XCover 4 (S) it works fine.
Apart from the hardware differences, there is only one difference...the android version. The S10e has Android 10 and the XCover 4(S) has Android 9.
Is this Auto-Upload-Issue maybe a android 10 problem?

@tobiasKaminsky  @

**Comment by KnallbertLp** [comment]
> Do you have excluded the app from power saving?

Yes, I have
