### ISSUE TITLE
auto upload of older files deletes the creation date of those files

### ISSUE THREAD

**Issue by lxto** [nextcloud/android#6406]
### Steps to reproduce
1. on creation of auto uploads older files lose their creation date
2. 
3. 

### Expected behaviour
- creation date of uploaded older files should be preserved

### Actual behaviour
- creation date is replaced by by current date

**Comment by tobiasKaminsky** [comment]
Where do you see the creation date? On server it should still show the old date?

**Comment by invario** [comment]
Android 3.12.1 RC1 and I'm experiencing this. It's made apparent when you go browse into the folder in NextCloud and sort with newest first and see files from years back on top mixed up.

**Comment by invario** [comment]
![Screenshot_20200703-132212_Nextcloud](https://user-images.githubusercontent.com/67800603/86488815-4449f980-bd30-11ea-9147-305847a300ff.jpg)

**Comment by tobiasKaminsky** [comment]
Can you test if the same happens when manually uploading a file?

**Comment by invario** [comment]
Just did a manual upload of one file, date appears to have been retained correctly.
![Screenshot_20200706-113252_Nextcloud](https://user-images.githubusercontent.com/67800603/86611281-794a8c00-bf7c-11ea-8892-146946fb4cc7.jpg)

**Comment by tobiasKaminsky** [comment]
This seems not to be the creation date, but the last modified date.
Can you verify if this is in sync with server value?

Two cases:
1) manual upload
- have a file with modification date yesterday
- upload it
- see "yesterday" in web ui and NC app

2) have old images in DCIM/camera folder
- enable auto upload
- files get uploaded
- see "now" in web ui and NC app

Can you verify that this 2) is wrong?

**Comment by tobiasKaminsky** [comment]
As far as I can see there is no difference between manual and auto upload…

**Comment by invario** [comment]
Here's what I did today. I actually completed purged the user from NextCloud and wiped the app off my phone to force everything to start over for AutoUpload.

The problem is reproduced as a result and here are the (3) screenshots to show what's happening:

Screenshot from my phone's file manager showing the actual file timestamp as 06/11/2020 (it got reset due to moving the file with Samsung Gallery to my SD card.
![From Phone File Manager](https://user-images.githubusercontent.com/67800603/88469002-bb9b2500-ceb9-11ea-910d-8af08b2526f0.jpg)
)

Screenshot from my phone's NextCloud showing that after it uploaded, NextCloud has changed the file timestamp
![From Nextcloud](https://user-images.githubusercontent.com/67800603/88468975-59422480-ceb9-11ea-8419-d4297d338b21.jpg)


Screenshot from a shell window into my FreeNAS NextCloud jail. Simple "ls -l" for the files.  There are MANY more files that have this same behavior as 20190609_114405_016.jpg and 20190609_114405_032.jpg
![From FreeNAS shell](https://user-images.githubusercontent.com/67800603/88468978-5e06d880-ceb9-11ea-9e84-04cff8275d3d.jpg)



It resets the timestamp to when it was uploaded. (In my screenshots, that is today, July 25).

**Comment by invario** [comment]
Hmm I wonder if this is actually a problem with the server. I tried using a different app (FolderSync) to sync with my NextCloud server  and the date on all the files is the time of upload instead of the original modified date.  Very frustrating.

**Comment by invario** [comment]
So after Googling some, it appears this has been discussed (and complained about) extensively.

https://github.com/nextcloud/server/issues/15192

https://www.reddit.com/r/NextCloud/comments/d86j07/wrong_modified_dates/

Very inconsistent handling of modified date, dependent on several factors including the app itself.
