### ISSUE TITLE
Uploading folders?

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/android#6629]
### Steps to reproduce
1.  "upload files"
2.  navigate to root directory with folders I want to upload (emulated/0/pictures/*)
3. hit upload

### Expected behaviour
folders in the directory should start uploading

### Actual behaviour
no upload happening, but notification "Uploading files.." present. requires force stop to disappear.

### Environment data
Android version: 10

Device model: op5T

everything on latest version, app 3.12.1

**Comment by AndyScherzinger** [comment]
Thanks for the report @pilsnerbeer 🙏 the bug is being able to hit the upload button while upload a folder and its content would be a new feature.

> Expected behaviour
folders in the directory should start uploading

see for work in progress #4859 (stale dev!)

> no upload happening, but notification "Uploading files.." present. requires force stop to disappear.

@tobiasKaminsky file upload picker should deactivate button until 1 or more files have been chosen
