### ISSUE TITLE
Beta 20170221: Improving "Autoupload" event.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#674]
### Actual behaviour
-Tell us what happens
Having "Autoupload" enabled for one or more folders will actually not take place until the"autoupload" feature is being triggered.
There should be an option that can force "Autoupload" on any folder selected for Autouploads.
As a simple example, if we enable "Autoupload" on Camera folder, which already contains photos and videos, enabling "Autoupload" will not trigger the autoupload mechanism. Instead, it is waiting for a trigger event from camera. Only then will the folder be uploaded.

### Expected behaviour
-Tell us what should happen
There should be an option to force Autopload to process a folder even in the absence of the triggering event.

**Comment by mario** [comment]
That sounds like an intended behaviour. It will only upload new files/images in a selected folder, rather than an entire folder. While I would prefer it to upload an entire folder, this is the task of 1way sync for which I don't have time in this release cycle :(

You're probably looking for something like https://github.com/nextcloud/android/issues/667, right ? :)

**Comment by OlivierS1** [comment]
Yes.
