### ISSUE TITLE
Can’t access Server from android app inside the house with public IP

### ISSUE THREAD

**Issue by ArtyV** [nextcloud/android#682]
### Actual behaviour
in the app If i try to connect using the public ip to the server, it times out, 
but if i use the chrome app on my phone i can connect to the server
if i disable wifi and use data the app works.
I can connect to it via desktop browser
and outside the house via android app too. 

### Expected behaviour
It should always work.
 
### Steps to reproduce
1.  Use Public IP internally.

### Environment data
Android version: 7.1.2

Device model:  Nexus 5x

Stock or customized system: Stock

Nextcloud app version:
20170223
Nextcloud server version:
Lastest

**Comment by ArtyV** [comment]
What's also interesting, if I login on outside, i can use it inside the house, it is just a little bit "laggy".

**Comment by JSoko** [comment]
Ipv6?

**Comment by ArtyV** [comment]
I don't see how it's related to ivp6?, But I did try disabling on the network and it didn't change anything.

**Comment by JSoko** [comment]
Because the app has issues with ipv6...
#641 #427

**Comment by ArtyV** [comment]
Yes,  I read those, but  im not using the ipv6 adress......im using ipv4 anyway.......
I originally thought it was a DNS issue, but it works just fine, there is just a longer delay before connecting, Except in the app where the logging in timeout seems shorter, in which case the workaround was logging in outside the house then using it in the house.....

**Comment by JSoko** [comment]
I have exacty this bebavior of the app until i switch of ipv6 for my phone or the whole network on the rooter...

**Comment by ArtyV** [comment]
Hmmm idunno why that didn't work for me.... Ethier way the app does work with an ipv4 (with ipv6 enabled), it's just a little Goofy that I had to log in out of the house and then come back for it to work

**Comment by OlivierS1** [comment]
Check in you server log if "Brute force attack" appears.

**Comment by bl4ckOut** [comment]
I have exactly the same problem with my samsung tablet:
Try to connect via DNS from home wifi and the app always says "Server is not reachable". 
If I use the local IP or DNS with mobile data everything is fine.

**Very strange is following**: 
I have an android phone which is working at home since 3 months without any problems.

**Things I've tried**:

- disabled IPv6 on server (Ubuntu 16.10)
- Static IP on server
- Static IP in tablet
- Looked up bruteforcetable --> no entries
- Switched from nextcloud 1.4.2 to nextcloud_dev App 20170419 (Always newest version)

**My devices**:

1.)
Samsung Galaxy Tab A 2016 T580
Android 6.0.1, rooted
Stock
nextcloud 1.4.2 and nextcloud_dev 20170419

2.)
Xiaomi Redmi Note 3
Android 5.0.1, rooted
Stock
nextcloud 1.4.2

3.)
Nextcloud Server 11.0.3
(Tried also with 11.0.1, then updated to 11.0.3)

**Comment by ArtyV** [comment]
It's a Router/Network Issue

**Comment by bl4ckOut** [comment]
I still don't think this is a router problem.
Where do you get the information from?

**Comment by ArtyV** [comment]
I adjusted my router to forward all traffic to that Public url to the internal IP. It is most definitely a networking issue, not a nextcloud issue
