### ISSUE TITLE
App "stuck" in webview after login?

### ISSUE THREAD

**Issue by floe** [nextcloud/android#7075]
On two separate devices, I recently ran into the problem that after a fresh install of the Nextcloud app from the Playstore (v3.13.1), I can't properly login to my old Nextcloud instance (10.0.6) anymore.

After I enter the server address, I get a webview with the front page and can actually login there and browse my files, but none of the app's Android-specific functions work (auto-upload, for example). In fact, the app doesn't even show a hamburger menu, just the webview. And when I quit and restart the app, I'm back to the start screen.

Is this related to my old Nextcloud version, or is there any other explanation/possible fix?

**Comment by floe** [comment]
P.S. on another device where the app has been installed for some time, everything continues to work, as long as no new login is needed. (even with the old nextcloud version).

**Comment by AndyScherzinger** [comment]
@floe this is related to the old Nextcloud version, yes. Newer versions (not sure which one exactly) introduced the Login Flow https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html - which is used by the Android client to do the login and then work with the token for any future communication with the server.

So the best way (especially since Nc10 is end-of-life since quite a while) would be to update the server (best to go to Nc20) or to install an old version of the Android app (before we introduced webflow logins). 

Else if you can't update the server you need to stay with the Android client version 3.13.0 (https://github.com/nextcloud/android/releases/tag/stable-3.13.0) since https://github.com/nextcloud/android/commit/58ba15ac95ebf367033033bc83ca5419f9efd0a9#diff-db6f982b11dde1cc5625bb0b122e6f94 removed the unsupported legacy login (install 3.13.0 and wait for ~30 seconds then a legacy login option will show up in the web view).

cc @tobiasKaminsky

**Comment by floe** [comment]
Excellent, thanks for the quick answer.

**Comment by floe** [comment]
JFYI and maybe for anyone else running into this issue here, I gritted my teeth and upgraded the old Nextcloud cruft, first to 11.0.8 and then to 12.0.13, and now everything is back up and running as intended. Yes, I know 12.x is also EOL, but one step at a time :-)

**Comment by AndyScherzinger** [comment]
> to 12.0.13, and now everything is back up and running as intended

Nc12 is the first version supporting the web login flow 👍 

> Yes, I know 12.x is also EOL, but one step at a time :-)

All good, just as I mentioned you might run into issues with the client since we don't run any test with EOL servers so things might break. So take your time with the upgrades, no worries.
