### ISSUE TITLE
[Feature Request] Auto-Update should sync also old files(pics)

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/android#720]
At the moment old files won't sync if u enable Auto-Upload for one or more folders.
I think it would be better to sync also old files. Either first time autoupdate is enable for a folder or every time autoupload for a folder is disabled/enabled. The second one is also a manual one

One question could be is "old file upload"optional or not

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android/issues/285 v1.1. should cover that:

> add "upload/sync all existing images/videos/files" as an option to the auto upload folder three-dot menu.

**Comment by AndyScherzinger** [comment]
#285 v1.1. should cover that:

> add "upload/sync all existing images/videos/files" as an option to the auto upload folder three-dot menu.

please re-open if you disagree

**Comment by ioguix** [comment]
Hi,

I'm using version nightly 20170301 and I can confirm there is no such option in auto-upload folders three-dot menu.

BTW, I checked the "upload on wifi only" option, but it seems it tried to sync with no wifi connection...and now I have wifi again, it seems it tries to upload everything again :/

**Comment by AndyScherzinger** [comment]
> I'm using version nightly 20170301 and I can confirm there is no such option in auto-upload folders three-dot menu.

This option hasn't been implemented yet (also not in the nightly)

> BTW, I checked the "upload on wifi only" option, but it seems it tried to sync with no wifi connection...and now I have wifi again, it seems it tries to upload everything again

That shouldn't happen, there should be a new version available soon for the nightly though which may or may not fix this issue if present (can't test it at the moment). cc @mario @tobiasKaminsky

**Comment by edgartaor** [comment]
I was expecting that "auto upload" would upload all existing files by default (not only new files), like others sync apps. That made me think that auto-upload was not working, until I take a picture.

> "upload/sync all existing images/videos/files" <--option

IMHO, the app should upload/sync all files by default and have this option instead:
> "upload/sync ONLY NEW images/videos/files"

or prompt the user "Sync all existing files of this folder?" --YES-- --NO--

**Comment by AndyScherzinger** [comment]
@edgartaor it is part of #285 v1.1. but not yet implemented. Auto upload is the 1st evolutionary step towards a real sync but the first iteration is basically a new implementation for the former instant upload (that uploaded a picture right after it had been taken).

**Comment by edgartaor** [comment]
Thanks for your work.

**Comment by AndyScherzinger** [comment]
@edgartaor always happy to help. Would love to have all the feature versions of auto upload already done, but unfortunately it takes time and we mostl just work on the app in our spare time as contributors :)

**Comment by Bullnados** [comment]
Than u should stop doing all things nothing to do with the app ^^

Have u perhaps a rough releaseplan for that feature

**Comment by Bullnados** [comment]
Than u should stop doing all things nothing to do with the app ^^

Have u perhaps a rough releaseplan for that feature

**Comment by AndyScherzinger** [comment]
No schedule yet, sorry :(
There a couple of features that need to be implemented before taking on the next step regarding auto upload. If I would have to guess, I'd say April/May but that also depends on the availability of @mario and @tobiasKaminsky or any other contributor who would like to jump in....pretty busy with my day job... :(

**Comment by ioguix** [comment]
@AndyScherzinger,

> it is part of #285 v1.1. but not yet implemented

Ok, that's where I am lost and I thought this issue should have been kept open. As far as I understand it v1.1 is older than current v1.4.x. That's why I expected this feature to be there when I read:

> v1.1. should cover that

I'm pretty confused now... What is the release/version policy?

And, yes: Thanks you for your work :)

**Comment by mario** [comment]
@ioguix he meant v1.1 of Auto Upload which is a strange versioning scheme, but still ... so basically, it's gonna be an improvement of the current Auto Upload mechanism.

**Comment by ioguix** [comment]
Oh, ok, I understand now :)

Thx!

**Comment by Bullnados** [comment]
I know its closed but my APP starts today syncing old files? Has someone the same behavior?

**Comment by tobiasKaminsky** [comment]
@Bullnados the app recognizes files as "new" if they were modified, e.g. image resizing, or copy/move of the file. Maybe this is the case?

**Comment by Bullnados** [comment]
Yes, I removed the external SD card. That could be the trigger.

**Comment by thexmanxyz** [comment]
Its now over a year and this is a feature we really need. I know there might be higher priority issues on the list but this is a really basic feature of the app that's still missing. We would just need a checkbox on configuration and a simple program flow which on folder creation intiates the sync for all files in that folder, in addition to the current state of "new file sync". I don't want to be rude or anything like that, I could myself try to make a fork, fix it and submit a PR. However I've not that much android development xp and it would take me ages to test and actually fix it because I have nothing set up. Someone in the core team this would take just a tiny fraction of the time. So I just can hope that someone reads this and implements it. thx.

**Comment by thexmanxyz** [comment]
@AndyScherzinger @mario Its now over a year and this is a feature we really need. I know there might be higher priority issues on the list but this is a really basic feature of the app that's still missing. We would just need a checkbox on configuration and a simple program flow which on folder creation intiates the sync for all files in that folder, in addition to the current state of "new file sync". I don't want to be rude or anything like that, I could myself try to make a fork, fix it and submit a PR. However I've not that much android development xp and it would take me ages to test and actually fix it because I have nothing set up. Someone in the core team this would take just a tiny fraction of the time. So I just can hope that someone reads this and implements it. thx.

**Comment by grisu48** [comment]
Having the same issue and weirdly it works on the iPhone version already (my sister tried it just today). The app is awesome and all your work is appreciated much and we look forward to hopefully see this feature as well in the Android version! This is amazing work!
