### ISSUE TITLE
Add a message about the password error.

### ISSUE THREAD

**Issue by kimminji00** [nextcloud/android#7331]
### Is your feature request related to a problem? Please describe.

When a password is wrong, no message appears about the password error.
Just, we have to re-enter the password without any notice of password error.
This makes it ambiguity to use.

### Describe the solution you'd like

I think a message about the password error must be appeared.
So, solution is "Add a message about the password error.".
Also, I solved it this solution.
![capture](https://user-images.githubusercontent.com/44043952/99244419-6490d580-2845-11eb-9956-95cdde344b7c.GIF)

If you think this solution is okay, I would like to PR it. !

**Comment by Kuuuna98** [comment]
A incorrect password message is displayed at the bottom of the screen. 
So I think the user might not be able to check it because it is hidden by a keypad.
I think it'd be better to display the message at the top of the screen.

![Screenshot_20201116-221201_Nextcloud](https://user-images.githubusercontent.com/26339069/99256662-14bc0980-2859-11eb-9d9d-fe1e087a7151.jpg)
