### ISSUE TITLE
Add "shoot and upload a video right away"

### ISSUE THREAD

**Issue by kimminji00** [nextcloud/android#7358]
### Is your feature request related to a problem? Please describe.

When i click "+" button, i can upload files.
But, When I click "Upload from camera", I can only take pictures and I can't shoot videos.
So, I can't shoot and upload a video right away.
This causes a lot of inconvenience.

### Describe the solution you'd like

I think it would be nice if I could shoot and upload the video right away.

**Comment by joshtrichards** [comment]
Code in question is here: 
https://github.com/nextcloud/android/blob/3b3c5baaacd9177be4f854844a8823ef8aa29c3a/app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java#L1082

Due to the way [Intents work in Android](https://developer.android.com/training/camera/camera-intents), only Photo or Video mode is available when invoked by us unless we jump through extra hoops. 

It looks like the easiest way would be to either:

- add a second menu option and function like "Upload from Video Camera"  (easiest/most straightforward and probably just fine)
- add a chooser that comes up after someone clicks "Upload from Camera" to choose either Image or Video mode (something like [this](https://stackoverflow.com/questions/16551851/android-intent-for-capturing-both-images-and-videos) or [this](https://stackoverflow.com/questions/11021021/how-to-make-an-intent-with-multiple-actions/11038348#11038348))

I personally prefer the first approach.

**Comment by prajyot004** [comment]
Is this issue resolved ?
I want to work on this issue.

**Comment by joshtrichards** [comment]
You're welcome to do so, @prajyot004. Thanks!

**Comment by timedin-de** [comment]
Hey @prajyot004 are you still working on this? Otherwise I'd like to open a pull request.

**Comment by timedin-de** [comment]
@joshtrichards @kimminji00 I guess this issue can be closed, as the pull request got merged.

**Comment by Yogeshjindal** [comment]
@joshtrichards please close this issue, it might waste time for other developers to read and then find out that this issue was already sorted.

**Comment by joshtrichards** [comment]
Fixed in #12995
