### ISSUE TITLE
PNG transparency not shown in image viewer

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#7360]
File explorer preview:
https://user-images.githubusercontent.com/15892014/99540141-6ecee300-29af-11eb-9333-a07bf21bc77f.png

Nextcloud app preview:
https://user-images.githubusercontent.com/15892014/99540376-b5bcd880-29af-11eb-9c31-766466b892ec.png

(images added as URLs because the title is probably enough explanation already and github makes images HUGE)

Thumbnails lack transparency as well.

### Environment data
Android version: 11

Device model: Pixel 3a

Stock or customized system: Stock

Nextcloud app version: 3.14.0 (downloaded apk from github)

Nextcloud server version: 20

**Comment by AndyScherzinger** [comment]
@Derkades this is actually "by design": 
_if_ you
* downloaded the file first (else you just see a server-side, generated thumbail)
* open the image
* click once to open the full-screen view (toolbar gets hidden)
* click again (white backround gets removed for images with transparent background)

This is the way it has been discussed and implemented a while ago. If you think this needs to be changed please get in touch with @nextcloud/designers 😃
