### ISSUE TITLE
Share Link: "Share via App" Dialog opens before set share options

### ISSUE THREAD

**Issue by 90er** [nextcloud/android#743]
### Actual behaviour
When i try to create a share link, the "Share via App" dialog opens just before i can set some options like "allow editing", "Password protect" or "Set expiration date". I have to use the "back" button to close the dialog. After it i can set my options and click on "Get Link".

### Expected behaviour
Open "Share via App" Dialog only if i click on "Get Link".
 
### Steps to reproduce
1. Go to an file/folder
2. click on "Share"
3. enable "Share Link"

### Environment data
Android version: 5.1.1
Device model: HTC One M8
Stock or customized system: CyanogenMod 12.1
Nextcloud app version: 1.4.2
Nextcloud server version: 11.0.2

**Comment by AndyScherzinger** [comment]
Same behavior on OP3T Android7, running 1.4.2 and I agree with @90er 

What do you think @mario @tobiasKaminsky @jancborchardt @eppfel ?

**Comment by tobiasKaminsky** [comment]
As always it is a good idea to see the other side: if a user wants just to share a file he then would have to do an additional click. Additionally, in my case I have enforced password protection so a password is asked for before getting the link.
But I would tend to do it the way this issue suggests, @jancborchardt ?

**Comment by eppfel** [comment]
mh, I am undecided. the only real issue is password protect, because sending the link before setting a password, is a threat (altough very very small).

But then it's true, that it feels weird that you are presented with the options only afterwards...

Maybe two actions `share directly` and `share options`? But not good UX either...

I think we have to keep in mind, that sharing a file/folder is THE use-case of nextcloud, so this has to be streamlined at all times.

**Comment by AndyScherzinger** [comment]
I'd also vote for the solution described by @90er since on that screen you can do all kinds of share related stuff and when you activate the link (hit the switch element) a share popup comes up because the link has been generated right away and fired an event to process it. So to me you are doing all your work for sharing via link and you may or may not do additional configurations for the link. To me clicking a settings element (switch) doesn't expect me to fire a action, just to activate the option...especially when there is a "get link" button ;)

**Comment by joshtrichards** [comment]
Seems alright to me now. The UI is fairly different these days.

**Comment by jancborchardt** [comment]
@joshtrichards thanks a bunch for cleaning up issues! :heart:
