### ISSUE TITLE
Nextcloud Push Notifications doesn't work

### ISSUE THREAD

**Issue by LucasTrombim** [nextcloud/android#7567]
I tried everything to make push notifications work on Nextcloud, but i cant. Someone got how to do it?

**Comment by tobiasKaminsky** [comment]
Which app version do you use?
Which device?
What do you see when you open up notification view?

**Comment by LucasTrombim** [comment]
My device: Motorola G6 Play
App version: 3.13.1

When i receive a notification, will go to Notifications tab. But i need to make a push notification, but i dont know how..

**Comment by fracklaus** [comment]
Same problem here. Device(s) are a Samsung Galaxy Tab S2 and a Samsung Galaxy S7.
For both, push notifications do not work. On the devices in the notifiaction view, "push notifications are currently not available" is being displayed. I am not able to send a test push message from occ notification:test-push user. Error message is: "No devices found for user".

For me this happens on a fresh install of nextcloud - I just disabled a few apps after installing it (of course, the notification app is still active). I did a fresh install of the nextcloud app on the android devices as well.

When I connect an iOS device, I can successfully execute "php occ notification:test-push user", and the message is displayed on the iPhone. Hence I guess the problem is with the android client, and not with my nextcloud server.

**Comment by franconianmetal** [comment]
3.13 works, 3.14 not. 
server not touched. occ cmd works.
in 3.14 app says "push currently not available"
reverted to 3.13

**Comment by Happyfeet01** [comment]
Why Nextcloud need Google Play Services for Push?![Screenshot_20201203_113745_com.nextcloud.client.jpg](https://user-images.githubusercontent.com/3295104/100999162-ae273300-355c-11eb-8696-dfd6cbec1f43.jpg)

I have an device without google services

**Comment by tobiasKaminsky** [comment]
This is the concept of push notifications: one central listener on device, so that it is energy efficient.
It takes care of listening to all incoming push notifications and then distributes them to the specified app.

If you do not have google services, you will not receive a push notification, but any notification will be shown in this view, if you open it manually.

**Comment by franconianmetal** [comment]
I have google services activated, push is declared as deactivated in nextcloud app.
As mentioned above: no change of device/googleservice-stuff, just downgrade to 3.13 -> works

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I guess #7616 is the reason why this is happening

**Comment by Webbeh** [comment]
Same issue, same tempfix.
3.13 works with notifications, 3.14.2 doesn't.

Android 11 (rooted).

**Comment by Luke1982** [comment]
Same issue with the stock playstore version on a Fairphone 3

**Comment by Webbeh** [comment]
Is there any way to re-enable notifications in the dev previews ?

**Comment by Webbeh** [comment]
3.14.2 RC1 fixed this for my device.
Oneplus 8 pro, Android 11.

**Comment by franconianmetal** [comment]
3.14.2 RC1: push works, but upload didn't work - chrashed the app. sorry don't have a screenshot for it

**Comment by elgorro** [comment]
On my Pixel 2 XL (AOSiP 10) with Nextcloud 20.0.5 (and before all 20.*.* versions) and Android-App 3.14.3 I got a "bug" where it pushes "emtpy" notifcations ("NEW NOTIFICATION" - "NEW NOTIFICATION"). Also sometimes random notifactions, but the server hasn't any new notifications...

**Comment by fracklaus** [comment]
I can confirm the behavior regarding empty push notifications on Android-app v. 3.14.3.
Device is a Galaxy Tab S7.

**Comment by ero646545** [comment]
Hey same problem with all my phones and TV i also tried 8.09 version of NextcloudTalk... so sad that a simple notification or ringtone cannot work...

**Comment by Webbeh** [comment]
Same here. The notification tab in the app works properly, but the android notification shows "NEW NOTIFICATION - NEW NOTIFICATION". It is delayed as well.

**Comment by Webbeh** [comment]
Same on 3.15.0 from yesterday.

**Comment by elgorro** [comment]
Fixed for me probably: NC 20.0.0.7 and Client 3.15.0.

**Comment by Webbeh** [comment]
> Fixed for me probably: NC 20.0.0.7 and Client 3.15.0.

Still the same for me with NC20.0.7 and client 3.15.0

**Comment by elgorro** [comment]
@Webbeh FYI: https://www.androidauthority.com/android-11-notification-changes-1127807/
I still have Android 10!

**Comment by Webbeh** [comment]
Little bit of news : my phone boot looped and I had to factory reset it. I now have fully functional notifications on client 3.15.0 and server 20.0.7, with the same firmware (android 11, oxygen OS 11.0. 3.3IN11BA.

**Comment by sunjam** [comment]
https://f-droid.org/packages/com.polar.nextcloudservices

Currently in beta.  Adds notifications for users not installing from the Play Store.
