### ISSUE TITLE
Use a single notification when downloading (syncing) an entire folder

### ISSUE THREAD

**Issue by locness3** [nextcloud/android#7651]
### Is your feature request related to a problem? Please describe.
When syncing a folder, the app will show a seperate notification for each file it syncs, which gets removed when the file is done. On Android (at least for me) the notification center automatically closes when there's no more notifications, so I can't open the notification center to keep track of the sync as it gets closed when each file is done.

### Describe the solution you'd like
Use a single status notification when syncing a directory.

**Comment by Webbeh** [comment]
This improvement could be used for instant uploads as well.

**Comment by newhinton** [comment]
I was just thinking about this behaviour. I will try to create a fix for this

**Comment by newhinton** [comment]
@AndyScherzinger @jancborchardt This can be fixed relatively easily. I actually have "nailed down" the notification, it doesnt dissapear anymore. However, there is still a new notification plopping up for each successful notification.

From an UI-perspective, does it make sense to show that it succeeded (and then immediately dismiss the success-notification anyway) or is it fine to just show the progress in a singular notification and only create new notifications for failed uploads? (and actually stack them with unique id's so that there is a log of each failed notification?)

**Comment by Webbeh** [comment]
If I can have a say, I do believe having one single progress bar will feel better. Please do create a separate "currently uploading" notification channel that can be deactivated while being able to keep the failed notifications.

**Comment by newhinton** [comment]
@Webbeh i agree with the "flashing" notification. But i dont think we need a seperate channel for this, since it is rather important to see if an upload actually takes place. I'd place it as equally important as the error display.

On the other hand, if they agree that this is a good change, we reduce the amount of notifications from X uploads plus X Success/Error-Notifications to just one upload-notification and N-errors. (also this should apply to everything, not just uploads)

I'd like someone else to chime in on this though :D

**Comment by Webbeh** [comment]
I understand the reasoning and think I agree with a single "transfer errors" channel. I do wonder what the actual downside of having a separate channel for current uploads actually is, if you can shed some light onto that. I don't personally see any downside to it.

**Comment by newhinton** [comment]
It's not really a downside, but an argument could be made that "notification-channel-spamming" is not really helpful and is unwanted in some cases. 

So there is not really an argument against it besides style, but to be honest it's also not a decision i want to make :D im fine with either one, so i'd like a maintainer to chime in and give their opinion :D

**Comment by AndyScherzinger** [comment]
So Looping in @tobiasKaminsky and @jancborchardt for feedback

From my POV:
* One notification for upload status should be the way to go ("progressbar etc...") while this would likely make it two notifications atm (there is one persistent notification which is used to have a priority within Android to schedule work (not sure if this is still correct!))
* Same could apply for multiple downloads
* Errors could probably also only be 1 single notification since the reason is the likely the same for all failed uploads/downloads (or at least one notification per error type (e.g. server not reachable)

**Comment by tobiasKaminsky** [comment]
To have it step by step, I would first go with "combined progress bar" and keep errors apart from it.
Then later try to combine them (e.g. I am not sure if it useful to have >10 failing file names in one notification or if we then simply redirect to upload queue).

**Comment by newhinton** [comment]
@tobiasKaminsky Sure, i already did the combined progressbar, although it generally shows only the progress of a singular up/download (and i think this cannot be changed without redoing the whole upload/download code)

however i'd also like to remove the success/error notifications, since they show the same behaviour this issue is about: 
When the download is finished, it pops up, then the next one starts and it is immediately dismissed.
To me, this is the same issue and i'd like to resolve them together (its not really hard to do, dont show it if it succeeded, and give it an unique id if it failed, so that it is not dismissed)

I could just show a general error message at the end instead of each one, as @AndyScherzinger suggested
Slightly more work, but it would not really blow up the pr unreasonably

**Comment by newhinton** [comment]
Another idea i had: Should the progressbar show items done/todo*

Something like:

(15/100) Dowloading file CoolImage.jpeg: 50%

This is just an idea, i dont know if that is feasable. And should this be included here or in an additional pr?

**Comment by AndyScherzinger** [comment]
> Another idea i had: Should the progressbar show items done/todo*

Sound like the right solution to me 👍 

> This is just an idea, i dont know if that is feasable. And should this be included here or in an additional pr?

If @tobiasKaminsky is also fine with it and it doesn't lead to a very large PR I'd be fine with inclusion

**Comment by AndyScherzinger** [comment]
@newhinton I talked to @tobiasKaminsky -> feel free to move forward 🚀 🎉

**Comment by Webbeh** [comment]
> 
> 
> > Another idea i had: Should the progressbar show items done/todo*
> 
> Sound like the right solution to me 👍
> 
> > This is just an idea, i dont know if that is feasable. And should this be included here or in an additional pr?
> 
> If @tobiasKaminsky is also fine with it and it doesn't lead to a very large PR I'd be fine with inclusion

I believe anything that doesn't rapidly fire new notifications is a win to me.

About the "channel spam", I believe Whatsapp (to only take that example) has 10 channels to granuarly separate informations, without counting the per-conversation channels. I believe this is a non-issue.

**Comment by ezaquarii** [comment]
@locness3 @AndyScherzinger I'd consider moving this code to [AppNotificationManager](https://github.com/nextcloud/android/blob/b83bf828f2fe24bdf1dc25764c645ec481316f12/src/main/java/com/nextcloud/client/notifications/AppNotificationManagerImpl.kt)

If we could clean it up now, we won't have another re-write again when we push new file transfer manager forward.

**Comment by ezaquarii** [comment]
@locness3 @AndyScherzinger I'd consider moving this code to [AppNotificationManager](https://github.com/nextcloud/android/blob/b83bf828f2fe24bdf1dc25764c645ec481316f12/src/main/java/com/nextcloud/client/notifications/AppNotificationManagerImpl.kt)

If we could clean it up now, we won't have another re-write again when we push new file transfer manager forward.

Actually, the code for single notification is already there, one would need to just call it instead of the previous implementation. What is missing is the UX review.

**Comment by AndyScherzinger** [comment]
@ezaquarii sounds like a plan! 👍

**Comment by newhinton** [comment]
so, is my pr still required then? I mean, depending on how big the other pr is going to get, we could treat my pr as a hotfix (it isnt bigger than one anyway)

**Comment by AndyScherzinger** [comment]
I would need to search the codebase so maybe @ezaquarii can answer that.

**Comment by ezaquarii** [comment]
@newhinton The notification manager can post notifications, but:

1. it's not called
2. exact notification content is not UX-reviewed
3. upload notification is not merged (you could just copy-paste it from the linked PR)

> so, is my pr still required then?

I'd answer "yes", but not necessarily in the current form.

**Comment by newhinton** [comment]
@ezaquarii What would you change then? If i understood it correctly, you are redoing the whole upload-thing to make it better (yay!) but it would also fix this issue

So we have two PR's that do the same, except yours is way bigger and does way more.

If i didnt undestand something, please correct me!

**Comment by ezaquarii** [comment]
@newhinton
>  If i understood it correctly, you are redoing the whole upload-thing to make it better (yay!) but it would also fix this issue

As a side effect - yes - but there is absolutely no point in waiting for my PR to be merged as it will take quite some time.

Here is the plan proposal:

1. copy and paste upload notification code from my PR
2. instead of modifying existing notification code, replace it with calls to `AppNotificationManager` API
3. get it reviewed and accepted
4. profit

Don't worry about merge conflicts - it's the least of our issues.
