### ISSUE TITLE
timestamps aren't preserved when uploading (in 2020/21)

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/android#7792]
Basically the same as in "timestamps aren't preserved when uploading #1433 "

### Steps to reproduce
1. Upload file via Android-app (I used the automatic-upload option and synced a whole folder)
2. Upload the same file via browser (I used Chrome, for the record)
3. Compare modified date.

### Expected behavior
The modified date should be the same - the actual modified date.

### Actual behavior
The file uploaded via the app shows the upload date.
The file uploaded via the browser shows the actual modified date (mtime afaik).

### Environment data
Android version: 9
Device model: H3113
Stock or customized system: stock
Nextcloud app version: 3.14.1 (from F-Droid)
Nextcloud server version: 20.0.4 (docker:fpm)

### Logs
Needed?

**Comment by EngelPika32** [comment]
To make sure the files are the same, I compared the md5 and sha1 checksum for one set of example files.
- Android file (generated there)
- PC file (generated there)
- Uploaded file (downloaded to pc and generated there). 

As expected, they are all the same, and therefore the file wasn't modified on its way.

And, I uploaded my image folder with subfolders for month and year - the folders are correct, but the files show the upload date/timestamp.

**Comment by johannestophoj** [comment]
I can confirm this. Android 10. Just finished setting up my nextcloud server and tried uploading images via the Android. It was confusing and disappointing to enter the Photos app and see the year-old images in a seemingly random order, all under "January 2021".

**Comment by johannestophoj** [comment]
I did some more experimenting yesterday. Just uninstalling and reinstalling the android app returns the app to a messed up state. After clearing both cache and storage, and then uninstalling (and even deleting and recreating the user on the next cloud server) the uploads somehow still resumes upon reinstall. Deleting the nextcloud folder in Android/data/com.nextcloud.client on internal storage and SDcard finally allowed me to retry the uploads, but even then some of the upload history remains. Then I experienced the following:

-I set the "Storage path" to the SD card as I would otherwise get at intermittent error about lack of local storage.
-after that directories with ~20 files upload quickly and preserve the time stamps
-my Camera folder with 10GB of images did start to upload but unfortunately the time stamps were not preserved here. The upload completed although the app became very laggy

Could this be due to some caching that only happens for large jobs - and that the copy to the cache does not preserve the time stamps?

Today I wanted to retry and confirm the above behaviour. I could, except the Camera folder does not upload at all in spite of all the data clearing, uninstalling (did not remove and recreate the user on the nextcloud server this time though). I am not an Android developer but there clearly is some additional data that I cannot clear. 

I will consider rooting my phone to look at the /data/user folder, but clearly it should not be this problematic

**Comment by tobiasKaminsky** [comment]
We try to read the modification time, but if this fails, the current date is used.
The question is now why does it fail.

Do you see anything related in logcat?
 https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by johannestophoj** [comment]
From my investigations (but not being an android developer) I have the impression that this might be related to the files being on the SD card.

I tried to fetch the log information using adb and catlog but I cannot find anything about nextcloud catlog. My device is not rooted.

I have a lot of things. At the moment the auto upload does not work at all. Maybe it uploads new files. I have tried uninstalling and reinstalling, clearing cache and storage and deleting what I could from a file browser. A /data/user folder has been mentioned but I cannot find it - probably because my phone is not rooted. Even after clearing all those things and reinstalling some settings persist. 

I have given up on the app for now. Instead I am using AutoSync, which works well and preserves the timestamps

**Comment by EngelPika32** [comment]
The issue still exists and isn't solved at all.

Nextcloud app version: 3.15.1 (from F-Droid)
Nextcloud server version: 21.0.1 (docker:fpm)

Additionally, it seems to be not a good idea to edit files on the phone as the timestamp might corrupt due to later upload (no wifi) leading to incorrect files when editing the files somewhere else again. Luckily, I have versioning enabled allowing me to merge the difference again.

\
Adding to a previously mentioned behavior which I first saw as "okay"…
> We try to read the modification time, but if this fails, the current date is used.
The question is now why does it fail.

If it fails, it fails – then it should give proper feedback to the user and not silently ignore the issue.
The user should decide whether these files should be uploaded as "newly created" (aka. ignore the issue) or not.  


\
PS: Please do not close issues like these (bugs) automatically. They aren't solved simply because nobody had time to look into them / fix them and sending a "bump" message every few weeks would be stupid and spammy.

PPS: As of now, I can't root my device to gather additional log information. However, this issue doesn't seem to be "very new" when looking back. Hopefully, someone else can add more info.

**Comment by EmadFathy** [comment]
Still exists in the current version!!!! (when uploading via android).

**Comment by Igorgro** [comment]
Any plans to fix this? I tried to upload some of my photos from android phone to nextcloud but the creation date was set tu the upload date

**Comment by AlvaroBrey** [comment]
This was fixed by https://github.com/nextcloud/android/pull/9736 and more recently a bug was solved in #https://github.com/nextcloud/android-library/pull/985, which will be available in next version of the app
