### ISSUE TITLE
App does not offer obvious way to allow automatic uploads outside WiFi

### ISSUE THREAD

**Issue by arnwas** [nextcloud/android#7845]
### Is your feature request related to a problem? Please describe.

I cannot find the option to allow Photo Uploads via mobile Data (it waits for WiFi)

### Describe the solution you'd like

The settings show an easy to find option to tick or untick permission for uploads outside WiFi

### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
> I cannot find the option to allow Photo Uploads via mobile Data (it waits for WiFi)

your auto upload config for the folder likely has the option set "only on wifi", if that option is de-activated files will upload on your cellular connection if no wifi is available. Beware that files that have been detected before you change this option won't respect the change since the mechanism present at the moment doesn't respect config changes so each detected file is locked to the current state of the auto upload config at that very moment
