### ISSUE TITLE
Disable auto update snackbar in F-droid dev builds

### ISSUE THREAD

**Issue by proletarius101** [nextcloud/android#7865]
### Is your feature request related to a problem? Please describe.

It's known that the F-droid builds are always delayed for days. The in-app updater will then notify the updates when newer versions come out, and link to a build that's signed by NextCloud. But that can't be installed due to signature mismatch. The the snackbar will popup constantly, especially for the dev versions.

### Describe the solution you'd like

Disable update checks for F-droid builds since F-droid has an app updater.

### Describe alternatives you've considered

Add a switch to disable the in-app updater and disable the checks by default for F-droid builds. The update snackbar should link to the nextcloud page on F-droid.org.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by joshtrichards** [comment]
Since this only impacts the dev version I don't think it's too big a of a deal. In terms of prioritizing resources it's unlikely to get traction, but it's certainly a reasonable idea. I'll close for now since traction/interest has been low after nearly 3 years, but if you or someone wants to step up and give a PR making the appropriate changes a shot, feel free. I think the changes would be somewhere around here:

https://github.com/nextcloud/android/blob/5701d299c72706e315ef5dd03d9ce9ac52d2f2b6/app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java#L646

**Comment by joshtrichards** [comment]
Follow-up: On second thought, let's consolidate efforts into #1996 since the snackbar shouldn't even be coming up so often from the looks of it.

**Comment by joshtrichards** [comment]
Duplicate of #1996
