### ISSUE TITLE
Share by mail

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#794]
NC 12 will get a revamped "share by mail", which we do not even have in our app: 
With this it is possible to share a file/folder to an email address, which then has all the know options (permissions, expiration date, ...)

TODO:
- [ ] upon entering an email address it should be displayed "email@server.de (remote)" and "email@server.de (mail)"
- [ ] this is an external app and must be checked via capabilities
- [ ] later, as a separate issue: figure out if the local address book can be used to find additional sharees, but then filter for duplicates

CC @schiessle if I missed something
PR for NC12: https://github.com/nextcloud/server/pull/4136

**Comment by AndyScherzinger** [comment]
Uuuuh import issue here imho is also that we need to test this even for simply loading folder structures which contain files/folders that a re shared like this since it might lead to crashes when we don't handle this share type (happen before).

**Comment by schiessle** [comment]
With capabilities you can check if the app is enabled and if it supports password, expire date and secure drop. Share by mail exists since Nc11 but password, expire date and secure drop will only come with 12.

Also if expire dates for internal shares are supported can be checked by the capabilities.

Share type for mail shares is '4'

**Comment by Bertel3** [comment]
Is it possible to add this feature in one of the next releases? I think it very convenient to share something by mail. Too sad that this is currently not supported in the app.

**Comment by joshtrichards** [comment]
Fixed in #2700
