### ISSUE TITLE
uncommon file extensions are renamed to .bin when using the share from file explorer

### ISSUE THREAD

**Issue by ism00** [nextcloud/android#7962]
### Steps to reproduce
1 use any file explorer,  select a file with an uncommon file extension (ie: .backup or .keys)
2.  Press share and select Nexctloud as destination 

### Expected behaviour
- The file extension should remain as it is

### Actual behaviour
- .bin extension is added to the file name in nexcloud

### Environment data
Android version:  10

Device model: LYA-L29

Stock or customized system: Stock

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.2

**Comment by tobiasKaminsky** [comment]
Root cause is this:
https://github.com/nextcloud/android/blob/27572446cd0310389500e926fd6e3d29943c0e66/src/main/java/com/owncloud/android/utils/UriUtils.java#L70-L79

If we do not know extension (via getMimeTypeFromExtension(…)) then we assume one and append it.

My preferred solution would be to not tamper with name at all.
If there is no display name for what reason, then we should rather fail than upload with a different name.

@AndyScherzinger @ezaquarii

**Comment by AndyScherzinger** [comment]
Fully agree with your assessment @tobiasKaminsky 👍
