### ISSUE TITLE
Eclipse file structure

### ISSUE THREAD

**Issue by hannesa2** [nextcloud/android#8008]
You still stuck on old Eclipse files structure, where in root `build.gradle` a `apply plugin: 'com.android.application'` is located.

This all ends into a one-build.gradle-rules-it-all and a lot of `src` specifications

Do you have a plan to change this ?
I'll not make a pull request of this, because it's better, when a contributor with more trust fulfill this task and I guess all pull requests will need a rebase

**Comment by AndyScherzinger** [comment]
> You still stuck on old Eclipse files structure

true

> Do you have a plan to change this ?

currently it hasn't been on the agenda (as in high priority) but let's see what @tobiasKaminsky says and if he would find the time to refactor this (since my leisure time is rather limited to start such a task).

> I guess all pull requests will need a rebase

Probably, yeah

**Comment by tobiasKaminsky** [comment]
Indeed, this is something we should do, thanks for pointing out!
I currently see no easy way, as we have that many open PRs, so rebasing all of them will be a nightmare.
Last months were a bit tight, as I had to help out in Talk, which is now handled perfectly by Marcel, so maybe the best is to get PR count down to a reasonable number (e.g <5) and then do this.

**Comment by hannesa2** [comment]
I guess rebase will not cause that much issues, only create and delete of files needs manual adjustments.

Branches form this repositories could be done easily but from forks are much more an issue. The contributor have to do this, or you rape them by add that fork as remote and push branch to this repository. But doing this, cause more work then  approve and merge 😉

**Comment by AndyScherzinger** [comment]
Well, for most PRs coming from fork we do have push rights and also push to forks while that has been discussed with the contributor upfront in case they can't or don't have the time to do this themselves.

Other than that depending on how such a changes would change the overall file structures this might be an easy usually conflict-free rebase.

I'd also say it is easier to have a PR and rebase on-demand than wait for <5 PRs because that never happened since this repo existed (or the oC one)...

@hannesa2 could you maybe do an initial "draft" and we try to collaborate from there and get it to work and merge? Depending on if this would be fine with @tobiasKaminsky of course
