### ISSUE TITLE
Choose any folder on sdcard

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#802]
Wished via email:
Choose any folder on sdcard instead of the pre-defined data folder.

@przybylski maybe you want jump in here? :D

**Comment by AndyScherzinger** [comment]
Sounds good to me and also should the same thing be possible for the internal storage (to prevent the .nomedia issue some people dislike)?

**Comment by daemonkeeper** [comment]
This is more or less a duplicate of #429 and I can't emphasize enough how important this change is. The inability to choose a folder on a sdcard renders the nextcloud client more or less unusable to me, because the default location is protected by .nomedia as you mentioned. This way I cannot keep my data synchronized _and_ accessible through the Android media scanner API.

I would highly appreciate this change.

**Comment by tobiasKaminsky** [comment]
The external storage path will be /SD/Android/media and not "/SD/Android/data" to allow other apps to access the download files.
This will be part of the next version.

**Comment by daemonkeeper** [comment]
Personally that's fine with me as it solves the underlying problem for me. Thank you!

**Comment by tobiasKaminsky** [comment]
Then closing. 
It is always a good idea to have as less "techy" settings as possible.

**Comment by AndyScherzinger** [comment]
> The external storage path will be /SD/Android/media and not "/SD/Android/data" to allow other apps to access the download files.
This will be part of the next version.

> So, do we still need to choose any arbitrary folder? I think not so...

Not an arbitrary one, no but we should in the end offer both /data and /media because now we are reverting back to pre 1.4 so users that wanted to block media indexing will get mad. So the best would be to offer both with the hint for (SD card - media indexed / SD card - not media indexed).
