### ISSUE TITLE
Nextcloud trademark (permission for usage)

### ISSUE THREAD

**Issue by LukeVader-IV** [nextcloud/android#8101]
### Is your feature request related to a problem? Please describe.
wanting to use the nextcloud logo for a related app

### Describe the solution you'd like
I want to modify the icon for the app nextcloud yaga app as the developer originally wanted using the nextcloud circles inside the app icon

### Additional context
you can see more in the nextcloud yaga app github
https://github.com/vauvenal5/yaga/issues/87

the plan is to have the icon look something like this:
https://github.com/LukeVader-IV/yaga/blob/svg_icons/assets/icon/icon-original(2).svg

PS: I have no clue where i should post a question like this so if there if anyone knows where i can ask permission for this please tell me

**Comment by AndyScherzinger** [comment]
@LukeVader-IV the guideline can be found here: https://nextcloud.com/trademarks/ As per my understanding mixing it isn't allowed, neither is the combination with the Word "Nextcloud", same goes for the internal Apps, e.g. the Android Client for Deck is simply called Deck, not Nextcloud Deck.

For further discussion if needed best talk to @jancborchardt and @jospoortvliet

**Comment by stefan-niedermann** [comment]
To be consistent with other mobile clients, i'd suggest to simply remove the three circles and just use the "photo" icon?

**Comment by jospoortvliet** [comment]
Hi @LukeVader-IV Andy is right, we would have to give permission - we generally don't as it is confusing and people might think we are developing the app. But honestly, more importantly - the icon as you make it won't look very good, the logo is way to complicated to fit in something that is usually shown very small. An icon looks best when it is not too complicated!

Here's examples of the icon big, at 64, and at typical 32 and 16 pixel sizes:
![icon-64](https://user-images.githubusercontent.com/551757/109946366-73a67100-7cd8-11eb-95b6-83300b6bf54f.png)
![icon-32](https://user-images.githubusercontent.com/551757/109946021-17dbe800-7cd8-11eb-8d68-9e3efec20cb3.png)
![icon-16](https://user-images.githubusercontent.com/551757/109946019-17dbe800-7cd8-11eb-9d67-a7bc5177d709.png)
You see at small size, the Nextcloud logo becomes impossible to see.

Now see this one, which is simpler, at 64 and at 16:
![icon-edit-64](https://user-images.githubusercontent.com/551757/109946237-4ce83a80-7cd8-11eb-9a4a-558df128305e.png)
![icon-edit-16](https://user-images.githubusercontent.com/551757/109946017-17435180-7cd8-11eb-9e67-87c68dad8bae.png)

Even at small size, the logo looks roughly the same.

Now I'm not a designer, but my point is - you shouldn't include something as complicated as another logo into a logo you are making ;-)

**Comment by jancborchardt** [comment]
Yep, thanks to @AndyScherzinger @stefan-niedermann and @jospoortvliet for the explanation. :)
To sum it up:
- The Android app icons should all be circular in their default form
- They should all use the blue background fade (as posted by @stefan-niedermann at https://github.com/vauvenal5/yaga/issues/87 )
- Then a simple white icon over it which is the same as the server app they relate to
- They should _not_ use the Nextcloud icon. The only exception here is of course the main Files app

In the case of Nextcloud Yaga, I would recommend to do it like Deck:
- Use a descriptive name, like "Nextcloud Photos" since that is the app it relates to
- Use the same icon as Photos uses on the server: https://github.com/nextcloud/photos/blob/master/img/app.svg
- Use the circular blue-fade background

Cheers :)

**Comment by vauvenal5** [comment]
Hi everyone!

Since this this was not originally started by me I will chip in at this point for some clarifications:
- When I started I wasn't sure if it is alright to simply call it Nextcloud Photos, however, currently I do not want to go through the process of renaming it since this will probably also involve quite some things with both app stores. Maybe in the future.
- @jancborchardt does this mean I can simply reuse the icon from Photos or is it necessary to re-create it? 
- Blue-fade background will be added soon.

Cheers!

**Comment by jospoortvliet** [comment]
You can re-use the image from Photos as logo, re-creating it seems a bit of a wast of time ;-)
