### ISSUE TITLE
Option to change URL

### ISSUE THREAD

**Issue by Mister-Muffin** [nextcloud/android#8125]
You can edit the Url of your Nextcloud in the config file on the Deskop Nextcloud app, but i didn't find any option to do this in the Android Client.
This option would be nice to have, because with that you won't have to reconfigure your automatic uploads and other settings.

**Comment by Batcastle** [comment]
I second this. I've had to change my NextCloud instances' URL  a number of times and being able to change it in a config file would be much easier since I wouldn't have to delete all the data from the last URL and redownload who know how many GB worth of data all over again.

**Comment by eplanet** [comment]
I really want that feature too: I frequently switch the URL between local IP address when at home and remote DNS when outside. Why? Because DNS loopback doesn't work anymore, my provider blocked it and there's nothing I can do.

Feels like a simple feature but I guess it's easy only if you point to the same instance that happened to have its URL changed? Otherwise I guess things could go wrong if you point to a totally new instance. But anyway, an answer from Nextcloud would be appreciated!

**Comment by SuperdukeGates** [comment]
> I really want that feature too: I frequently switch the URL between local IP address when at home and remote DNS when outside. Why? Because DNS loopback doesn't work anymore, my provider blocked it and there's nothing I can do.

I have a better idea. Since you have the ability to setup a nextcloud server, how about setup a DNS server too ?

You can setup a DNS server with the recursive domain name resolution enabled, and additionally configure a private authoritative domain for your target domain. I assume that you own a ddns domain name from some provider and the domain name for your nextcloud server is mynextcloud.ddns.provider.net for example. Then you can configure your DNS server to host mynextcloud.ddns.provider.net as an authoritative domain (master) and give it an A record, such as 192.168.0.5 for example, which is your nexcloud server's IP address in LAN.

Then you have to configure your DHCP server from your router device to use your DNS server. For example, if your DNS server's IP is 192.168.0.1, then you have to setup the DHCP to distribute 192.168.0.1 as the DNS server. So that all the devices at home will use your private DNS server (192.168.0.1) to resolve mynextcloud.ddns.provider.net to 192.168.0.5. When you are outside, the mobile network provider will give you a formal DNS server and then you can resolve the real IP address of your mynextcloud.ddns.provider.net.

Then you'll never need to manually change the server's url.
