### ISSUE TITLE
It Stalls. Never download the Files and then Don't lettinge in to yhe app to see them

### ISSUE THREAD

**Issue by Vinz719** [nextcloud/android#8235]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Vinz719** [comment]
What do you mean? Closed motherfucker?
You didn't do anything

**Comment by christianlupus** [comment]
@Vinz719 you did not provide enough information for this issue to be valid. Please go to [github](https://github.com/nextcloud/android/issues/8235) and edit the first post. Update all the information as requested. The template is not there just for fun but because the developers need these information to track down the problem.
There are a dozen issues open with just violent and useless titles. I closed as it seemed to me this was some sort of spam. If you have a real problem, you might want to describe your problem in detail and perform the required steps to get this running.

One more hint from my side: Many of the users in the community are volunteers. So, please be so kind and keep your temper at bay. It might be unfortunate if something is not working. We are all people and try to make good code. Sometimes we fail. No need for provocations there, though.

Once you updated the issue to be valid and useful (in the sense that all required information is there), you can add a comment and notify me by @christianlupus and I will reopen.

**Comment by Vinz719** [comment]
I had explained all...there's no needcto say more...they don't send me the
email to update a f..password.
And now the server is gone and no way to open the app. I am sending you
detailed information about my phone .

**Comment by christianlupus** [comment]
@Vinz719 I am sorry, I will not reopen the issue. In fact, nothing really is explained in your burst of issues.

@Spartachetto is absolutely correct in his comment https://github.com/nextcloud/android/issues/8234#issuecomment-812731371. You are refusing to cooperate and help the devs to do their job. That way you are just a troll and will be ignored (and potentially banned if you continue to behave like that).

Good bye

**Comment by Spartachetto** [comment]
Vinz719 ....you were advised....

@ christianlupus was even too kind with you given your behaviour. Praise on him for his patience and kindness.

Suffice to say that we are still unable to understand who are the ones that don't send me the email to update a f..passwor

**Comment by Vinz719** [comment]
Garbage!!!!🤬
