### ISSUE TITLE
Upload on WiFi stopped working

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#8384]
### Steps to reproduce
0. use OpenBSD 6.9 httpd
1. connect to wifi
2. try uploading a file

### Expected behaviour
- Hm...

### Actual behaviour
- Connection error

### Can you reproduce this problem on https://try.nextcloud.com?
- No, as it uses different transfer encoding

If the server reply uses `Transfer-Encoding: chunked`, `OkHttp` returns a reply with content length of -1.
This is obviously causing `ConnectivityService.isInternetWalled()` to return true:

https://github.com/nextcloud/android/blob/247d422b3748f0c2b6ea270bdf3613dba0abe6cc/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java#L77

When chunked encoding is used (as happens with FastCGI), content length is simply not available.

**Comment by barbosaaob** [comment]
My Android client also can't upload to my OpenBSD server with httpd.
iPhone client works fine with the same server.

**Comment by maanloper** [comment]
I do not know if my current problem is related, but since ~2 weeks, my phone refuses to AutoUpload, whereas before it worked like a charm. For 'new' files it shows 'Connection error' and for files that have tried for longer it shows 'Waiting for non-metered wifi'. As far as I'm aware, nothing has changed on my side (maybe android client auto-updated in the background?), but suddenly a working feature stopped working...

**Comment by tootbrute** [comment]
I also have this problem it looks like it started about 4 days ago. I now get "Connection Error" for all my files.

Server is Debian on Yunohost
Android is on LineageOS 18.1
