### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by dsnettleton** [nextcloud/android#8688]
### Steps to reproduce
1. Log in
2. Remove account 
3. Add account again

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
Hi @dsnettleton, thanks for contributing! Unfortunately, developers need a _lot_ more information than what's here to fix bugs. That's why the issue template is there - you need to fill it out.

Closing since there isn't any actionable information here, but I'd be happy to reopen if more info becomes available :)
