### ISSUE TITLE
Enhance "no favorites" 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#871]
https://github.com/nextcloud/server/pull/4422

**Comment by tobiasKaminsky** [comment]
@jancborchardt also in yellow?

This is our current view
![fileodwwc6](https://cloud.githubusercontent.com/assets/5836855/25278961/38bc8706-26a5-11e7-9349-b53f39eda055.png)

**Comment by jancborchardt** [comment]
Yep, the changes to be made are:

- Star should be yellow, just like on the web itnerface (for clarification – only the yellow star and the blue empty folder icon get color – just to not have everything bland, and also because they are quite important core functions :)
- Text adjusted to »No favorites yet« (add »yet«)
- Title on top adjusted to »Favorites«

Ok? :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'll do the changes so you can focus on other tasks :)

**Comment by AndyScherzinger** [comment]
![device-2017-04-24-102146](https://cloud.githubusercontent.com/assets/1315170/25330142/de31b108-28de-11e7-8858-2bdfb760e1b1.png)
