### ISSUE TITLE
App doesn't use DNS to lookup IP Address

### ISSUE THREAD

**Issue by modzilla99** [nextcloud/android#8877]
### Steps to reproduce
1. Have a local DNS that resolves the Nextcloud domain to a local IP address
2. Login to Nextcloud locally
3. Try to use Nextcloud otg (Port forwarding enabled with public IP in the right A record of course)

### Expected behaviour
- Nextcloud with sync all data

### Actual behaviour
- The app tries to connect but fails in doing so
- When enabling my VPN the App instantly syncs
- The page is btw fully working in Firefox/Chrome

### Can you reproduce this problem on https://try.nextcloud.com?
- No I cannot since I can't resolve it to a local IP

### Environment data
Android version: 11

Device model: OnePlus 7 Pro

Stock or customized system: Stock OxygenOS

Nextcloud app version: 3.17.0

Nextcloud server version: 22.1.0

Reverse proxy: Traefik 2.5

### Logs

There are no logs since it tries to connect to a non routable IP address

**Comment by sta11** [comment]
Hello,

I have the same problem with my fresh Nextcloud installation.

I started a docker-compose version of Nextcloud 21.0.4 on a VM and make it accessible from Internet through a reverse proxy installed on a different VM (Traefik 2).
I followed the Nextcloud documentation for the reverse proxy configuration (https://docs.nextcloud.com/server/21/admin_manual/configuration_server/reverse_proxy_configuration.html).

I am able to sync my files with the Nextcloud desktop app (no problem to add a new account) and use the web interface without any issue.

If I try to configure an account on the latest version of the Android app, I am stuck at the testing connection step, no matter the Android version.
If I establish a VPN connection to my network from my Android device, the testing connection step of the Nextcloud wizard completes successfully. In that case I am able to configure the account on the Android device and sync my files.

I tried to use nginx as a reverse proxy instead of Traefik 2 without more success.

I am not familiar with Nextcloud yet, so if there is anything (logs, tools, etc...) I can run or read to find some relevant information, I would be happy to contribute to the identification and resolution of this problem.

Thanks

**Comment by sta11** [comment]
> Hello,
> 
> I have the same problem with my fresh Nextcloud installation.
> 
> I started a docker-compose version of Nextcloud 21.0.4 on a VM and make it accessible from Internet through a reverse proxy installed on a different VM (Traefik 2).
> I followed the Nextcloud documentation for the reverse proxy configuration (https://docs.nextcloud.com/server/21/admin_manual/configuration_server/reverse_proxy_configuration.html).
> 
> I am able to sync my files with the Nextcloud desktop app (no problem to add a new account) and use the web interface without any issue.
> 
> If I try to configure an account on the latest version of the Android app, I am stuck at the testing connection step, no matter the Android version.
> If I establish a VPN connection to my network from my Android device, the testing connection step of the Nextcloud wizard completes successfully. In that case I am able to configure the account on the Android device and sync my files.
> 
> I tried to use nginx as a reverse proxy instead of Traefik 2 without more success.
> 
> I am not familiar with Nextcloud yet, so if there is anything (logs, tools, etc...) I can run or read to find some relevant information, I would be happy to contribute to the identification and resolution of this problem.
> 
> Thanks

In reply to myself, I found the origin of my issue and solved it.
My reverse proxy IPv6 address was not set appropriately.

- From Android, the Nextcloud app tried only to contact my reverse proxy by using IPv6. As far as I understood, it is an Android behavior, not specific to the Nextcloud app
- From my desktop computer, the Nextcloud desktop app or my web browser were able to contact the reverse proxy. I suppose there is an automatic fallback to IPv4 if IPv6 does not work in that case

Setting IPv6 address on my reverse proxy solved this issue.
For info, my reverse proxy is a VPS hosted by OVHCloud. I followed this guide to setup my VPS IPv6 address: https://docs.ovh.com/asia/en/vps/configuring-ipv6/

Thanks

**Comment by modzilla99** [comment]
Same here, the IPv6 DNS entry was wrong! Sorry for opening this bug
