### ISSUE TITLE
App should give a notification when server is not reachable

### ISSUE THREAD

**Issue by joekerna** [nextcloud/android#894]
My internet is down and my Nextcloud not reachable.
I think a nice enhancement of the app would be to notify me when the server is not reachable or hasn't been reachable for a certain time without me checking.

**Comment by AndyScherzinger** [comment]
Good idea @joekerna! 

@tobiasKaminsky @mario I'll post a mockup when I find the time how this can/should look like. Since I already discussed displaying such an info with @eppfel but never found the time to take care of writing an issue or posting a mockup, sorry...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should we further enhance what we have now? 

Right know the client, when browsing files/folder will display such an information. I am unsure if we should add a OS notification to it since this might happen quite often so its likely to annoy most of the users while only be of help for a extremely small amount of people.
I'd vote to leave it as is.

**Comment by joekerna** [comment]
How about an OS notification with an option like _don't bother me again_. That way the user can decide and in worst case is only annoyed once.

**Comment by AndyScherzinger** [comment]
> How about an OS notification with an option like don't bother me again. That way the user can decide and in worst case is only annoyed once.

Hmm, that might be an option. Looping in @nextcloud/designers and developers @tobiasKaminsky @mario @ardevd for (UX) feedback:
Issue is about showing a notification in case the server can't be reached while the notification gives the user the option to disable such notifications.

**Comment by tobiasKaminsky** [comment]
Same as Jan. If the app is in background, it should not give any warning. Only if the app is used, the user is interested if a connection is offline.

> What we really need to work on is improve the UX when offline or on bad connection. :)

Right, in short the ideal scenario would be that any action can still be done, but remembered and then done when online again, with proper sync/conflict handling. But this is a very very long time to go…)

(not talking about AutoUpload, where it is ok to notice the user about a failing upload job in background)

**Comment by tobiasKaminsky** [comment]
Same as Jan. If the app is in background, it should not give any warning. Only if the app is used, the user is interested if a connection is offline.

> What we really need to work on is improve the UX when offline or on bad connection. :)

Right, in short the ideal scenario would be that any action can still be done, but remembered and then done when online again, with proper sync/conflict handling. But this is a very very long time to go…)

(not talking about AutoUpload, where it is ok to notice the user about a failing upload job in background)

**Comment by joekerna** [comment]
It happened to me again: My server was down which I didn't know until I urgently wanted to download a file on the go. If I had known I could have fixed the server much quicker.
Also the app doesn't even tell me that the server is down when opened. It just doesn't list the directories (it says they are empty).
Does this not bother anyone else?

**Comment by AndyScherzinger** [comment]
> Also the app doesn't even tell me that the server is down when opened. It just doesn't list the directories (it says they are empty).
Does this not bother anyone else?

@tobiasKaminsky @jancborchardt at least this is something the app should tell the user, maybe through the same mechanism we already have for "no internet connection", like "server unreachable"

**Comment by tobiasKaminsky** [comment]
We have currently "no internet connection" and "maintenance mode".
A "server unreachable" should be monitored by the server admin / watchdog and fixed on their side.
But for transparency it does not hurt, if we can show it.

**Comment by tobiasKaminsky** [comment]
apache running, but nc not available, e.g. moved:
405 method not allowed on refresh folder

apache not running, e.g. server completely down:
"no internet connection" shown in app

Which case was it for you @joekerna?

**Comment by joekerna** [comment]
The server was completely down but _No internet connection_ was not shown

**Comment by AndyScherzinger** [comment]
> apache not running, e.g. server completely down:
app should show "server unreachable"

**Comment by tobiasKaminsky** [comment]
So we will have with next pr
- ssl cert warning
- maintenance mode
- no network (e.g. device offline)
- server not available

![2019-02-06-105828](https://user-images.githubusercontent.com/5836855/52333693-32124180-29fe-11e9-8e6a-1c8a62613ecb.png)

@joekerna still it is strange that you do not see any warning.
Do you run latest version?

**Comment by joekerna** [comment]
I checked again: When I stop nginx I get _no internet connection_

Yesterday the port forwarding in my router wasn't set up correctly and I did not get any warning

**Comment by tobiasKaminsky** [comment]
It shows only a warning if you go into/refresh a folder (a network call is executed).
Just opening the app shows nothing.

**Comment by jonathanmmm** [comment]
My Nextcloud Server runs behind nginx proxy on another nginx server.
My front nginx server is almost all the time online. But the second server is shutting down automatically when not needed. It needs to be woken up manually.

Proxy pass response normally with error code 502. I changed it to 503 with custom error_page.

Mynextcloud.com gets a error page which redirects to another website (startnextcloud.org, to start the server remotely). 
Mynextcloud.com/status.php just gets the standard nginx 503 error page.


The App does not show server offline.
I thought the clients check for the status.php file and if this is error 503 or similar they will say server is unavailable.

No that my nginx before replies with 503 still the notification is not shown. Can browse folders and says by folders that they are empty.

Is it because I redirect to another URL?
(through Meta refresh in html header)

I don't redirect status.php.

I have Android 3.6.0
Nextcloud 15.0.7 (should not matter, the server is in this case down).

Do I have to give another error code then 503 or which path are the clients checking (Android, iOS, Windows) to see if the server is available? Is it something different then status.php?
