### ISSUE TITLE
Tablet friendly UI?

### ISSUE THREAD

**Issue by Aasemoon** [nextcloud/android#912]
Hi there,
I imagine this may have already come up, but I don't think it has been addressed. So I would like to request for this issue to be fixed.

### Actual behaviour
When browsing the app on a tablet in landscape mode, the content [files, folders et al] show up in a narrow space on the left side of the screen, leaving the rest of the screen empty. Especially when browsing pictures for instance, this is not very user friendly.

### Expected behaviour
Well I think the content should be spread on the whole page rather than a small margin on the left.
 

### Environment data
Android version: 6.0

Device model:  Sony tablet Z2

Nextcloud app version: 1.4.2

**Comment by tobiasKaminsky** [comment]
@jancborchardt @eppfel 
Indeed this must be improved.

Current file listing in landscape on a tablet:
![filejgaugc](https://cloud.githubusercontent.com/assets/5836855/25553533/18285ca6-2cb6-11e7-8186-d13a190ecae1.png)

- clicking on an image leads to a fullscreen image.

Long pressing on a file -> details
![fileizxw8d](https://cloud.githubusercontent.com/assets/5836855/25553543/60dd71fc-2cb6-11e7-825b-e7f58a43022e.png)

My rough, not well thought idea, is to preview the file on the side if you click on the file name.
If you then click on the image you toggle fullscreen (with then swipe left/right to show other images/videos).

Remaining question: what shall we show if we first enter a folder?

**Comment by Aasemoon** [comment]
Personally what I'd like to see mainly is for the gallery view of images et al [not having clicked on anything] to be spread across the whole page in the landscape mode, similar to the way it is in portrait mode.

**Comment by twosky2000** [comment]
I just saw the iOS app. Are Tiere any communications between the projects? IOS has preview functions Android don't.

**Comment by eppfel** [comment]
mh, I guess we need a proper Tablet design audit to make sophisticated proposals.

Just a quick response to @tobiasKaminsky: I highly recommend against different interactions in the same app. With Android 7 the layout could switch from one to the other on the same device...

**Comment by jancborchardt** [comment]
As an example, Dropbox shows the left sidebar by default on tablet:
![](https://lh3.googleusercontent.com/Jwef0acZpcPHlbRn90csGJj4uFZeWQEMfF2fhjzUNbXXQ-OcJXpkzVh9Al8sOyK7aQ=h900)
On iOS they do it like we do though: https://itunes.apple.com/us/app/dropbox/id327630330?mt=8

Google drive just does whole-screen of thumbnail view:
![](https://lh3.googleusercontent.com/wykzPWwa8_R-Mzq2jvtlO1Kk8K4FvMBPPUyO8Tn9KaPqFmHkEWXF-R110-9MbQUUyw=h310)

The essence is that focus on the content, that is the files which are opened, is very important.

**Comment by tobiasKaminsky** [comment]
As I want to solve #924 and it is somehow related, what is the idea here?
Big thumbnails like google drive does it, are only useful for images as otherwise you will just see a big e.g. zip-archive icon.

**Comment by jancborchardt** [comment]
What do you think about doing it like Dropbox? For tablets, showing the sidebar on the left, and the file listing in the main view? Viewing a file takes over the whole screen.

**Comment by tobiasKaminsky** [comment]
Fine for me.
File listing then would then be spread across the remaining space, showing one item per line on file list and many items on the grid view.

What happens to this file detail view:
![fileizxw8d](https://cloud.githubusercontent.com/assets/5836855/25553543/60dd71fc-2cb6-11e7-825b-e7f58a43022e.png)

**Comment by AndyScherzinger** [comment]
File detail view would then be an activity getting launched and not a fragment being shown on the right side. Other than that having file list view on landscape spread all across an 10 inch screen... seems wrong to me and isn't done by Google (e.g. GMail) or Apple (e.g. mail).

Grid is grid and should imho always spread across the screen (since it is a certain way of looking at a lot of data more or less visually) and a list is a list and works best with a master detail view concept. Just my 2 cents...

**Comment by AndyScherzinger** [comment]
For a quick win I'd say go for @jancborchardt's suggestion and make everything full screen

**Comment by jancborchardt** [comment]
File detail view is something I wanted to align to the server for a long time already. It's basically the right sidebar, but a less beautiful version of it.

Check out how the Mail.ru cloud app does it:
![screenshot_2017-06-15-09-37-51](https://user-images.githubusercontent.com/925062/27579635-821369ee-5b28-11e7-8662-4d9ba163a5ad.png)

Ideally we combine that with sharing in a tabbed view, because they both should have the big preview and name. In the future we can also put the other items from the server sidebar in there lile Activity, Comments, Versions as tabbed items, just like on the server.

**Comment by tobiasKaminsky** [comment]
Why is there now a popup for file details?

Can you please make some mockups (or find similar images) which shows 
- regular file display with file listing
- regular file display with grid view
- show file details 
- image preview

so that we have all views at a glance. The approach now (adding more and more ideas) is just too confusing for me :-/

**Comment by AndyScherzinger** [comment]
I already started working on that, see: https://github.com/nextcloud/android/pull/1127#issuecomment-311340916

beware that this is strongly WiP so don't pay to much attention to the UI itself since I just started getting the infos into thhe UI and will then move on to a tabbed pane and maybe for images (might be iteration 2) a preview mode like in Jan's screenshot which I already implemented on the user info screen.

So bare with me and just wait a little longer, I think I get what @jancborchardt is proposing for the details screen itself and it is also what I am working on as a side track.

**Comment by AndyScherzinger** [comment]
issue for FAB positioning on tablet UIs: #1509

**Comment by comradekingu** [comment]
Considering most people are right handed and left eye dominant (?) Wouldnt the opposite of this make sense:
![bilde](https://user-images.githubusercontent.com/13802408/30175022-5cefbeb6-93fd-11e7-9e13-7bc1be16c20f.png)

Or is your hand then in the way of what you are trying to see? To me it seems if in the way, it would be preferable to only have it cover the latter part of the filename, though that is where the difference lies.

**Comment by tobiasKaminsky** [comment]
Close in favor of https://github.com/nextcloud/android/issues/6769
