### ISSUE TITLE
Client Certificate Authentication ( Please do not say its a duplicate )

### ISSUE THREAD

**Issue by kushmittal2009** [nextcloud/android#9189]
### Steps to reproduce
1.  Open the app
2. Connect to a server with client certificate authentication
### Expected behavior
The expected behavior is that the app connects to the server with no issues.
### Actual behavior
Right now when I connect to my server that has client certificate authentication it gives me an ssl error.

### Environment data
Android version:
Tried on 12,11 and 10
Device model: Samsung s6 Lite, Pixel 3, Samsung s9+, Samsung s20 plus ultra 5G, Lenovo m10 plus, android emulator x64_86

Stock or customized system:

Nextcloud app version: 3.17.1

Nextcloud server version: 22

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by strugee** [comment]
Hi @kushmittal2009, thanks for contributing to Nextcloud. Unfortunately, this looks like a duplicate of #603. If so, I would suggest closing this issue, subscribing to that issue, and leaving a 👍 reaction (but please do not comment "+1", "👍", etc. because that generates useless email for everyone watching either this repository or the issue). If not, can you clarify why this issue is different?
