### ISSUE TITLE
auto upload fails with "connection error", resumes for one picture after reconnecting wifi and fails again

### ISSUE THREAD

**Issue by SirSiggi** [nextcloud/android#9258]
### Steps to reproduce
1. take picture
2. let auto upload do its thing and let it fail
3. disable and re-enable wifi
4. repeat

### Expected behaviour
- All photos should be uploaded without connection errors and manual interaction in between.

### Actual behaviour
- Auto-upload stops after every picture and fails until wifi is deactivated and activated again.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11 RKQ1.200826.002

Device model: Poco X3 NFC

Stock or customized system: Stock (MIUI Global 12.5.3 Stabil 12.5.3.0(RJGEUXM)

Nextcloud app version: 3.17.1

Nextcloud server version: 22.2.0 (running in docker)

Reverse proxy: traefik2 2.5.3 (running in docker)

#### Web server error log
```
no visible activity for auto upload
```

#### Nextcloud log (data/nextcloud.log)
```
see files
```

[config and logs.zip](https://github.com/nextcloud/android/files/7531742/config.and.logs.zip)

### Additional information
The issue seems to be related to something network dependend. All my old files were uploaded correctly after setting up the client, after some days it stopped working. Using my dataplan does not work either (same issue). However, yesterday as I connected to a different wifi, it worked fine at least for one pass.

From the outside the service is avaiable via: FritzBox => port forwarding (80, 443) => Synology-NAS => traefik2 (on 80 and 443) => Nextcloud in docker

From the inside the device avoids reaching out to the public IP. The FritzBox uses a pihole-Server for DNS and gives out the internal IP of the Synology NAS, so that the phone can directly connect using the local IP.

**Comment by balert** [comment]
I am having the same issue for a few weeks already. My setup seems very similar to yours. Docker-based nextcloud:production, container image self-built for cron support, Fritzbox network, but no pihole in my case. I was already suspecting something like IPv4/IPv6 mess, but so far that's only a feeling. 

I believe the problem started when I disabled my pihole and let the Fritzbox do DNS alone. Since then I am not able to provide local IP lookups for IPv4 because FritzBox does not support that. Before that, my pihole was providing the local IPv4 address of the nextcloud.

**Comment by SirSiggi** [comment]
> I was already suspecting something like IPv4/IPv6 mess, but so far that's only a feeling.

This was my first guess, too. However, I'm simply not that proficient in ipv4/6 issues and docker so that I could debug the issue myself.

Nevertheless, if the Nextcloud-app itself is working perfectly, I don't think its a simple network issue. Every other function of Nextcloud simply is available and working as expected.

**Comment by balert** [comment]
> Every other function of Nextcloud simply is available and working as expected.

Yeah, same here, but that error already persisted several weeks.

**Comment by martin-schulze-vireso** [comment]
I debugged my side further and actually had an IPv6 issue: My server setup uses docker, but docker does not use ipv6, but my domain has an ipv6 entry, so the App tried to contact the server via ipv6 and failed. After setting up docker to host on ipv6 as well, the connection works correctly.

**Comment by balert** [comment]
@martin-schulze-vireso I believe in my case it is more likely to be related to TLSv1.3, which is the only version I support (on purpose). 

I just double checked the IPv6 connectivity, and the server is definitely reachable via both IPv4 and v6, so it should **not** be caused by the server's connectivity. In theory it **could** be caused by the client, which is using various networks (LTE, and various Wifis), but since the problem also occurs in my home wifi, which has correct v4 and v6 connectivity, I believe this is unlikely.

**Comment by SirSiggi** [comment]
Is there any active development in this or can anyone help me with that issue? If I can help by providing any information, feel free to ask.

Thanks.

**Comment by joshtrichards** [comment]
There are a couple issues and PRs here and in the library repo that might be relevant. From the server logs you provided, all the Android transactions failed authentication.

Can you confirm you're still experiencing this behavior today, @SirSiggi?
