### ISSUE TITLE
Automatic Uploads Settings ... displaying too much thumbnails

### ISSUE THREAD

**Issue by ne20002** [nextcloud/android#9311]
### Steps to reproduce
1. Open Settings - Automatic Uploads

### Expected behaviour
2. Thumbnails are displayed for a few images/videos plus
3. a last one grayed out with +NN shall appear.

### Actual behaviour
2. Thumbnails are displayed for a few images/videos plus
3. all thumbnails for the +NN images are displayed, all grayed out, all with +NN displayed.

It looks like **all** files in the possible upload folders are loaded and thumbnails are created ... looking at #8863 this might also have been the case before but before 3.18 only a few thumbnails have been displayed. Now thumbnails for all files are displayed.

### Can you reproduce this problem on https://try.nextcloud.com?
Not tried

### Environment data
Android version: 
11

Device model: 
Samsung S10e

Stock or customized system:
Stock

Nextcloud app version:
3.18

Nextcloud server version:
22.2.3

Reverse proxy:
nginx

**Comment by ne20002** [comment]
I wonder if #8863 has something to do with this ... trying to read all images in all possible upload folders for thumbnail creation may take a long time.

**Comment by bd-g** [comment]
I have this same issue

**Comment by AndyScherzinger** [comment]
Do you have a screenshot for this? I just checked and I get 8 thumbnails per folder display in auto upload, the last with the +NN - nothing else

**Comment by AlvaroBrey** [comment]
I also can't reproduce it either on android 10, 11 or 12.  @bd-g do you also have a Samsung device? Maybe it's a Samsung-specific thing...

**Comment by bd-g** [comment]
I do have a Samsung Galaxy S(

One UI Version - 2.5
Android Version - 10


One
*Brent George*
*Brigham Young University*
*Computer Engineering*
***@***.*** ***@***.***>*
*1-(248)-787-1795*

**Comment by ne20002** [comment]
I have this on a Huawei Tablet as well ...

**Comment by q-wertz** [comment]
Same on Nokia 7 plus (Android 10)

**Comment by b-pfl** [comment]
I can confirm this behavior (Samsung Galaxy S9, Android 10, NC client 13.18.0, own NC server 22.2.3).

**Comment by tleb** [comment]
Same issue on a Xiaomi Mi A3, Nextcloud Android 3.18.1 RC1, Android 10. After testing, it seems that the issue comes from 303ebe007113019babdfc018587ea5a6cf01f017. Basically, the `LIMIT` does not apply anymore: the content provider ignores `ContentResolver.QUERY_ARG_LIMIT` in the bundle.

The `android.content.ContentResolver::query` method signature that was used previously (in `com.owncloud.android.datamodel.MediaProvider::getImageFolders`):

```kotlin
public final @Nullable Cursor query(@RequiresPermission.Read @NonNull Uri uri,
        @Nullable String[] projection, @Nullable String selection,
        @Nullable String[] selectionArgs, @Nullable String sortOrder,
        @Nullable CancellationSignal cancellationSignal)
```

And the query method signature used after this commit (now in `com.owncloud.android.datamodel.ContentResolverHelper::queryResolver`):

```kotlin
public final @Nullable Cursor query(final @RequiresPermission.Read @NonNull Uri uri,
        @Nullable String[] projection, @Nullable Bundle queryArgs,
        @Nullable CancellationSignal cancellationSignal) 
```

(On my device, `Build.VERSION.SDK_INT >= Build.VERSION_CODES.O` returns true so it uses this.)

From this, I looked inside `ContentResolver` to see how it implemented the first signature, and it looks like this:

```kotlin
public final @Nullable Cursor query(@RequiresPermission.Read @NonNull Uri uri,
        @Nullable String[] projection, @Nullable String selection,
        @Nullable String[] selectionArgs, @Nullable String sortOrder,
        @Nullable CancellationSignal cancellationSignal) {
    Bundle queryArgs = createSqlQueryBundle(selection, selectionArgs, sortOrder);
    return query(uri, projection, queryArgs, cancellationSignal);
}

// And the implementation of createSqlQueryBundle:
public static @Nullable Bundle createSqlQueryBundle(
        @Nullable String selection,
        @Nullable String[] selectionArgs,
        @Nullable String sortOrder) {
    if (selection == null && selectionArgs == null && sortOrder == null) {
        return null;
    }
    Bundle queryArgs = new Bundle();
    if (selection != null) {
        queryArgs.putString(QUERY_ARG_SQL_SELECTION, selection);
    }
    if (selectionArgs != null) {
        queryArgs.putStringArray(QUERY_ARG_SQL_SELECTION_ARGS, selectionArgs);
    }
    if (sortOrder != null) {
        queryArgs.putString(QUERY_ARG_SQL_SORT_ORDER, sortOrder);
    }
    return queryArgs;
}
```

[Source code](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/ContentResolver.java)

As such, changing `com.owncloud.android.datamodel.ContentResolverHelper::getQueryArgsBundle` to something like the following solves the issue for me:

```kotlin
    @RequiresApi(Build.VERSION_CODES.O)
    private fun
        getQueryArgsBundle(selection: String?, sortColumn: String?, sortDirection: String?, limit: Int?): Bundle {
        return Bundle().apply {
            if (selection != null) {
                putString(ContentResolver.QUERY_ARG_SQL_SELECTION, selection)
            }

            // Make sure the direction is valid (ASC or DESC)
            val sortDirection2 =
                if (sortDirection == SORT_DIRECTION_ASCENDING) SORT_DIRECTION_ASCENDING else SORT_DIRECTION_DESCENDING

            if (sortColumn != null && limit != null) {
                putString(ContentResolver.QUERY_ARG_SQL_SORT_ORDER, "$sortColumn $sortDirection2 LIMIT $limit")
            } else if (sortColumn != null) {
                putString(ContentResolver.QUERY_ARG_SQL_SORT_ORDER, "$sortColumn $sortDirection2")
            } else if (limit != null) {
                putString(ContentResolver.QUERY_ARG_SQL_SORT_ORDER, "LIMIT $limit")
            }
        }
    }
```

I don't know enough about the Android environment to know in what context the SDK version condition returns true or false and I don't know enough to make assertions about why `QUERY_ARG_LIMIT` doesn't have an impact (`QUERY_ARG_SQL_LIMIT` isn't functional either but it requires API level 30 so it cannot be a solution).

Is this an appropriate solution? It would have been cleaner IMO to rely on `QUERY_ARG_LIMIT`, `QUERY_ARG_SORT_COLUMNS` and  `QUERY_ARG_SORT_DIRECTION` but I found no appropriate solution.

This is my first time touching Android dev, do not hesitate if I can provide more data from a device on which the bug occurs.

**Comment by AlvaroBrey** [comment]
Thanks for the detailed analysis @tleb, this is very helpful.  Unfortunately, the reason that `ContentResolverHelper` is precisely that we can't put the `LIMIT` inside the `SORT_ORDER` string directly, as it will throw an exception on Android 11+. See https://stackoverflow.com/questions/66280961/contentresolver-query-method-throws-invalid-token-limit-error.

From your reply I understand that it might be better to leave the old way until android 11 (api 30) instead of O (api 26). However, the first reporter was using android 11 and it was still broken, so I don't know what to think of it.

It doesn't help that I can't reproduce this in any emulator (over or under android 11). It seems to be something implementation-dependent. I will need to do some more testing.

**Comment by tleb** [comment]
One first workaround would be to ensure we don't read the full number of items from the cursor by stopping the iteration if we go above the item limit. However, this would hide if the `LIMIT` worked and we might never detect in the future if the `LIMIT` stops working for everyone.

I believe the main reason to not settle on such a solution would be performance, but it seems to be OK. On my device, having something like 1000 pictures:

 - 294ms for `getImagesFolder` with the cursor including all items.
 - 220ms for `getImagesFolder` with the cursor including all items but stopping the iteration when `i >= itemLimit`.
 - 202ms for `getImagesFolder`, with `getQueryArgsBundle` patched as above to have a functional `LIMIT` on my device.

What about try-catching the version with `QUERY_ARG_LIMIT`, resting on the `QUERY_ARG_SQL_SORT_ORDER` version if it fails? If this still fails, no `LIMIT`. In all cases, have a fallback check in `getImageFolders` + `getVideoFolders` to stop iterating if too many results were returned.

**Comment by AlvaroBrey** [comment]
If anyone wants to test, I pushed a patch in https://github.com/nextcloud/android/pull/9597. There's a QA apk there.

The patch should go out in 3.18.1.
