### ISSUE TITLE
Login crashes when server URL contains invalid characters

### ISSUE THREAD

**Issue by Mariehf64** [nextcloud/android#9365]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hello, please fill in the issue template with a description of the error and steps to reproduce, and reopen this issue if appropriate. Thank you.

**Comment by Mariehf64** [comment]
Hi,
This is happening when there is a blank in the address on the Windows after starting the app to open the cloud. 
This is because when I enter a dot a blank is automatically inserted.

Example:

Sync2. Totalcloud. Fr

**Comment by AlvaroBrey** [comment]
> Hi, This is happening when there is a blank in the address on the Windows after starting the app to open the cloud. This is because when I enter a dot a blank is automatically inserted.
> 
> Example:
> 
> Sync2. Totalcloud. Fr

Thanks for bringing this to our attention. We already had a partial fix for a related crash lined up in #9354, but this particular case had escaped.  This will be fixed in 3.18.1.

_However_, this doesn't mean that the app will accept an URL with spaces in it, that's still an invalid URL. It will just not crash.

**Comment by Mariehf64** [comment]
Hi,

It took several trials before I understood that the issue was the blank
because it was very small on my mobile and almost not visible.
I was sure that my url was correct, but imagine somebody trying for the
first time, he might think his url is wrong (the blank is added
automatically).
I think that at least an error message saying "Please check there is no
blank on your address" could be helpful.

Marie




Le ven. 26 nov. 2021 à 10:58, Álvaro Brey ***@***.***> a
écrit :

**Comment by AlvaroBrey** [comment]
@Mariehf64 unfortunately we can't do that, as it can happen with many invalid characters and not only spaces. Moreover, adding spaces depends on the keyboard that you're using (GBoard and the AOSP keyboards don't add spaces).

We could however add a generic message that the URL is invalid, rather than just a "couldn't connect" message.
