### ISSUE TITLE
Can't change share permissions

### ISSUE THREAD

**Issue by lampgnu** [nextcloud/android#9405]
### Steps to reproduce
1. Create folder
2. Share the folder 
3. Select share link
4. Select allow upload and modify
### Actual behaviour
- When I select on Allow upload and modify  remain on read only

### Environment data
Android version: 11

Device model: Xiaomi Redmi 9

Stock or customized system: Miui 12.5.1

Nextcloud app version: 3.18.0

Nextcloud server version: 22.2.3

With the nextcloud web not are anomalies.

**Comment by lampgnu** [comment]
Hello,
this bug is also versioned 3.18.1.
You can verify plecase?
Thanks you.

**Comment by lampgnu** [comment]
Hello, 

now not is possible share file with upload and modify permission.

Nextcloud App 3.19.0 RC2

**Comment by AlvaroBrey** [comment]
Can't reproduce this; I just tested it and it works fine for me.

After selecting "allow upload and editing", are you accepting the changes? ("share and copy link" button)

**Comment by lampgnu** [comment]
Hello,

I accept the change.

View my video for the the problem:

https://my-c.it/index.php/s/KqTGTbSQXLQjbx2

Thank you.

**Comment by AlvaroBrey** [comment]
Thanks for the video. Unfortunately, I still can't reproduce the problem when following your exact steps, either in 3.18.0 or master. 

If you can, I'd like you to try to reproduce the problem with another server. That way we can figure out if it's a server issue or a client issue, You can use [try.nextcloud.com](try.nextcloud.com) for that. How to login:

1. Go to [try.nextcloud.com](try.nextcloud.com) through a web browser and choose the "Instant trial" ("Take me there!"). You will be logged into `demo2.nextcloud.com` automatically.
2. Go to Settings > Security in the web UI and create a new app password. The name is not important. You will be shown a username and password.
3. Open the Android app and tap Log In. Enter `demo2.nextcloud.com` as a server address.
4. On the next screen, choose "Alternative login with app token" instead of the normal "Log in".
5. Input the username and password from step 2, and continue the login flow normally.

After this you will be logged into `demo2.nextcloud.com` in your android app, and can try to reproduce the issue.

**Comment by lampgnu** [comment]
Hello,

I have tester e the problem not exist, watch the video screen:

https://my-c.it/index.php/s/SDqoiZQjZzda8Cb

The problem is on My server, but from a web browser not have this problem.

What I can see on my configuration server for resolve?

Thanks you

**Comment by AlvaroBrey** [comment]
Unfortunately I have no idea. Do you have a reverse proxy in front of your server? That's the first place I would look. However it seems odd that the rest of the app would work, but not share permissions.

**Comment by lampgnu** [comment]
I not have a reverse server.

Attach the log of the App:

https://my-c.it/index.php/s/EAjGdTTDFfm62DK

**Comment by joshtrichards** [comment]
Since no one else has indicated a similar issue and this doesn't appear with other servers, this seems a local configuration matter. I suggest posting at the Nextcloud Help Forum - https://help.nextcloud.com - to try to get some assistance or troubleshooting ideas if you're still experiencing this.

P.S. I was unable to accsss your most recently shared client debug log unfortunately.
