### ISSUE TITLE
PlayerService crash (again)

### ISSUE THREAD

**Issue by lampgnu** [nextcloud/android#9491]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1953b9 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: galahad
Model: M2004J19C
Id: RP1A.200720.011
Product: galahad_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.3.0.RJCEUXM

**Comment by AlvaroBrey** [comment]
From #8686:

> Therefore it seems like the crash only occurs, this way:

>    selecting a song to play
 >   stay within that view, until the song finished
 >   use the (Android) back button
 >   wait a couple of seconds

**Comment by ezaquarii** [comment]
Sigh... this is caused by the workaround implemented in https://github.com/nextcloud/android/issues/6665, as a consequence of this: https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all

We should not use `startForegroundService()` to send command to stop it, basically.
I cannot change it to `startService()` however, because the player activity lifecycle is a complete mess and tries to stop the audio when being woken up after long inactivity (triggering #6665).

I need to rig some other mechanism to communicate with the service, most likely based on `Binder`.
