### ISSUE TITLE
Auto Upload with subfolder (month/year) gives 409 and does not work anymore

### ISSUE THREAD

**Issue by HolgerHees** [nextcloud/android#9825]
### Steps to reproduce
1. Install Nextcloud 23.0.0
2. Install Nextcloud App 3.19.0
2. Configure Autoupload on your Android device and select 'Use Subfolder'

### Expected behaviour
- During the upload the needed sub folders should be created automatically

### Actual behaviour
"GET /index.php/204 HTTP/2.0" - 204 - - (78672) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"GET /index.php/204 HTTP/2.0" - 204 - - (73617) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"HEAD /remote.php/dav/files/hhees//Upload/Kamera/2022/02/PXL_20220213_101435370.jpg HTTP/1.1" - 404 - - (203655) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"MKCOL /remote.php/dav/uploads/hhees/{replaced-folder-id} HTTP/1.1" - 405 - 247 (87444) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"PROPFIND /remote.php/dav/uploads/hhees/{replaced-folder-id} HTTP/1.1" - 207 - 1066 (86607) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"MOVE /remote.php/dav/uploads/hhees/{replaced-folder-id}/.file HTTP/1.1" - 409 - 225 (89575) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"

I investigated further and I saw that the last "409 Conflict" response is coming from /3rdparty/sabre/dav/lib/DAV/Server.php line 750. The reason there is that the destination folder for the move operation does not exists.

In my case it is the folder "2" for the month. After I created it manually. The upload operation succeeded. I got the same behavior for all my configured uploads. Like Camera, Threema, Screenshots, Whatsapp etc

**Comment by raphraph** [comment]
I noticed the same bug with Nextcloud App 3.19.1.

In my case I had manually deleted the month folder that had previously been automatically created by the app. I did this thinking the app would recreate one.

As soon as I manually recreated the folder, the auto upload worked fine.

**Comment by oliv3r** [comment]
I'm seeing the same behavior with nextcloud 23.0.1 and nextcloud app 3.19.1; AutoUpload is enabled and Use subfolders (Store in subfolders based on year and month) is enabled. Yet all files get uploaded without this setting being applied.

I'm not seeing any errors or rejections in the logs however. So now I have a few hundered duplicate uploaded foto's that I have to weed out the actual duplicates from :(

**Comment by joshtrichards** [comment]
@HolgerHees:

> "MKCOL /remote.php/dav/uploads/hhees/{replaced-folder-id} HTTP/1.1" - 405 - 247 (87444) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"PROPFIND /remote.php/dav/uploads/hhees/{replaced-folder-id} HTTP/1.1" - 207 - 1066 (86607) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
"MOVE /remote.php/dav/uploads/hhees/{replaced-folder-id}/.file HTTP/1.1" - 409 - 225 (89575) - "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"

That log looks weird. There should have been at least one PUT before the MOVE since this was a chunked upload (v1: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html#chunked-upload-v1).

In any case I'm unable to reproduce this today. I can't pinpoint the PR, but several potentially relevant changes have been made.

Are you still able to reproduce this behavior?

@raphraph:

> In my case I had manually deleted the month folder that had previously been automatically created by the app. I did this thinking the app would recreate one.

A missing month folder should get created if it doesn't exist. This holds true even if manually deleted in my testing. The folder is checked for (and created if needed) when the upload is placed in the queue. This occurs even if wifi only or upload-when-charging are set. Even if the folder is deleted at that point, it still gets recreated at upload time in my testing today.

Are you able to reproduce this behavior today?

@oliv3r:

> Update: It seems that the settings are ignored, if they are changed 'while' nextcloud is trying to do things

Correct. That is expected behavior. Only newly added items to the upload queue get the new configuration. Existing queued items aren't touched.
