### ISSUE TITLE
Login mask that hides WebView during authentication 

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#9968]
### Is your feature request related to a problem? Please describe.
Users are confused when a web page opens and they are asked to enter their username and password. Especially with mobile or bad internet this takes a moment until the page is completely displayed.

### Describe the solution you'd like
When logging into the Nextcloud app, do not redirect to the login page of the Nextcloud instance, but create a mask in which you can log in without opening an external page.

### Additional context
Many companies use such a login mask like for example Synology at their Diskstation.

**Comment by AlvaroBrey** [comment]
The Nextcloud login flow is not always the same, depending on server config, authentication apps, third party authentication integrations, user config... etc.  That's why we log in through the server UI, rather than providing local fields for login.

I'm not sure what you mean by "login mask", but changes to the login flow in our app are not technically feasible.
