### ISSUE TITLE
Can't access `Android/data`, `Android/obb` or some subdirectories of `Android/media` on Android 11+

### ISSUE THREAD

**Issue by crashcoq** [nextcloud/android#9988]
On Android 11, I can't select a directory android/data

**Comment by AlvaroBrey** [comment]
This is a limitation on Android`s storage policies from Android 11. We can't do anything about this, unfortunately.

More information on [Android 11's storage documents](https://developer.android.com/about/versions/11/privacy/storage) (developer documentation).

I'm gonna pin this issue since we keep getting asked about this.
